blackducksoftware/blackduck-alert

src/main/js/component/general/distribution/job/HipChatJobConfiguration.js
The javascript used to set the notify property as a string now it sets
it to boolean which correct type and fixes the issue.
=> The notify property is a boolean use the boolean rather than string

src/main/java/com/synopsys/integration/alert/provider/blackduck/BlackDuckProviderContentTypes.java, src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyMessageContentCollector.java, src/test/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyMessageContentCollectorTest.java, src/test/resources/json/policyRuleClearedNotification.json
* Fix the construction of the policy rule messages to avoid creating N x M categories which creates incorrect policy messages. 
This affects the RULE_VIOLATION and RULE_VIOLATION_CLEARED
N = # of policies (policyInfos attribute in JSON)
M = # of components (componentVersionStatuses in JSON)
For each policy and component a new category message would be created even if the component doesn't violate the policy.  
The fix is to map the components to the policies they are affected by and then create the category items from that.
=> Ps policy duplication fix

src/main/java/com/synopsys/integration/alert/channel/hipchat/HipChatChannel.java, src/main/java/com/synopsys/integration/alert/channel/hipchat/descriptor/HipChatGlobalDescriptorActionApi.java, src/main/java/com/synopsys/integration/alert/channel/rest/RestChannelUtility.java, src/main/java/com/synopsys/integration/alert/channel/slack/SlackChannel.java, src/test/java/com/synopsys/integration/alert/channel/hipchat/HipChatChannelTest.java, src/test/java/com/synopsys/integration/alert/channel/hipchat/HipChatGlobalDescriptorActionApiTest.java, src/test/java/com/synopsys/integration/alert/channel/rest/RestDistributionChannelTest.java, src/test/java/com/synopsys/integration/alert/channel/slack/SlackChannelTest.java
Removed RestDistributionChannel from the hierarchy of DistributionChannels. Replaced the functionality there with a utility class that can now be used if you want to make rest calls in your channel.
This was originally being changed in anticipation of the MS Teams channel which looks to be getting pushed back now. Now it's just a QOL improvement
=> Removed RestDistributionChannel and added a rest utility class

src/main/java/com/synopsys/integration/alert/common/ConfigurationFieldModelConverter.java, src/main/java/com/synopsys/integration/alert/component/settings/SettingsDescriptorActionApi.java, src/main/java/com/synopsys/integration/alert/web/config/ConfigActions.java, src/main/java/com/synopsys/integration/alert/web/config/FieldModelProcessor.java, src/main/java/com/synopsys/integration/alert/workflow/startup/AlertStartupInitializer.java, src/test/java/com/synopsys/integration/alert/workflow/startup/AlertStartupInitializerTest.java
Startup variables now call the save and update actions (Probably want this reworked in 4.1.0 as action api requires FieldModels).
our save and update endpoints now call the save and update actions before actually saving to the DB
=> Fix startup variables

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/accessor/ProviderDataAccessor.java, alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultProviderDataAccessor.java, src/main/java/com/synopsys/integration/alert/provider/blackduck/tasks/BlackDuckProjectSyncTask.java
This should ensure all the provider data that gets synced in the database is encapsulated in a single transaction to prevent read access during the sync process
=> Merging sync changes to master

src/main/java/com/synopsys/integration/alert/component/settings/SettingsDescriptor.java, src/main/java/com/synopsys/integration/alert/component/settings/SettingsUIConfig.java, src/main/java/com/synopsys/integration/alert/database/api/user/UserRole.java, src/main/java/com/synopsys/integration/alert/web/security/HttpPathManager.java, src/main/java/com/synopsys/integration/alert/web/security/authentication/ldap/LdapManager.java, src/main/js/component/settings/SettingsConfigurationForm.js, src/main/resources/db/changelog/alert/4.0.0/changelog-authentication.xml, src/main/resources/db/changelog/alert/4.0.0/changelog-configuration-initialization.xml, src/test/java/com/synopsys/integration/alert/audit/controller/AuditEntryControllerTestIT.java, src/test/java/com/synopsys/integration/alert/database/api/user/UserAccessorTestIT.java, src/test/java/com/synopsys/integration/alert/database/api/user/UserModelTest.java, src/test/java/com/synopsys/integration/alert/web/actions/LoginActionsTestIT.java, src/test/java/com/synopsys/integration/alert/web/config/GroupConfigControllerTestIT.java, src/test/java/com/synopsys/integration/alert/web/controller/AuthenticationControllerTestIT.java, src/test/java/com/synopsys/integration/alert/web/controller/HomeControllerTestIT.java, src/test/java/com/synopsys/integration/alert/web/controller/SystemControllerTestIT.java, src/test/java/com/synopsys/integration/alert/web/security/authentication/ldap/LdapManagerTest.java
Remove the LDAP role prefix field value since it isn't used.  Changed the alert role to ALERT_ADMIN from ADMIN to make it Alert specific. ADMIN was too generic.
=> Ldap prefix removal

src/main/js/distribution/job/EmailJobConfiguration.js, src/main/js/distribution/job/HipChatJobConfiguration.js, src/main/js/distribution/job/SlackJobConfiguration.js, src/main/js/store/actions/distributionConfigs.js
This PR fixed an issue where old field errors remained when they should have been cleaned up when the page was closed.
=> Returned empty config if no ID supplied

src/main/java/com/synopsys/integration/alert/web/actions/LoginActions.java, src/test/java/com/synopsys/integration/alert/web/actions/LoginActionsTestIT.java
Add a check to make sure the user contains a role that alert recognizes during the login.  This authorization check is used to determine if the user can login to the application.
=> fix add a check for the roles to make sure the user can use alert

src/main/java/com/synopsys/integration/alert/provider/blackduck/BlackDuckProperties.java
Right now if either the timeout or API token is null for the Black Duck provider. The error message just says the global config can not be null. 
This will hopefully clarify what fields are null in the Black Duck provider
=> Attempting to make the error message clearer

src/main/java/com/synopsys/integration/alert/common/workflow/processor/MessageContentCollector.java
Added code to make the sub topic linkable item optional.  The AggregateMessageContent object has a constructor
that does not take a sub topic as a parameter.  Therefore use that constructor when a sub topic is not present.
=> fix create AggregateMessageContent without sub topic when necessary

src/main/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckProviderDescriptorActionApi.java, src/main/java/com/synopsys/integration/alert/provider/polaris/descriptor/PolarisGlobalDescriptorActionApi.java
Now that we have the option to delete global configurations, I stop the provider tasks when the configuration is deleted.
=> Stop tasks on config delete

alert-common/src/main/java/com/synopsys/integration/alert/common/rest/model/FieldModel.java, src/main/java/com/synopsys/integration/alert/web/config/FieldModelProcessor.java
When saving sensitive fields after a refresh, we would accidentally clear the value if a user didn't try to change the field value. We now properly check if the field is set and save appropriately.
=> Fixed saving sensitive fields

src/main/java/com/synopsys/integration/alert/provider/DefaultEmailHandler.java, src/main/js/component/audit/Index.js
License notifications do not have groups associated with them. Because of this, we need to check if the message is about licenses then add all the emails associated with the job.
This is meant to be temporary until we rework the way providers handle the Email channel.
=> Temporary fix for License notifications

src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyCollector.java, src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyLinkableItem.java, src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyOverrideCollector.java, src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyViolationCollector.java, src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/PolicyComponentMapping.java, src/test/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyViolationMessageContentCollectorTest.java
We now group message content based off of policy violations and component name. Component version and the policies will be grouped if there are similar results from the BlackDuckProvider. New messages can look like this:
Type: ADD
Component: GNU Compiler Collection
Component Version: [5.4.0][6.0.1]
Policy: [No GNU compiler collection][No dynamic]
=> Bm fix policy message for BD

src/main/java/com/synopsys/integration/alert/web/actions/LoginActions.java, src/main/java/com/synopsys/integration/alert/web/security/authentication/AlertAuthenticationProvider.java, src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/AlertSAMLEntryPoint.java, src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/SAMLAuthProvider.java, src/test/java/com/synopsys/integration/alert/web/actions/LoginActionsTestIT.java
This branch was originally intended to fall back to our regular authentication scheme if SAML failed.  It couldn't be done as of now. 
However the authentication methods of the LoginActions were encapsulated into a AuthenticationProvider.  This makes it fit with Spring Security conventions and cleans up the code in case we need other authentication schemes from our login screen.
=> Saml fallback

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/Descriptor.java, alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/ui/DescriptorMetadata.java, alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/ui/UIConfig.java, src/main/java/com/synopsys/integration/alert/channel/email/descriptor/EmailGlobalUIConfig.java, src/main/java/com/synopsys/integration/alert/channel/hipchat/descriptor/HipChatGlobalDescriptorActionApi.java, src/main/java/com/synopsys/integration/alert/channel/hipchat/descriptor/HipChatGlobalUIConfig.java, src/main/js/component/common/ChannelTestModal.js, src/main/js/dynamic/GlobalConfiguration.js, src/main/js/store/actions/globalConfiguration.js
Added a new item to descriptor metadata that will autogenerate the test modal for global configurations. All you pass this new field is the label for the destination field that you want displayed. The modal should work exactly as before.
In the future, I would like to expand this feature to accept multiple field definitions so we can have a mini testing form, but that is not necessary at the moment.
=> Bm auto test modals

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/CountdownConfigField.java, alert-common/src/main/java/com/synopsys/integration/alert/common/enumeration/FieldType.java, alert-common/src/main/java/com/synopsys/integration/alert/common/workflow/task/ScheduledTask.java, src/main/java/com/synopsys/integration/alert/component/scheduling/SchedulingDescriptor.java, src/main/java/com/synopsys/integration/alert/component/scheduling/SchedulingDescriptorActionApi.java, src/main/java/com/synopsys/integration/alert/component/scheduling/SchedulingUIConfig.java, src/main/java/com/synopsys/integration/alert/provider/polaris/descriptor/PolarisGlobalDescriptorActionApi.java, src/main/js/field/CounterField.js, src/main/js/util/fieldMapping.js, src/main/resources/db/changelog-master.xml, src/main/resources/db/changelog/alert/4.2.0/changelog-scheduling.xml, src/main/resources/db/changelog/alert/4.2.0/changelog.xml, src/test/java/com/synopsys/integration/alert/component/scheduling/SchedulingDescriptorActionApiTest.java
To finish the scheduling page, I needed to add a countdown timer to match our accumulator. I did that and fixed the actual countdown value. Apparently we were counting down from the BD accumulator which ran after 60 seconds but the ondemand task runs every 10 seconds.
The only issue with this change is the countdown field takes a bit longer than all the other fields to display a value for some reason. That can be fixed some time in the future if necessary.
=> Countdown field

src/main/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckProviderDescriptorActionApi.java
Using DescriptorActionApi, I delete all projects associated with BlackDuck when a used deletes their one and only BD global config. This is what it looks like when you try testing with deleted projects.
=> Delete BlackDuck Projects on delete

package-lock.json, package.json, src/main/css/app.scss, src/main/java/com/synopsys/integration/alert/channel/jira/descriptor/JiraDescriptor.java, src/main/java/com/synopsys/integration/alert/channel/slack/descriptor/SlackDescriptor.java, src/main/js/App.js, src/main/js/LoginPage.js, src/main/js/Navigation.js, src/main/js/component/AboutInfo.js, src/main/js/component/AboutInfoFooter.js, src/main/js/component/common/CollapsiblePane.js, src/main/js/component/common/ConfigButtons.js, src/main/js/component/common/ConfigurationLabel.js, src/main/js/component/common/DescriptorLabel.js, src/main/js/component/common/DescriptorOption.js, src/main/js/component/common/EditTableCellFormatter.js, src/main/js/component/common/NotificationTypeLegend.js, src/main/js/component/common/RefreshTableCellFormatter.js, src/main/js/component/common/ResetPasswordModal.js, src/main/js/component/common/SystemMessage.js, src/main/js/distribution/Index.js, src/main/js/distribution/ProjectConfiguration.js, src/main/js/dynamic/ChannelTestModal.js, src/main/js/dynamic/loading/audit/AuditPage.js, src/main/js/field/LabeledField.js, src/main/js/util/iconUtility.js
- Update the Font Awesome icon usage to the FontAwesomeIcon React component to make it consistent. 
- Change the icon paths for slack and jira to have the icon set name before the icon name i.e. 'fab/sack' and 'fab/jira' 
- Create a utility to construct the array that FontAwesomeIcon needs to load branded icons correctly.
- Created the alert-icon CSS class to add space between the FontAwesomeIcons and text elements.
=> Ps icon refactor

alert-common/build.gradle, src/main/java/com/synopsys/integration/alert/provider/blackduck/tasks/BlackDuckProjectSyncTask.java, src/test/java/com/synopsys/integration/alert/provider/blackduck/tasks/BlackDuckProjectSyncTaskTest.java
If a user sets up Alert and they are not associated with a project that is set in a distribution job, we will automatically add the user to the project.
Also updated to next version of blackduck common.
=> Projects now associated with current user

package-lock.json, src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckCollector.java, src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyCollector.java, src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyOverrideCollector.java, src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyViolationCollector.java, src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckVulnerabilityCollector.java, src/test/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyOverrideMessageContentCollectorTest.java, src/test/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyViolationMessageContentCollectorTest.java
Created a more appropriate link for BlackDuck policy and vulnerability components and their versions. Added a new Parent class that uses BlackDuck end points to properly update which URL should be hit.
=> Fixed links to BlackDuck

src/main/java/com/synopsys/integration/alert/channel/jira/web/JiraCustomEndpoint.java
Added saving functionality to the configure button to make the user experience better. New flow is like this.
Add normal text fields.
Save.
Error as you didn't press button to configure plugin (Normal fields are still saved).
Properly install custom plugin by pressing button.
Automatic save of button field occurs on success.
User does not need to press save again after pressing button (They can if they'd like).
=> Added save functionality to the Custom Jira endpoint button.

alert-common/src/main/java/com/synopsys/integration/alert/common/AlertProperties.java, deployment/blackduck-alert.env, deployment/cm-alert.yml, src/main/resources/application.properties
Remove the need for the PUBLIC_HUB_WEBSERVER_HOST and PUBLIC_HUB_WEBSERVER_PORT variables.
Use the ALERT_HOSTNAME and ALERT_SERVER_PORT environment variables.
=> Ps alert env var update

src/main/js/dynamic/GlobalConfiguration.js
The new endpoint button prevents users from being able to delete. We will now ignore those fields when we perform a delete action.
=> Fixed global configuration delete functionality

src/main/java/com/synopsys/integration/alert/channel/email/EmailAddressHandler.java, src/main/java/com/synopsys/integration/alert/channel/email/descriptor/EmailDescriptor.java, src/main/java/com/synopsys/integration/alert/channel/email/descriptor/EmailDistributionUIConfig.java, src/main/resources/db/changelog/alert/5.1.0/changelog-configuration-initialization.xml
Add a checkbox to allow email jobs to only send to the 'Additional Email Addresses'.
=> Additional Email Addresses Only

Dockerfile, deployment/docker-compose/docker-compose.yml, deployment/docker-swarm/docker-compose.yml, deployment/kubernetes/hub/3-alert.yml, deployment/kubernetes/standalone/3-alert.yml, docker-entrypoint.sh
Backport of 5.1.0 deployment file changes.
See https://github.com/blackducksoftware/blackduck-alert/pull/549 for analogous changes.
There is one file different in Kubernetes that is different because the healthcheck was not implemented in master for 5.1.0.  This PR fixes that issue.
=> Fix(deployment): Migrate 5.1.0 deployment fixes to 5.0.0

src/main/java/com/synopsys/integration/alert/channel/jira/util/JiraIssueFormatHelper.java
Fixed an issue with Jira component versions not properly linking back to BlackDuck like we do in other channels.
=> Jira Component Version link fix

src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckCollector.java, src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckVulnerabilityCollector.java
I also added this in a previous commit on master. Before, it was the same without the if-statement.
```java
public static final ComponentItemPriority findPriority(String priority) {
String upperCasePriority = priority.toUpperCase();
if ("CRITICAL".equals(upperCasePriority) || "BLOCKER".equals(upperCasePriority)) {
return HIGHEST;
}
try {
return ComponentItemPriority.valueOf(upperCasePriority);
} catch (IllegalArgumentException ex) {
// couldn't find the enum value default to STANDARD
return NONE;
}
}
```
=> Get cvss3 severity from Black Duck if it exists

alert-common/src/main/java/com/synopsys/integration/alert/common/AlertProperties.java, alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/util/FilePersistenceUtil.java, alert-common/src/main/java/com/synopsys/integration/alert/common/security/EncryptionUtility.java, src/test/java/com/synopsys/integration/alert/common/security/EncryptionUtilityTest.java, src/test/java/com/synopsys/integration/alert/util/TestAlertProperties.java
Try to read the new salt secret first otherwise attempt to read the old secret file name.
Added unit tests to the encryption utility class.
=> Ps encryption read fix

src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckCollector.java, src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/util/BlackDuckDataHelper.java
Fix: Fixing an issue where the VulnerableComponentView links have changed. The vulnerabilities link is now the href as of Black Duck 2019.10.0
=> Fixed vulnerable component link change

build.gradle, docker-entrypoint.sh, src/main/resources/db/release-locks-changelog.xml
A patch where upon startup of Alert liquibase will release the changelocks on the database.
A new changelocks directory is created with an empty changeset.
The jar files for the liquibase command line are copied into the lib/ directory of the deployment.
The entrypoint script executes the liquibase command line to release the locks on the database.
=> Ps changelock fix

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/ui/ProviderDistributionUIConfig.java
This is necessary so that we always save a value with it in new jobs. If we don't do this, filtering will not work correctly when filterByProject is never checked.
=> Add default value for filterByProject

src/main/java/com/synopsys/integration/alert/component/settings/descriptor/SettingsDescriptor.java, src/main/java/com/synopsys/integration/alert/component/settings/descriptor/SettingsUIConfig.java, src/test/java/com/synopsys/integration/alert/component/settings/SettingsGlobalApiActionTest.java
Remove the UI components for setting the default user email and password since it can now be done through the user management screen.
=> Fix(settings): Remove the admin email and password settings.

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/UserModel.java, alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultUserAccessor.java, src/main/java/com/synopsys/integration/alert/web/model/UserConfig.java, src/main/java/com/synopsys/integration/alert/web/security/authentication/UserManagementAuthoritiesPopulator.java, src/main/java/com/synopsys/integration/alert/web/security/authentication/event/AuthenticationEventManager.java, src/main/java/com/synopsys/integration/alert/web/security/authentication/ldap/MappingLdapAuthoritiesPopulator.java, src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/UserDetailsService.java, src/main/java/com/synopsys/integration/alert/web/user/UserActions.java, src/main/js/dynamic/loaded/users/UserTable.js, src/test/java/com/synopsys/integration/alert/component/settings/PasswordResetServiceTest.java, src/test/java/com/synopsys/integration/alert/component/settings/SettingsGlobalApiActionTest.java, src/test/java/com/synopsys/integration/alert/database/api/user/UserAccessorTestIT.java, src/test/java/com/synopsys/integration/alert/database/api/user/UserModelTest.java, src/test/java/com/synopsys/integration/alert/web/security/authentication/UserManagementAuthoritiesPopulatorTest.java, src/test/java/com/synopsys/integration/alert/web/security/authentication/saml/UserDetailsServiceTest.java
Allow the assignment of internal roles to external users.
Change the UI to make the fields in user management readonly for external users.
Allow an external user to be deleted since only roles can be modified.  when the user logs in they will be re-added to Alert.
I will have a different PR to remove the external boolean to be a more descriptive if the user has logged in via SAML or LDAP.  This is the initial change to add internal roles to external users.
=> Ps external user roles

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/PermissionMatrixModel.java, alert-common/src/main/java/com/synopsys/integration/alert/common/security/authorization/AuthorizationManager.java, src/main/java/com/synopsys/integration/alert/web/user/UserActions.java
Always assume readonly in the isReadOnly methods.
Always load the cache when the user roles are updated.
=> Ps role permission fix

src/main/java/com/synopsys/integration/alert/web/security/AuthenticationHandler.java
Forces the SAMLEntryPoint to always get called.
=> Fix(SAML): Always make authenticated requests

src/main/js/field/FieldsPanel.js, src/main/resources/db/changelog/alert/5.2.0/changelog-authentication-permissions.xml, src/main/resources/db/changelog/alert/5.2.0/changelog.xml
Add the permissions to create and delete the scheduling component.  In previous versions every descriptor had an empty configuration created for it.  Because the configuration is missing a POST request would be sent from the UI to create the scheduling configuration.  This requires the 'create' permission.
=> Ps scheduling fix

src/main/java/com/synopsys/integration/alert/component/settings/DefaultSettingsUtility.java
Converting to a field model to convert back to a configuration model doesn't make sense.  Only read the data from the database because the conversion to the FieldModel will set the password fields to null.  That was causing the issue with the password missing when using the proxy manager to build the ProxyInfo object.
=> Fix(config): Read the settings configuration from the database only.

alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultProviderDataAccessor.java, src/main/resources/db/changelog/alert/5.2.0/changelog-migrate-provider-projects.xml, src/main/resources/db/changelog/alert/5.2.0/changelog.xml
Fix for the project name column issue.  Increase the size to 512 which will handle the current issue where the largest project name is 367 characters long.  Although the length is arbitrary and alert may run into the same issue in the future.  This will provide enough of a buffer to avoid running into the issue again for some time.
=> Ps project name increase

src/main/java/com/synopsys/integration/alert/component/settings/actions/SettingsGlobalApiAction.java, src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/SAMLManager.java
This allows the SAML to be disabled because the database settings are saved first before the runtime changes to the SAML.  If there's an exception log it which will catch PKIX exceptions that prevent SAML from being disabled because it isn't a caught exception and it bubbles up.
=> fix: Update SAML settings after database save and log exceptions.

alert-common/src/main/java/com/synopsys/integration/alert/common/event/ContentEvent.java, src/main/java/com/synopsys/integration/alert/channel/email/EmailAddressHandler.java, src/main/java/com/synopsys/integration/alert/channel/email/EmailChannel.java, src/test/java/com/synopsys/integration/alert/channel/email/EmailChannelChannelDescriptorTestIT.java
The two remaining FIXME comments are from previous versions of Alert and need to be re-evaluated.  To avoid more changes beyond the multiple provider configuration feature I have left those FIXME comments to be addressed later.
=> Handle email channel FIXME related to multiple providers.

src/main/java/com/synopsys/integration/alert/web/user/UserActions.java, src/test/java/com/synopsys/integration/alert/web/user/UserActionTest.java
If the user is an external user skip validating the email address on update because LDAP and SAML manage the email address.
=> ldap validation fix

src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/SAMLAuthProvider.java
Sending the SAML auth event was using the wrong authentication object.  Use the populated Authentication object from the super.authenticate call.  It will have the granted authorities populated.
=> Use returned auth object from super.authenticate.

src/main/js/field/input/TableSelectInput.js
The event of the click of the select button is propagating to the ok button on the table. This closes it immediately in firefox.  Stop the event propagation when the select button is clicked.
=>  table select event propagation

deployment/helm/templates/alert.yaml, deployment/helm/values.yaml
* N/A
* Users should be able to use Volumes that they have already created (aka not have them dynamically created by the cluster). They need to specify the volumeName in order to do this.
* Add pvcVolumeName to Values.yaml and set it in the Persistent Volume Claim
*
*
=> Helm Chart: Allow the user to set the volumeName in the PVC resource

deployment/helm/templates/alert-cfssl.yaml, deployment/helm/templates/alert.yaml, deployment/helm/values.yaml
* N/A
* The User can specify any k8s resource configurations in the Values.yaml
* Have the format for taking in resources in the Values.yaml file match the format of k8s objects. Then pass the values directly into the deployment manifest for Alert and Cfssl
=> Helm Chart: Have the resources in Values.yaml match the k8s format

deployment/helm/templates/alert.yaml, deployment/helm/values.yaml
* N/A
* The synopsysctl bug fixed by the following PR needs to be fixed in the Alert Helm Chart (https://github.com/blackducksoftware/synopsys-operator/pull/1268)
* The customer should first create secrets for their certificates and then pass the secret name to the helm chart
* Set the correct value for the RUN_SECRETS_DIR environ
* Add Helm values for certificates and java-keystore
=> [WIP] Helm Chart: Fix configuring volumes for certificates and keystore

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/SelectConfigField.java
With some refactoring the clearable option was set to false by default.  It was true before 5.3.0.  So changing the default back to 5.3.0.  The fields that need to disable the clearable field call the applyClearable method.
=> Set clearable to true by default.

deployment/helm/templates/alert-cfssl.yaml, deployment/helm/templates/alert.yaml, deployment/helm/values.yaml
* N/A
* JIRA Ticket: https://jira-sig.internal.synopsys.com/browse/CLOUD-663
* The user should be able to start/stop an alert instance with the Helm Chart. (ex: they need to manage their storage)
* Add a status field in the Helm Chart's Values.yaml
* If the status is not "Running" then scale down all pods to 0
=> Helm Chart: Add field to start/stop an alert instance

deployment/helm/templates/alert.yaml, deployment/helm/values.yaml
* N/A
* The user should be able to create their own Persistent Volume Claim that the Alert instance can use for storage. 
* Add persistentVolumeClaimName field to Values.yaml
* If persistentVolumeClaimName is set then don't create the PVC and use the specified value for the name
=> Helm Chart: Ability to specify a persistent volume claim name

deployment/helm/templates/_helpers.tpl, deployment/helm/templates/alert-environ-configmap.yaml, deployment/helm/templates/alert-environ-secret.yaml, deployment/helm/values.yaml
* N/A
* JIRA Ticket: https://jira-sig.internal.synopsys.com/browse/CLOUD-664
* This is done to match the conventions in the Black Duck Helm Chart (which uses a map)
* Change the Values.environs field to be a map
* Modify how they are transcribed into the ConfigMap and Secret
=> Helm Chart: Values.environs are passed through a map

deployment/helm/templates/alert.yaml, deployment/helm/values.yaml
* N/A
* The Helm Chart should allow Alert's port to be configured
* Add a port value in Values.yaml
* Use the port value in the Alert's Deployment, Services, and ConfigMap (ALERT_SERVER_PORT)
=> Helm Chart: Ability to configure Alert's port

deployment/helm/templates/alert-cfssl.yaml, deployment/helm/templates/alert.yaml, deployment/helm/values.yaml
* N/A
* The Helm Chart should be able to allow users to easily configure the imageTag and registry for their images
* Create a global registry field in Values.yaml
* Create a registry field for alert and cfssl (overrides the global if set)
* Create an imageTag for alert and cfssl
* The image is constructed using the above values in alert.yaml and cfssl.yaml
=> Helm Chart: Use separate fields for registry and imageTag like BlackDuck

deployment/helm/templates/_helpers.tpl, deployment/helm/templates/alert-environ-secret.yaml
* N/A
* The values in a k8s Secret should be base64 encoded
* Change the function in _helpers.tpl to encode the values from secretEnvirons
* Change the templating in alert-environ-secret.yaml to loop through each environ and encode the data
=> Helm Chart: Bug - secret values aren't encoded

deployment/helm/templates/alert-environ-configmap.yaml
* N/A
* The additional environs are not set at the correct indentation in the config map
* Use the nindent function to set them correctly
=> Helm Chart: Bug - Incorrect indentation for additional environs

deployment/helm/templates/_helpers.tpl, deployment/helm/templates/alert-cfssl.yaml, deployment/helm/templates/alert.yaml, deployment/helm/values.yaml
* N/A
* The Alert Helm Chart should allow the user to specify imagePullSecrets for pulling images from private registries
* Add an imagePullSecrets field to Values.yaml
* Put the imagePullSecrets into the Deployments for Alert and Cfssl
=> Helm Chart: Set imagePullSecrets for Alert and Cfssl images

src/main/js/dynamic/loaded/users/PermissionTable.js
If the id is the same for the permission we are editing and the list of permissions from the same descriptor and context allow the update of the permissions.  If the IDs are different report the duplicate error.
=> Check id field to allow edits.

deployment/helm/Chart.yaml
* N/A
* JIRA: https://jira-sig.internal.synopsys.com/browse/IALERT-1678
* N/A
* change appVersion to VERSION_TOKEN in Chart.yaml
=> Helm Chart: Add VERSION_TOKEN to the appVersion in Chart.yaml

deployment/helm/synopsys-alert/templates/_helpers.tpl, deployment/helm/synopsys-alert/templates/alert-cfssl.yaml, deployment/helm/synopsys-alert/templates/alert-environ-configmap.yaml, deployment/helm/synopsys-alert/templates/alert-environ-secret.yaml, deployment/helm/synopsys-alert/templates/alert.yaml, deployment/helm/synopsys-alert/values.yaml
* GitHub: N/A
* Progress on JIRA: https://jira-sig.internal.synopsys.com/browse/IALERT-1590
* Progress on JIRA: https://jira-sig.internal.synopsys.com/browse/CLOUD-592
* The Helm Chart should be able to set Security Contexts so customers can run as non-root. Synopsysctl will need to use this ability from the Helm Chart.
* Add podSecurityContext and securityContext in Values.yaml for Alert and Cfssl
* Configure podSecurityContext and securityContext in the Deployments for Alert and Cfssl
=> Helm Chart: Make security contexts configurable in the helm chart

alert-database/src/main/resources/liquibase/6.0.0/notification-migration-procedures.xml, alert-database/src/main/resources/liquibase/6.0.0/notifications.xml
Fix the procedure to get the provider configuration id.
Remove the not null constraint on the provider_config_id column.  Because valueComputed is used the first statement that liquibase issues is 
ALTER TABLE raw_notification_content ADD COLUMN 'provider_config_id' NOT NULL;
But there is no default value defined so NULL is used but the column can't be null.
May be related to this liquibase bug which has similar behavior:
https://liquibase.jira.com/browse/CORE-3028
=> upgrade fix

src/main/java/com/synopsys/integration/alert/channel/email/descriptor/EmailDistributionUIConfig.java, src/main/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckDistributionUIConfig.java, src/main/java/com/synopsys/integration/alert/provider/blackduck/web/PolicyNotificationFilterCustomEndpoint.java
Allow the provider config name to be included in the field model.  Read the configuration from the database to create the options for the field.
=> Read the provider config to get the missing data.

deployment/helm/synopsys-alert/values.yaml
Resolves: 
* change PVC claim size representation from G to Gi
* If you specify limits alone on kubernetes container resources, then internally Kubernetes will set requests as same as limits and hence removed requests from resources in order to remove the duplicates.
=> change PVC claim size representation from G to Gi

alert-database/src/main/resources/liquibase/6.0.0/changelog.xml, alert-database/src/main/resources/liquibase/6.0.0/component-tasks.xml, alert-database/src/main/resources/liquibase/6.0.0/init-auth-db.xml, alert-database/src/main/resources/liquibase/6.0.0/init-config-db.xml, build.gradle, docker-entrypoint.sh
Fix the check for the H2 database to determine whether to upgrade or not.  Alert was always performing an upgrade.
Create changesets for inserting the component_tasks descriptor.
=> Database task management fixes

src/main/java/com/synopsys/integration/alert/component/authentication/actions/AuthenticationTestAction.java
Add an error case to check if both LDAP and SAML are disabled when clicking on the test button.
=> Check if both LDAP and SAML are disabled.

alert-common/src/main/java/com/synopsys/integration/alert/common/security/CertificateUtility.java
The keystore had an error dealing with the keystore contents being corrupted.  With multiple deletes happening they could be running in different threads.  Since CertificateUtility is a shared resource of CertificateActions, add the synchornized keyword to the public methods of CertificateUtility to ensure that multiple requests from the controller only modify the truststore one at a time.
=> Add 'synchronized' to prevent concurrent modification of the keystore

alert-common/src/main/java/com/synopsys/integration/alert/common/workflow/processor/notification/NotificationProcessor.java
When processing a job only get the notifications that match the provider config id in the job with the provider config id of the accumulated notification.  By using just the project name if two Black Duck providers have projects of the same name, then the jobs using other providers will cause a notification to be sent again because the project name matches. Limit to match the provider config id to solve the issue.
=> Filter notifications by provider config to prevent duplicates.

alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultProviderTaskPropertiesAccessor.java
Need to add transactional to save the task properties.  The getTaskProperty method always returned an optional.empty() in the accumulator task because the saved entity was not getting flushed to the database and written.
=> real time fix

build.gradle, src/main/resources/application.properties, src/test/resources/spring-test.properties
I have configured Spring to use the pooled-lo optimizer by default.  So any SequenceGenerator annotations added will use the pooled-lo optimizer rather than the default pooled optimizer.  The pooled optimizer subtracts from the current hi which is why I was seeing negative IDs in the database. With this change this adds to the lowest rather than subtract from the highest which appears to cause id collisions. 
Here's a link to explain the pooled-lo provider.  
https://vladmihalcea.com/hibernate-hidden-gem-the-pooled-lo-optimizer/
=>  hibernate fix

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/SystemMessageModel.java, alert-common/src/main/java/com/synopsys/integration/alert/common/provider/state/ProviderProperties.java, alert-common/src/main/java/com/synopsys/integration/alert/common/provider/state/StatefulProvider.java, alert-database/src/main/java/com/synopsys/integration/alert/database/system/DefaultSystemMessageUtility.java, src/main/java/com/synopsys/integration/alert/provider/blackduck/BlackDuckValidator.java, src/main/java/com/synopsys/integration/alert/provider/blackduck/factories/BlackDuckTaskFactory.java, src/main/java/com/synopsys/integration/alert/provider/blackduck/tasks/BlackDuckValidatorTask.java, src/test/java/com/synopsys/integration/alert/AboutReaderTest.java, src/test/java/com/synopsys/integration/alert/database/system/SystemMessageUtilityTestIT.java, src/test/java/com/synopsys/integration/alert/web/actions/SystemActionsTest.java, src/test/java/com/synopsys/integration/alert/web/model/SystemMessageModelTest.java, src/test/java/com/synopsys/integration/alert/workflow/startup/SystemValidatorTest.java
Add a task for each provider to validate the configuration every minute and update system messages for any provider configuration errors.
=>  validator fix

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/accessor/DefaultDescriptorGlobalConfigUtility.java, alert-common/src/test/java/com/synopsys/integration/alert/common/descriptor/accessor/DefaultDescriptorGlobalConfigUtilityTest.java
For sensitive fields read the values from the database and use the value if the value from the field model isn't set.
We were writing the empty string as the LDAP password each time Alert starts up. Read if the value is saved in the database and use that if the field isn't set in the new configuration to be saved.
=> ldap password fix

Dockerfile, docker-entrypoint.sh
Fix the application of the security context in helm.  Change file permissions to allow non root users to generate the certificates.
=> Ps security context fix

alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultNotificationManager.java
Add a flush call before handleEvent in order to ensure the notifications are saved in the database and can be read via notification ID's in the real time event handler.
=> Add repository flush call to save method.

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/ConfigurationModel.java, alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/mutable/ConfigurationModelMutable.java, alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/util/ConfigurationFieldModelConverter.java, alert-common/src/test/java/com/synopsys/integration/alert/common/persistence/model/ConfigurationModelTest.java, alert-common/src/test/java/com/synopsys/integration/alert/common/persistence/model/mutable/ConfigurationModelMutableTest.java, alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultConfigurationAccessor.java, alert-database/src/test/java/com/synopsys/integration/alert/database/api/DefaultAuditUtilityTest.java, alert-database/src/test/java/com/synopsys/integration/alert/database/api/DefaultNotificationManagerTest.java, alert-database/src/test/java/com/synopsys/integration/alert/database/api/DefaultProviderDataAccessorTest.java, src/test/java/com/synopsys/integration/alert/mock/MockConfigurationModelFactory.java, src/test/java/com/synopsys/integration/alert/provider/blackduck/tasks/BlackDuckProjectSyncTaskTest.java, src/test/java/com/synopsys/integration/alert/web/security/authentication/ldap/LdapManagerTest.java, src/test/java/com/synopsys/integration/alert/workflow/scheduled/PurgeTaskTest.java, src/test/java/com/synopsys/integration/alert/workflow/scheduled/frequency/DailyTaskTest.java
After discussing with Gavin, we decided rather to use a builder to instead separate the model into having a mutable and immutable version, where the mutable is a subclass of main ConfigurationModel by removing the put method. 
Let me know if there are any questions related to the refactor or tests.
=> Create and separate a mutable and immutable version of the ConfigurationModel class

buildSrc/deploymentTasks.gradle, deployment/helm/synopsys-alert/DEVELOPER_README.md, deployment/helm/synopsys-alert/README.md
- Updates to gradle to create a helm package tarball as part of the build.
- Add a developer's readme to explain the helm chart versioning and what's expected of the helm charts.
- Remove the beta text that was present in the 6.0.0 files since with 6.1.0 the chart will be used and tested.
=> helm packaging

src/main/java/com/synopsys/integration/alert/web/security/AuthenticationHandler.java, src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/SamlConfig.java
This is an attempt to remove the clutter in AuthenticationHandler.
=> Move unreferenced SAML Beans out of AuthenticationHandler

alert-common/src/main/java/com/synopsys/integration/alert/common/action/UploadEndpointManager.java, alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/CheckboxConfigField.java, alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/ConfigField.java, alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/NumberConfigField.java, alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/SelectConfigField.java, alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/URLInputConfigField.java, alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/validators/ConfigValidationFunction.java, alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/validators/EncryptionSettingsValidator.java, alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/validators/UploadValidationFunction.java, alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/validators/ValidationResult.java, alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/ui/ProviderDistributionUIConfig.java, alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/ui/ProviderGlobalUIConfig.java, alert-common/src/test/java/com/synopsys/integration/alert/common/ConfigurationFieldModelTest.java, alert-common/src/test/java/com/synopsys/integration/alert/common/action/UploadEndpointManagerTest.java, alert-common/src/test/java/com/synopsys/integration/alert/common/descriptor/config/field/validators/ValidationResultTest.java, src/main/java/com/synopsys/integration/alert/channel/email/descriptor/EmailDistributionUIConfig.java, src/main/java/com/synopsys/integration/alert/component/authentication/descriptor/AuthenticationUIConfig.java, src/main/java/com/synopsys/integration/alert/component/settings/descriptor/SettingsUIConfig.java, src/main/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckProviderUIConfig.java, src/main/java/com/synopsys/integration/alert/web/config/FieldValidationAction.java, src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/SamlMetaDataFileUpload.java, src/test/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckDescriptorTest.java
Previously we used a Collection of strings to handle error messages produced by the validators. In this refactor I instead created a ValidationResult object to instead be used with several other convenience methods.
=> Refactor validation functions into a ValidationResult object

src/main/java/com/synopsys/integration/alert/component/scheduling/actions/SchedulingGlobalApiAction.java
While working on IALERT-1740, Paulo and I realized that we cannot remove refreshConfig from globalConfiguration.js. Because the update is a PUT call it returns no body and in order for the UI to be correctly updated to reflect the new cron we need the refresh to still run.
The changes here will let the fieldModel be updated since currently it will only be updated when a GET call is run. This method will clean up that process so we do not need to run a GET after a PUT to get the new/next runtimes.
=> Add an afterUpdateAction to get the latest fieldModel after an update

src/main/js/dynamic/loaded/certificates/CertificatesPage.js, src/main/js/dynamic/loaded/tasks/TaskManagement.js, src/main/js/dynamic/loaded/users/PermissionTable.js, src/main/js/dynamic/loaded/users/RoleTable.js, src/main/js/dynamic/loaded/users/UserTable.js, src/main/js/field/TableDisplay.js
- Fix table display to only have one popup used for both insert and edit which prevents the duplicate ids. 
- Use a table reference to be able to change the save and test functions that are called since insert and edit call different functions.
- Add ids to the fields table display renders to help with automation.
- Fix lint issues with the classes that use TableDisplay
=> table id fix

src/main/js/field/TableDisplay.js, src/main/js/providers/ProviderTable.js, src/main/js/store/reducers/globalConfiguration.js
Clear the Global Configuration errors when reading all the configurations.
The clearing of the errors when fetching all configurations is an issue with TableDisplay because in the background it keeps reading all the configs which clears the errors when the modal is up.  Therefore if the modal is up disable the refresh of the table data.  While the new or edit modals are up we save processing in the UI because we aren't making a request every 10 seconds to the Alert server. When the modal is closed the table will be refreshed with data.
=> When configurations are fetched clear the errors.

src/main/js/field/TableDisplay.js
Fix the PermissionsTable cancel by testing if the methods on the reference are valid.
=> Test if the reference functions are valid before assigning them.

src/main/js/store/actions/globalConfiguration.js
The global configuration delete action was calling the .json() function on the response inside a lambda function for the response.json() promise.  There is an error with the JSON body being locked therefore the delete operation never dispatches its state changes.
=> fix delete

src/main/js/field/input/TableSelectInput.js
Make the buttons for select and clear appear underneath the select input.  This allows the screen to re-size and not display the buttons off of the modal window.
=>  fix select style

src/main/js/dynamic/loaded/audit/Details.js
Change the size of the text area to be the same size as the column.  The size it had was larger than the error message in the same column causing the issue.
=>  Change the size of the text area to match the column size.

src/test/java/com/synopsys/integration/alert/channel/email/EmailChannelTestIT.java, src/test/java/com/synopsys/integration/alert/database/api/configuration/ConfigurationAccessorTestIT.java
Only use the try catch block to test a single exception.  Move the methods that throw IntegrationExceptions that aren't part of the test out of the try/catch block to address sonar cloud issues.
=> Fix sonar cloud issues with exception tests.

alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultProviderDataAccessor.java
The mapUsersToProjectByEmail method is called inside a forloop in a transaction.  It uses the batch methods deleteAll and saveAll.  Need to flush after those methods are called so the next iteration of the loop can find the repository data.
=> Method called in a for loop so flush the repository at the end.

src/main/js/component/common/AutoRefresh.js, src/main/js/distribution/Index.js, src/main/js/dynamic/loaded/audit/AuditPage.js, src/main/js/field/TableDisplay.js
The following changes are updates and improvements to the auto-refresh, bringing the refresh rate up to 30 seconds as well as pausing it on modals that it previously did not effect such as some delete modals. 
As a note, currently the insert modal for the distribution jobs will continue to refresh the table in the background as we cannot get the state of the table easily. After discussing it with Paulo, the solution for this table will be to change update the distributions page to use TableDisplay to simplify the modals in a future ticket.
Laslty, several style changes were made to use object destructuring.
=> Auto-refresh Improvements

src/main/js/providers/ProviderTable.js
Clear the field errors when the provider table component mounts.  The component mounts when you click on the BlackDuck provider link in the Navigation portion of the UI.  This is done in other components that use TableDisplay as well.
=> Clear the field errors when the component mounts.

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/ui/ProviderDistributionUIConfig.java, src/main/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckDistributionUIConfig.java, src/main/js/field/EndpointSelectField.js, src/test/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckDescriptorTest.java, src/test/java/com/synopsys/integration/alert/web/config/JobConfigControllerTestIT.java
Clear the fieldmodel of a value for the endpoint select field if the options are empty or if the value of the field is not present in the options.  This will update the field model to have an empty value which will be validated.  If the field is required like the provider config name then saving a configuration will report a field validation error for the required field because the fiedlModel sent to the server has an empty value for the config name.  If this isn't done the UI will not display any options but the fieldModel will have the old value which is still valid.  Also add a validation check to see if the config name exists in the back end java code in case a request is made via the API.
=> Ps endpoint select clear

src/main/js/field/TableDisplay.js, src/main/js/providers/ProviderTable.js
The provider table uses the globalConfiguration.js actions and reducers therefore the action messages are sent the same as the global configuration screens in alert.  The provider table has multiple configurations and displays a dialog with the error message.  To delete a provider a user clicks on the delete button.  If the user presses the edit button of an existing config due to redux state change timing the message in the dialog may show 'delete successful' which is the status of the items that were deleted.  To fix this issue add a mechanism to ignore action messages for the time being.  There are other changes in the future to render errors and messages in TableDisplay in a better way.  This is to fix the immediate issue.
=> delete message fix

build.gradle, src/main/java/com/synopsys/integration/alert/web/security/AuthenticationHandler.java, src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/SAMLManager.java, src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/SamlConfig.java
Fix the SAML functionality to work with Azure AD SAML.  Needed to disable signature verification to avoid the certificate errors.  Then needed to add an additional metadata provider to create the SAML hand shake.
=> Azure AD SAML Fixes

alert-common/src/main/java/com/synopsys/integration/alert/common/channel/issuetracker/message/IssueTrackerResponse.java, alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/errors/AlertFieldStatus.java, alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/errors/FieldStatusSeverity.java, alert-common/src/main/java/com/synopsys/integration/alert/common/message/model/MessageResult.java, alert-common/src/main/java/com/synopsys/integration/alert/common/rest/model/JobFieldStatuses.java, alert-common/src/test/java/com/synopsys/integration/alert/common/rest/model/JobFieldErrorsTest.java, src/main/java/com/synopsys/integration/alert/provider/blackduck/actions/BlackDuckDistributionTestAction.java, src/main/java/com/synopsys/integration/alert/web/config/ConfigActions.java, src/main/java/com/synopsys/integration/alert/web/config/JobConfigActions.java, src/main/java/com/synopsys/integration/alert/web/config/JobConfigController.java, src/test/java/com/synopsys/integration/alert/common/exception/AlertFieldStatusTest.java, src/test/java/com/synopsys/integration/alert/web/config/JobConfigControllerTestIT.java
- Include field statuses in `MessageResult` to allow channels to expose more granular error/warning messages.  
- Implement combined usage of `MessageResult` in `JobConfigActions` for job validation, provider validation, and test messages
=> Enhance MessageResult

src/main/java/com/synopsys/integration/alert/channel/azure/boards/oauth/OAuthRequestPurgeTask.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/oauth/OAuthRequestValidator.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/web/AzureBoardsCustomEndpoint.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/web/AzureOAuthCallbackController.java, src/test/java/com/synopsys/integration/alert/channel/azure/boards/oauth/OAuthRequestPurgeTaskTest.java, src/test/java/com/synopsys/integration/alert/channel/azure/boards/oauth/OAuthRequestValidatorTest.java
Create a small in memory cache to manage the OAuth request keys contained in the state as part of validating a request to the AzureOAuthCallbackController.  If it isn't a request that Alert has made then do not process the request further.
=>  oauth  request validation

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/util/ConfigurationFieldModelConverter.java, alert-common/src/main/java/com/synopsys/integration/alert/common/rest/ProxyManager.java, alert-common/src/test/java/com/synopsys/integration/alert/common/ConfigurationFieldModelTest.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/AzureRedirectUtil.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/descriptor/AzureBoardsGlobalUIConfig.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/oauth/AzureOAuthTokenValidator.java, src/test/java/com/synopsys/integration/alert/workflow/startup/AlertStartupInitializerTest.java
Was going to add this in 6.2.0 but the warnings are treated as errors and would prevent saving.  This will allow pushing the save and test button and having the UI display a warning message.
Fixed the cause of a circular dependency in the ConfigurationFieldModelConverter.  The class uses the descriptor keys.  If we use the DescriptorMap it needs all the descriptors which is where the validator is getting used.  So it can't autowire the objects correctly.
=> Add validator for OAuth 

azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/service/comment/model/WorkItemCommentRequestModel.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/descriptor/AzureBoardsDistributionUIConfig.java
This fixes an error when previously submitting this field without a value. Now it will be pre-populated with the DEFAULT_WORK_ITEM_TYPE of "Task" and the field will be made required.
=> Make Azure Work Item Type a required field

azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/service/comment/model/WorkItemCommentRequestModel.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/AzureBoardsSearchProperties.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/AzureBoardsSearchPropertiesUtil.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/AzureBoardsTestIssueRequestCreator.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/actions/AzureBoardsCreateIssueTestAction.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/actions/AzureBoardsDistributionTestAction.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/service/AzureBoardsIssueHandler.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/service/AzureBoardsMessageParser.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/service/AzureBoardsRequestCreator.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/service/AzureCustomFieldManager.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/service/model/AzureCustomFieldDescriptor.java
The hope with the original custom fields was since they are potentially user-visible, to minimize the number of them. Unfortunately, the text fields we used have a size limit of 255, and the other option is not queryable beyond 255 characters, so we needed to add more fields.
=> Fix Azure Custom Fields

azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/oauth/AzureAuthorizationCodeFlow.java, azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/oauth/AzureCredential.java, azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/oauth/AzureOAuthConstants.java, azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/oauth/AzureTokenResponse.java
Implement custom classes to be able to construct a refresh token request with the same type of body as the new token request.  The refresh token is used as the assertion in the body rather than the authorization code in the request.
Also updated the AzureTokenResponse class to only include the bare minimum that is needed.  The overridden methods weren't needed the way we were using it.
=> Ps refresh token fix

alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultConfigurationAccessor.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/actions/AzureBoardsConfigurationAction.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/actions/AzureBoardsGlobalApiAction.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/descriptor/AzureBoardsGlobalUIConfig.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/oauth/AzureOAuthAuthenticateValidator.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/oauth/OAuthRequestValidator.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/web/AzureBoardsCustomEndpoint.java, src/main/js/field/OAuthEndpointButtonField.js
Fix issues with clicking save and test while authentication is happening.  Also fixed an issue where test fails after clicking save.
Test would fail because none of the token fields that are saved in the controller are preserved in the new configuration that is saved.  Read those existing fields and save them.
Fixed an issue with JPA batch update errors.  Needed to flush repositories.
Added a validator to see if authentication was in process.
=> Ps authenticate save fix

build.gradle, buildSrc/buildTasks.gradle
Changing the build to no longer always run npm_run or the copyToTemplates task. These 2 tasks will now only run if you call them directly OR if you are calling the task 'runServer' or 'all'
=> Changing the build to no longer always run npm_run

build.gradle
The HomeControllerTestIT checks if the index url of "/" returns ok.  That uses Thymeleaf to load the index.html page which is compiled by npm and copied by the copyToTemplates gradle task.  Change testIntegration and testAll to depend on the copyToTemplates task.
=> Make sure testIntegrations and testAll run after copyToTemplates.

alert-common/src/main/java/com/synopsys/integration/alert/common/workflow/task/ScheduledTask.java, src/main/java/com/synopsys/integration/alert/provider/blackduck/tasks/BlackDuckAccumulator.java, src/test/java/com/synopsys/integration/alert/provider/blackduck/tasks/BlackDuckAccumulatorTest.java
While investigating the error message returning next accumulator run time as either 0 or a negative time we discovered that the logging does not reflect the correct results. This feature appears to not have been working as intended or correctly since before 5.3.0. Because future is currently referring to the running instance of the accumulator we are getting a negative run time as the time is actually reflecting the time since it last ran the accumulator. In the cases of it reporting 0 or -1 this is due to a rounding error as the message would be generated in about 500-900ms or occasionally just over 1000ms. When debugging, this time would reflect the amount of time since the accumulator first ran and would therefore be several seconds or minutes depending on how long you stop the …
=> Removing incorrect logging from BlackDuckAccumulator

src/main/java/com/synopsys/integration/alert/channel/azure/boards/service/AzureBoardsProperties.java, src/main/java/com/synopsys/integration/alert/channel/azure/boards/service/AzureBoardsRequestDelegator.java
Validate the Azure properties before attempting to create an issue in order to avoid a NPE when the global configuration is missing.
=> Fixing NPE issue when trying to create work items while the Azure global config is missing.

alert-common/src/main/java/com/synopsys/integration/alert/common/action/ValidationActionResponse.java, alert-common/src/main/java/com/synopsys/integration/alert/common/action/api/AbstractConfigResourceActions.java, alert-common/src/main/java/com/synopsys/integration/alert/common/action/api/AbstractJobResourceActions.java, alert-common/src/main/java/com/synopsys/integration/alert/common/action/api/AbstractResourceActions.java, src/main/java/com/synopsys/integration/alert/web/api/certificate/CertificatesController.java, src/main/java/com/synopsys/integration/alert/web/api/config/ConfigController.java, src/main/java/com/synopsys/integration/alert/web/api/job/JobConfigController.java, src/main/js/store/actions/distributions.js
Make sure forbidden messages propagate for test and validate calls.  Before we would return OK status responses and we might leak information.
Simplify the controller to just process the content result and move the transformation of the result into the actions.
=>  validation fix

src/main/js/dynamic/GlobalConfiguration.js, src/main/js/util/fieldModelUtilities.js
The context and descriptor name are missing from the global configurations after delete.  Any custom endpoints like the Azure authenticate will not work because the permissions will fail.  There is no context or descriptor name in the field model to use for the permission check of a custom endpoint.  Therefore add the context and descriptor name if they are missing.
=> Include the context and descriptor in the field model since they are missing

src/main/css/table.scss
This prevents overriding the page size dropdown from being visible above the container.
=> Fix(CSS): Set overflow-y to inherit on expandableContainer

src/main/java/com/synopsys/integration/alert/component/authentication/descriptor/AuthenticationUIConfig.java, src/main/java/com/synopsys/integration/alert/web/security/authentication/ldap/MappingLdapAuthoritiesPopulator.java, src/test/java/com/synopsys/integration/alert/web/security/authentication/ldap/MappingLdapAuthoritiesPopulatorTest.java
Update the LDAP handling to deal with exceptions if the search group is wrong and read the roles from the database and add them to the existing set of roles.  If the group search base is null an empty set is returned and the database roles are added.  This resolves the issues for customers who to not have LDAP groups configured for their users.
=> ldap improvements

src/main/java/com/synopsys/integration/alert/component/authentication/actions/AuthenticationTestAction.java
Wrap the authentication test in a try catch and create an error message to display to the user.
=>  Create error message when an exception occurs.

channel/build.gradle, channel/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/util/JiraCloudIssueHandler.java, channel/src/main/java/com/synopsys/integration/alert/channel/jira/server/util/JiraServerIssueHandler.java, channel/src/test/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudRequestDelegatorTest.java, channel/src/test/java/com/synopsys/integration/alert/channel/jira/server/JiraServerRequestDelegatorTest.java
The biggest change is the issue creation returns a new object that more accurately represents the data returned. Use this returned data to then retrieve all the data about the newly created response object.
=> Update to jira common 2.0.0

web/src/main/java/com/synopsys/integration/alert/web/api/job/JobConfigActions.java
In 6.3.0 we split up the validation step and had a case where if the name was missing it wouldn't get the field status messages for the other fields. This changes the name validation to also return a fieldstatus and correctly display all of the errors in the UI.
=> Fix all field error messages not displaying on distribution test configuration error

ui/src/main/js/dynamic/DistributionConfiguration.js, ui/src/main/js/store/actions/distributionConfigs.js, ui/src/main/js/store/reducers/distributionConfigs.js, ui/src/main/js/util/httpErrorUtilities.js
Due to our changes around fieldStatuses, warnings were coming up in the UI as errors but containing a success message and a successful response. This change makes it so that we will check for a severity of ERROR first to determine if we should throw an error status in the UI and allow warnings to continue as a success status.
As a side note, my save actions were messing with the formatting removing spaces in several areas. I tried to play around with this and fix it but the save actions would overwrite it each time. If anyone thinks its incorrect, please let me know how you modified it in your save actions so I can try to fix it.
=> Fix distribution test configuration to display warnings as successes

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/accessor/ProviderDataAccessor.java, alert-common/src/main/java/com/synopsys/integration/alert/common/workflow/processor/notification/NotificationProcessor.java, alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultProviderDataAccessor.java, alert-database/src/test/java/com/synopsys/integration/alert/database/api/DefaultProviderDataAccessorTest.java, channel/src/main/java/com/synopsys/integration/alert/channel/email/EmailAddressHandler.java, channel/src/main/java/com/synopsys/integration/alert/channel/email/actions/EmailActionHelper.java, provider/src/main/java/com/synopsys/integration/alert/database/api/BlackDuckProviderDataAccessor.java, provider/src/main/java/com/synopsys/integration/alert/provider/blackduck/BlackDuckProviderDataAccessor.java, provider/src/test/java/com/synopsys/integration/alert/provider/blackduck/mock/MockProviderDataAccessor.java, src/test/java/com/synopsys/integration/alert/channel/email/EmailChannelChannelDescriptorTestIT.java, src/test/java/com/synopsys/integration/alert/channel/email/EmailChannelTestIT.java, src/test/java/com/synopsys/integration/alert/channel/email/EmailGlobalTestActionTest.java, src/test/java/com/synopsys/integration/alert/database/api/ProviderDataAccessorTestIT.java
- Retrieve the Black Duck data on demand, instead of syncing the Black Duck data with the Alert database
* Leave the old DefaultProviderDataAccessor in place in case we need to switch back to it
* Add a new BlackDuckProviderDataAccessor to replace the DefaultProviderDataAccessor
* The BlackDuckProviderDataAccessor will retrieve the Project and User data from Black Duck as needed
=> On demand data

alert-common/src/main/java/com/synopsys/integration/alert/common/rest/api/ReadPageController.java, alert-common/src/main/java/com/synopsys/integration/alert/common/rest/model/AlertPagedModel.java, alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultNotificationAccessor.java, component/src/main/java/com/synopsys/integration/alert/component/audit/web/AuditEntryActions.java
Fixes IALERT-2008
In the method `DefaultNotificationAccessor::getPageRequestForNotifications` the paging parameters are `@Nullable`, this should not be the case and default value handling should happen at a higher level.
- Move default value handling higher into the API
- Change default page size from `Integer.MAX_VALUE` to `10`. Uses the constant defined in `AuditEntryPageModel`.
=> Remove default value handling from DefaultNotificationAccessor

ui/src/main/js/store/actions/distributionConfigs.js, ui/src/main/js/util/httpErrorUtilities.js
containsErrors now checks to see if there are errors in the list and modifies the hasErrors field from the response object. This way it will throw an error message if at least one of the messages has a severity of error. Likewise, if there are no severities as in the case of a backend test message it will continue to return the hasErrors field. I've also verified this is working correctly in the case of an error and warning produced at the same time.
=> Fix back-end errors coming up as success messages in the UI

component/src/main/java/com/synopsys/integration/alert/component/authentication/web/AuthenticationActions.java, web/src/main/java/com/synopsys/integration/alert/web/api/home/HomeActions.java
Fixed an issue where users who do not have a role set are able to still log into Alert by refreshing the page.  We have validated this for regular alert users as well as SAML and LDAP.
=> Fix unauthorized users logging into Alert

alert-common/src/main/java/com/synopsys/integration/alert/common/action/api/AbstractJobResourceActions.java, ui/src/main/js/distribution/Index.js, ui/src/main/js/dynamic/DistributionConfiguration.js
Copying a job was allowing you to create jobs with duplicate names.
=> Fixing an issue when you copy a job

component/src/main/java/com/synopsys/integration/alert/component/authentication/actions/AuthenticationTestAction.java
Hiding the Additional details message if the exception message is null or empty.
=> Fixing the LDAP configuration validation message

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/util/ConfigurationFieldModelConverter.java, src/test/java/com/synopsys/integration/alert/web/api/job/JobConfigActionsTest.java, web/src/main/java/com/synopsys/integration/alert/web/api/config/ConfigActions.java, web/src/main/java/com/synopsys/integration/alert/web/api/job/JobConfigActions.java
Per IALERT-2011, we want to change ConfigurationFieldModelConverter.getDescriptorName to throw a runtime exception rather than an AlertDatabaseConstraintException. We do not want this exception because if we trace it up to where the ConfigurationModel that is being passed in comes from, it will come from a database read where an option check has already been performed (in DefaultDescriptorGlobalConfigUtility).
=> Change ConfigurationFieldModelConverter to throw a Runtime exception

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/endpoint/table/TableSelectColumn.java, alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/endpoint/table/model/ProviderProjectSelectOption.java, alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/ui/ProviderDistributionUIConfig.java, channel/src/main/java/com/synopsys/integration/alert/channel/email/descriptor/EmailDistributionUIConfig.java, provider/src/main/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckDistributionUIConfig.java, ui/src/main/js/field/input/TableSelectInput.js, web/src/main/java/com/synopsys/integration/alert/web/api/provider/project/ProviderProjectCustomFunctionAction.java
Allow hidden columns to be defined through code and add hidden href column for provider projects.
This is a prelude to saving the href on the back-end.
=> Include href in provider projects table (hidden)

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/accessor/AuditAccessor.java, alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/AuditJobStatusModel.java, alert-common/src/main/java/com/synopsys/integration/alert/common/rest/model/AuditJobStatusesModel.java, alert-common/src/main/java/com/synopsys/integration/alert/common/rest/model/JobIdsRequestModel.java, alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultAuditAccessor.java, alert-database/src/main/java/com/synopsys/integration/alert/database/audit/AuditEntryEntity.java, alert-database/src/main/java/com/synopsys/integration/alert/database/audit/AuditEntryRepository.java, component/src/main/java/com/synopsys/integration/alert/component/audit/web/AuditEntryActions.java, component/src/main/java/com/synopsys/integration/alert/component/audit/web/AuditEntryController.java, src/test/java/com/synopsys/integration/alert/component/audit/JobAuditModelTest.java, src/test/java/com/synopsys/integration/alert/component/audit/mock/MockAuditJobStatusModel.java, src/test/java/com/synopsys/integration/alert/web/api/job/JobConfigActionsTest.java, ui/src/main/js/store/actions/distributions.js, web/src/main/java/com/synopsys/integration/alert/web/api/job/JobConfigActions.java, web/src/main/java/com/synopsys/integration/alert/web/api/job/JobConfigController.java
This is to minimize network latency and remove the odd-looking loading of one row at a time.
=> Request all job-audit data at once

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/accessor/JobAccessorV2.java, alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/job/DistributionJobModel.java, alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/job/DistributionJobModelData.java, alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/job/DistributionJobRequestModel.java, alert-database/src/main/java/com/synopsys/integration/alert/database/api/StaticJobAccessor.java, alert-database/src/main/java/com/synopsys/integration/alert/database/api/StaticJobAccessorV2.java, alert-database/src/main/java/com/synopsys/integration/alert/database/job/blackduck/BlackDuckJobDetailsAccessor.java
* Create new `JobAccessor` interface: `JobAccessorV2`
* Create new `JobAccessorV2` implementation: `StaticJobAccessorV2`
* Don't carry over `JobAccessor::getAllJobs` or `JobAccessor::getJobsByFrequency`
Classes that currently use `JobAccessor` will be incrementally updated in future PR's to utilize these new classes.
=> Jm job accessor refactor

buildSrc/src/main/java/com/synopsys/integration/alert/build/CreateKeystoreTask.java
Makes the certificate a root certificate that is a CA.  Also added SubjectAlternativeName values.  This allows the certificate to be accepted by the chrome browser.  The MacOS would block the certificate with the Catalina OS update in a chrome browser.  This will give the option to accept the certificate.
=> Fix the self-signed cert to be a root certificate with SAN values.

provider/src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/builder/VulnerabilityNotificationMessageBuilder.java
https://jira-sig.internal.synopsys.com/browse/IALERT-2083
This is a temporary work around to Blackduck 2020.10.0 removing the: 
GET /api/components/{componentId}/versions/{componentVersionId}/remediating endpoint. In this version calling the endpoint will return to the user a 410 GONE. 
In the future the blackduck api team recommends that we switch to:
GET /api/components/{componentId}/versions/{componentVersionId}/upgrade-guidance.
The purpose for this change is to still allow us to send messages even if remediation fails. Currently if that step fails, Alert will not send any notifications for vulnerabilities in 2020.10 or greater.
=> Ignore remediation data from Blackduck 2020.10.*+

provider/src/main/java/com/synopsys/integration/alert/provider/blackduck/BlackDuckProviderDataAccessor.java
We used to do this when the projects were synced. Long descriptions bloat the table in the UI.
=> Truncate provider project descriptions

alert-common/src/main/java/com/synopsys/integration/alert/common/provider/lifecycle/ProvidersMissingTask.java, alert-common/src/main/java/com/synopsys/integration/alert/common/workflow/task/ScheduledTask.java
The desire was to have `ProvidersMissingTask` validate on startup and only validate every hour instead of every minute.
`ProvidersMissingTask` already extends `StartupScheduledTask` so the `StartupScheduledTask::postTaskStartup` needed to be implemented.
=> Update the ProvidersMissingTask validation

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/job/DistributionJobModel.java, alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/job/DistributionJobModelData.java, alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/job/details/DistributionJobDetailsModel.java, alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/job/details/DistributionJobDetailsModelDeserializer.java, alert-common/src/test/java/com/synopsys/integration/alert/common/persistence/model/job/details/DistributionJobDetailsModelDeserializerTest.java
- JMS uses Gson to serialize/deserialize
- DistributionJobDetailsModel is an abstract class, so it cannot be deserialized by Gson out of the box
- A custom type adapter allows abstract classes to be deserialized
=> Add deserializer for DistributionJobDetailsModel

alert-common/src/main/java/com/synopsys/integration/alert/common/AlertProperties.java, deployment/helm/synopsys-alert/templates/_helpers.tpl, deployment/helm/synopsys-alert/templates/alert-environ-configmap.yaml
If the User manually configures the exposed Node port this change will allow us to grab that value by setting an environment variable and we can then use that when constructing the URL's that we expose in Alert. This addresses the issues with the links in the emails we send out, the callback URL for Azure, and the Swagger doc link.
Thank you Paulo for the assistance with these changes.
=> Helm exposed Node port

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/accessor/JobAccessorV2.java, alert-database/src/main/java/com/synopsys/integration/alert/database/api/StaticJobAccessorV2.java, alert-database/src/test/java/com/synopsys/integration/alert/database/api/StaticJobAccessorV2Test.java, src/test/java/com/synopsys/integration/alert/channel/ChannelDescriptorTestIT.java
Added test for StaticJobAccessor.
This will allow us to safely remove the DefaultJobAccessor.
=> refactor(job-accessor): Added StaticJobAccessorV2Test.

build.gradle, component/src/main/java/com/synopsys/integration/alert/component/authentication/security/AuthenticationHandler.java, ui/package-lock.json, ui/package.json
The SAML post binding uses an auto-submit form that requires inline javascript to be executed to communicate with the IDP as part of the SAML Login process.  Add the header to allow the inline execution of javascript for the auto-submit form to work for SAML IDP providers like Azure.
=> Add content-security-policy header and allow inline script execution

src/main/resources/application.properties, workflow/src/main/java/com/synopsys/integration/alert/workflow/message/NotificationReceiver.java
Per this mornings discussion, I've updated NotificationReciever to timeout after 2 hours of running. Also I've updated the time-to-live for the jms messages to now be 4 hours long.
I will add a new ticket to the 6.5.0 changes to change this timeout back to 2 minutes.
=> NotificationReciever timeout

processor-api/src/main/java/com/synopsys/integration/alert/processor/api/extract/model/SimpleMessage.java, processor-api/src/main/java/com/synopsys/integration/alert/processor/api/summarize/ProjectMessageSummarizer.java, processor-api/src/test/java/com/synopsys/integration/alert/processor/api/ProviderMessageHolderTest.java
If a `SimpleMessage` is derived, its source can be used by consumers to determine specific (strongly-typed) details about it.
=> Add source for simple messages

channel/src/main/java/com/synopsys/integration/alert/channel/msteams2/MSTeamsChannelMessageConverter.java, channel/src/main/java/com/synopsys/integration/alert/channel/msteams2/MSTeamsChannelMessageModel.java, channel/src/main/java/com/synopsys/integration/alert/channel/msteams2/MSTeamsChannelMessageSection.java, channel/src/main/java/com/synopsys/integration/alert/channel/msteams2/MSTeamsChannelMessageSender.java
An `MSTeamsChannelMessageModel` now contains message sections and titles. This allows the entire message to be constructed in `MSTeamsChannelMessageConverter` rather than partially in the `MSTeamsChannelMessageSender`.
This PR also removes the need to complete IALERT-2247 (Add provider field to ProviderMessageHolder) as the `ProviderDetails` are no longer needed in `MSTeamsChannelMessageSender`.
=> Jm ms teams improvements

channel/src/main/java/com/synopsys/integration/alert/channel/jira2/cloud/delegate/JiraCloudIssueCommenter.java, channel/src/main/java/com/synopsys/integration/alert/channel/jira2/common/delegate/JiraIssueCommenter.java, channel/src/main/java/com/synopsys/integration/alert/channel/jira2/server/delegate/JiraServerIssueCommenter.java
`JiraIssueCommenter` is abstract. Instead of passing in a ThrowableConsumer to add the comments via IssueService, we should use another abstract method.
=> Abstract Commenter

channel-api/src/main/java/com/synopsys/integration/alert/channel/api/issue/model/IssueCommentModel.java, channel-api/src/main/java/com/synopsys/integration/alert/channel/api/issue/send/IssueTrackerIssueCommenter.java, channel-api/src/main/java/com/synopsys/integration/alert/channel/api/issue/send/IssueTrackerIssueCreator.java, channel-api/src/main/java/com/synopsys/integration/alert/channel/api/issue/send/IssueTrackerIssueResponseCreator.java, channel-api/src/test/java/com/synopsys/integration/alert/channel/api/issue/IssueTrackerChannelTest.java, channel/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/delegate/AzureBoardsIssueCommenter.java, channel/src/main/java/com/synopsys/integration/alert/channel/jira/common/distribution/delegate/JiraIssueCommenter.java
Issue-Tracker post-create comments are ignored if no "source" is present
Source should become optional (its usage in the commenter is to create the IssueTrackerIssueResponseModel in which it is optional).
IALERT-2337
=> Fix Issue-Tracker post-create comments being ignored

alert-common/src/main/java/com/synopsys/integration/alert/common/workflow/MessageReceiver.java
IALERT-2218
Constrained `MessageReceiver` to accept `AlertEvent`s to allow the EventID to be logged.
All usages of `MessageReceiver` currently pass in `AlertEvent`s.
=> Constrain MessageReceiver to AlertEvents

alert-common/src/main/java/com/synopsys/integration/alert/common/action/ConfigurationAction.java, alert-common/src/main/java/com/synopsys/integration/alert/common/channel/DistributionChannelTestAction.java, alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/DescriptorProcessor.java, alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/action/DescriptorAction.java, alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/action/DescriptorActionMap.java, channel-api/src/main/java/com/synopsys/integration/alert/channel/api/action/DistributionChannelMessageTestAction.java, channel-api/src/main/java/com/synopsys/integration/alert/channel/api/issue/action/IssueTrackerTestAction.java, channel/src/main/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsConfigurationAction.java, channel/src/main/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsDistributionTestAction.java, channel/src/main/java/com/synopsys/integration/alert/channel/email/action/EmailConfigurationAction.java, channel/src/main/java/com/synopsys/integration/alert/channel/email/action/EmailDistributionTestAction.java, channel/src/main/java/com/synopsys/integration/alert/channel/email/action/EmailTestActionHelper.java, channel/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/action/JiraCloudConfigurationAction.java, channel/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/action/JiraCloudDistributionTestAction.java, channel/src/main/java/com/synopsys/integration/alert/channel/jira/server/action/JiraServerConfigurationAction.java, channel/src/main/java/com/synopsys/integration/alert/channel/jira/server/action/JiraServerDistributionTestAction.java, channel/src/main/java/com/synopsys/integration/alert/channel/msteams/actions/MSTeamsDistributionTestAction.java, channel/src/main/java/com/synopsys/integration/alert/channel/msteams/actions/MsTeamsConfigurationAction.java, channel/src/main/java/com/synopsys/integration/alert/channel/slack/action/SlackConfigurationAction.java, channel/src/main/java/com/synopsys/integration/alert/channel/slack/action/SlackDistributionTestAction.java, src/test/java/com/synopsys/integration/alert/channel/ChannelDescriptorTestIT.java, src/test/java/com/synopsys/integration/alert/channel/Channel_ComprehensiveRequirements_ITTest.java, src/test/java/com/synopsys/integration/alert/channel/Channel_ComprehensiveRequirements_TestIT.java, src/test/java/com/synopsys/integration/alert/channel/email/EmailChannelChannelDescriptorTestIT.java, src/test/java/com/synopsys/integration/alert/channel/slack/SlackChannelChannelDescriptorTestIT.java, src/test/java/com/synopsys/integration/alert/web/api/job/JobConfigActionsTest.java, web/src/main/java/com/synopsys/integration/alert/web/api/job/JobConfigActions.java
- In 6.4.0, the introduction of concrete classes for Distribution Jobs created an opportunity for improving "TestActions". Up until this point, all TestActions took a FieldModel and FieldUtility as parameters, but now they could take in a DistributionJobModel. A separate class was created for Distribution TestActions (i.e. TestActions that distributed a message based on a Distribution Job's fields). 
- The class ConfigurationAction used to manage all actions of a single "descriptor" and it did this with TestActions by putting them into a Map from Context to TestAction. With the introduction of a new class for Channel DistributionTestActions, the Map was no longer useful.
- In making these changes, it became apparent that these classes existed primarily to serve the dynamic UI.
- The class …
=> Improve generic usage of configuration test actions

channel/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudPropertiesFactory.java, channel/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/action/JiraCloudDistributionTestAction.java, channel/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/distribution/JiraCloudMessageSenderFactory.java, channel/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/distribution/JiraCloudProcessorFactory.java
- Created a `JiraCloudMessageSenderFactory` with code pulled from `JiraCloudProccesorFactory`
- Implemented the new `IssueTrackerTestAction`
- Added a no-args method for creating `JiraCloudProperties`
=> Jm jira cloud test action

provider/src/main/java/com/synopsys/integration/alert/provider/blackduck/factory/BlackDuckPropertiesFactory.java, provider/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/NotificationExtractorBlackDuckServicesFactoryCache.java, provider/src/main/java/com/synopsys/integration/alert/provider/blackduck/web/BlackDuckProjectCustomFunctionAction.java, src/main/java/com/synopsys/integration/alert/BlackDuckConfiguration.java, src/test/java/com/synopsys/integration/alert/provider/blackduck/TestBlackDuckProperties.java
It was conflicting with Spring's ObjectMapper for deserialization of REST requests.
=> Remove BlackDuck ObjectMapper from Spring Components

build.gradle
Resolve the correct view name for the Azure Boards OAuth redirect to avoid a timeout.
=> thymeleaf fix

alert-common/build.gradle, alert-database/build.gradle, build.gradle, channel-api/build.gradle, channel/build.gradle, component/build.gradle, processor-api/build.gradle, provider/build.gradle, test-common/build.gradle, web/build.gradle, workflow/build.gradle
Changing dependencies in test-common from implementation to api in order to remove duplicate testImplementations in other sub projects.
=> Update test-common to use api depedencies

alert-database/build.gradle, build.gradle
For more flexibility we should split the all task into separate pieces, one to build and one to publish
=> Splitting the "all" task in to "buildAll" and "publishDockerImage".

.gitignore, src/test/java/com/synopsys/integration/alert/util/TestPropertiesFileGenerator.java, test-common/src/main/java/com/synopsys/integration/alert/test/common/TestProperties.java, test-common/src/main/java/com/synopsys/integration/alert/test/common/TestResourceUtils.java
Notice this is a _main_ resource and not a _test_ resource. This is because _test-common_ is a library and not a set of actual tests.
=> Load test.properties from test-common

api-channel-issue-tracker/src/main/java/com/synopsys/integration/alert/api/channel/issue/convert/IssuePolicyDetailsConverter.java, api-channel-issue-tracker/src/test/java/com/synopsys/integration/alert/api/channel/issue/convert/IssuePolicyDetailsConverterTest.java, api-channel-issue-tracker/src/test/java/com/synopsys/integration/alert/api/channel/issue/convert/ProjectIssueModelConverterTest.java, api-channel-issue-tracker/src/test/java/com/synopsys/integration/alert/api/channel/issue/convert/ProjectMessageToIssueModelTransformerTest.java, api-channel/src/test/java/com/synopsys/integration/alert/api/channel/convert/BomComponentDetailConverterTest.java, api-channel/src/test/java/com/synopsys/integration/alert/api/channel/convert/ProjectMessageConverterTest.java, api-processor/src/main/java/com/synopsys/integration/alert/processor/api/extract/model/project/ComponentPolicy.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/distribution/search/AzureBoardsSearcherTest.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/service/policy/BlackDuckComponentPolicyDetailsCreator.java
Added a nullable field in ComponentPolicy for description to be used in IssuePolicyDetailsConverter.
If no description is provided in the blackduck policy, the description field will not be printed
=> Add policy description to issue tracker descriptions

ui/src/main/js/common/table/TableDisplay.js, ui/src/main/js/page/user/UserTable.js, ui/src/main/js/store/reducers/users.js
Status wasn't showing why you couldn't delete the main users. Added a status bar to show this info.
This class needs to be rewritten with hooks and without the TableDisplay dependency.
=> Temporary fix for Users table delete

channel-email/src/main/java/com/synopsys/integration/alert/channel/email/distribution/ProjectMessageToMessageContentGroupConversionUtils.java
While working on upgrade guidance changes I noticed that in the following code we were creating a List<LinkableItem>. componentAttributes but did nothing with this list. I believe this was overlooked and have added in the builder step to apply the componentAttributes.
This change impacts the email attachment json file where the attributes was previously left blank.
=> Add missing builder method for ComponentItemBuilder

api-channel-issue-tracker/src/main/java/com/synopsys/integration/alert/api/channel/issue/model/IssueBomComponentDetails.java, api-channel-issue-tracker/src/test/java/com/synopsys/integration/alert/api/channel/issue/IssueTrackerModelExtractorTest.java, api-channel-issue-tracker/src/test/java/com/synopsys/integration/alert/api/channel/issue/callback/IssueTrackerCallbackInfoCreatorTest.java, api-channel-issue-tracker/src/test/java/com/synopsys/integration/alert/api/channel/issue/convert/IssuePolicyDetailsConverterTest.java, api-channel-issue-tracker/src/test/java/com/synopsys/integration/alert/api/channel/issue/convert/ProjectIssueModelConverterTest.java, api-channel-issue-tracker/src/test/java/com/synopsys/integration/alert/api/channel/issue/convert/ProjectMessageToIssueModelTransformerTest.java, api-channel-jira/src/main/java/com/synopsys/integration/alert/api/channel/jira/distribution/custom/MessageReplacementValues.java, api-channel-jira/src/main/java/com/synopsys/integration/alert/api/channel/jira/distribution/custom/MessageValueReplacementResolver.java, api-channel-jira/src/main/java/com/synopsys/integration/alert/api/channel/jira/distribution/delegate/JiraIssueCreator.java, api-channel-jira/src/test/java/com/synopsys/integration/alert/api/channel/jira/distribution/custom/MessageValueReplacementResolverTest.java, api-channel/src/main/java/com/synopsys/integration/alert/api/channel/convert/BomComponentDetailConverter.java, api-channel/src/test/java/com/synopsys/integration/alert/api/channel/convert/BomComponentDetailConverterTest.java, api-channel/src/test/java/com/synopsys/integration/alert/api/channel/convert/ProjectMessageConverterTest.java, api-processor/src/main/java/com/synopsys/integration/alert/processor/api/extract/model/project/AbstractBomComponentDetails.java, api-processor/src/main/java/com/synopsys/integration/alert/processor/api/extract/model/project/BomComponentDetails.java, api-processor/src/main/java/com/synopsys/integration/alert/processor/api/extract/model/project/ComponentUpgradeGuidance.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/distribution/search/AzureBoardsComponentIssueFinderTest.java, channel-email/src/main/java/com/synopsys/integration/alert/channel/email/distribution/ProjectMessageToMessageContentGroupConversionUtils.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/AbstractRuleViolationNotificationMessageExtractor.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/BomEditNotificationMessageExtractor.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/PolicyOverrideNotificationMessageExtractor.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/VulnerabilityNotificationMessageExtractor.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/service/BlackDuckMessageBomComponentDetailsCreator.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/service/BlackDuckMessageComponentVersionUpgradeGuidanceService.java, provider-blackduck/src/test/java/com/synopsys/integration/alert/provider/blackduck/processor/message/service/BlackDuckMessageComponentVersionUpgradeGuidanceServiceTest.java, ui/src/main/js/common/input/FieldMappingField.js, ui/src/main/js/page/channel/jira/cloud/JiraCloudDistributionConfiguration.js, ui/src/main/js/page/channel/jira/server/JiraServerDistributionConfiguration.js
Removed upgrade guidance from additional attributes and created a new object ComponentUpgradeGuidance to hold the values. This ticket was to track refactoring the places it was previously used and updating the tests.
Lastly, we implemented the changes in the  MessageValueReplacementResolver, MessageReplacementValues and its builder, and in JiraIssueCreator.
UI updates to refer to the docs will be made in a separate PR.
=> Create ComponentUpgradeGuidance and implement it as a custom field replacment

provider-blackduck/src/test/java/com/synopsys/integration/alert/provider/blackduck/processor/NotificationExtractorBlackDuckServicesFactoryCacheTest.java, provider-blackduck/src/test/java/com/synopsys/integration/alert/provider/blackduck/processor/model/BomEditWithProjectNameNotificationContentTest.java, provider-blackduck/src/test/java/com/synopsys/integration/alert/provider/blackduck/processor/model/PolicyOverrideUniquePolicyNotificationContentTest.java, provider-blackduck/src/test/java/com/synopsys/integration/alert/provider/blackduck/processor/model/RuleViolationClearedUniquePolicyNotificationContentTest.java, provider-blackduck/src/test/java/com/synopsys/integration/alert/provider/blackduck/processor/model/RuleViolationUniquePolicyNotificationContentTest.java, provider-blackduck/src/test/java/com/synopsys/integration/alert/provider/blackduck/processor/model/VulnerabilityUniqueProjectNotificationContentTest.java
Adding tests for classes in processor/model package. 
Also, I added one test outside of this package for the NotificationExtractorBlackDuckServicesFactoryCache to verify the cache would return a copy of the BlackDuckServicesFactory.
=> provider-blackduck processor/model package tests

ui/src/main/js/application/auth/BlackDuckSSOConfigImportModal.js
The entity ID doesn't always match what's pulled in from BD leading to issues setting up SAML
=> Removed the Entity ID from the BlackDuck import functionality

api-processor/src/test/java/com/synopsys/integration/alert/processor/api/summarize/ProjectMessageSummarizerTest.java
Added coverage for the ProjectMessageSummarizer under api-processor. The test is broken into several parts to ensure coverage and covering several other cases.
- We are testing the multiple message reasons to ensure the summary and description contain the correct relevant information. (Project Status, Project Version Status, Component Update, Component Concern) 
- For components we are also verifying that the correct information is used for the label in the LinkableItem
- Lastly we are verifying if there are multiple operations with the same ComponentConcernSummaryGrouping that they are correctly added to the value in the LinkableItem
To avoid matching specific strings I have been using the String.contains method to verify if key pieces of information are present in the Strings.
=> api-processor summarize test coverage

provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/VulnerabilityNotificationMessageExtractor.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/service/BlackDuckMessageBomComponentDetailsCreator.java
Azure uses a querly URL to determine which issues need to be updated. Our Extractor tool was not using consistent URLs when it couldn't find a specific bom component
=> Modified the Notification extraction service to fix Azure lookup

ui/src/main/js/page/audit/Details.js
If a user is missing audit "EXECUTE" permissions, we will disable the button.
=> Disable audit resend from Details modal

src/test/java/com/synopsys/integration/alert/processing/NotificationReceivedEventHandlerTestIT.java
The test had the transactional annotation which caused the test to behave in a way that we were not testing what we were expecting exactly.  Have to re-write the setup of the tests to create a real provider configuration, use the configuration in the notification content, then invoke the processor. Also need to remove the transactional annotation from the test class since that was causing issues with the data saved in the database and the thread used to execute the processor.
=> test: Rewrite test to use transactional boundaries correctly.

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/accessor/UniqueConfigurationAccessor.java, alert-common/src/main/java/com/synopsys/integration/alert/common/rest/api/StaticUniqueConfigResourceController.java, alert-database/src/main/java/com/synopsys/integration/alert/database/settings/proxy/SettingsProxyConfigurationRepository.java, component/src/main/java/com/synopsys/integration/alert/component/settings/proxy/action/SettingsProxyCrudActions.java, component/src/main/java/com/synopsys/integration/alert/component/settings/proxy/database/accessor/SettingsProxyConfigAccessor.java, component/src/main/java/com/synopsys/integration/alert/component/settings/proxy/web/SettingsProxyController.java, component/src/test/java/com/synopsys/integration/alert/component/settings/proxy/actions/SettingsProxyCrudActionsTest.java, src/test/java/com/synopsys/integration/alert/component/settings/proxy/web/SettingsProxyControllerTestIT.java, ui/src/main/js/page/settings/standalone/SettingsProxyConfiguration.js
Update proxy configuration to use only a single configuration and remove the id field. In addition, we've created a "Unique" controller and accessor interfaces to better deal with configurations that do not have an ID.
=> Proxy controller refactor

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/accessor/ConfigurationAccessor.java, alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/accessor/UniqueConfigurationAccessor.java, alert-common/src/main/java/com/synopsys/integration/alert/common/rest/AlertRestConstants.java, channel-email/src/main/java/com/synopsys/integration/alert/channel/email/distribution/EmailChannelMessageSender.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/action/EmailGlobalConfigurationActionTest.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/distribution/EmailChannelTestIT.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/validator/EmailGlobalConfigurationValidatorTest.java, component/src/main/java/com/synopsys/integration/alert/component/settings/proxy/database/accessor/SettingsProxyConfigAccessor.java, component/src/test/java/com/synopsys/integration/alert/component/settings/proxy/actions/SettingsProxyCrudActionsTest.java, component/src/test/java/com/synopsys/integration/alert/component/settings/proxy/validator/SettingsProxyValidatorTest.java, src/main/java/com/synopsys/integration/alert/update/UpdateEmailService.java, src/test/java/com/synopsys/integration/alert/component/settings/proxy/web/SettingsProxyControllerTestIT.java
Rather than have to call the accessor interfaces for the default configuration name, we've moved it into a single location in AlertRestConstants.
=> Move default configuration name into a single constants file

alert-common/src/main/java/com/synopsys/integration/alert/common/message/model/ConfigurationTestResult.java, alert-common/src/main/java/com/synopsys/integration/alert/common/rest/api/ConfigurationTestHelper.java, alert-common/src/test/java/com/synopsys/integration/alert/common/rest/api/TestHelperConfigurationTest.java, channel-email/src/main/java/com/synopsys/integration/alert/channel/email/action/EmailGlobalTestAction.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/action/EmailGlobalTestActionTest.java
We will now use ConfigurationTestResult to determine success or failure for the ConfigurationTestHelper. MessageResult is still required and will be converted to the new object in the implementing classes such as EmailGlobalTestAction.
=> Improve Test Configuration to use a new status object

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/job/FilteredDistributionJobResponseModel.java, alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultProcessingJobAccessor.java, alert-database/src/main/java/com/synopsys/integration/alert/database/job/DistributionJobRepository.java, api-processor/src/main/java/com/synopsys/integration/alert/processor/api/detail/DetailedNotificationContent.java, api-processor/src/main/java/com/synopsys/integration/alert/processor/api/filter/JobNotificationFilterUtils.java, api-processor/src/test/java/com/synopsys/integration/alert/processor/api/NotificationProcessorTest.java, api-processor/src/test/java/com/synopsys/integration/alert/processor/api/detail/DetailedNotificationContentTest.java, api-processor/src/test/java/com/synopsys/integration/alert/processor/api/filter/JobNotificationFilterUtilsTest.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/action/BlackDuckDistributionFieldModelTestAction.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/detail/BomEditNotificationDetailExtractor.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/detail/ComponentUnknownVersionNotificationDetailExtractor.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/detail/PolicyOverrideNotificationDetailExtractor.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/detail/ProjectNotificationDetailExtractor.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/detail/ProjectVersionNotificationDetailExtractor.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/detail/RuleViolationClearedNotificationDetailExtractor.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/detail/RuleViolationNotificationDetailExtractor.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/detail/VulnerabilityNotificationDetailExtractor.java, src/test/java/com/synopsys/integration/alert/database/api/ProcessingJobAccessorTestIT.java, src/test/java/com/synopsys/integration/alert/processor/api/filter/JobNotificationMapperTestIT.java
Adds a configuration option to allow users to filter by project version name
Filters on version after filtering by project name
Adds a warning to the test action in the case a matching version is not found
=> Bm filter by version

channel-email/src/main/java/com/synopsys/integration/alert/channel/email/action/EmailGlobalTestAction.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/action/EmailGlobalTestActionTest.java
Fixes issue when attempting to test a configuration after saving. Note: Right now this will use the default configuration for the global email channel which will resolve the issue in the UI. I have left a TODO comment to find a better solution once we support multiple configurations in the UI. 
Perhaps as a future solution we could determine which configuration is "in view" and use the ID to get the correct configuration from the database.
=> Use default Email SMTP password when testing saved configuration

src/main/java/com/synopsys/integration/alert/update/UpdateChecker.java, src/test/java/com/synopsys/integration/alert/update/UpdateCheckerTest.java
Update the logic to find the first hyphen to extract the version.
=>  Fix the update test to handle unique tag snapshot builds.

provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/service/BlackDuckMessageBomComponentDetailsCreator.java, provider-blackduck/src/test/java/com/synopsys/integration/alert/provider/blackduck/processor/message/VulnerabilityNotificationMessageExtractorTest.java
Create the older vulnerabilities links from previous versions of Alert if there are no origins in the notification for the bom component.  This ensures that a ticket is created by the issue tracker for the component.
=> fix: If the origins list is empty create the old vulnerabilities link.

alert-database/build.gradle
alertDatabaseDockerImageVersion is defined as a local variable, which prevents us from getting this value using `./gradlew -p alert-database properties`. This is desired in order to automate getting the value of alertDatabaseDockerImageVersion for use in PoP builds.
With this change, we are able to retrieve this value AND the image is created with the correct version.
=> build: Adjust alertDatabaseDockerImageVersion to be a property

alert-common/src/main/java/com/synopsys/integration/alert/common/action/ValidationActionResponse.java, alert-common/src/main/java/com/synopsys/integration/alert/common/rest/api/ConfigurationTestHelper.java
This is a fix where previously validation would find errors with the configuration and would instead continue testing causing 500 server errors being thrown to the user and logged stack traces when failures occurred.
=> Check if validation error exist when testing the configurations

alert-platform/build.gradle, build.gradle, src/test/java/com/synopsys/integration/alert/processing/JmsNotificationReceiverTestIT.java, src/test/java/com/synopsys/integration/alert/util/AlertIntegrationTest.java, src/test/resources/spring-test.properties
Test containers can be configured for JDBC through the URLS.  However testcontainers needs a few dependencies to be able to start the containers at the beginning of each test.
https://www.testcontainers.org/modules/databases/jdbc/
You still need the correct dependencies with spring boot to start the container before each test:
https://github.com/Playtika/testcontainers-spring-boot
=> testcontainers config to start the container before the tests

component/src/main/java/com/synopsys/integration/alert/component/settings/encryption/action/SettingsEncryptionCrudActions.java
This is to cover an edge case during new installations where the customer does not use encryption settings and has not set up an alert_encryption_data.json file. This file would normally get created during the write but due to how we have implemented the ConfigurationCrudHelper we would perform check to see if the configuration exists (which will always fail and the update never runs). 
Due to the unique nature of encryption, we will only perform updates. Checking the configuration does not matter for the update since the encryptionUtility handles all the functionally of saving these values or getting  them back from the environment. For this reason, we've made the existing configuration supplier always return  true.
=> Fix update encryption  settings when default configuration was missing

channel-email/src/main/java/com/synopsys/integration/alert/channel/email/action/EmailGlobalCrudActions.java, channel-email/src/main/java/com/synopsys/integration/alert/channel/email/action/EmailGlobalTestAction.java, channel-email/src/main/java/com/synopsys/integration/alert/channel/email/convert/EmailGlobalConfigurationModelSaveActions.java, channel-email/src/main/java/com/synopsys/integration/alert/channel/email/database/accessor/EmailGlobalConfigAccessor.java, channel-email/src/main/java/com/synopsys/integration/alert/channel/email/database/configuration/EmailConfigurationRepository.java, channel-email/src/main/java/com/synopsys/integration/alert/channel/email/distribution/EmailChannelMessageSender.java, channel-email/src/main/java/com/synopsys/integration/alert/channel/email/web/EmailGlobalConfigController.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/action/EmailGlobalConfigurationActionTest.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/action/EmailGlobalTestActionTest.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/convert/EmailGlobalConfigurationModelSaveActionsTest.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/distribution/EmailChannelTestIT.java, src/main/java/com/synopsys/integration/alert/update/UpdateEmailService.java, src/test/java/com/synopsys/integration/alert/channel/email/environment/EmailEnvironmentHandlerFactoryTestIT.java, src/test/java/com/synopsys/integration/alert/web/config/EmailConfigActionTestIT.java, ui/package.json, ui/src/main/js/page/channel/email/EmailGlobalConfiguration.js
Remove the support for multiple email configs in favor of a single entity that is always updated.
=> Bm convert email single config

component/src/main/java/com/synopsys/integration/alert/component/settings/proxy/validator/SettingsProxyValidator.java, component/src/test/java/com/synopsys/integration/alert/component/settings/proxy/validator/SettingsProxyValidatorTest.java
This is to catch a case where the optional field is present, but empty. This occurs if the field was saved, but later erased and re-saved.
=> Change validation for proxy model to ignore checking password if username is blank

alert-database/src/main/java/com/synopsys/integration/alert/database/settings/proxy/NonProxyHostsConfigurationRepository.java, component/src/main/java/com/synopsys/integration/alert/component/settings/proxy/database/accessor/SettingsProxyConfigAccessor.java, src/test/java/com/synopsys/integration/alert/component/settings/proxy/web/SettingsProxyControllerTestIT.java
When saving a proxy configuration, if you delete the non-proxy hosts we would revert back to all of the saved configurations.  In order to fix this issue we must add a delete before we perform the save all in the accessor. This is similar to  what we were already doing in the email global config with additional properties.
=> Non proxy host save fix

alert-database-job/src/main/java/com/synopsys/integration/alert/database/api/DefaultProcessingJobAccessor.java, api-processor/src/main/java/com/synopsys/integration/alert/processor/api/NotificationProcessor.java, api-processor/src/main/java/com/synopsys/integration/alert/processor/api/filter/JobNotificationMapper.java, component/src/test/java/com/synopsys/integration/alert/component/tasks/ProcessingTaskTest.java, src/test/java/com/synopsys/integration/alert/channel/email/environment/EmailEnvironmentHandlerFactoryTestIT.java, src/test/java/com/synopsys/integration/alert/processing/NotificationReceivedEventHandlerTest.java, src/test/java/com/synopsys/integration/alert/processor/api/filter/JobNotificationMapperTestIT.java
Removed a findAny statement that randomly picked which provider to use.
Removed unnecessary notifications from the wrapper when they did not apply to the job.
=> Fixed an issue with too many or not enough messages getting created by Alert with duplicate providers

channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/action/JiraServerGlobalTestAction.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/action/JiraServerGlobalTestActionTest.java, ui/src/main/js/page/channel/jira/server/ConcreteJiraServerGlobalConfiguration.js
- Fix the test action to read a password from the database if saved.
- Show cancel option when creating or editing a jira server configuration
=>  jira server fixes

ui/src/main/js/common/util/configurationRequestBuilder.js
It's possible that the queryParamValue is blank in the UI and therefore we should not be checking it along with the key. The UI will encode and make a request using "" as the value which is handled by the validators in the backend.
=> Front end blank value test config fixes for proxy/email 

alert-database/src/main/resources/liquibase/6.10.0/changelog.xml, alert-database/src/main/resources/liquibase/6.10.0/migrate-jira-server-global-config.xml
Update liquibase scripts to migrate jira jobs to use the new default configuration.
=> jira job migrate

channel-email/src/main/java/com/synopsys/integration/alert/channel/email/action/EmailGlobalTestAction.java, channel-email/src/main/java/com/synopsys/integration/alert/channel/email/convert/EmailGlobalConfigurationModelConverter.java, channel-email/src/main/java/com/synopsys/integration/alert/channel/email/database/accessor/EmailGlobalConfigAccessor.java, channel-email/src/main/java/com/synopsys/integration/alert/channel/email/distribution/EmailChannelMessageSender.java, channel-email/src/main/java/com/synopsys/integration/alert/channel/email/environment/EmailEnvironmentVariableHandler.java, channel-email/src/main/java/com/synopsys/integration/alert/channel/email/validator/EmailGlobalConfigurationValidator.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/action/EmailGlobalConfigurationActionTest.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/action/EmailGlobalTestActionTest.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/action/EmailGlobalValidationActionTest.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/convert/EmailGlobalConfigurationModelConverterTest.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/distribution/EmailChannelTestIT.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/validator/EmailGlobalConfigurationValidatorTest.java, service-email/src/main/java/com/synopsys/integration/alert/service/email/JavamailPropertiesFactory.java, service-email/src/main/java/com/synopsys/integration/alert/service/email/model/EmailGlobalConfigModel.java, service-email/src/test/java/com/synopsys/integration/alert/service/email/JavamailPropertiesFactoryTest.java, src/main/java/com/synopsys/integration/alert/update/UpdateEmailService.java, src/test/java/com/synopsys/integration/alert/channel/email/environment/EmailEnvironmentVariableHandlerTestIT.java, src/test/java/com/synopsys/integration/alert/web/config/EmailConfigActionTestIT.java
EmailGlobalConfigModel requires smtp from and smtp host to be set in in order to properly save the model to the database. This change brings the email configuration in line with the changes  we created for global models in 6.10.0. 
As an aside, some formatting changes are included in this release due to the style changes.
=> Update Email model to use required fields

alert-common/src/main/java/com/synopsys/integration/alert/common/action/api/AbstractJobResourceActions.java, alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/accessor/ConfigurationAccessor.java, alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/accessor/JobAccessor.java, alert-common/src/main/java/com/synopsys/integration/alert/common/rest/api/ReadPageController.java, alert-common/src/main/java/com/synopsys/integration/alert/common/util/SortUtil.java, alert-common/src/test/java/com/synopsys/integration/alert/common/ConfigurationFieldModelTest.java, alert-common/src/test/java/com/synopsys/integration/alert/common/util/DataStructureUtilsTest.java, alert-common/src/test/java/com/synopsys/integration/alert/common/util/DateUtilsTest.java, alert-common/src/test/java/com/synopsys/integration/alert/common/util/MarkupEncoderTest.java, alert-common/src/test/java/com/synopsys/integration/alert/common/util/PagingParamValidationUtilsTest.java, alert-common/src/test/java/com/synopsys/integration/alert/common/util/SortUtilTest.java, alert-database-job/src/main/java/com/synopsys/integration/alert/database/api/StaticJobAccessor.java, alert-database-job/src/test/java/com/synopsys/integration/alert/database/api/StaticJobAccessorTest.java, channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/action/JiraServerGlobalCrudActions.java, channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/database/accessor/JiraServerGlobalConfigAccessor.java, channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/database/configuration/JiraServerConfigurationRepository.java, channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/web/JiraServerGlobalConfigController.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/action/JiraServerGlobalCrudActionsTest.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/database/accessor/JiraServerGlobalConfigAccessorTest.java, src/test/java/com/synopsys/integration/alert/channel/jira/server/action/JiraServerGlobalCrudActionsTestIT.java, src/test/java/com/synopsys/integration/alert/channel/jira/server/web/JiraServerGlobalConfigControllerTestIT.java, src/test/java/com/synopsys/integration/alert/database/api/StaticJobAccessorTestIT.java, web/src/main/java/com/synopsys/integration/alert/web/api/job/JobConfigActions.java, web/src/main/java/com/synopsys/integration/alert/web/api/job/JobConfigController.java, web/src/test/java/com/synopsys/integration/alert/web/api/job/JobConfigActionsTest.java
This was already added to the master branch in PR 2054.  Back porting to v6.10.0
* feat: Add paging to the job and configuration accessor.
* refactor: Rename sortField to sortName.
* feat: Add search and sort to database query for jira server.
* chore: Clean up some code smells.
* test: Add tests for the search and sort of jobs.
* test: Add search and sort tests to crud actions.
* test: Add tests for search and sort.
* refactor: Encapsulate sort object creation.
* chore: Clean up code smells.
* chore: Adjust some formatting.
=> Add search and sort to the paging of Jira server (#2054)

alert-common/src/main/java/com/synopsys/integration/alert/common/util/SortUtil.java, channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/web/JiraServerCustomFunctionAction.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/web/JiraServerCustomFunctionActionTest.java
Fix the Old Jira Server Plugin install API.
Check if an id with a UUID is in the request payload.
Check if a configuration named "default-configuration" exists.  When upgrading from the prior version the upgrade will migrate the Jira Server configuration to the new table structure  and supply the name "default-configuration"
=> jira server api fix

ui/webpack.common.config.js
This PR reverts https://github.com/blackducksoftware/blackduck-alert/pull/2090.  I should not have touched the webpack.common.config file.  Instead I should have adjusted the webpack.dev.config file.
=> Reverting PR:2090

ui/src/main/js/page/audit/AuditPage.js, ui/webpack.common.config.js
This PR reverts the changes to the direct vs relative path for css files in the `webpack.common.config.js` file.
=> Reverting css direct path declaration in webpack common config file

api-event/src/main/java/com/synopsys/integration/alert/api/event/EventManager.java, api-event/src/test/java/com/synopsys/integration/alert/api/event/EventManagerTest.java, src/main/java/com/synopsys/integration/alert/configuration/ApplicationConfiguration.java, src/test/java/com/synopsys/integration/alert/performance/LargeNotificationTest.java, src/test/java/com/synopsys/integration/alert/performance/utility/BlackDuckProviderService.java, src/test/java/com/synopsys/integration/alert/processing/NotificationReceivedEventHandlerTest.java, src/test/java/com/synopsys/integration/alert/processing/NotificationReceivedEventHandlerTestIT.java
When implementing RabbitMQ the example code used a SyncTaskExecutor which makes everything synchronous.  Remove the bean to create the SyncTaskExecutor in order to use the default which is a ThreadPoolTaskExecutor.  This will make handling events from the queue multi-threaded to increase throughput.  
Also change the EventManager to use the TaskExecutor to post events onto the queue in a multi-threaded fashion.
=> Remove SyncTaskExecutor use default.

provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/BlackDuckProperties.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/action/BlackDuckDistributionFieldModelTestAction.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/task/accumulator/BlackDuckAccumulator.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/validator/BlackDuckApiTokenValidator.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/validator/BlackDuckSystemValidator.java, provider-blackduck/src/test/java/com/synopsys/integration/alert/provider/blackduck/action/BlackDuckDistributionFieldModelTestActionTest.java, src/test/java/com/synopsys/integration/alert/provider/blackduck/task/accumulator/BlackDuckAccumulatorTest.java, src/test/java/com/synopsys/integration/alert/startup/component/SystemValidatorTest.java
In the current implementation of Alert, we perform the full provider validation, which includes checking user/role permissions in BD, when configuring a provider, configuring a distribution, and on each launch of the accumulator.
Changes:
- New canConnect() method which checks the return http status code of connecting to BD using an API token.
- Use canConnect() first when communicating with an instance of BD
- Only call isApiTokenValid() from provider
- Update tests to reflect changes
- Add full coverage for canConnect()
=> IALERT-3051 - Only perform provider validation when configuring provider

src/test/java/com/synopsys/integration/alert/performance/utility/NotificationWaitJobTaskV2.java
Make the same change to wait for audit entries to be processing only.  That will measure how fast it takes to process the notifications.
=> Wait for when jobs are processing only.

provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/validator/BlackDuckApiTokenValidator.java
Update validation to use the inherited roles link instead of checking each project
Update validation to use a Predicate so the validation will succeed as soon as it finds a role that Alert requires.
=> IALERT-3001: Use corrected api link and succeed fast (Predicate)

provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/action/BlackDuckDistributionFieldModelTestAction.java, provider-blackduck/src/test/java/com/synopsys/integration/alert/provider/blackduck/action/BlackDuckDistributionFieldModelTestActionTest.java
While running a performance test the test of the provider tries to test the project name and project name version patterns.  this process connects to blackduck and reads the projects from blackduck.  The connectivity check was done after the pattern checks.  Move the connection check first because if you can't connect then you can't read project data from Black Duck.
=> fix: Check Black Duck connectivity before testing patterns.

channel-email/src/test/java/com/synopsys/integration/alert/channel/email/action/EmailGlobalTestActionTest.java, channel-jira-cloud/src/test/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudSummaryFieldLengthTestIT.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/JiraServerSummaryFieldLengthTestIT.java
* Disable test we can't run as we don't have SMTP server
* Improve readability/supportability for Jira summary length tests
=> Improve tests

component/src/main/java/com/synopsys/integration/alert/component/diagnostic/database/DefaultDiagnosticAccessor.java, component/src/main/java/com/synopsys/integration/alert/component/diagnostic/model/AuditDiagnosticModel.java, component/src/main/java/com/synopsys/integration/alert/component/diagnostic/model/DiagnosticComponentModel.java, component/src/main/java/com/synopsys/integration/alert/component/diagnostic/model/DiagnosticModel.java, component/src/main/java/com/synopsys/integration/alert/component/diagnostic/model/NotificationDiagnosticModel.java, component/src/test/java/com/synopsys/integration/alert/component/diagnostic/database/DefaultDiagnosticAccessorTest.java, src/test/java/com/synopsys/integration/alert/component/audit/repository/AuditEntryRepositoryTestIT.java, src/test/java/com/synopsys/integration/alert/component/diagnostic/action/DiagnosticCrudActionsTestIT.java, src/test/java/com/synopsys/integration/alert/database/notification/NotificationContentRepositoryTestIT.java
- DiagnosticModel is now made up of two new models, NotificationDiagnosticModel and AuditDiagnosticModel
- Added test coverage for diagnostic classes
- Added test coverage to repositories for new diagnostic calls
=> IALERT-3072: Break up diagnostic model into sub-components 

src/test/java/com/synopsys/integration/alert/performance/LargeNotificationTest.java, src/test/java/com/synopsys/integration/alert/performance/utility/BlackDuckProviderService.java, test-common/src/main/java/com/synopsys/integration/alert/test/common/TestPropertyKey.java
* Add new property 'TEST_PERFORMANCE_BLACKDUCK_START_PROJECT_NUMBER' to control what the starting project number should be
* Add createTestProjects to only create the projects without triggering a notification
The thinking/intention behind this change is to allow us to configure a job in Jenkins to run createTestProjects multiple times simultaneously. I tested created 10K projects and it took 230. I then ran the job 5 times at once, with different values for the new property, and each creating 2K projects. The total runtime was 97 minutes.
If this is approved, I will create a Jenkins job that will run this based on some information from the user:
- BD server to run against
- BD API key
- Number of jobs to execute
- Number of projects to create in each job
- Starting project number
=> test: Add new property and test to create projects only

channel-email/src/main/java/com/synopsys/integration/alert/channel/email/attachment/MessageContentGroupCsvCreator.java, channel-email/src/main/java/com/synopsys/integration/alert/channel/email/attachment/compatibility/MessageContentGroup.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/attachment/MessageContentGroupCsvCreatorTest.java
Previous we fixed potential issues where commas in the additional attributes  would cause CSV files to break as the values contained a comma. This is resolved by encapsulating the values in quotes which the csv then filters out.
=> IALERT-3082: CSV with commas fix

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/ConcreteGlobalConfigExistsValidator.java, alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/GlobalConfigExistsValidator.java, channel-email/src/main/java/com/synopsys/integration/alert/channel/email/validator/EmailGlobalConfigExistsValidator.java, channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/validator/JiraServerGlobalConfigExistsValidator.java, component/src/main/java/com/synopsys/integration/alert/component/diagnostic/model/AuditDiagnosticModel.java, component/src/main/java/com/synopsys/integration/alert/component/diagnostic/model/NotificationDiagnosticModel.java
Since we updated the email and jira models in 6.10.0 we broke the global config check when configuring a distribution job. This fix adds another validator simply stating if a global config exists for any concrete model.
=> IALERT-3084 Warning messages when testing global channels

component/src/main/java/com/synopsys/integration/alert/component/scheduling/workflow/DailyTask.java, component/src/main/java/com/synopsys/integration/alert/component/tasks/ProcessingTask.java, component/src/test/java/com/synopsys/integration/alert/component/scheduling/DailyTaskTest.java, component/src/test/java/com/synopsys/integration/alert/component/tasks/ProcessingTaskTest.java
The DailyTask was not sending an event to indicate jobs were mapped to notifications to begin the process for sending messages to the channels.  Also the time range isn't calculated correctly.  It would only run the daily task if notifications came in since it started running.
=> IALERT-3099: Send the event to indicate jobs are mapped to notifications

api-channel-issue-tracker/build.gradle, api-channel-issue-tracker/src/main/java/com/synopsys/integration/alert/api/channel/issue/callback/ProviderCallbackIssueTrackerResponsePostProcessor.java, api-channel-issue-tracker/src/test/java/com/synopsys/integration/alert/api/channel/issue/callback/ProviderCallbackIssueTrackerResponsePostProcessorTest.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/task/accumulator/BlackDuckNotificationRetriever.java, src/main/java/com/synopsys/integration/alert/processing/ProcessingJobEventHandler.java
Update the issue tracker post processor to use the event manager to post events onto a queue to update blackduck.
=> Issue Tracker callback events

alert-database/src/test/java/com/synopsys/integration/alert/database/api/mock/MockCustomCertificateRepository.java, alert-database/src/test/java/com/synopsys/integration/alert/database/api/mock/MockProviderTaskPropertiesRepository.java, alert-database/src/test/java/com/synopsys/integration/alert/database/api/mock/MockSettingsKeyRepository.java, alert-database/src/test/java/com/synopsys/integration/alert/database/api/mock/MockSystemStatusRepository.java, alert-platform/build.gradle, build.gradle, buildSrc/src/main/java/com/synopsys/integration/alert/build/CreateKeystoreTask.java, buildSrc/src/main/java/com/synopsys/integration/alert/build/RunServerTask.java, channel-email/build.gradle, service-email/build.gradle, src/main/resources/application.properties
Update springboot -> 2.7.1
Update jsoup -> 1.15.2
Update implementation of JPA in Mock test classes
Remove/Add dependencies where applicable
Add new spring property to allow Swagger to work with springboot versions > 2.6
Annotate custom task properties with "@Internal" as required by Gradle 7. * This was missed in Gradle upgrade *
This branch was run successfully in the dev & comprehensive builds, as well as running runServer locally
=> IALERT-3107 - Update dependencies #2

alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultConfigurationModelConfigurationAccessor.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/AzureBoardsMessageSenderFactory.java, src/main/java/com/synopsys/integration/alert/processing/ProcessingJobEventHandler.java, src/test/java/com/synopsys/integration/alert/database/api/configuration/ConfigurationModelConfigurationAccessorTestIT.java
Fixed a stack overflow when creating an Async message sender where we were recursively calling the same create method.
Reordered cache cleanup in the processor to happen after we remove the job mappings.
Fixed an issue where the field model repository would attempt to delete an empty list of items.
=> Azure stack overflow fix and cache fixes

channel-email/src/main/java/com/synopsys/integration/alert/channel/email/attachment/compatibility/ProviderMessageContent.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/attachment/compatibility/ComponentItemTest.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/attachment/compatibility/ContentKeyTest.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/attachment/compatibility/MessageContentGroupTest.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/attachment/compatibility/MessageContentKeyTest.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/attachment/compatibility/ProviderMessageContentTest.java
Update apply methods in ProviderMessageContent to perform assignment in fewer locations
Bring test coverage to 100% for channel-email/src/test/java/com/synopsys/integration/alert/channel/email/attachment/compatibility
Code coverage verified increase of 0.5% and no new code smells
=> Add test coverage to channel-email

channel-jira-cloud/build.gradle, channel-jira-cloud/src/test/java/com/synopsys/integration/alert/channel/jira/cloud/database/accessor/mock/MockJiraCloudJobCustomFieldRepository.java, channel-jira-cloud/src/test/java/com/synopsys/integration/alert/channel/jira/cloud/database/accessor/mock/MockJiraCloudJobDetailsRepository.java, channel-jira-cloud/src/test/java/com/synopsys/integration/alert/channel/jira/cloud/distribution/event/JiraCloudCommentEventListenerTest.java, channel-jira-cloud/src/test/java/com/synopsys/integration/alert/channel/jira/cloud/distribution/event/JiraCloudCreateIssueEventHandlerTest.java, channel-jira-cloud/src/test/java/com/synopsys/integration/alert/channel/jira/cloud/distribution/event/JiraCloudCreateIssueEventListenerTest.java, channel-jira-cloud/src/test/java/com/synopsys/integration/alert/channel/jira/cloud/distribution/event/JiraCloudTransitionEventListenerTest.java, channel-jira-cloud/src/test/java/com/synopsys/integration/alert/channel/jira/cloud/distribution/event/mock/MockCorrelationToNotificationRelationRepository.java, channel-jira-cloud/src/test/java/com/synopsys/integration/alert/channel/jira/cloud/distribution/event/mock/MockJobSubTaskStatusRepository.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/distribution/event/JiraServerCommentEventHandlerTest.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/distribution/event/JiraServerCommentEventListenerTest.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/distribution/event/JiraServerCreateIssueEventHandlerTest.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/distribution/event/JiraServerCreateIssueEventListenerTest.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/distribution/event/JiraServerTransitionEventHandlerTest.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/distribution/event/JiraServerTransitionEventListenerTest.java
Adding test coverage for the api-channel-issue-tracker  issue.event package. The handlers and listeners are abstract classes so the tests created were for their implementations in Jira Server and Jira Cloud. 
Azure implementations are blocked by a necessary refactor of the services factory and will therefore need to be revisited in the future.
=> distribution event test coverage

azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/service/process/AzureProcessService.java, azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/service/process/ProcessWorkItemTypeFieldResponseModel.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/search/AzureCustomFieldManager.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/oauth/storage/AzureBoardsCredentialDataStore.java
- Make the OAuth credential store thread safe by providing a lock for reads and updates
- Check if the OAuth fields have changed before updating in the database.  If no changes have occurred do not write and flush the same data to the database causes an error in JPA when flush is called due to no changes between the cache and the database.
- Make the custom field manager thread safe when installing custom fields by check if the custom field has been added to the workitemtype before attempting to add the custom field to the work item type.
=> IALERT-3147: Make Azure Boards thread safe

channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/distribution/delegate/JiraServerIssueCreator.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/distribution/delegate/JiraServerCommentGeneratorTest.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/distribution/delegate/JiraServerCreateEventGeneratorTest.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/distribution/delegate/JiraServerIssueCreatorTest.java
New unit tests for  channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/distribution/delegate. 
Removed unused issueCategoryRetriever in JiraServerIssueCreator.
=> Test: Unit tests for channel-jira-server/.../distribution/delegate

alert-common/src/main/java/com/synopsys/integration/alert/common/rest/AlertRestConstants.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsGlobalCrudActions.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/web/AzureBoardsGlobalConfigController.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsGlobalCrudActionsTest.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/action/JiraServerGlobalCrudActionsTest.java
- Added global CRUD actions and controller for azure boards
- Added endpoint path for azure boards (subject to change)
- TODOs are added for validation
=> FEAT: IALERT-2950 and IALERT-2948

channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/AzureBoardsPropertiesFactory.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/AzureBoardsPropertiesLegacy.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsGlobalFieldModelTestAction.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/AzureBoardsMessageSenderFactory.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/AzureBoardsProcessorFactory.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/event/AzureBoardsCommentEventHandler.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/event/AzureBoardsCreateIssueEventHandler.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/event/AzureBoardsTransitionEventHandler.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/web/AzureBoardsCustomFunctionAction.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/web/AzureOAuthCallbackController.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/distribution/event/AzureBoardsCreateIssueEventHandlerTest.java
Renaming AzureBoardsProperties to AzureBoardsPropertiesLegacy for IALERT-3183 refactor of the Azure OAuth actions for replacement
=> Rename azure properties file to legacy 

alert-platform/build.gradle, build.gradle, buildSrc/docker-v2.gradle, deployment/helm/synopsys-alert/README.md, deployment/helm/synopsys-alert/templates/postgres.yaml, docker/blackduck-alert-db/Dockerfile, src/test/resources/spring-test.properties
Update the build pieces needed to go to Postgres 13. This PR does **NOT** handle upgrades, that will be in a later PR.
* Update testcontainers version to latest version (that does not have breaking issues)
* Add logic to Docker gradle build to automate adding build arguments to the docker build step(s)
* Update helm to use Postgres 13 supported image
* Update alert-db image to leverage base image coming from gradle
* Update spring resources to use Postgres 13
A full comprehensive build was run with these changes
=> IALERT-3149 - Update build pieces for going to Postgres 13

channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/web/AzureBoardsGlobalConfigController.java
We are revealing the Authenticate endpoint for azure before it is fully implemented for the purpose of creating the new UI. The implementation for this change will follow up in IALERT-3183.
=> Initial implementation for the OAuth authenticate endpoint

channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/AzureBoardsPropertiesLegacy.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsGlobalTestAction.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/web/AzureBoardsGlobalConfigController.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsGlobalTestActionTest.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/validator/AzureBoardsGlobalConfigurationValidatorTest.java
- Add AzureBoardsGlobalTestAction
- Checkout AzureBoardsPropertiesLegacy.fromGlobalConfigurationModel from mc_IALERT-3183_Azure_OAuth_actions
- Hook validation and test actions to Azure Boards controller
=> FEAT: IALERT-2952 Azure Boards Test action

alert-platform/build.gradle, src/test/java/com/synopsys/integration/alert/performance/NotificationRemovalTest.java, src/test/java/com/synopsys/integration/alert/performance/ScalingPerformanceTest.java, src/test/java/com/synopsys/integration/alert/performance/serialization/ComponentUnknownVersionNotificationSerializationTest.java, src/test/java/com/synopsys/integration/alert/performance/utility/IntegrationPerformanceTestRunner.java, src/test/java/com/synopsys/integration/alert/performance/utility/IntegrationPerformanceTestRunnerLegacy.java
This is for 6.11.1
* Update to latest libraries which handles upgrading org.apache.commons:commons-text to address https://github.com/advisories/GHSA-599f-7c49-w659
* Updates for changes from integration-common for ResilientJobConfig
=> build: Update to latest libraries to address CVE-2022-42889

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/accessor/GitHubJobDetailAccessor.java, alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/job/details/DistributionJobDetailsModel.java, alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/job/details/GitHubJobDetailsModel.java, channel-github/build.gradle, channel-github/src/main/java/com/synopsys/integration/alert/channel/github/database/accessor/DefaultGitHubJobDetailAccessor.java, channel-github/src/main/java/com/synopsys/integration/alert/channel/github/distribution/GitHubChannel.java, channel-github/src/main/java/com/synopsys/integration/alert/channel/github/distribution/GitHubEventHandler.java, channel-github/src/main/java/com/synopsys/integration/alert/channel/github/distribution/GitHubEventReceiver.java
- create job details accessor interface
- Create default job details accessor
- Create the Job Details model
- Create the event receiver
- Create the event handler
The implementation of the event handler needs to be done.  The implementation of the Job Details and the accessor needs to be done.
=> feat: Implement the channel wiring for GitHub.

alert-database/src/main/resources/liquibase/6.12.0/oauth-credential-store.xml, api-oauth/src/main/java/com/synopsys/integration/alert/api/oauth/AlertOAuthCredentialDataStore.java, api-oauth/src/main/java/com/synopsys/integration/alert/api/oauth/database/accessor/AlertOAuthConfigurationAccessor.java, api-oauth/src/main/java/com/synopsys/integration/alert/api/oauth/database/configuration/AlertOAuthConfigurationEntity.java, build.gradle, channel-azure-boards/build.gradle, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/AzureBoardsProperties.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/AzureBoardsPropertiesFactory.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/AzureBoardsPropertiesLegacy.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsGlobalFieldModelTestAction.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsGlobalTestAction.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsOAuthAuthenticateAction.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsOAuthCallbackAction.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/AzureBoardsMessageSenderFactory.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/AzureBoardsProcessorFactory.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/event/AzureBoardsCommentEventHandler.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/event/AzureBoardsCreateIssueEventHandler.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/event/AzureBoardsTransitionEventHandler.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/oauth/OAuthRequestValidator.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/oauth/storage/AzureBoardsCredentialDataStoreFactory.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/web/AzureBoardsCustomFunctionAction.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsGlobalTestActionTest.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/distribution/event/AzureBoardsCreateIssueEventHandlerTest.java, src/main/java/com/synopsys/integration/alert/Application.java
This PR is set up to accomplish the following:
- Moved existing  AzureBoardsProperties into AzureBoardsPropertiesLegacy to be slowly deprecated and removed
- Fixed several issues in AlertOAuthCredentialDataStore that were causing new issues to  be updated rather than created, causing the oauth credential save to fail silently. 
- Fixed typos and incorrect objects types in the database
- Implemented AlertOAuthCredentialDataStore in existing OAuth authorization and callback for the global configuration
What is currently not supported:
- Distribution configurations for Azure will fail as a result of invalid Azure configurations still using the old legacy  AzureBoardsProperties. This fix will need to be made in a followup PR.
=> Azure OAuth Implementation - global configuration

alert-common/src/main/java/com/synopsys/integration/alert/common/action/api/GlobalConfigurationModelToConcreteConverter.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/convert/AzureBoardsGlobalConfigurationModelConverter.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/convert/AzureBoardsGlobalConfigurationModelSaveActions.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/convert/AzureBoardsGlobalConfigurationModelConverterTest.java, channel-email/src/main/java/com/synopsys/integration/alert/channel/email/convert/EmailGlobalConfigurationModelConverter.java, channel-email/src/main/java/com/synopsys/integration/alert/channel/email/convert/EmailGlobalConfigurationModelSaveActions.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/convert/EmailGlobalConfigurationModelConverterTest.java, channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/convert/JiraServerGlobalConfigurationModelConverter.java, channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/convert/JiraServerGlobalConfigurationModelSaveActions.java, channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/validator/JiraServerGlobalConfigurationValidator.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/convert/JiraServerGlobalConfigurationModelConverterTest.java, component/src/main/java/com/synopsys/integration/alert/component/settings/convert/ProxyConfigurationModelConverter.java, component/src/main/java/com/synopsys/integration/alert/component/settings/convert/ProxyConfigurationModelSaveActions.java, component/src/test/java/com/synopsys/integration/alert/component/settings/convert/ProxyConfigurationModelConverterTest.java
Pushing changes to support update requests by the old field model converters. The change here is that we will now pass in an @Nullable existingGlobalConfig Id that whenever an update is passed in we can pass in a UUID. This is required by the validator to ignore duplicate names when the ID is the same, indicating that an update is being performed.
Test improvements will follow in a future PR.
=> IALERT-3195 old rest endpoint update fix

channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/validator/AzureBoardsGlobalConfigExistsValidator.java
Fixes the banner showing only when there is no config in distribution jobs when Azure Boards is selected.
=> ConfigExistValidator for Azure Boards

channel-email/src/main/java/com/synopsys/integration/alert/channel/email/action/EmailDistributionTestAction.java, channel-email/src/main/java/com/synopsys/integration/alert/channel/email/action/EmailTestActionHelper.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/action/EmailTestActionHelperTest.java
If users were added to the additional email addresses AND ProjectOwnerOnly was checked, the test configuration should have only sent a test email to the ProjectOwner(s), but it was also sending to the list of additional email addresses.
* Move logic for calculating who to email into EmailTestActionHelper to have one location which is performing the necessary logic to get the email addresses to send a test message.
* Remove logic to validate BDconfig ID as this is done as part of UI validation
* Add test logic to cover 8 different combinations of options (see below) for Additional Email Addresses, Additional Email Addresses Only, Project Owner Only.
| Additional Email Addresses  | Additional Email Addresses Only | Project Owner Only | Who is emailed |
| ------------- | ------------- | …
=> IALERT-2752 - Fix Test configuration emailing users it shouldn't

channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/AzureBoardsProperties.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/AzureBoardsPropertiesFactory.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsGlobalTestAction.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsOAuthAuthenticateAction.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsOAuthCallbackAction.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsGlobalTestActionTest.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsOAuthAuthenticateActionTest.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsOAuthCallbackActionTest.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/database/mock/MockAlertOAuthConfigurationRepository.java
Previously AzureBoardsProperties had a static  method in order to create the object which was used by the AzureBoardsPropertiesFactory in order to create an instance of the former. This is somewhat backwards as traditionally if we're following a factory workflow, the factory class creates an instance of the object using its constructor rather than it's static methods.
This accomplishes a few things:
It's easier for testing and mocking since we can mock out the properties class.
It lets us be consistent with other  issue trackers such as Jira Server which use a similar factory approach.
In addition to these changes we've also added increased test coverage for OAuth actions in Azure as they require afformentioned changes.
=> IALERT-3230: Move AzureBoardsProperties creation into factory class & test updates

deployment/helm/synopsys-alert/templates/postgres-config.yaml, deployment/helm/synopsys-alert/templates/postgres.yaml, deployment/helm/synopsys-alert/values.yaml, docker/blackduck-alert-db/Dockerfile, docker/blackduck-alert-db/alertdb-pg-migrate.sh, docker/blackduck-alert-db/openshift-custom-postgresql.conf.template, docker/blackduck-alert/docker-entrypoint.sh
This address 3 different problems encountered while performing upgrades:
1. Centos image creates an Admin user and non-admin user as part of its standard deployment. Alpine does not do this. The user passed to the Alpine image is created is an admin. Because of this, we need to make the admin user used for the Centos DB initialization available to Alpine.
2. Centos creates a conf file (openshift-custom-postgresql.conf) that is included in postgresql.conf. This file is generated on every startup, and is stored outside of the volume. Because of this, we need to handle creating this file.
3. Centos stores its DB data in a different directory. Because of this, we had to handle being able to override this value.
** Please review ticket for testing scenarios done using the changes in this PR
=> IALERT-3236: Address upgrade problems in helm deployments

api-oauth/src/main/java/com/synopsys/integration/alert/api/oauth/database/accessor/AlertOAuthConfigurationAccessor.java, api-oauth/src/test/java/com/synopsys/integration/alert/api/oauth/AlertOAuthCredentialDataStoreFactoryTest.java, api-oauth/src/test/java/com/synopsys/integration/alert/api/oauth/AlertOAuthCredentialDataStoreTest.java, api-oauth/src/test/java/com/synopsys/integration/alert/api/oauth/database/accessor/AlertOAuthConfigurationAccessorTest.java
The refresh and access tokens are encrypted in previous versions of Alert.  Need to make sure the new class for storing OAuth  tokens encrypts and decrypts the values.
=> IALERT-3240: encrypt and decrypt access tokens in new accessor.

channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/oauth/OAuthRequestValidator.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/validator/AzureBoardsGlobalConfigurationValidator.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsGlobalCrudActionsTest.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsGlobalTestActionTest.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsGlobalValidationActionTest.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsOAuthAuthenticateActionTest.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/convert/AzureBoardsGlobalConfigurationModelConverterTest.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/convert/AzureBoardsGlobalConfigurationModelSaveActionsTest.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/environment/AzureBoardsEnvironmentVariableHandlerTest.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/oauth/OAuthRequestValidatorTest.java, channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/validator/AzureBoardsGlobalConfigurationValidatorTest.java
The goal of these changes is to remove the oAuth validation from Azure. If a failure occurs this will allow users to attempt to authenticate again without having to wait the timeout delay. To accomplish this, we now do thee following:
- Attempting  to add a new request will first inspect if there is already a request for that configuration. If it exists, it will delete the old entry and replace it with the new one.
- Failed requests will remain in memory until, it is either cleared by an existing configuration overwriting it (see above bullet) or it will be purged after 5 minutes. 
- As a result of these changes the global config validator no longer depends on the oAuth request validator and it can be removed from test classes.
The idea for keeping only the last successful request and run …
=> IALERT-3238 oauth validation refactor

provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/AbstractRuleViolationNotificationMessageExtractor.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/VulnerabilityNotificationMessageExtractor.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/service/BlackDuckMessageComponentVersionUpgradeGuidanceService.java, provider-blackduck/src/test/java/com/synopsys/integration/alert/provider/blackduck/processor/message/RuleViolationClearedNotificationMessageExtractorTest.java, provider-blackduck/src/test/java/com/synopsys/integration/alert/provider/blackduck/processor/message/RuleViolationNotificationMessageExtractorTest.java, test-common-blackduck/src/main/java/com/synopsys/integration/alert/test/common/blackduck/BlackDuckResponseTestUtility.java
In previous versions of Alert we would not provide upgrade guidance on component policies if it was available. We now pass along the upgrade guidance information and will post it if it's available. 
As part of this change we will also remove duplication in the private methods of the extractors by building the services directly.
=> IALERT-3139 policy upgrade guidance

deployment/docker-swarm/docker-compose.local-overrides.yml, deployment/helm/synopsys-alert/README.md, deployment/helm/synopsys-alert/templates/postgres.yaml, deployment/helm/synopsys-alert/values.yaml, docker/blackduck-alert-db/alertdb-docker-entrypoint.sh, docker/blackduck-alert-db/alertdb-pg-migrate.sh
Because the CentOS image stores the Postgres DB in a different directory, this had to be handled in the migration and was done by adding the postgres.postgresDataDirectory value in values.yaml. This would allow the migration to proceed, but it kept the data within the CentOS directory. Going forward this would require this value to be set for any future upgrades.
This PR makes the following changes
* Remove postgres.postgresDataDirectory and it's usage from the orchestration
* Edit alertdb-pg-migrate.sh so that if the Postgres DB is found in the CentOS directory, it would move it to the Alpine directory.
* Remove the MIGRATE_POSTGRES and postgresMigration from the orchestration and scripts. The migration script will always run, as it determines if it needs to launch the PG migration or …
=> IALERT-3269: Handle data staying in CentOS directory

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/accessor/RoleAccessor.java, alert-common/src/main/java/com/synopsys/integration/alert/common/security/authorization/AuthorizationManager.java, alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultRoleAccessor.java, component/src/main/java/com/synopsys/integration/alert/component/users/web/role/RoleActions.java, src/test/java/com/synopsys/integration/alert/component/users/web/role/RoleActionsTest.java
Failures in the old roles table would default to throwing a 500 internal server error. I've changed the exception thrown and will now instead return a BAD_REQUEST.
Further improvements to this functionality should likely be done when we refactor this endpoint.
=> IALERT-3271: Improve error status codes on role failures

docker/blackduck-alert/Dockerfile
Alpine 3.17.0 is now available and resolves an existing vulnerability in curl that exists. This should resolve existing security issues when scanning this version of Alert.
=> IALERT-3241: Update alpine base container image to 3.17

alert-database-job/src/main/java/com/synopsys/integration/alert/database/distribution/DistributionRepository.java
Add LIMIT 1 to the query.  Only get 1 audit entry for the job with the latest timestamp.
Without the limit the query can return a row per audit entry in the database.
=> IALERT-3277: Update the query to return 1 audit entry for the job.

alert-database-job/src/main/java/com/synopsys/integration/alert/database/distribution/DistributionRepository.java
fix: Display correct timestamp and status with multiple jobs.
- Get the max timestamp and status for each job configuration. 
- Only display 1 row per job
=> IALERT-3277: Display correct time last sent and status

api-processor/src/main/java/com/synopsys/integration/alert/processor/api/JobNotificationContentProcessor.java, component/src/main/java/com/synopsys/integration/alert/component/tasks/ProcessingTask.java, src/main/java/com/synopsys/integration/alert/processing/ProcessingJobEventHandler.java, src/test/java/com/synopsys/integration/alert/processing/ProcessingJobEventHandlerTest.java, src/test/java/com/synopsys/integration/alert/processing/ProcessingJobEventHandlerTestIT.java
Do not send the notification mapped event for every page of notifications found within the time range of a processing task.  Only send one event when the processing task has finished mapping the notifications.
=> IALERT-3277: duplicate email fix

alert-common/src/main/java/com/synopsys/integration/alert/common/rest/AlertRestConstants.java, alert-common/src/main/java/com/synopsys/integration/alert/common/rest/api/FileUploadHelper.java, alert-database/src/main/resources/liquibase/6.13.0/concrete-saml-configuration-table.xml, authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/action/SAMLFileUploadActions.java, authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/database/accessor/SAMLConfigAccessor.java, authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/database/configuration/SAMLConfigurationEntity.java, authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/model/SAMLConfigModel.java, authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/validator/SAMLConfigurationValidator.java, authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/validator/SAMLFileUploadValidator.java, authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/web/SAMLConfigController.java, component/src/main/java/com/synopsys/integration/alert/component/authentication/web/SamlMetaDataFileUpload.java
- Create FileUploadHelper, SAMLFileUploadValidator, SAMLFileUploadActions for uploading and validation of saml metadata file
- Fixed SAMLConfigValidator to not perform check on metadataFilePath string but on fileExists instead
=> IALERT-3299 SAML metadata file upload

api-authentication/src/main/java/com/synopsys/integration/alert/api/authentication/descriptor/AuthenticationDescriptor.java, api-authentication/src/main/java/com/synopsys/integration/alert/api/authentication/descriptor/AuthenticationDescriptorKey.java, api-authentication/src/main/java/com/synopsys/integration/alert/api/authentication/security/AuthenticationPerformer.java, api-authentication/src/main/java/com/synopsys/integration/alert/api/authentication/security/UserManagementAuthoritiesPopulator.java, api-authentication/src/main/java/com/synopsys/integration/alert/api/authentication/security/event/AlertAuthenticationEvent.java, api-authentication/src/main/java/com/synopsys/integration/alert/api/authentication/security/event/AuthenticationEventHandler.java, api-authentication/src/main/java/com/synopsys/integration/alert/api/authentication/security/event/AuthenticationEventListener.java, api-authentication/src/main/java/com/synopsys/integration/alert/api/authentication/security/event/AuthenticationEventManager.java, api-authentication/src/main/java/com/synopsys/integration/alert/api/authentication/validator/AuthenticationConfigurationFieldModelValidator.java, authentication-ldap/build.gradle, authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/LdapAuthenticationPerformer.java, authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/LdapConfig.java, authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/MappingLdapAuthoritiesPopulator.java, authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/action/LDAPTestAction.java, authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/action/LdapManager.java, authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/model/LDAPConfigTestModel.java, authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/web/LDAPConfigController.java, authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/MappingLdapAuthoritiesPopulatorTest.java, authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/action/LdapManagerTest.java, authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/database/configuration/MockLDAPConfigurationRepository.java, build.gradle, component/build.gradle, component/src/main/java/com/synopsys/integration/alert/component/authentication/actions/AuthenticationFieldModelTestAction.java, component/src/main/java/com/synopsys/integration/alert/component/authentication/security/AuthenticationHandler.java, component/src/main/java/com/synopsys/integration/alert/component/authentication/security/saml/UserDetailsService.java, component/src/test/java/com/synopsys/integration/alert/component/authentication/security/saml/UserDetailsServiceTest.java, src/test/java/com/synopsys/integration/alert/component/authentication/security/UserManagementAuthoritiesPopulatorTest.java, src/test/java/com/synopsys/integration/alert/component/authentication/web/AuthenticationActionsTestIT.java, src/test/java/com/synopsys/integration/alert/component/authentication/web/AuthenticationControllerTestIT.java
* Move following classes out of component and into authentication-ldap
LdapAuthenticationPerformer.java
LdapConfig.java
MappingLdapAuthoritiesPopulator.java
LdapManager.java
MappingLdapAuthoritiesPopulatorTest.java
LdapManagerTest.java
* Move the following class out of component and into api-authentication
UserManagementAuthoritiesPopulator.java
* Adjust gradle files to handle move
* Adjust classes for moved files
* Remove copyright headers
* Create new classes to begin implementing Test Configuration
LDAPTestAction.java  **Not fully implemented
LDAPConfigTestModel.java
* Update LDAPConfigController.java to use TestAction
* Update LdapManager to work with new ConfigModel and remove logic for FieldUtility
* Update some variable names for clarity
* Add MockLDAPConfigurationRepository.java …
=> IALERT-3288 - Move classes and update for new Test Configuration

api-channel/src/main/java/com/synopsys/integration/alert/api/channel/DistributionEventHandler.java, api-channel/src/test/java/com/synopsys/integration/alert/api/channel/DistributionEventHandlerTest.java, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/AzureBoardsDistributionEventHandler.java, channel-email/src/main/java/com/synopsys/integration/alert/channel/email/distribution/EmailDistributionEventHandler.java, channel-jira-cloud/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/distribution/JiraCloudDistributionEventHandler.java, channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/distribution/JiraServerDistributionEventHandler.java, channel-msteams/src/main/java/com/synopsys/integration/alert/channel/msteams/distribution/MSTeamsDistributionEventHandler.java, channel-slack/src/main/java/com/synopsys/integration/alert/channel/slack/distribution/SlackDistributionEventHandler.java, channel-slack/src/test/java/com/synopsys/integration/alert/channel/slack/distribution/SlackDistributionEventHandlerTest.java
- Fix an issue where audit failures aren't sent.
- Remove unused dependencies to old audit class.
=> IALERT-3155: Audit failure fix

alert-database-job/src/main/java/com/synopsys/integration/alert/database/api/DefaultDistributionAccessor.java, alert-database-job/src/main/java/com/synopsys/integration/alert/database/distribution/DistributionRepository.java, api-channel-issue-tracker/src/main/java/com/synopsys/integration/alert/api/channel/issue/send/IssueTrackerAsyncMessageSender.java, api-channel-issue-tracker/src/test/java/com/synopsys/integration/alert/api/channel/issue/send/IssueTrackerAsyncMessageSenderTest.java, api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/JobSubTaskEventHandler.java, api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/audit/AuditSuccessHandler.java, api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/execution/ExecutingJob.java, api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/execution/ExecutingJobManager.java, api-processor/src/main/java/com/synopsys/integration/alert/processor/api/JobNotificationContentProcessor.java, api-processor/src/main/java/com/synopsys/integration/alert/processor/api/distribute/ProviderMessageDistributor.java, api-processor/src/test/java/com/synopsys/integration/alert/processor/api/JobNotificationProcessorTest.java, build.gradle, component/src/main/java/com/synopsys/integration/alert/component/diagnostic/database/DefaultDiagnosticAccessor.java, component/src/main/java/com/synopsys/integration/alert/component/diagnostic/model/CompletedJobDurationDiagnosticModel.java, component/src/main/java/com/synopsys/integration/alert/component/diagnostic/model/CompletedJobStageDurationModel.java, component/src/test/java/com/synopsys/integration/alert/component/diagnostic/database/DefaultDiagnosticAccessorTest.java, provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/task/accumulator/BlackDuckAccumulator.java, src/test/java/com/synopsys/integration/alert/database/api/DefaultDistributionAccessorTestIT.java, src/test/java/com/synopsys/integration/alert/performance/utility/IntegrationPerformanceTestRunner.java, src/test/java/com/synopsys/integration/alert/performance/utility/ProcessingCompleteWaitJobTask.java
- Implement missing diagnostics models for the executing jobs.
- Create wait task which relies on the job execution diagnostic data.
- Fix unit tests and IT tests to pass in the builds.
- Don't use the database for the jobSubTask handler to fire success events use the ExecutingJobManager directly.
- No longer create pending audit entries to cut down on the number of items in the database.
Additional refactoring to the classes will be done separately.  These changes get the test to complete.
=> IALERT-3155: wait task

buildSrc/docker-v2.gradle
Prior to this change, if an image didn't exist, the task would fail. Now, this will show the following output:
```
> Task :dockerRemoveBlackduckAlert
Removing docker image:: blackducksoftware/blackduck-alert:6.13.0-SNAPSHOT
Image does not exist, continuing.
```
If the image can not be removed, we will still fail, the output being:
```
> Task :dockerRemoveBlackduckAlert FAILED
Removing docker image:: blackducksoftware/blackduck-alert:6.13.0-SNAPSHOT
FAILURE: Build failed with an exception.
* Where:
Script '/home/serv-builder/hudson-build/workspace/integration-builds-v2/generated-builds/solutions/blackduck-alert/comprehensive/ps-IALERT-3155-wait-task/buildSrc/docker-v2.gradle' line: 119
* What went wrong:
Execution failed for task ':dockerRemoveBlackduckAlert'.
> Error response from daemon: …
```
=> IALERT-3206: Do not fail if image does not exist

authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/action/LdapManager.java, authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/database/accessor/LDAPConfigAccessor.java, authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/environment/LDAPEnvironmentVariableHandler.java, authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/model/LDAPConfigModel.java, authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/validator/LDAPConfigurationValidator.java, authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/action/LdapManagerTest.java
* As the DB field for isEnabled is not nullable, change the data model to not return Optional.ofNullable for boolean values
* Update any impacted areas
* Update validation to not allow null for input data model
=> fix: Update LDAP ConfigModel to not return Optional for Booleans

deployment/helm/synopsys-alert/templates/alert.yaml, deployment/helm/synopsys-alert/values.yaml, docker/blackduck-alert/docker-entrypoint.sh
The current implementation did not volume mount in the certs/keys needed, and set the variables to the value of the cert/key instead of pointing to the file.
Edits include:
* Create and use variable for secrets directory.
* Set helm SSL variables to file path
* Volume mount the secrets into the pod
* Correct default variable names in entrypoint
* Readability and supportability edits in entrypoint
Follow instructions [HERE](https://sig-confluence.internal.synopsys.com/display/integration/Configuring+and+Verifying+SSL+within+Helm+using+external+DB) for set-up and validation.
=> IALERT-3074: Address issues with sslmode

authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/action/LDAPTestAction.java
With bad test credentials, this throws an exception:
```
Authentication authentication = ldapAuthenticationProvider.get().authenticate(pendingAuthentication)
```
This exception was not being caught, and the test was always coming back positive. The original implementation was also catching Exception.
=> fix: Catch any exception to fail test endpoint

authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/database/accessor/LDAPConfigAccessor.java, authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/action/LdapManagerTest.java
* ConfigAccessor was not encrypting/decrypting data when posting/getting data from DB
* ConfigAccessor fix: If user is editing existing configuration, which has a PW saved, AND not changing the password, we should use the password that exists in the DB.
* Test coverage
=> IALERT-3342 - LdapManager fixes and tests

authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/validator/LDAPConfigurationValidator.java, authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/validator/LDAPConfigurationValidatorTest.java
* Remove unnecessary logic as LDAPConfigModel now returns `BooleanUtils.toBoolean()`
* Readability change to `if` statement
* Implement test coverage
=> IALERT-3342 -  LDAPConfigurationValidator cleanup and tests

authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/action/LDAPTestAction.java, authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/action/LdapManager.java, authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/validator/LDAPConfigurationValidator.java, authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/action/LdapManagerTest.java, authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/validator/LDAPConfigurationValidatorTest.java
* LDAPTestAction - If using a previously saved LDAP configuration, the PW will not be present in the UI. If that is the case, get the PW from the DB
* LDAPTestAction - Testing the LDAP configuration should require you to enable LDAP
* LdapManager - 4 fields are required, including being enabled. Re-work to perform a check on all 4
* LDAPConfigurationValidator - isManagerPasswordSet should have been doing a Boolean test. Update getIsManagerPasswordSet to use StringUtils as Optional.isEmpty() is false if it's an empty string
* Update tests
=> LDAP fixes from UI testing

api-channel-issue-tracker/src/main/java/com/synopsys/integration/alert/api/channel/issue/IssueTrackerChannel.java, api-channel-issue-tracker/src/test/java/com/synopsys/integration/alert/api/channel/issue/IssueTrackerChannelTest.java, api-channel/src/main/java/com/synopsys/integration/alert/api/channel/DistributionChannel.java, api-channel/src/main/java/com/synopsys/integration/alert/api/channel/DistributionEventHandler.java, api-channel/src/main/java/com/synopsys/integration/alert/api/channel/MessageBoardChannel.java, api-channel/src/main/java/com/synopsys/integration/alert/api/channel/action/DistributionChannelMessageTestAction.java, api-channel/src/test/java/com/synopsys/integration/alert/api/channel/DistributionEventHandlerTest.java, api-channel/src/test/java/com/synopsys/integration/alert/api/channel/MessageBoardChannelTest.java, api-channel/src/test/java/com/synopsys/integration/alert/api/channel/action/DistributionChannelMessageFieldModelTestActionTest.java, api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/JobSubTaskEventHandler.java, api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/audit/AuditEvent.java, api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/audit/AuditFailedEvent.java, api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/audit/AuditFailedHandler.java, api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/audit/AuditSuccessEvent.java, api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/audit/AuditSuccessHandler.java, api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/execution/ExecutingJob.java, api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/execution/ExecutingJobManager.java, api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/audit/AuditEventTest.java, api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/audit/AuditFailedEventListenerTest.java, api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/audit/AuditFailedEventTest.java, api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/audit/AuditFailedHandlerTest.java, api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/audit/AuditSuccessEventListenerTest.java, api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/audit/AuditSuccessEventTest.java, api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/audit/AuditSuccessHandlerTest.java, api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/execution/ExecutingJobManagerTest.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/EmailITTestAssertions.java, channel-msteams/src/test/java/com/synopsys/integration/alert/channel/msteams/distribution/MsTeamsChannelTest.java, channel-slack/src/test/java/com/synopsys/integration/alert/channel/slack/ChannelITTestAssertions.java, src/test/java/com/synopsys/integration/alert/database/api/DefaultDistributionAccessorTestIT.java
Write the failed audit entries per notification if the job hasn't completed to collect them all.
Need to add the Job Configuration ID to the audit events to save the notification data per audit failed entry.
=> fix: Write the failed audit entries if the job hasn't completed.

api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/audit/FailedAuditPurgeTask.java, component/src/main/java/com/synopsys/integration/alert/component/scheduling/actions/SchedulingGlobalApiAction.java, ui/src/main/js/page/audit/AuditModel.js, ui/src/main/js/page/scheduling/SchedulingConfiguration.js
- Change Audit title page to Audit Failures
- Change the title of the purge data to purge notification data
- Change purge audit failed data frequency to purge audit failed data
- Fix the issue setting the default purge of audit data to 10
- Remove the in Days portion of the purge field titles since the number of days are in the selection.
=> fix: Update Audit title and scheduling page fixes.

authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/web/LDAPConfigController.java, authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/web/LDAPConfigControllerTest.java
**** THIS IS MERGING INTO v6.13.0 ****
* delete() does not create any content, so calling createContentResponseFromAction() was actually throwing an exception. Correct this to call createResponseFromAction()
* Test coverage
=> IALERT-3342 - LDAPConfigController fix and tests

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/accessor/JobNotificationMappingAccessor.java, alert-database-job/src/main/java/com/synopsys/integration/alert/database/api/DefaultJobNotificationMappingAccessor.java, alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultProcessingFailedAccessor.java, api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/execution/ExecutingJobManager.java, api-processor/src/main/java/com/synopsys/integration/alert/processor/api/NotificationMappingProcessor.java, api-processor/src/main/java/com/synopsys/integration/alert/processor/api/mapping/JobNotificationMapper2.java, api-processor/src/test/java/com/synopsys/integration/alert/processor/api/mapping/JobNotificationMapper2Test.java, build.gradle, src/main/java/com/synopsys/integration/alert/processing/NotificationReceivedEventHandler.java
- For each Correlation ID limit the maximum number of notifications that are mapped to jobs for that correlation ID to 10000.
- Fix a database issue with the audit failures table when multiple jobs map to the same notifications.
=> IALERT-3356: Limit Batch Size

channel-jira-cloud/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/action/JiraCloudGlobalFieldModelTestAction.java, channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/action/JiraServerGlobalTestActionWrapper.java
Make a request to the issue service.  If the user cannot search for issues because a role is missing on the user then an HTTP 403 will cause an exception to be thrown.  A user can be a valid user for Jira but the Jira server may not have any issues because it is a new instance or a new project is getting setup.
=> IALERT-3059: fix issue check

build.gradle, channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/event/AzureBoardsCreateIssueEventHandler.java, channel-jira-cloud/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/distribution/event/JiraCloudCreateIssueEventHandler.java, channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/distribution/event/JiraServerCreateIssueEventHandler.java, src/test/java/com/synopsys/integration/alert/performance/utility/ProcessingCompleteWaitJobTask.java
use synchronized to lock on the search and creation of issues to deal with concurrency.
=> IALERT-3356: block before create

alert-common/src/main/java/com/synopsys/integration/alert/common/action/api/AbstractResourceActions.java, src/test/java/com/synopsys/integration/alert/component/users/web/role/RoleActionsTest.java
Add validation that the ID provided as part of the URL and the ID provided as part of the json is the same. This will affect certificates, users, and roles. If they are not, you will get an error similar to the following (from postman)
```
{
"timestamp": "2023-02-23T21:13:03.914+00:00",
"status": 400,
"error": "Bad Request",
"message": "IDs in request do not match",
"path": "/alert/api/configuration/role/5"
}
```
=> IALERT-2535: Add validation

authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/action/LDAPTestAction.java, authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/validator/LDAPConfigurationValidator.java, authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/validator/LDAPConfigurationValidatorTest.java, ui/src/main/js/application/auth/LdapForm.js, ui/src/main/js/common/configuration/global/GlobalTestModal.js, ui/src/main/js/common/configuration/global/concrete/ConcreteConfigurationForm.js
* Perform validation on the LDAPConfigTestModel prior to executing the test connection. This checks combines errors found while validating LDAPConfigModel with any while found validating LDAPConfigTestModel
* Implement JUnit test coverage for new logic
UI changes by @bseifert14 
* In pop-up when prompting for testLDAPUsername and testLDAPPassword, change name of button from "Send Test Message" -> "Test User Connection".
* On same pop-up, prevent user from clicking Test User Connection button until testLDAPUsername and testLDAPPassword are filled in.
NOTE: The UI does not send in a null if no data is supplied for the LDAP configuration. Instead, it sends a valid LDAPConfigModel, with no values. So, the null check is really only for when users hit the API directly, such as when using …
=> IALERT-3346 - Implement validation for LDAPConfigTestModel

alert-database/src/main/resources/liquibase/6.13.0/migrate-ldap-configuration.xml, authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/MappingLdapAuthoritiesPopulator.java, authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/action/LdapManager.java, authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/model/LDAPAuthenticationType.java, authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/model/LDAPConfigModel.java, authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/action/LDAPCrudActionsTest.java, authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/action/LdapManagerTest.java, authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/environment/LDAPEnvironmentVariableHandlerTest.java, ui/src/main/js/application/auth/LdapForm.js
* Prior versions of Alert set a default for Group Search Filter that was not saved in the DB. Update liquibase migration to set this default in the DB when performing a migration.
* Improve error message when Group settings aren't set.
* Reorder items in UI for "Authentication Type" and "Referral".
* When setting Authentication Type, set default too simple if value is empty, null, or not one of the supported values.
* Update tests
**Tests were changed to leverage a new LDAPTestHelper in master. These tests will be updated when v6.13.0 is merged into master.**
=> IALERT-3364 : Handle issues found with LDAP

api-authentication/src/main/java/com/synopsys/integration/alert/api/authentication/security/event/AuthenticationEventManager.java
Correct issue of username not being set when authenticating via LDAP.
=> IALERT-3369: Address getting username for LDAP users

api-channel-issue-tracker/src/main/java/com/synopsys/integration/alert/api/channel/issue/send/IssueTrackerAsyncMessageSender.java, api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/execution/ExecutingJob.java, api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/execution/ExecutingJobManager.java, api-processor/src/main/java/com/synopsys/integration/alert/processor/api/distribute/ProviderMessageDistributor.java, api-processor/src/test/java/com/synopsys/integration/alert/processor/api/JobNotificationProcessorTest.java, api-processor/src/test/java/com/synopsys/integration/alert/processor/api/distribute/ProviderMessageDistributorTest.java, src/test/java/com/synopsys/integration/alert/processing/ProcessingJobEventHandlerTestIT.java
- Add a count of expected notifications.
- Increment the count of expected notifications before sending a distribution event.
- In the issue tracker if there are no remaining events and the expected number of notifications has been reached end the job with success.
=> fix: Issue tracking jobs in pending status.

alert-common/src/main/java/com/synopsys/integration/alert/common/security/authorization/AuthorizationManager.java
SAML principals cant be casted to UserDetails. Use authentication.getName instead (better support for different princpal types as well). Confirmed authentication.getName and UserDetails.getUsername values are the same for both db and saml login.
=> IALERT-3394 saml distjob not showing

authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/model/LDAPAuthenticationType.java, authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/LDAPTestHelper.java, authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/model/LDAPAuthenticationTypeTest.java
Sonar issue:
```
Rename this constant name to match the regular expression '^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$'.
```
* Update to address sonar issue will still maintaining functionality of returning the lowercase value
* Update tests accordingly
=> sonar: Address sonar issues

buildSrc/runTasks.gradle
About 6 times in the last couple weeks, runServer failed (after doing all of the Alert startup tasks) because the keystore file did not exist. Re-running the gradle tasks fixes this.
Instead, add doFirst logic to fail if the file doesn't exists before doing all of the startup tasks.
=> Block runServer task if required file is not present

alert-platform/build.gradle, component/build.gradle
- All specific versions being used in Alert should be defined in alert-platform.
- There were openSAML libraries of version 3.4.6 in the dependency tree as a transitive in addition to 4.1.1 defined direct dependencies in the component project.
- Specify the openSAML library versions to 4.1.1 accross the board.
=>  Single SAML version defined in alert-platform only.

api-processor/src/main/java/com/synopsys/integration/alert/processor/api/JobNotificationContentProcessor.java, api-processor/src/main/java/com/synopsys/integration/alert/processor/api/extract/ProviderMessageExtractionDelegator.java
Policy notification, if they happen against the same component, can contain multiple policies in one notification. This is filtered during mapping but as a result of message extraction further down the line these policies are re-introduced as messages. This fix is it to perform an additional layer of filtering during message extraction by looking at the job details.
=> IALERT-3337: Policy filtering fix

channel-email/src/main/java/com/synopsys/integration/alert/channel/email/attachment/EmailAttachmentFileCreator.java, channel-email/src/main/java/com/synopsys/integration/alert/channel/email/distribution/EmailChannelMessagingService.java, channel-email/src/test/java/com/synopsys/integration/alert/channel/email/attachment/EmailAttachmentFileCreatorTest.java, test-common/src/main/java/com/synopsys/integration/alert/test/common/MockAlertProperties.java
Email attachments when occurring for multiple projects are broken up and distributed per project. Due to our concurrency changes this resulted in us having concurrency issue where we were trying to write to the same file multiple times. This resulted in an IOException, and submitting the wrong csv for the wrong project.
We will now create attachment files by adding a date timestamp to the file name.
=> IALERT-3307 email attachment fix

api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/audit/AuditEventTest.java, api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/audit/AuditFailedEventTest.java, api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/audit/AuditSuccessEventTest.java
Replace null checks on primitive types.
=> Fix test to check primitive timestamps.

buildSrc/deploymentTasks.gradle
- no longer create the helm chart tgz file in the deployment directory.
- create a new build/helmchart directory.
=> Create the helm chart in the build/helmchart package.

authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/model/LDAPConfigModel.java, authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/model/LDAPConfigTestModel.java
During DEV of 6.13.1, the get method name was changed. This caused Jackson to not be able to map the object name to the getter. As we want to refer to LDAP objects as all caps, leverage using JsonProperty to instruct Jackson how to map the object.
Also add serialVersionUID to both Data models.
=> IALERT-3418 - Specify object name to Jackson via JsonProperty annotation

build.gradle, buildSrc/buildTasks.gradle, buildSrc/docker.gradle
One of the PoP scans is failing for 2 reasons:
- The build is launched within a Docker image, as root. The source files are owned by the build account. When trying to run git, git fails as it detect files owned by multiple users
- The docker exec is not present within the Docker image where the build is being run.
Fixes:
* Create new project variable commitHash, with a default value.
* Create new Gradle task (getCommitHash). If it **can** run successfully, update the project variable to the commitHash.
* Update Gradle task createAboutText to use the new project variable for commitHash and not try to get it itself
* Add onlyIf logic to the Docker clean stages so it only runs if the Docker exec is found
=> Fix PoP scan failure

channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/JiraServerPropertiesFactory.java, channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/convert/JiraServerGlobalConfigurationModelConverter.java, channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/database/accessor/JiraServerGlobalConfigAccessor.java, channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/environment/JiraServerEnvironmentVariableHandler.java, channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/model/JiraServerGlobalConfigModel.java, channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/model/enumeration/JiraServerAuthorizationMethod.java, channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/validator/JiraServerGlobalConfigurationValidator.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/JiraServerExternalConnectionTest.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/action/JiraServerGlobalCrudActionsTest.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/action/JiraServerGlobalTestActionTest.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/convert/JiraServerGlobalConfigurationModelConverterTest.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/database/accessor/JiraServerGlobalConfigAccessorTest.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/validator/JiraServerGlobalConfigurationValidatorTest.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/web/JiraServerCustomFunctionActionTest.java, src/test/java/com/synopsys/integration/alert/channel/jira/server/action/JiraServerGlobalCrudActionsTestIT.java, src/test/java/com/synopsys/integration/alert/channel/jira/server/environment/JiraServerEnvironmentVariableHandlerTestIT.java, src/test/java/com/synopsys/integration/alert/channel/jira/server/web/JiraServerGlobalConfigControllerTestIT.java, src/test/java/com/synopsys/integration/alert/performance/utility/jira/server/JiraServerPerformanceUtility.java
The purpose of this PR is to implement three new fields into JiraServerGlobalConfigModel in order to support Bearer authorization in the future. To support this we've added the JiraServerAuthorizationMethod enum, accessToken, and isAccessToken set fields into the model.
The remainder of the changes are refactoring the implementation of this model and updating broken tests.
=> IALERT-3437: Jira Server model updates

README.md
Update documentation URL to point to the new Doc Portal. 
Remove broken link to Docker Compose README file.
Remove link to Docker Swarm README and indicate that install instructions are available on the Portal. 
Remove link to synopsysctrl install wiki.
(https://jira-sig.internal.synopsys.com/browse/IALERT-3429)
=> Resolve IALERT-3429

alert-database/src/main/resources/liquibase/6.13.0/concrete-saml-configuration-table.xml, alert-database/src/main/resources/liquibase/6.13.0/job-completion-status.xml
Liquibase throws an error if you changed files that had previously been run:
```
2023-04-28 18:51:02.427  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.ValidationFailedException: Validation Failed:
1 change sets check sum
liquibase/6.13.0/concrete-saml-configuration-table.xml::add_saml_metadata_mode_fk::mau was: 8:655766efe026e9689e2527913fe7a252 but is now: …
```
=> Revert "Adjusting liquibase files to work properly when re-run"

channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/validator/JiraServerGlobalConfigurationValidator.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/action/JiraServerGlobalValidationActionTest.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/validator/JiraServerGlobalConfigurationValidatorTest.java
This PR is being merged against IALERT-3430 to support the validation changes needed to work with the new authorization method.
Currently, we want to avoid merging into master as this would break against the existing Jira Server instance without the latest changes in int-jira-common being public. Additionally, the UI will need to be updated to support the new authorization method field as without it validation checks will fail.
=> IALERT-3443: Update validation for Jira Server to include access token auth

authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/security/SAMLGroupConverter.java
When granting authorities to user, get the preexisting ones to include as well if exists. This mimics the behavior of SAML pre-6.13.0 where added roles to a SAML user stay. However; if roles were removed, they will be regranted by SAML again upon log in (same behavior pre-6.13.0).
=> IALERT-3454 SAML grant preexisting roles

channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/database/accessor/JiraServerGlobalConfigAccessor.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/action/JiraServerGlobalCrudActionsTest.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/database/accessor/JiraServerGlobalConfigAccessorTest.java, src/test/java/com/synopsys/integration/alert/channel/jira/server/action/JiraServerGlobalCrudActionsTestIT.java, src/test/java/com/synopsys/integration/alert/channel/jira/server/web/JiraServerGlobalConfigControllerTestIT.java
Jira Server global configurations will only persist one set of credentials. Either username/password or access token. The end user can flip between the two but by doing so will be required to re-authenticate as a result.
The following cases should be noted:
- If using JiraServerAuthorizationMethod = BASIC, then access token is ignored and not persisted to the database on a save/update.
- If using JiraServerAuthorizationMethod = PERSONAL_ACCESS_TOKEN, then username & password are ignored and not persisted to the database on a save/update.
- Using the REST API a user can populate ALL authentication fields, but whatever the value is set for JiraServerAuthorizationMethod will determine which values are actually persisted. Ex. providing user/password/and accessToken but setting …
=> IALERT-3467 jira accessor persistance changes

channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/web/JiraServerInstallPluginAction.java
Extract the values from the database if they were persisted and not updated. This fixes a bug where attempting to install the plugin while editing a configuration would fail due to a missing password since we were passing in the obfuscated model.
=> IALERT-3475: Fix Jira Server install plugin when passing in a valid obfuscated model

ui/src/main/js/page/channel/jira/server/JiraServerModal.js, ui/src/main/js/store/actions/jira-server.js
Removed a close from the Jira Server modal when installing the plugin. Additionally I've renamed and moved around some logic to be a bit more explicit for what type of request is being made. We can rename these if the team prefers.
=> IALERT-3489: Fix Jira Server Install Plugin modal closing incorrectly

ui/src/main/js/page/audit/AuditFailureTable.js, ui/src/main/js/page/audit/RefreshFailureCell.js
The issue occurred only when the audit failures table was populated with values thereby displaying the RefreshFailureCell. There was a typo in this component leading to an error rendering the page.
Secondly, while investigating this fix I discovered the auto-refresh was also causing the page to error out. The cause of this issue was missing parameter configuration in the auto-refresh fetchAuditData function. Any time the page refreshed, undefined data was sent and led to an issue rendering the page as well.
=> IALERT_3493: Fix audit failures page not rendering

channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/web/JiraServerInstallPluginAction.java, ui/src/main/js/store/actions/jira-server.js
When returning a message from the Jira Install Plugin endpoint we would print only the general message but miss any additional information from the log message as well as the exception. This PR covers the back end fix as well as redux changes to support both message and errors fields.
=> IALERT-3476: Plugin error logging fix

ui/src/main/js/page/distribution/DistributionTable.js, ui/src/main/js/store/reducers/distribution.js
Use sortBy in the ui for distributions. There is a ticket created to address naming inconsistency namely sortBy vs sortName (used in AB and JS configs) and jobName vs name (name is used as a search term but our distribution model returned calls it jobName which leads to confusion in the ui).
=> IALERT-3483 distribution sorting not working

ui/src/main/js/page/about/AboutChannelCell.js, ui/src/main/js/page/about/AboutProviderCell.js, ui/src/main/js/store/actions/session.js
Navigation from the about page uses a different system of navigation via a-tags rather than NavLinks. As a result, pressing any of these to navigate essentially reloads the page but at the new URL. 
The change here is to bring navigation more in line with how we navigate on the left side navigation menu.
=> IALERT-3510: Fix navigation on audit page

ui/src/main/js/page/channel/azure/AzureBoardsModel.js
We accidentally changed the names of the field keys on the front end so the back end validation no longer recognized them. This change reverts the names.
=> IALERT-3514: Azure Boards distribution configuration fixes

ui/src/main/js/common/component/input/DropdownField.js, ui/src/main/js/common/component/table/SearchFilter.js, ui/src/main/js/common/component/table/Table.js, ui/src/main/js/common/component/table/TableFooter.js, ui/src/main/js/page/audit/AuditFailureTable.js, ui/src/main/js/page/channel/azure/AzureBoardsTable.js, ui/src/main/js/page/channel/jira/server/JiraServerTable.js, ui/src/main/js/page/distribution/DistributionTable.js
Adding the ability to update a table's page size.  What this does is allows the user to switch between 10, 25, 30, and 50 rows shown in a table.  These numbers came from legacy code, and can easily be updated in the TableFooter component.  A screenshot below shows where this can be found in a table.
=> IALERT-3515: Add Table Capability - Change Amount of Rows Shown in Table

alert-database/src/main/java/com/synopsys/integration/alert/database/audit/AuditEntryEntity.java, alert-database/src/main/java/com/synopsys/integration/alert/database/audit/AuditFailedEntity.java
It seems we removed annotation that specified error_stack_track as a text column in https://github.com/blackducksoftware/blackduck-alert/commit/eabb415fd92f66afe412b9613e04fa08b7e109b4
Resources online indicate that @Lob annotation does not work with postgres and will convert it to an id and store the contents in another table: https://stackoverflow.com/questions/67261808/jpa-with-postgres-anomalously-writes-text-in-lob-column-as-a-number
Since it is expecting a long and received text instead (pre-PR mentioned earlier will store it as text), the error throws. Fix is to remove @Lob annotation and monitor if the same upgrade results in audit page failures again.
=> IALERT-3526 Remove @Lob annotation

ui/src/main/js/common/component/button/Button.js, ui/src/main/js/common/component/button/IconButton.js, ui/src/main/js/page/usermgmt/user/UserCopyCell.js, ui/src/main/js/page/usermgmt/user/UserEditCell.js, ui/src/main/js/page/usermgmt/user/UserModal.js
Several improvements for the user page
- Disable copying externally managed users
- Add warning logging when editing externally managed users
- Fix console logging some errors when using incorrect props for the loading icon
=> IALERT-3513: Edit & Copy user page improvements 

ui/src/main/js/page/channel/email/EmailGlobalConfiguration.js
Popup on the help dialog for the only field in the Email Test Configuration Modal wasn't showing properly.  It should have been updated to use 'customDescription' prop.
=> IALERT-3519: Update Email Test Config Popup

ui/src/main/js/page/provider/ProviderModal.js, ui/src/main/js/store/reducers/provider.js
In the Provider modal, if a user doest not have the encryption settings set, then testing or saving a provider model will fail.  We did not properly show a message before.  This should fix that.  HUGE props to @ChomickiM for solving the root of this.
=> IALERT-3518: Show Error Message with No Password Setup

ui/src/main/js/application/Navigation.js
**Bug:**  
When a user clicks on 'Logout', the modal opens.  If they try to navigate to a separate link in the navigational list on the left hand side of the screen, the page will render with the clicked on navigation but the modal will still display.  In 6.13.x we closed the modal.
=> IALERT-3521: Close the Logout Modal When User Clicks on Separate Navigation Link

ui/src/main/js/common/component/modal/Modal.js
**Bug:**  
When a users viewport was small enough to make enable a modal scroll, the modal footer would be locked in place (relative to the position it initially was placed).  To fix this, I've just enabled overflow on the y axis of the modal body to automatically correct for itself.  This should allow the modal to scroll, locking the header/footer in place.
=> IALERT-3524: Modal Body Overflow

ui/src/main/js/page/channel/azure/AzureBoardsTable.js, ui/src/main/js/page/channel/azure/AzureBoardsTableActions.js, ui/src/main/js/page/channel/jira/server/JiraServerTable.js, ui/src/main/js/page/channel/jira/server/JiraServerTableActions.js, ui/src/main/js/page/distribution/DistributionTable.js, ui/src/main/js/page/distribution/DistributionTableActions.js
This MR should persist the search query, page number,  page length, and sort direction for a refresh on the updated 'concrete model' tables.  This also solves, IALERT-3496
=> IALERT-3528: Persist API Params on Table Refresh

ui/src/main/js/_theme.js, ui/src/main/js/page/distribution/DistributionStatusCell.js, ui/src/main/js/page/distribution/DistributionTable.js
Simple update to the ui of the audit status.  Here's the new look:
=> IALERT-3529: Update UI for Audit Status Cell

ui/src/main/js/page/audit/AuditFailureTable.js, ui/src/main/js/page/channel/azure/AzureBoardsTable.js, ui/src/main/js/page/channel/jira/server/JiraServerTable.js, ui/src/main/js/page/distribution/DistributionTable.js
Weird bug where the autorefresh would not use the params passed in by the user.  Solution was to provide the params for the api inside of the useEffect parameters array to ensure that the autorefresh is accepting the updated params.  Steps to reproduce bug can be seen in the comments of the ticket.
=> IALERT-3528: Ensure Autorefresh Utilizes API Params

alert-database-job/src/main/java/com/synopsys/integration/alert/database/api/DefaultDistributionAccessor.java, alert-database-job/src/main/java/com/synopsys/integration/alert/database/distribution/DistributionRepository.java, alert-database/src/main/resources/liquibase/7.1.0/changelog.xml, alert-database/src/main/resources/liquibase/7.1.0/update_timestamp_columns.xml, alert-database/src/main/resources/liquibase/changelog-postgres-master.xml, buildSrc/src/main/resources/init_test_db.sql, src/test/java/com/synopsys/integration/alert/database/api/DefaultDistributionAccessorTestIT.java
This is a fix to the issue that came up from updating spring boot.
The column last_run for table job_completion_status did not include 'with timezone' for the type. This PR adds in a liquibase file to alter the table, as well as data type changes to handle the data returned from PG including the timezone.
=> IALERT-3611 - Add timezone to DB column

ui/src/main/js/store/actions/audit.js
When ending with a slash, we throw a 404.
=> IALERT-3618 - Fix endpoint called when resend a failed notification

component/src/main/java/com/synopsys/integration/alert/component/certificates/AlertClientCertificateManager.java, component/src/main/java/com/synopsys/integration/alert/component/certificates/AlertSSLContextManager.java, component/src/main/java/com/synopsys/integration/alert/component/certificates/AlertTrustStoreManager.java, src/test/java/com/synopsys/integration/alert/component/certificates/AlertClientCertificateManagerTestIT.java, src/test/java/com/synopsys/integration/alert/component/certificates/AlertSSLContextManagerTestIT.java, src/test/java/com/synopsys/integration/alert/component/certificates/AlertTrustStoreManagerTestIT.java, src/test/java/com/synopsys/integration/alert/component/certificates/web/CertificateTestUtil.java, test-common/src/main/java/com/synopsys/integration/alert/test/common/MockAlertProperties.java
- Update the AlertSSLContextManager to create an SSL Context from the client certificate and the trust store file.
- Use the AlertClientCertificateManager to get the keystore for the client certificate data.  
- Use the AlertTrustStoreManager to get the keystore containing all the trusted certificates.  
- Use Spring Boot SSLBundle objects to load the keystores and create an SSLContext object to be used with HTTP requests in the future.
- Add additional tests to increase code coverage for the AlertTrustStoreManager class.
- Add additional tests to increase code coverage for the AlertClientCertificateManager class.
=> IALERT-3584: Create SSLContext from client keystore and truststore

component/src/main/java/com/synopsys/integration/alert/component/certificates/AlertSSLContextManager.java, src/main/java/com/synopsys/integration/alert/startup/component/AlertClientCertificateManagerStartupComponent.java, src/test/java/com/synopsys/integration/alert/component/certificates/AlertClientCertificateManagerTestIT.java, src/test/java/com/synopsys/integration/alert/component/certificates/web/CertificateTestUtil.java, src/test/java/com/synopsys/integration/alert/startup/component/AlertClientCertificateManagerStartupComponentTestIT.java
Adding a startup component to import the client certificate into memory from the database if one exists. 
Additionally to this, we've added some integration test coverage.
=> IALERT-3588: mtls certificate startup

api-certificates/src/main/java/com/synopsys/integration/alert/api/certificates/AlertSSLContextManager.java, api-channel/build.gradle, api-channel/src/main/java/com/synopsys/integration/alert/api/channel/rest/ChannelRestConnectionFactory.java, api-channel/src/test/java/com/synopsys/integration/alert/api/channel/rest/ChannelRestConnectionFactoryTest.java, channel-msteams/src/test/java/com/synopsys/integration/alert/channel/msteams/distribution/MsTeamsChannelTest.java, channel-slack/src/test/java/com/synopsys/integration/alert/channel/slack/distribution/SlackChannelTestIT.java, channel-slack/src/test/java/com/synopsys/integration/alert/channel/slack/distribution/SlackDistributionEventHandlerTest.java, src/test/java/com/synopsys/integration/alert/component/certificates/AlertSSLContextManagerTestIT.java
- Change AlertSSLContextManager to return the SSL Context only if client certificates are used.
- Change ChannelRestConnectionFactory to use the AlertSSLContextManager to utilize client certificates if they are configured.
=> IALERT-3585: Update ChannelRestConnectionFactory to use SSLContext.

channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/JiraServerProperties.java, channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/JiraServerPropertiesFactory.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/JiraServerExternalConnectionTest.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/JiraServerPropertiesTest.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/JiraServerSummaryFieldLengthTestIT.java, channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/web/JiraServerCustomFunctionActionTest.java
Added SSLContext to the JiraServerProperties and updated JiraServerPropertiesFactory to use the the SSLContextManager to build an SSL context from the persisted client certificate.
=> IALERT-3587: Add SSLContext support for jira server properties

src/main/resources/application.properties, web/src/main/java/com/synopsys/integration/alert/web/documentation/CustomOperationNameGenerator.java, web/src/main/java/com/synopsys/integration/alert/web/documentation/SwaggerConfiguration.java
The Open API generator can generate postman scripts from Alert's Open API specification created by SpringDoc.  While using the generator tool there were some issues uncovered that needed some updates in Alert.
The issues were:
- The REST API is not shown in alphabetical order in the Swagger UI
- The operation IDs aren't shown in the swagger UI
- The operation IDs generated although unique are in a naming convention that lacks context when the generator is used
- The operation IDs are getOne, getOne1, getOne12, getPage, getPage2, getPage12 which doesn't provide much context
- Use a bean that implements GlobalOperationCustomizer to update the operation IDs via a custom algorithm
- The algorithm creates a string from a prefix, context, and suffix string
- Prefix: api
- Context: abbreviated …
=> IALERT-3627: Generate unique operation ids

build.gradle, buildSrc/postman.gradle
Add necessary tasks to create the input to the OpenAPI postman collection generator, and execute the generate. The final task listed, createPostmanCollection, is what will be called by the build.  Comprehensive build run successfully
Postman tasks
-------------
createPostmanCollection - All tasks to create Postman collection. <primary task>
createSwaggerAPISpec - Runs the test which generates the input to create Postman collection. <sub-task>
pullOpenApiGeneratorImage - Pulls Docker image needed to create Postman collection. <sub-task>
renamePostmanCollection - Rename Postman collection. <sub-task>
runOpenAPIGenerator - Create the Postman collection. <sub-task>
=> IALERT-3631 - Add gradle tasks to generate postman collection

build.gradle, buildSrc/postman.gradle
Default ID in openapitools/openapi-generator-cli container is root. So all files created when running the container are owned by root. Within the build environment, the build ID is not able to clean up files owned by root.
Edit the build to run the Docker container as the same ID as the ID which launched gradle.
=> IALERT-3631 - Run Docker container as user running build

api-certificates/src/main/java/com/synopsys/integration/alert/api/certificates/AlertClientCertificateManager.java, component/src/main/java/com/synopsys/integration/alert/component/certificates/web/ClientCertificateConfigurationValidator.java, component/src/main/java/com/synopsys/integration/alert/component/certificates/web/ClientCertificateCrudActions.java, component/src/test/java/com/synopsys/integration/alert/component/certificates/web/ClientCertificateConfigurationValidatorTest.java, component/src/test/java/com/synopsys/integration/alert/component/certificates/web/ClientCertificateCrudActionsTest.java, src/test/java/com/synopsys/integration/alert/component/certificates/AlertClientCertificateManagerTestIT.java, src/test/java/com/synopsys/integration/alert/component/certificates/web/ClientCertificateControllerTestIT.java
It was discovered that if importing the certificate fails, the configuration remained persisted. The goal of this change is to remove the persisted certificate on a failure to import the certificate when the AlertClientCertificateManager cannot import the values.
To better prevent this issue I've enhanced the validation to also attempt creating the PemSslStoreBundle. This would do a dry-run without saving the bundle in memory but would test all the inputs of the model. To facilitate that behavior I've also slightly refactored the AlertClientCertificateManager to remove duplicate code for import and validation.
=> IALERT-3637: Add additional validation for client certificates

build.gradle
Since we don’t use yaml within liquibase, this dependency isn’t really needed. Force the version of snakeyaml in compile time to be the same as the version coming in for runtime.
Comprehensive build was successful
**output of gradle task `dependencies` for snakeyaml BEFORE edit**
```
|    +--- org.yaml:snakeyaml:1.33 (c)  <--- HERE
|    |    \--- org.yaml:snakeyaml:1.33  <--- HERE
|    +--- org.yaml:snakeyaml:1.33 -> 2.1 (c)
|    |    +--- org.yaml:snakeyaml:1.33 -> 2.1
|    |    |    |    \--- org.yaml:snakeyaml:1.33 -> 2.1
|         |    |         +--- org.yaml:snakeyaml:1.33 -> 2.1
|         |    |         |    +--- org.yaml:snakeyaml:2.1
|    +--- org.yaml:snakeyaml:1.33 -> 2.1 (c)
|    |    +--- org.yaml:snakeyaml:1.33 -> 2.1
|    |    |    |    \--- org.yaml:snakeyaml:1.33 -> 2.1
| …
```
=> IALERT-3643 - Force version of snakeyaml to be version from runtime

ui/src/main/js/page/certificates/CertificateModal.js
Each time the auto-refresh runs (30s) it updates the state of "data" in the front end from the values we have persisted. This then means that whenever your in the modal, it would clear the values that you've input with whatever was saved previously if you are updating.
Now, we only get the data in the initial state when you open the modal, and no longer re-check the state of the data. This resolves the issue where the server certificate was still working for Jira Server even when an invalid value was provided as it was getting reset before the user saved it.
=> IALERT-3651: Fix certificate data being overwritten while editing the certificate content

ui/src/main/js/application/auth/LdapForm.js
**Overview:**  
When the LDAP Test Configuration Modal was rendered on screen, the help text tooltips were on showing up on user click. 
**Fix Overview:**  
The fix was simple, switch the prop from `description` to `customDescription`.  `customDescription` was implemented in our UI changes in 7.0.0 specifically for tooltip/popovers in modals.
=> IALERT-3624 Display HelpText Popover in Test LDAP Config Modal

ui/src/main/js/common/component/table/SearchFilter.js, ui/src/main/js/common/component/table/Table.js, ui/src/main/js/common/component/table/TableSkeleton.js, ui/src/main/js/common/component/table/cell/MultiSelectCell.js, ui/src/main/js/page/distribution/DistributionConfigurationForm.js, ui/src/main/js/page/distribution/ProjectSelectModal.js
**Overview:**  
Client has requested the Project selection field, found in the Distribution Job Form, to be restructured.  Their request included that the dropdown field was not able to update the search, limit, or paging of the request that populates the data in that dropdown.  After review, I discovered that the request was hardcoded with searchQuery, limit, and pagination.  
**Fix Overview:**  
To fix this I reworked the field to do the following:
- A user can click on the field which will open a modal
- Inside the modal, a table will render where the user can select any or all projects
- Once the user has selected and pressed 'Save', the modal will disappear and the field will render the selected projects, to which the user can unselect a project(s) directly from the field, or they …
=> IALERT-3600 Reconfigure BlackDuck Project Selection For Distribution Job Form

ui/src/main/js/application/auth/AuthenticationModel.js, ui/src/main/js/application/auth/LdapForm.js
Matches 6.12.0 LDAP test modal where data was not retained for the LDAP test modal.
Rebased to v7.1.2
=> IALERT-3625 Do not retain test form data on fetch

ui/src/main/js/page/distribution/ProjectSelectModal.js
When a user is creating a distribution job and they are have selected a Black Duck provider, they have the ability to filter by project.  With the project selection modal open, if they navigate to any page other than 1 on the table and attempt to search/filter, the request returns no results.  This is due to the request containing the page number.  To fix this, I have reset the page number to 0 whenever a user searches/filters.
=> IALERT-3600: Reset Page Number on Search

authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/LDAPAuthenticationPerformerTest.java, authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/action/LDAPTestActionTest.java, authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/web/LDAPConfigControllerTest.java, build.gradle, buildSrc/src/main/resources/init_test_db.sql, src/test/java/com/synopsys/integration/alert/provider/blackduck/task/accumulator/BlackDuckAccumulatorTest.java
Upgrade the Spring Boot dependency to version 3.2.9.
To support this new version, the following additional changes needed to be made:
- Mockito spy can no longer be performed on a mocked object and will therefore error at test time. Refactored the tests to use mockito when without passing the spied object
- Added a missing semi-colon in causing failures after upgrade in init_test_db.sql
- Passing in the java compiler argument '-parameters' to resolve runtime errors with parameter matching in Spring 3.2
- Remove snakeyaml resolution strategy
=> IALERT-3610: upgrade sprint boot dependency

alert-platform/build.gradle
When performing upgrades, Liquibase is failing with a check sum error. Upon investigation, it seems very similar to this reported Liquibase bug: https://github.com/liquibase/liquibase/issues/5278
The fix is to upgrade to Liquibase 4.25.1. This change passed the dev, comprehensive, and deploy_test builds
=> IALERT-3732 - Upgrade version of liquibase to address liquibase issue

component/src/main/java/com/synopsys/integration/alert/component/authentication/security/AuthenticationHandler.java, ui/src/main/js/page/about/AboutInfoFooter.js
Update the security context to remove deprecated methods.  
Add the content security policy header to the security context.
Tests performed:
1. Open Alert UI verify the style of the UI and make sure images loaded.
3. Login to the Alert UI.
4. Create a Black Duck provider configuration.
5. Create a Jira Server configuration.
6. Create a distribution job.
7. In Black Duck generate notifications and make sure the Jira Issue is created and transitioned to Done.
=> IALERT-3676: add content-security-policy header

ui/src/main/js/page/usermgmt/user/UserModal.js, ui/src/main/js/page/usermgmt/user/UserModel.js
Test steps:
1. Verified "Passwords do not match." error message appears in UI for non-matching passwords
2. Verified create and update of user succeeds on matching password
3. Verified create and update payload do not have confirmPassword field
Following HUB; copy of password fields is disallowed but paste is allowed.
Create payload:
Update payload:
=> IALERT-3685 Remove confirm password field key from UI

ui/src/main/js/common/component/modal/Modal.js
For some reason the modals were not fitting the content within them.  This was likely due to one of our dependabot updates.  The fix for this was just to add left/right padding, as there was none prior to this.  This will ensure that content fits within the given space of our Modals.
=> IALERT-3746: Ensure Modals Fit Content

deployment/docker-swarm/external-db/docker-compose.local-overrides.yml, deployment/helm/synopsys-alert/templates/_helpers.tpl, deployment/helm/synopsys-alert/templates/alert.yaml, deployment/helm/synopsys-alert/values.yaml, docker/blackduck-alert/docker-entrypoint.sh, src/main/resources/application.properties
* Add new configuration option to values.yaml for Postgres named sslMode. --> [sslmode](https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-PROTECTION)
* Update logic in alert.yaml to only include Postgres secrets if sslUseFiles is true AND the individual secrets are configured.
* Update values.yaml to put comments on the Postgres secrets
* Update docker-entrypoint.sh for the following
* Default sslmode to disable as it is elsewhere
* New function setDatabaseConnectionDetails. 
* If root cert is configured, include it in connection
* If sslkey & sslcert are configured, include it in connection
* Define new value for spring datasource URL
* Pass new spring datasource URL to Alert exec, overriding default spring configuration value.
=> IALERT-3554 - Update SSL to better control SSL secrets and sslmode

ui/src/main/css/field.scss
After the recent dependabot fixes, it seems like a few UI elements broke including the alignment for fields. The original ticket lists alignment issues on the About page but upon investigation this is widespread in the entire UI impacting fields in both pages as well as modals. Attached are sample screenshots of the issue before and after the alignment and padding changes.
Before changes:
After the fix is applied:
Additionally, this solutions resolves as it was impacted by the same changes IALERT-3762
=> IALERT-3761: Fix field alignment issues

ui/src/main/js/page/settings/standalone/SettingsProxyConfiguration.js
The description field in an Input field is for non-modals and instead should be using customDescription field when setting the description inside of a modal.
This PR resolves the bug that was discovered. A separate task will be created to investigate consolidating the descriptions to be the same for both modals and non-modals as it is out of the scope of this bug fix.
=> IALERT-3763: Fix missing description in proxy modal

ui/src/main/js/common/component/input/field/LabeledField.js
This change is similar to the previous task regarding the tooltip description between modals and pages. Throughout the Alert app the colors for modal tooltips are also inconsistent as a result of using a custom tooltip.
The change here is to update the style of the custom tooltip to be similar to page tooltips.
=> IALERT-3764: modal tooltip consistency fix

ui/src/main/js/common/component/input/ToggleSwitch.js
It appears that after the bootstrap update some UI elements have been changed. The toggle switch for auto-refresh appears to have extra padding causing it to look too long compared to 7.2.0 and previous versions. This is a small change to update the padding so that the button is consistent with 7.2.0 and prior again.
=> IALERT-3771: auto refresh button fix

ui/src/main/js/page/channel/jira/server/JiraServerModal.js
Jira Server global configuration has an issue currently in the UI where clicking the test button multiple times will never actually call the test endpoint. The first time testing a validate request will be made, followed by a test assuming validation was successful. Regardless of valid or invalid input, any followup presses of the test config button will only validate, but never call test.
The fix here is a missing dispatch to the clear field errors which was missing from Jira but was present in other channels such as Azure. This resets the state of the for jira-server to re-validate and to re-test as the old test status was never reset.
=> IALERT-3656: Fix Jira Server Re-test

ui/src/main/css/field.scss
Status message padding was not properly aligned after the side nav and logo changes were made. These padding changes set it to be slightly more centered along the page and extends it to just before the side nav. Additionally, as the logo is now longer we have shifted the status message slightly below the Black Duck Alert logo.
See image for example of new status message.
=> IALERT-3776: Fix status message padding

src/test/java/com/blackduck/integration/alert/AboutReaderTest.java, src/test/java/com/blackduck/integration/alert/update/UpdateCheckerTest.java, web/src/main/java/com/blackduck/integration/alert/web/api/about/AboutReader.java, web/src/test/java/com/blackduck/integration/alert/web/api/about/AboutActionsTest.java
Use getContextPath for swagger ui link always. Tested on helm and docker-swarm (port 443, 30003).
=> IALERT-3615 Swagger UI public server port fix

ui/src/main/js/common/component/navigation/SideNavSubmenu.js
This PR is intended to fix 2 issues:
1. The alignment of the dropdown was incorrect and was opening the drop down under the nav button covering the other nav options. Shifting the dropdown to start at the end brings it to the right and out of the way.
2. This fixes the dropdown menu persisting after selecting an option and not closing. We continue to use NavLink rather than going directly to the href as going to the href directly would reload Alert between pages.
Alignment Before:
New alignment:
=> IALERT-3775: Fix side nav bugs

ui/src/main/js/common/component/modal/Modal.js
Disable scrolling for modal background. Note modal is the whole greyed area and modal content is where the actual modal is so scrolling is not affected for it.
=> IALERT-3780 Disable modal overflow

ui/src/main/js/common/component/modal/Modal.js
Resolves an issue where the save/edit button were cut off for long modals
=> IALERT-3780 Remove overflow and max height on modal content/area

provider-blackduck/src/main/java/com/blackduck/integration/alert/provider/blackduck/BlackDuckProviderDataAccessor.java, ui/src/main/js/page/channel/email/AdditionalEmailAddressesModal.js
The changes here are to add the a black duck query when fetching emails for the additional email addresses in the distribution job. The issue occurs because in blackduck-common when a page of results is fetched the total count reflects the number of items found prior to the predicate being applied. This means that while a subset of results are returned, the total count reflects the unfiltered set.
By using the query for the email field in Blackduck we can filter down the results at the time we make the request to get an accurate total count.
Secondly, there was a minor UI bug where if you filter from another page that reduces the total number of pages below the current page, the user would be presented with a modal table with no results. By switching it to page 0 every time we ensure that …
=> IALERT-3563: Fix additional email address search

channel-azure-boards/src/main/java/com/blackduck/integration/alert/channel/azure/boards/web/AzureBoardsOAuthFunctionController.java, channel-email/src/main/java/com/blackduck/integration/alert/channel/email/web/EmailAddressFunctionController.java, channel-jira-server/src/main/java/com/blackduck/integration/alert/channel/jira/server/web/JiraServerFunctionController.java, component/src/main/java/com/blackduck/integration/alert/component/audit/web/AuditEntryControllerLegacy.java, component/src/main/java/com/blackduck/integration/alert/component/authentication/web/SAMLMetadataUploadFunctionController.java, provider-blackduck/src/main/java/com/blackduck/integration/alert/provider/blackduck/web/PolicyFilterFunctionController.java, provider-blackduck/src/main/java/com/blackduck/integration/alert/provider/blackduck/web/VulnerabilityFilterFunctionController.java, web/src/main/java/com/blackduck/integration/alert/web/api/config/ConfigController.java, web/src/main/java/com/blackduck/integration/alert/web/api/job/JobConfigController.java, web/src/main/java/com/blackduck/integration/alert/web/api/metadata/ContextController.java, web/src/main/java/com/blackduck/integration/alert/web/api/metadata/DescriptorController.java, web/src/main/java/com/blackduck/integration/alert/web/api/metadata/DescriptorTypeController.java, web/src/main/java/com/blackduck/integration/alert/web/api/provider/processing/ProcessingTypeFunctionController.java
These controllers will no longer be getting additional features and lowered support. The goal is to migrate all Alert functionality into the new scheme for creating controllers and away from the generic controllers we've used in the past. As such, we want to flag controllers that will eventually be removed and replaced.
=> IALERT-3733: Deprecate legacy REST API controllers

channel-email/src/main/resources/templates/email/message_content.ftl
The freemarker template generating the Black Duck emails had it's height and width scaled for the old Synopsys logo. The scaling change here is to keep the same height as the old logo but switch the width to match the new logo.
=> IALERT-3758: Fix Black Duck logo scaling in the email template

alert-common/src/main/java/com/blackduck/integration/alert/common/rest/api/AbstractUploadFunctionController.java, component/src/main/java/com/blackduck/integration/alert/component/authentication/web/SAMLMetadataUploadFunctionController.java
During the previous deprecation changes the SAML upload function controller was not getting marked deprecated in Swagger. The change here is to update the controller to use the @RestController annotation which contains the @Controller annotation. Additionally, this deprecates the abstract controller that was only used by the legacy SAML upload controller.
=> IALERT-3733: Fix deprecated endpoint in Swagger UI

ui/src/main/js/page/channel/email/EmailDistributionConfiguration.js
If you attempt to save an email distribution job checking off "Additional Email Addresses Only" but do not provide any Additional Email Addresses we would return an error containing an error field and message but would never render it underneath the field. We would just print the banner message of "Invalid Configuration" with no additional context of what is invalid.
The change here is to just take the error name and value that were already correctly received, and pass the prop along to the DynamicSelectInput to correctly render the field error.
=> IALERT-3773: Fix missing error messages on email distribution configuration

api-channel-jira/src/main/java/com/blackduck/integration/alert/api/channel/jira/JiraConstants.java, api-channel-jira/src/main/java/com/blackduck/integration/alert/api/channel/jira/distribution/search/JqlStringCreator.java, api-channel-jira/src/test/java/com/blackduck/integration/alert/api/channel/jira/distribution/search/JqlStringCreatorTest.java
Jira tickets rely on a specific JQL query to find existing issues. As part of the rebranding we have changed in name of the property we used for indexing. In order to support backwards compatibility we are changing the condition we use to check and see if an issue exists, allowing us to find tickets made prior to 8.0.0 that still use the legacy property keys.
=> IALERT-3774: JQL search string backwards compatability

ui/src/main/js/application/MainPage.js, ui/src/main/js/common/component/modal/Modal.js
The empty space was taking in to account the nav bar. Since the nav bar and modal have different parent divs on the main page, there isnt an easy to have the modal just fill "content page". Instead just give the top nav bar a higher z index priority than modal.
=> IALERT-3780 Modal background fits scrolled content

web/src/main/java/com/blackduck/integration/alert/web/api/job/JobConfigActions.java, web/src/test/java/com/blackduck/integration/alert/web/api/job/JobConfigActionsTest.java
If a distribution job is configured in Alert that filters by Black Duck projects if no projects are selected we throw an error that a project must be selected. However, if an empty project that does not contain a project name or link is instead passed Alert will run into an error attempting to save these. 
The change here is to add additional validation to ensure that empty values cannot be passed in for required fields if project filtering is being used in distribution jobs.
=> IALERT-3782: Add empty project validation for disitribution jobs

ui/src/main/js/page/distribution/DistributionConfigurationForm.js
When solving https://github.com/blackducksoftware/blackduck-alert/pull/2634 I introduced a bug that did not send the proper request payload.  A user was able to create a Distribution Job, but when editing that job they were unable to save as the project filter portion of the payload contained an empty list.  This fix checks whether the payload object looks correct, and if not updates it to what it should be.
=> IALERT-3765: Project Filter Request

provider-blackduck/src/main/java/com/blackduck/integration/alert/provider/blackduck/processor/message/service/BlackDuckComponentVulnerabilityDetailsCreator.java, provider-blackduck/src/main/java/com/blackduck/integration/alert/provider/blackduck/processor/message/service/BlackDuckProjectVersionComponentVulnerabilitiesView.java, provider-blackduck/src/main/java/com/blackduck/integration/alert/provider/blackduck/processor/message/service/ProjectVersionComponentVersionVulnerabilityRemediationCvssView.java, provider-blackduck/src/test/java/com/blackduck/integration/alert/provider/blackduck/processor/message/service/BlackDuckComponentVulnerabilityDetailsCreatorTest.java
Hub 2025.1.0 replaces `useCvss3` field with `cvssVersion` in notification objects. To ensure backwards compatibility with 2024.10.0 of hub, `useCvss3` is kept and `cvssVersion` is added. If `cvssVersion` value is available, it will use that; otherwise it will attempt to use `useCvss3`. Logic for getting CVSS4 severity is also included in this PR.
=> IALERT-3790 Fix for compatibility with cvss 4

ui/src/main/js/Index.js, ui/src/main/js/index.html
As Dana was working on a re-routing issue, he had to introduce some additions to headers.  Adding `script-src 'self' 'unsafe-eval'` imposes some risks to our UI.  To counteract this, I removed the reference for `FontAwesomeConfig` via `<script>` in our index.html file and instead call it now in the index.js file where it will be applied directly to the dom via Javascript.
=> IALERT-3800: Updates to FontAwesome Configuration

component/src/main/java/com/blackduck/integration/alert/component/authentication/security/AuthenticationHandler.java
Connecting to SAML stopped working in 8.0.0. @psantos1113 figured out the edits to the content security policy in order to get this working again.
I performed a deploy of the images from this branch, and I was able to connect and login to SAML successfully, and get redirected back to Alert.
=> IALERT-3805 - Remove default-src, set script-src to unsafe-inline

api-channel-jira/src/main/java/com/blackduck/integration/alert/api/channel/jira/distribution/custom/JiraCustomFieldResolver.java
Add support for the Jira Cloud Custom Field type of "object" and add support for Jira Server Custom Field type of "any".
Had to build a forge app to define a custom field of type "object" for Jira Cloud to be able to configure a custom field with the correct "object" type to test.  For this type Alert will create a `JsonObject`.
Had to build a plugin app for Jira Server to define a custom field of type "any" to be able to configure a custom field with the correct "any" type to test.  For this type Alert will pass the string as is to Jira Server.
=> Fix: IALERT-3810 add custom field type object and any support

deployment/helm/blackduck-alert/templates/postgres.yaml, deployment/helm/blackduck-alert/values.yaml
ALERT-3312 
https://documentation.blackduck.com/bundle/alert/page/topics/troubleshooting/troubleshooting-issues-in-alert.html
Helm Deployment Storage Configuration Issue
"To workaround this issue you must update the postgres.yaml file under helm/blackduck-alert/templates/postgres.yaml.Update the following sections."
Allows to pass in config update to the postgres volumeMount using helm instead of having to patch the postgres.yaml file
Can do this update in values if require to use subPath
```
volumeMounts:
- mountPath: /var/lib/postgresql
subPath: data
name: alert-postgres-data-volume
```
This makes doing this update much easier and not needing to either patch or fork your helm chart …
=> ALERT-3312 - Adding volumeMounts option to postgres in values

alert-common/src/main/java/com/blackduck/integration/alert/common/persistence/model/job/details/JiraJobCustomFieldModel.java, alert-database/src/main/java/com/blackduck/integration/alert/database/job/jira/cloud/DefaultJiraCloudJobDetailsAccessor.java, alert-database/src/main/java/com/blackduck/integration/alert/database/job/jira/cloud/custom_field/JiraCloudJobCustomFieldEntity.java, alert-database/src/main/resources/liquibase/8.1.0/changelog.xml, alert-database/src/main/resources/liquibase/8.1.0/jira-custom-field-add-create-object-column.xml, alert-database/src/main/resources/liquibase/changelog-postgres-master.xml, api-channel-jira/src/main/java/com/blackduck/integration/alert/api/channel/jira/distribution/JiraIssueCreationRequestCreator.java, api-channel-jira/src/main/java/com/blackduck/integration/alert/api/channel/jira/distribution/custom/JiraCustomFieldConfig.java, api-channel-jira/src/main/java/com/blackduck/integration/alert/api/channel/jira/distribution/custom/JiraCustomFieldResolver.java, api-channel-jira/src/main/java/com/blackduck/integration/alert/api/channel/jira/validation/JiraFieldMappingValidator.java, api-channel-jira/src/test/java/com/blackduck/integration/alert/api/channel/jira/distribution/custom/JiraCustomFieldConfigTest.java, channel-jira-server/src/main/java/com/blackduck/integration/alert/channel/jira/server/database/accessor/DefaultJiraServerJobDetailsAccessor.java, channel-jira-server/src/main/java/com/blackduck/integration/alert/channel/jira/server/database/job/custom_field/JiraServerJobCustomFieldEntity.java, channel-jira-server/src/test/java/com/blackduck/integration/alert/channel/jira/server/database/accessor/JiraServerJobDetailsAccessorTest.java, ui/src/main/js/page/channel/jira/common/FieldMappingModal.js, ui/src/main/js/page/channel/jira/common/JiraFieldAlwaysCreateJsonCell.js, ui/src/main/js/page/channel/jira/common/JiraFieldMapDistributionTable.js
Add a checkbox to indicate that the value for the custom field should be serialized as a JSON element when sent as a value for a custom field.  This overrides the inspection of the custom field type done by Alert to create JSON content for  custom fields that match the defined type.  This is because when a custom field has a type of any the implementation of the custom field controls what the REST API accepts as a value for the type.  When this checkbox is selected the value is assumed to be a valid JSON string that can be parsed into a JSON object or JSON array.
In order to provide this functionality the following was needed:
1. Add a new database column
2. Change the models the accessor to include the new field
3. Change the UI to display a checkbox in the custom field modal
4. Make the …
=> Fix: IALERT-3810 add override for custom fields

deployment/helm/blackduck-alert/values.yaml
The logic to handle subPath was added to `templates/postgres.yaml`, but we weren't adding this to values.yaml with a default. Adjust the implementation to do this, but still have the final directory that the PV/PVC points at is ultimately the same thing. 
To see the original change, see this MR --> [https://github.com/blackducksoftware/blackduck-alert/pull/2650/files](https://github.com/blackducksoftware/blackduck-alert/pull/2650/files)
=> IALERT-3312 - Include subPath in values.yaml with defaults

ui/src/main/js/page/usermgmt/roles/PermissionTable.js, ui/src/main/js/page/usermgmt/roles/PermissionTableActions.js, ui/src/main/js/page/usermgmt/roles/RoleModal.js
When a user creates a role in the UI, we currently allow them to add as many permissions with as many descriptors as they want, regardless of if there are duplicate descriptors.  If a user then tries to remove a permission, we will remove all permissions that match the descriptor name.  This happens because we remove a permission based on the descriptor name (**That is the bug**).  The catch all is that a user should not be allowed to add duplicate descriptors, as the validation will fail and a message will show, letting the user know this cannot happen.
To fix this, the UI will proactively check if there are duplicate descriptors and not allow the user to add a second descriptor if this is the case.  We now will show a validation message inside of the modal that lets the user know this …
=> IALERT-3811: Stop User from Adding Duplicate Descriptors When Creating Roles

deployment/helm/blackduck-alert/values.yaml
On upgrade, having a different mountPath is breaking the installation. Revert the addition of subPath, and set mountPath to be the same as what it was before the edit for this ticket.
=> IALERT-3312 - Revert adding subPath to values.

alert-database-job/src/main/java/com/blackduck/integration/alert/database/job/api/StaticJobAccessor.java, alert-database/src/main/java/com/blackduck/integration/alert/database/job/jira/cloud/DefaultJiraCloudJobDetailsAccessor.java, ui/src/main/js/page/channel/jira/common/JiraFieldMapDistributionTable.js
The Jira cloud custom fields UI was not showing the correct value for the "Treat Value as JSON" checkbox.  The correct data was being persisted but when converting from the database model to a distribution model the wrong constructor was being used.  The value was always being set to false for Jira Cloud jobs specifically resulting in the wrong state being viewed in the UI for Jira Cloud only.
=> IALERT-3810: fix jira cloud custom field

docker/blackduck-alert-db/Dockerfile, docker/blackduck-alert-rabbitmq/Dockerfile, docker/blackduck-alert/Dockerfile
Address the docker build warnings listed below before they become build failures.
**blackduck-alert-db**
```
4 warnings found (use docker --debug to expand):
- InvalidDefaultArgInFrom: Default value for ARG ${POSTGRESIMAGEVERSION_MIGRATION} results in empty or invalid base image name (line 6)
- InvalidDefaultArgInFrom: Default value for ARG ${POSTGRESIMAGEVERSION} results in empty or invalid base image name (line 8)
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 12)
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 13)
```
**blackduck-alert-rabbitmq**
```
3 warnings found (use docker --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)
- …
```
=> Address docker build warnings

ui/src/main/js/page/usermgmt/user/UserModal.js
When a user attempts to create a user, but does not enter any information into the fields, the network request returns a 500 but the form field errors do not appear.  This happens because the design of the endpoint.  The request will not be successful if the password fields do not have values.  Because of this, the form validation never occurs.  As a side note, if the user places any values into the password/confirm password fields and submits the form, then the form validation will occur thus showing the proper field errors.  
So as to not change anything on the BE, the UI will now proactively check if the password/confirm password fields contain values. In the event that they do not, we will disable the ability to submit the form (the 'Create' button will be disabled in the modal). …
=> IALERT-3808: Create User Field Validation

api-channel-jira/src/main/java/com/blackduck/integration/alert/api/channel/jira/distribution/search/JiraExactIssueFinder.java, channel-azure-boards/src/main/java/com/blackduck/integration/alert/channel/azure/boards/distribution/search/AzureBoardsComponentIssueFinder.java, channel-azure-boards/src/main/java/com/blackduck/integration/alert/channel/azure/boards/distribution/search/AzureSearchFieldMappingBuilder.java, channel-azure-boards/src/test/java/com/blackduck/integration/alert/channel/azure/boards/distribution/search/AzureSearchFieldMappingBuilderTest.java
The issue occurs when you have a component with a specific version that violates policy i.e. Component 1.0.0. This generates a policy violation ticket and Alert creates the Policy related issue tracking ticket.  When a new scan is performed or the component is manually edited in Black Duck SCA to a new version, then the policy related issue tracking ticket will not be resolved because the component version is included in the query for the issue.  When the component is updated to a new version then the original ticket will not be updated.  
For example if Component 1.0.0 violates the policy then the component version is used when the issue is created.  Now if the component is updated to Component 1.0.1, a patched version that no longer violates policy, the issue would not be found because …
=> Fix: IALERT-3832 resovle policy tickets when component version is updated

ui/src/main/js/page/usermgmt/roles/PermissionTable.js, ui/src/main/js/page/usermgmt/roles/PermissionTableActions.js, ui/src/main/js/page/usermgmt/roles/RoleModal.js
When a user creates a role in the UI, we currently allow them to add as many permissions with as many descriptors as they want, regardless of if there are duplicate descriptors. If a user then tries to remove a permission, we will remove all permissions that match the descriptor name. This happens because we remove a permission based on the descriptor name (That is the bug). The catch all is that a user should not be allowed to add duplicate descriptors, as the validation will fail and a message will show, letting the user know this cannot happen.
This was a regression based on the fact that a user could no longer add a descriptor with differing contexts, as Dana mentioned offline, "Azure Boards has 2 types for Context. If you use the Descriptor Name as the only value to prove uniqueness, …
=> IALERT-3811: (Regression) Stop User from Adding Duplicate Descriptors When Creating Roles

ui/src/main/js/page/usermgmt/user/UserModal.js
When a user attempts to edit a user, they are unable to click 'Save' as the button is disabled based on some client side validation in the code
Since we are validating the password fields are entered in the UI code (before they are server side validated to match the requirements), we need to update the validation to allow for editing.  Previously we would disable submit in this modal if one or both Password and Confirm Password fields were empty.  This creates an issue when editing a user, as the Confirm Password field will be empty.  To combat this, I've updated the validation to:
- First check if the password is set (this means the user has already created a password and only occurs when the user is editing)
- Second check if either the Password or Confirm Password fields are empty, if …
=> IALERT-3855: Create/Edit/Copy User Client Side Password Validation

ui/src/main/js/page/usermgmt/user/UserModal.js
In https://github.com/blackducksoftware/blackduck-alert/pull/2669, we improved the validation steps on the confirm password field but unintentionally removed the asterisks associated with a filled in password on that field.  When a user is editing within the User Modal, we should show that the "Confirm Password" field is indeed filled in by showing the asterisks.  
In component, `UserModal` on line 209, revert the `isSet` prop to check if the model does have `IS_PASSWORD_SET`.  This does not impact the work done in IALERT-3811.
=> IALERT-3685: Show Password Set Field Asterisks

build.gradle
Updating the version of spring-boot to 3.3.13 to update versions of transitive dependencies.
=> IALERT-3815: Upgrade spring-boot to 3.3.13

alert-platform/build.gradle, api-channel-jira/src/main/java/com/blackduck/integration/alert/api/channel/jira/distribution/JiraIssueCreationRequestCreator.java, api-channel-jira/src/main/java/com/blackduck/integration/alert/api/channel/jira/distribution/delegate/JiraIssueCommenter.java, api-channel-jira/src/test/java/com/blackduck/integration/alert/api/channel/jira/util/JiraCallbackUtilsTest.java, channel-jira-cloud/src/main/java/com/blackduck/integration/alert/channel/jira/cloud/action/JiraCloudGlobalFieldModelTestAction.java, channel-jira-cloud/src/main/java/com/blackduck/integration/alert/channel/jira/cloud/distribution/JiraCloudMessageSenderFactory.java, channel-jira-cloud/src/main/java/com/blackduck/integration/alert/channel/jira/cloud/distribution/JiraCloudQueryExecutor.java, channel-jira-cloud/src/main/java/com/blackduck/integration/alert/channel/jira/cloud/distribution/delegate/JiraCloudIssueCommenter.java, channel-jira-cloud/src/main/java/com/blackduck/integration/alert/channel/jira/cloud/distribution/event/JiraCloudCommentEventHandler.java, channel-jira-cloud/src/main/java/com/blackduck/integration/alert/channel/jira/cloud/distribution/event/JiraCloudCreateIssueEventHandler.java, channel-jira-cloud/src/main/java/com/blackduck/integration/alert/channel/jira/cloud/distribution/event/JiraCloudTransitionEventHandler.java, channel-jira-cloud/src/main/java/com/blackduck/integration/alert/channel/jira/cloud/task/JiraPropertyUpdateTask.java, channel-jira-cloud/src/test/java/com/blackduck/integration/alert/channel/jira/cloud/JiraCloudIssueCreatorTest.java, channel-jira-cloud/src/test/java/com/blackduck/integration/alert/channel/jira/cloud/distribution/event/JiraCloudCommentEventHandlerTest.java, channel-jira-cloud/src/test/java/com/blackduck/integration/alert/channel/jira/cloud/distribution/event/JiraCloudCreateIssueEventHandlerTest.java, channel-jira-cloud/src/test/java/com/blackduck/integration/alert/channel/jira/cloud/model/TestIssueResponse.java, channel-jira-server/src/main/java/com/blackduck/integration/alert/channel/jira/server/distribution/JiraServerMessageSenderFactory.java, channel-jira-server/src/main/java/com/blackduck/integration/alert/channel/jira/server/distribution/delegate/JiraServerIssueCommenter.java, channel-jira-server/src/main/java/com/blackduck/integration/alert/channel/jira/server/distribution/event/JiraServerCommentEventHandler.java, channel-jira-server/src/main/java/com/blackduck/integration/alert/channel/jira/server/distribution/event/JiraServerCreateIssueEventHandler.java, channel-jira-server/src/main/java/com/blackduck/integration/alert/channel/jira/server/distribution/event/JiraServerTransitionEventHandler.java, channel-jira-server/src/test/java/com/blackduck/integration/alert/channel/jira/server/distribution/delegate/JiraServerIssueCreatorTest.java, channel-jira-server/src/test/java/com/blackduck/integration/alert/channel/jira/server/distribution/event/JiraServerCommentEventHandlerTest.java, channel-jira-server/src/test/java/com/blackduck/integration/alert/channel/jira/server/distribution/event/JiraServerCreateIssueEventHandlerTest.java, channel-jira-server/src/test/java/com/blackduck/integration/alert/channel/jira/server/model/TestIssueResponse.java
Update Alert to use int-jira-common 6.0.0.  This is dependent upon the release of int-jira-common 6.0.0 which is blocked by the merge of this MR: https://github.com/blackducksoftware/int-jira-common/pull/64
Once that MR is merge int-jira-common 6.0.0 can be released and this is the changes to Alert to use the new APIs.
Since the communication issue with Jira Cloud was found while testing the timeout feature this change will be merged into the branch for the Jira Cloud timeout value. 
If we need to cherry pick the changes to create a different branch this MR can be used as a blueprint but the goal is to get the Jira Cloud timeout feature reviewed and merged into v8.3.0.
=> Update to use new Jira Cloud APIs

ui/src/main/js/page/channel/jira/server/JiraServerModal.js
Timeout for Jira Server was in a different layout than other timeouts (Jira Cloud & Blackduck Provider) small change to just shuffle the UI elements around to come after the credentials.
=> IALERT-3886: jira server timeout reorder

channel-jira-cloud/src/main/java/com/blackduck/integration/alert/channel/jira/cloud/validator/JiraCloudGlobalConfigurationFieldModelValidator.java
Errors occuring when invalid inputs were passed in were not getting appropriately handled and were failing silently in the backend with no messages in the UI. This change uses NumberUtils in a way similar to what was implemented in the provider  timeout.
=> IALERT-3894: Jira timeout input handling

ui/src/main/js/page/channel/jira/cloud/JiraCloudGlobalConfiguration.js
Description field placement was over arrow, and description ended with 2 periods:
Fixed:
=> IALERT-3898 - Fix description for Jira cloud
