build.gradle
package-lock.json
package.json
src/main/css/main.css
src/main/js/App.js
webpack.config.js

Added the necessary changes to webpack for styling as well as adding tabs and css modules.

Alert ready for styling

---

src/main/css/main.css
src/main/js/App.js
src/main/js/component/EmailConfiguration.js
src/main/js/component/GlobalConfiguration.js
src/main/js/component/HipChatConfiguration.js
src/main/js/component/SlackConfiguration.js

Completed everything (Except the logo in top left) for the first look of the UI.

Alert styling

---

src/main/java/com/blackducksoftware/integration/hub/alert/channel/DistributionChannel.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/email/EmailChannel.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/hipchat/HipChatChannel.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/slack/SlackChannel.java
src/main/java/com/blackducksoftware/integration/hub/alert/datasource/entity/CommonDistributionConfigEntity.java
src/main/java/com/blackducksoftware/integration/hub/alert/datasource/entity/EmailGroupDistributionConfigEntity.java
src/main/java/com/blackducksoftware/integration/hub/alert/datasource/entity/repository/CommonDistributionRepository.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/actions/CommonDistributionConfigActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/actions/DistributionConfigActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/actions/EmailGroupDistributionConfigActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/actions/GlobalEmailConfigActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/CommonDistributionConfigController.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/EmailGroupDistributionController.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/GlobalEmailConfigController.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/model/CommonDistributionConfigRestModel.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/model/ConfigRestModel.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/model/EmailGroupDistributionRestModel.java
src/test/java/com/blackducksoftware/integration/hub/alert/channel/email/EmailChannelTestIT.java
src/test/java/com/blackducksoftware/integration/hub/alert/datasource/entity/repository/CommonDistributionRepositoryTestIT.java
src/test/java/com/blackducksoftware/integration/hub/alert/datasource/entity/repository/ConfiguredProjectsRepositoryTestIT.java
src/test/java/com/blackducksoftware/integration/hub/alert/datasource/entity/repository/EmailDistributionRepositoryTestIT.java
src/test/java/com/blackducksoftware/integration/hub/alert/datasource/entity/repository/HipChatDistributionRepositoryTestIT.java
src/test/java/com/blackducksoftware/integration/hub/alert/datasource/entity/repository/NotificationRepositoryIT.java
src/test/java/com/blackducksoftware/integration/hub/alert/datasource/entity/repository/SlackDistributionRepositoryTestIT.java
src/test/java/com/blackducksoftware/integration/hub/alert/datasource/entity/repository/global/GlobalEmailRepositoryIT.java
src/test/java/com/blackducksoftware/integration/hub/alert/datasource/entity/repository/global/GlobalHipChatRepositoryIT.java
src/test/java/com/blackducksoftware/integration/hub/alert/datasource/entity/repository/global/GlobalRepositoryIT.java
src/test/java/com/blackducksoftware/integration/hub/alert/datasource/entity/repository/global/GlobalSlackRepositoryIT.java
src/test/java/com/blackducksoftware/integration/hub/alert/datasource/relation/repository/DistributionProjectRepositoryTestIT.java

EmailGroup and CommonDistribution functionality.

EmailGroup restructure

---

build.gradle
src/main/java/com/blackducksoftware/integration/hub/alert/web/actions/LoginActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/LoginController.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/handler/LoginDataHandler.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/handler/LoginHandler.java
src/test/java/com/blackducksoftware/integration/hub/alert/web/actions/LoginActionsTestIT.java

Verifies that the user has the administrator role before they are allowed to log in.

Login action

---

src/main/java/com/blackducksoftware/integration/hub/alert/channel/ChannelEventFactory.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/ChannelRestConnectionFactory.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/DistributionChannel.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/email/EmailGroupChannel.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/email/EmailManager.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/hipchat/HipChatChannel.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/hipchat/HipChatManager.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/manager/ChannelEventFactory.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/manager/DistributionChannelManager.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/slack/SlackChannel.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/slack/SlackManager.java
src/main/java/com/blackducksoftware/integration/hub/alert/datasource/entity/distribution/DistributionChannelConfigEntity.java
src/main/java/com/blackducksoftware/integration/hub/alert/datasource/entity/distribution/EmailGroupDistributionConfigEntity.java
src/main/java/com/blackducksoftware/integration/hub/alert/datasource/entity/distribution/HipChatDistributionConfigEntity.java
src/main/java/com/blackducksoftware/integration/hub/alert/datasource/entity/distribution/SlackDistributionConfigEntity.java
src/main/java/com/blackducksoftware/integration/hub/alert/datasource/entity/global/GlobalChannelConfigEntity.java
src/main/java/com/blackducksoftware/integration/hub/alert/datasource/entity/global/GlobalEmailConfigEntity.java
src/main/java/com/blackducksoftware/integration/hub/alert/datasource/entity/global/GlobalHipChatConfigEntity.java
src/main/java/com/blackducksoftware/integration/hub/alert/datasource/entity/repository/global/GlobalSlackRepository.java
src/main/java/com/blackducksoftware/integration/hub/alert/digest/filter/NotificationEventManager.java
src/main/java/com/blackducksoftware/integration/hub/alert/event/AbstractChannelEvent.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/ObjectTransformer.java
src/test/java/com/blackducksoftware/integration/hub/alert/channel/manager/DistributionChannelManagerTestIT.java

Add functionality to create events more dynamically.

---

src/main/java/com/blackducksoftware/integration/hub/alert/datasource/entity/repository/ConfiguredProjectsRepository.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/actions/distribution/CommonDistributionConfigActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/actions/distribution/DistributionConfigActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/actions/distribution/EmailGroupDistributionConfigActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/actions/distribution/HipChatDistributionConfigActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/actions/distribution/SlackDistributionConfigActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/model/distribution/CommonDistributionConfigRestModel.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/model/distribution/EmailGroupDistributionRestModel.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/model/distribution/HipChatDistributionRestModel.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/model/distribution/SlackDistributionRestModel.java
src/test/java/com/blackducksoftware/integration/hub/alert/web/actions/distribution/CommonDistributionConfigActionsTestIT.java

I will be adding tests before this is merged, but the logic should be fairly clear at this time.

Configured Projects in RestModels

---

src/main/java/com/blackducksoftware/integration/hub/alert/datasource/entity/CommonDistributionConfigEntity.java
src/main/java/com/blackducksoftware/integration/hub/alert/datasource/entity/NotificationTypeEntity.java
src/main/java/com/blackducksoftware/integration/hub/alert/datasource/entity/repository/NotificationTypeRepository.java
src/main/java/com/blackducksoftware/integration/hub/alert/datasource/relation/DistributionNotificationTypeRelation.java
src/main/java/com/blackducksoftware/integration/hub/alert/datasource/relation/key/DistributionNotificationTypeRelationPK.java
src/main/java/com/blackducksoftware/integration/hub/alert/datasource/relation/repository/DistributionNotificationTypeRepository.java
src/main/java/com/blackducksoftware/integration/hub/alert/digest/filter/NotificationPostProcessor.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/actions/ConfiguredProjectsActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/actions/NotificationTypesActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/actions/distribution/CommonDistributionConfigActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/actions/distribution/DistributionConfigActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/actions/distribution/EmailGroupDistributionConfigActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/actions/distribution/HipChatDistributionConfigActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/actions/distribution/SlackDistributionConfigActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/model/distribution/CommonDistributionConfigRestModel.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/model/distribution/EmailGroupDistributionRestModel.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/model/distribution/HipChatDistributionRestModel.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/model/distribution/SlackDistributionRestModel.java
src/test/java/com/blackducksoftware/integration/hub/alert/datasource/entity/repository/CommonDistributionRepositoryTestIT.java
src/test/java/com/blackducksoftware/integration/hub/alert/digest/DigestNotificationProcessorIT.java
src/test/java/com/blackducksoftware/integration/hub/alert/web/actions/distribution/CommonDistributionConfigActionsTestIT.java

DO NOT MERGE UNTIL _scheduling_config_ IS IN _master_.

Notification types restructure

---

src/main/java/com/blackducksoftware/integration/hub/alert/channel/DistributionChannel.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/email/EmailGroupChannel.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/email/EmailGroupManager.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/hipchat/HipChatChannel.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/hipchat/HipChatManager.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/manager/ChannelEventFactory.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/manager/DistributionChannelManager.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/slack/SlackChannel.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/slack/SlackManager.java
src/main/java/com/blackducksoftware/integration/hub/alert/digest/filter/NotificationEventManager.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/actions/distribution/EmailGroupDistributionConfigActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/actions/distribution/HipChatDistributionConfigActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/actions/distribution/SlackDistributionConfigActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/distribution/CommonDistributionConfigController.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/distribution/EmailGroupDistributionController.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/distribution/HipChatDistributionConfigController.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/distribution/SlackDistributionConfigController.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/global/GlobalEmailConfigController.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/global/GlobalHipChatConfigController.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/global/GlobalHubConfigController.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/global/GlobalSchedulingConfigController.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/handler/CommonConfigHandler.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/handler/CommonGlobalConfigHandler.java
src/test/java/com/blackducksoftware/integration/hub/alert/channel/manager/DistributionChannelManagerTestIT.java
src/test/java/com/blackducksoftware/integration/hub/alert/web/actions/GlobalEmailConfigActionsTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/web/actions/GlobalHipChatConfigActionsTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/web/actions/distribution/EmailGroupDistributionConfigActionsTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/web/actions/distribution/HipChatDistributionConfigActionsTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/web/actions/distribution/SlackDistributionConfigActionsTest.java

I also refactored CommonConfigController to be CommonConfigHandler.
**NOTE**: This depends on the _test_message_ branch being merged to master.

Only allow one global configuration.

---

src/main/java/com/blackducksoftware/integration/hub/alert/datasource/entity/AuditEntryEntity.java
src/main/java/com/blackducksoftware/integration/hub/alert/datasource/entity/repository/AuditEntryRepository.java
src/main/java/com/blackducksoftware/integration/hub/alert/digest/DigestNotificationProcessor.java
src/main/java/com/blackducksoftware/integration/hub/alert/digest/model/ProjectDataFactory.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/ObjectTransformer.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/AuditEntryController.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/handler/AuditEntryHandler.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/model/AuditEntryRestModel.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/model/NotificationRestModel.java
src/test/java/com/blackducksoftware/integration/hub/alert/MockUtils.java
src/test/java/com/blackducksoftware/integration/hub/alert/web/controller/handler/AuditEntryHandlerTestIT.java

I will merge this after finishing tests.

Audit backend

---

src/main/css/table.css
src/main/java/com/blackducksoftware/integration/hub/alert/scheduling/controller/GlobalSchedulingConfigController.java
src/main/js/component/audit/Audit.js
src/main/js/component/distribution/DistributionConfiguration.js
src/main/js/component/distribution/job/BaseJobConfiguration.js
src/main/js/component/distribution/job/HipChatJobConfiguration.js

- Fixing color of pending status
- Adding auto refresh to Job table
- Adding color drop down to the HipChat configuration

Ui updates

---

src/main/css/field.css
src/main/java/com/blackducksoftware/integration/hub/alert/Application.java
src/main/java/com/blackducksoftware/integration/hub/alert/StartupManager.java
src/main/java/com/blackducksoftware/integration/hub/alert/accumulator/AccumulatorProcessor.java
src/main/java/com/blackducksoftware/integration/hub/alert/accumulator/AccumulatorWriter.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/email/EmailProperties.java
src/main/java/com/blackducksoftware/integration/hub/alert/config/CommonConfig.java
src/main/java/com/blackducksoftware/integration/hub/alert/config/GlobalProperties.java
src/main/java/com/blackducksoftware/integration/hub/alert/scheduling/controller/GlobalSchedulingConfigActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/scheduling/controller/GlobalSchedulingConfigController.java
src/main/java/com/blackducksoftware/integration/hub/alert/scheduling/controller/GlobalSchedulingConfigRestModel.java
src/main/java/com/blackducksoftware/integration/hub/alert/scheduling/controller/GlobalSchedulingHandler.java
src/main/java/com/blackducksoftware/integration/hub/alert/scheduling/repository/global/GlobalSchedulingConfigEntity.java
src/main/js/component/server/SchedulingConfiguration.js
src/test/java/com/blackducksoftware/integration/hub/alert/TestGlobalProperties.java
src/test/java/com/blackducksoftware/integration/hub/alert/channel/email/EmailChannelTestIT.java
src/test/java/com/blackducksoftware/integration/hub/alert/hub/controller/GlobalHubConfigActionsTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/scheduling/controller/GlobalSchedulingConfigActionsTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/scheduling/controller/GlobalSchedulingConfigControllerTestIT.java
src/test/java/com/blackducksoftware/integration/hub/alert/scheduling/controller/GlobalSchedulingConfigRestModelTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/scheduling/controller/GlobalSchedulingHandlerTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/scheduling/controller/MockGlobalSchedulingRestModel.java
src/test/java/com/blackducksoftware/integration/hub/alert/scheduling/mock/MockGlobalSchedulingEntity.java
src/test/java/com/blackducksoftware/integration/hub/alert/scheduling/repository/GlobalSchedulingConfigEntityTest.java

- The Accumulator is no longer configurable
- The daily digest and purge configurations are now extremely limited
- Now showing the seconds till next run for the accumulator
- Added a run now button for the accumulator
- The daily digest and purge now show their next run time as a Date and time in UTC

Jr scheduling updates

---

src/main/java/com/blackducksoftware/integration/hub/alert/channel/ChannelRestFactory.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/email/controller/global/GlobalEmailConfigActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/hipchat/controller/global/GlobalHipChatConfigActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/datasource/AbstractRepositoryWrapper.java
src/main/java/com/blackducksoftware/integration/hub/alert/scheduling/controller/GlobalSchedulingConfigController.java
src/test/java/com/blackducksoftware/integration/hub/alert/TestGlobalProperties.java
src/test/java/com/blackducksoftware/integration/hub/alert/accumulator/AccumulatorProcessorTestIT.java
src/test/java/com/blackducksoftware/integration/hub/alert/channel/ChannelFreemarkerTemplatingServiceTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/channel/ChannelRestConnectionFactoryTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/channel/ChannelRestFactoryTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/channel/ChannelTemplateManagerTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/channel/SupportedChannelsTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/channel/email/EmailChannelManagerTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/channel/email/EmailChannelTestIT.java
src/test/java/com/blackducksoftware/integration/hub/alert/channel/email/mock/MockEmailEntity.java
src/test/java/com/blackducksoftware/integration/hub/alert/channel/hipchat/HipChatManagerTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/channel/manager/ChannelManagerTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/channel/slack/SlackChannelManagerTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/scheduling/controller/GlobalSchedulingConfigActionsTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/web/actions/global/GlobalActionsTest.java

This PR will require a hub instance with an IntegrationTest group to properly test the email channel.

Added new tests

---

src/main/java/com/blackducksoftware/integration/hub/alert/channel/DistributionChannel.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/hipchat/HipChatChannel.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/hipchat/controller/global/GlobalHipChatConfigActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/hipchat/controller/global/GlobalHipChatConfigController.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/manager/DistributionChannelManager.java
src/main/java/com/blackducksoftware/integration/hub/alert/channel/rest/ChannelRequestHelper.java
src/test/java/com/blackducksoftware/integration/hub/alert/channel/DistributionChannelTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/channel/hipchat/HipChatChannelTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/channel/hipchat/controller/global/GlobalHipChatConfigActionsTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/channel/hipchat/controller/global/GlobalHipChatConfigControllerTestIT.java
src/test/java/com/blackducksoftware/integration/hub/alert/datasource/purge/PurgeJobIT.java
src/test/java/com/blackducksoftware/integration/hub/alert/web/controller/GlobalControllerTest.java

These are the back-end changes for testing the HipChat global config.

Hipchat api key test

---

build.gradle

Uses configuration properties from local environment for sonarqube server.

Add sonarqube analysis implementation in Gradle build.  

---

src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/LoginController.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/handler/LoginHandler.java
src/main/js/LoginPage.js
src/main/js/component/Header.js
src/test/java/com/blackducksoftware/integration/hub/alert/web/controller/LoginControllerTestIT.java
src/test/java/com/blackducksoftware/integration/hub/alert/web/controller/handler/LoginHandlerTest.java

Logout Fix

---

src/main/java/com/blackducksoftware/integration/hub/alert/audit/controller/AuditEntryController.java
src/main/java/com/blackducksoftware/integration/hub/alert/hub/controller/HubDataController.java
src/main/java/com/blackducksoftware/integration/hub/alert/hub/controller/global/GlobalHubConfigController.java
src/main/java/com/blackducksoftware/integration/hub/alert/scheduling/controller/GlobalSchedulingConfigController.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/AuthenticationHandler.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/SSLAuthenticationHandler.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/ConfigController.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/HomeController.java

Fixed an issue where all requests for the global configuration were permitted.  Remove the need for the preauthorize annotation and setup the security context in the AuthenticationHandler class.

Web permissions fix

---

src/main/js/component/general/SchedulingConfiguration.js

Fixed field name to output the next purge date and some general code

---

src/main/js/component/general/distribution/Index.js
src/main/js/component/general/distribution/JobAddModal.js
src/main/js/component/general/distribution/job/BaseJobConfiguration.js
src/main/js/component/general/distribution/job/GroupEmailJobConfiguration.js
src/main/js/component/general/distribution/job/HipChatJobConfiguration.js
src/main/js/component/general/distribution/job/SlackJobConfiguration.js

Using setTimeout will prevent requests from stacking up.

Switched to setTimeout instead of setInterval and removed unnecessary

---

build.gradle
src/main/java/com/blackducksoftware/integration/hub/alert/digest/DailyItemReader.java

Upgrade the dependencies to the latest in the 1.5 release of spring.
Upgrade to the latest hub-common.
Consolidate the gradle tasks so that runServer defines the debugging and
JMX profiling parameters in one task.

Upgrade dependencies and consolidate debug and profiling parameters

---

src/main/java/com/blackducksoftware/integration/hub/alert/hub/controller/HubDataActions.java
src/main/java/com/blackducksoftware/integration/hub/alert/hub/model/HubProject.java
src/main/js/component/general/distribution/ProjectConfiguration.js
src/main/js/store/actions/projects.js

Display the description field in the project selection field.

Add the project description to the models

---

src/main/java/com/blackducksoftware/integration/hub/alert/PhoneHome.java
src/main/java/com/blackducksoftware/integration/hub/alert/web/controller/BaseController.java
src/main/js/MainPage.js
src/main/js/Navigation.js
src/main/js/component/general/audit/Index.js
src/main/js/component/general/distribution/Index.js
src/main/js/component/general/distribution/job/GroupEmailJobConfiguration.js
src/main/js/component/general/distribution/job/HipChatJobConfiguration.js
src/main/js/component/general/distribution/job/SlackJobConfiguration.js
src/main/js/store/actions/about.js
src/main/js/store/actions/audit.js
src/main/js/store/actions/config.js
src/main/js/store/actions/emailConfig.js
src/main/js/store/actions/hipChatConfig.js
src/main/js/store/actions/projects.js
src/main/js/store/actions/schedulingConfig.js
src/main/js/store/actions/session.js
src/main/resources/application.properties
src/main/resources/ssl.application.properties
src/test/java/com/blackducksoftware/integration/hub/alert/web/controller/GlobalControllerTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/web/controller/HomeControllerTestIT.java
webpack.config.js
webpack.dev.config.js

*
* Change the base path for the application to /alert
* Change the tomcat server context to /alert 
* Change the UI to use /alert in the paths
*

Change the root path to be /alert for the application

---

src/main/css/table.scss
src/main/js/component/general/audit/Details.js
src/main/js/field/input/TextArea.js

*
* Fix the layout of the stack trace for the errors in the audit table
* Fix the layout issues in the UI for the stack trace portion of an audit error message.
*
*

Fix the stack trace container to be displayed under the error message

---

src/main/java/com/blackducksoftware/integration/hub/alert/accumulator/AccumulatorReader.java
src/main/java/com/blackducksoftware/integration/hub/alert/startup/AlertStartupInitializer.java

*
*Fixed bug with accumulator lastrun
*Recreated file if it's deleted
* if file doesn't exist, check the last minute for notficiation's
*

Fixed issue with removing accumulator last run

---

src/main/java/com/blackducksoftware/integration/hub/alert/accumulator/RealTimeListener.java
src/main/java/com/blackducksoftware/integration/hub/alert/digest/DigestNotificationProcessor.java
src/main/java/com/blackducksoftware/integration/hub/alert/digest/filter/NotificationEventManager.java
src/main/java/com/blackducksoftware/integration/hub/alert/digest/filter/NotificationPostProcessor.java
src/main/java/com/blackducksoftware/integration/hub/alert/digest/model/ProjectData.java
src/test/java/com/blackducksoftware/integration/hub/alert/accumulator/RealTimeListenerTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/digest/filter/NotificationEventManagerTest.java
src/test/java/com/blackducksoftware/integration/hub/alert/digest/filter/NotificationPostProcessorTestIT.java

Empty notification fix

---

src/main/js/AboutInfo.js
src/main/js/LoginPage.js
src/main/js/component/channels/EmailConfiguration.js
src/main/js/component/channels/HipChatConfiguration.js
src/main/js/component/common/ConfigButtons.js
src/main/js/component/common/EditTableCellFormatter.js
src/main/js/component/common/LogoutConfirmation.js
src/main/js/component/common/RefreshTableCellFormatter.js
src/main/js/component/general/SchedulingConfiguration.js
src/main/js/component/general/distribution/JobAddModal.js
src/main/js/component/general/distribution/ProjectConfiguration.js
src/main/js/component/general/distribution/job/BaseJobConfiguration.js
src/main/js/component/general/distribution/job/GroupEmailJobConfiguration.js
src/main/js/component/general/distribution/job/HipChatJobConfiguration.js
src/main/js/component/general/distribution/job/SlackJobConfiguration.js
src/main/js/component/providers/HubConfiguration.js
src/main/js/field/input/CancelButton.js
src/main/js/field/input/CheckboxInput.js
src/main/js/field/input/GeneralButton.js
src/main/js/field/input/NumberInput.js
src/main/js/field/input/PasswordInput.js
src/main/js/field/input/SubmitButton.js
src/main/js/field/input/TextArea.js
src/main/js/field/input/TextInput.js

*Added ID's for easier webdriver testing

Added id's to everything clickable

---

src/main/java/com/blackducksoftware/integration/alert/channel/slack/SlackDescriptor.java
src/main/java/com/blackducksoftware/integration/alert/processor/vulnerability/VulnerabilityNotificationTypeProcessor.java
src/main/java/com/blackducksoftware/integration/alert/scheduling/controller/GlobalSchedulingConfigActions.java
src/test/java/com/blackducksoftware/integration/alert/scheduling/controller/GlobalSchedulingConfigActionsTest.java

fix more sonar cloud fixes

---

src/main/java/com/blackducksoftware/integration/alert/database/entity/EntityPropertyMapper.java
src/main/java/com/blackducksoftware/integration/alert/workflow/processor/policy/PolicyNotificationTypeProcessor.java

*
* Fix the remaining items after all the merges
*
*
*

Fix the remaining items that weren't addressed after all the merges

---

src/main/java/com/blackducksoftware/integration/alert/workflow/processor/policy/PolicyNotificationTypeProcessor.java

*
* Add a check for an optional
*
*
*

add a check for optional

---

src/main/java/com/blackducksoftware/integration/alert/database/entity/NotificationContent.java
src/main/java/com/blackducksoftware/integration/alert/database/entity/repository/NotificationContentRepository.java
src/main/resources/db/changelog-master.xml
src/main/resources/db/changelog/alert/changelog-3.0.0.xml
src/test/java/com/blackducksoftware/integration/alert/database/entity/repository/NotificationContentRepositoryIT.java

*
* Create the new notification to contain the raw notification data
*
*
*

create the raw_notification_content table, entity, and repository

---

src/main/java/com/synopsys/integration/alert/common/workflow/processor/DefaultTopicFormatter.java
src/main/java/com/synopsys/integration/alert/common/workflow/processor/DigestTopicFormatter.java
src/main/java/com/synopsys/integration/alert/common/workflow/processor/TopicCollector.java
src/main/java/com/synopsys/integration/alert/common/workflow/processor/TopicFormatter.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyTopicCollector.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckTopicCollector.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckVulnerabilityTopicCollector.java
src/main/java/com/synopsys/integration/alert/workflow/processor/collapse/TopicCompressor.java
src/test/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyTopicCollectorTest.java
src/test/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckVulnerabilityTopicCollectorTest.java
src/test/resources/json/vulnerabilityTest.json

*
*
* Changes to process the category items based on the format for collection.
* Applies the digest collapsing in the TopicCollector base class.  Collect is no longer abstract.
*

Topic collector processing

---

src/main/java/com/synopsys/integration/alert/channel/ChannelTemplateManager.java
src/main/java/com/synopsys/integration/alert/channel/email/EmailChannelEvent.java
src/main/java/com/synopsys/integration/alert/channel/email/EmailGroupChannel.java
src/main/java/com/synopsys/integration/alert/channel/event/ChannelEvent.java
src/main/java/com/synopsys/integration/alert/channel/event/ChannelEventFactory.java
src/main/java/com/synopsys/integration/alert/channel/hipchat/HipChatChannel.java
src/main/java/com/synopsys/integration/alert/channel/hipchat/HipChatChannelEvent.java
src/main/java/com/synopsys/integration/alert/channel/slack/SlackChannel.java
src/main/java/com/synopsys/integration/alert/channel/slack/SlackChannelEvent.java
src/main/java/com/synopsys/integration/alert/common/event/ContentEvent.java
src/main/java/com/synopsys/integration/alert/common/model/CategoryItem.java
src/main/java/com/synopsys/integration/alert/common/workflow/processor/MessageContentCollector.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyMessageContentCollector.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckVulnerabilityMessageContentCollector.java
src/main/java/com/synopsys/integration/alert/workflow/processor/MessageContentAggregator.java
src/main/js/component/general/audit/Details.js
src/main/js/field/input/TextArea.js
src/test/java/com/synopsys/integration/alert/channel/ChannelTemplateManagerTest.java
src/test/java/com/synopsys/integration/alert/channel/DistributionChannelTest.java
src/test/java/com/synopsys/integration/alert/channel/email/EmailChannelTestIT.java
src/test/java/com/synopsys/integration/alert/channel/hipchat/HipChatChannelTest.java
src/test/java/com/synopsys/integration/alert/channel/rest/RestDistributionChannelTest.java
src/test/java/com/synopsys/integration/alert/channel/slack/SlackChannelTestIT.java
src/test/java/com/synopsys/integration/alert/common/event/ChannelEventFactoryTest.java
src/test/java/com/synopsys/integration/alert/common/event/ContentEventTest.java
src/test/java/com/synopsys/integration/alert/common/model/CategoryItemTest.java
src/test/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckVulnerabilityMessageContentCollectorTest.java
src/test/java/com/synopsys/integration/alert/workflow/scheduled/frequency/ProcessingTaskTest.java

*
* Fix the audit entry mappings to notifications
* Events now contain the AggregateMessageContent object
* Fix the unit tests for this change above
* Fix some concurrency issues and UI display issues
*

Audit entry refactor

---

src/main/java/com/synopsys/integration/alert/common/workflow/processor/MessageContentCollector.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/BlackDuckProviderContentTypes.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyMessageContentCollector.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckVulnerabilityMessageContentCollector.java
src/main/java/com/synopsys/integration/alert/workflow/filter/NotificationFilter.java
src/test/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyMessageContentCollectorTest.java
src/test/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckVulnerabilityMessageContentCollectorTest.java

* Add the policy overrider name to the collection of items
* Add the severity of the vulnerability to the collection of items
*
*
*

Category item add content

---

src/main/java/com/synopsys/integration/alert/channel/ChannelTemplateManager.java
src/main/java/com/synopsys/integration/alert/channel/DistributionChannel.java
src/main/java/com/synopsys/integration/alert/channel/email/EmailChannelEvent.java
src/main/java/com/synopsys/integration/alert/channel/event/ChannelEventProducer.java
src/main/java/com/synopsys/integration/alert/channel/event/DistributionEvent.java
src/main/java/com/synopsys/integration/alert/channel/event/NotificationToChannelEventConverter.java
src/main/java/com/synopsys/integration/alert/channel/hipchat/HipChatChannelEvent.java
src/main/java/com/synopsys/integration/alert/channel/rest/RestDistributionChannel.java
src/main/java/com/synopsys/integration/alert/channel/slack/SlackChannelEvent.java
src/main/java/com/synopsys/integration/alert/web/audit/AuditEntryActions.java
src/main/java/com/synopsys/integration/alert/workflow/processor/NotificationProcessor.java
src/main/java/com/synopsys/integration/alert/workflow/scheduled/frequency/ProcessingTask.java
src/test/java/com/synopsys/integration/alert/channel/rest/RestDistributionChannelTest.java
src/test/java/com/synopsys/integration/alert/workflow/filter/NotificationToChannelEventConverterTest.java
src/test/java/com/synopsys/integration/alert/workflow/scheduled/frequency/ProcessingTaskTest.java

Rename ChannelEvent to DistributionEvent

rename ChannelEvent to DistributionEvent

---

src/main/java/com/synopsys/integration/alert/database/security/StringEncryptionConverter.java
src/main/java/com/synopsys/integration/alert/workflow/startup/AlertStartupInitializer.java
src/main/java/com/synopsys/integration/alert/workflow/startup/StartupManager.java
src/test/java/com/synopsys/integration/alert/workflow/startup/StartupManagerTest.java

* Initializes the StringEncryptionConverter with the EncryptionUtility

Fix the initialization of the StringEncryptionConverter

---

src/main/java/com/synopsys/integration/alert/channel/email/descriptor/EmailGlobalStartupComponent.java
src/main/java/com/synopsys/integration/alert/channel/hipchat/descriptor/HipChatStartupComponent.java
src/main/java/com/synopsys/integration/alert/common/descriptor/config/StartupComponent.java
src/main/java/com/synopsys/integration/alert/component/scheduling/SchedulingStartupComponent.java
src/main/java/com/synopsys/integration/alert/database/entity/EntityPropertyMapper.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckProviderStartupComponent.java
src/main/java/com/synopsys/integration/alert/workflow/PropertyInitializer.java
src/main/java/com/synopsys/integration/alert/workflow/startup/AlertStartupInitializer.java
src/main/java/com/synopsys/integration/alert/workflow/startup/AlertStartupProperty.java
src/test/java/com/synopsys/integration/alert/workflow/startup/AlertStartupPropertyTest.java

* Allow startup properties to be overridden within the startup component

Allow startup properties to have an override that is programatic

---

src/main/java/com/synopsys/integration/alert/common/security/EncryptionUtility.java
src/main/java/com/synopsys/integration/alert/workflow/startup/install/SystemInitializer.java
src/main/js/SetupPage.js
src/main/js/store/reducers/system.js

Fix the refresh of the setup page

---

src/main/java/com/synopsys/integration/alert/channel/email/EmailGroupChannel.java
src/main/java/com/synopsys/integration/alert/channel/email/descriptor/EmailGlobalDescriptorActionApi.java
src/main/java/com/synopsys/integration/alert/channel/hipchat/HipChatChannel.java
src/main/java/com/synopsys/integration/alert/channel/hipchat/descriptor/HipChatGlobalDescriptorActionApi.java

Just moved the code to where it should be

Moving the channel global test code to where I think it should be

---

src/main/java/com/synopsys/integration/alert/channel/email/EmailAddressHandler.java
src/main/java/com/synopsys/integration/alert/channel/event/NotificationToDistributionEventConverter.java
src/main/java/com/synopsys/integration/alert/common/descriptor/DescriptorMap.java
src/main/java/com/synopsys/integration/alert/common/descriptor/config/context/ChannelDistributionDescriptorActionApi.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/tasks/BlackDuckAccumulator.java
src/main/java/com/synopsys/integration/alert/web/config/ConfigActions.java
src/main/java/com/synopsys/integration/alert/web/controller/UIComponentController.java
src/main/java/com/synopsys/integration/alert/workflow/startup/AlertStartupInitializer.java
src/main/java/com/synopsys/integration/alert/workflow/startup/SystemValidator.java
src/test/java/com/synopsys/integration/alert/channel/email/EmailChannelTestIT.java
src/test/java/com/synopsys/integration/alert/channel/email/EmailGlobalDescriptorActionApiTest.java
src/test/java/com/synopsys/integration/alert/common/descriptor/DescriptorMapTest.java
src/test/java/com/synopsys/integration/alert/web/controller/DescriptorControllerTest.java

*
* Made DescriptorMap getters optional
* Removed some TODOs
* Return optional when getting descriptor from descriptor map

Added optional to descriptormap

---

src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/CheckboxConfigField.java
src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/ConfigField.java
src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/ConfigValidationFunction.java
src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/NumberConfigField.java
src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/PasswordConfigField.java
src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/ReadOnlyConfigField.java
src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/SelectConfigField.java
src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/TextInputConfigField.java

This is an alternative to using the repeated mix of generics.

creating a token interface to wrap generics

---

src/main/java/com/synopsys/integration/alert/channel/email/descriptor/EmailGlobalDescriptorActionApi.java
src/main/java/com/synopsys/integration/alert/channel/hipchat/descriptor/HipChatGlobalDescriptorActionApi.java
src/main/java/com/synopsys/integration/alert/common/ConfigurationFieldModelConverter.java
src/main/java/com/synopsys/integration/alert/common/descriptor/config/context/ChannelDistributionDescriptorActionApi.java
src/main/java/com/synopsys/integration/alert/common/descriptor/config/context/DescriptorActionApi.java
src/main/java/com/synopsys/integration/alert/common/descriptor/config/context/ProviderDistributionDescriptorActionApi.java
src/main/java/com/synopsys/integration/alert/component/scheduling/SchedulingDescriptorActionApi.java
src/main/java/com/synopsys/integration/alert/component/settings/SettingsDescriptorActionApi.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckProviderDescriptorActionApi.java
src/main/java/com/synopsys/integration/alert/provider/polaris/descriptor/PolarisDistributionDescriptorActionApi.java
src/main/java/com/synopsys/integration/alert/provider/polaris/descriptor/PolarisGlobalDescriptorActionApi.java
src/main/java/com/synopsys/integration/alert/web/config/ConfigActions.java
src/main/java/com/synopsys/integration/alert/web/config/ConfigControllerHandler.java
src/main/java/com/synopsys/integration/alert/web/model/configuration/FieldModel.java
src/test/java/com/synopsys/integration/alert/channel/ChannelDescriptorTest.java
src/test/java/com/synopsys/integration/alert/channel/email/EmailGlobalDescriptorActionApiTest.java
src/test/java/com/synopsys/integration/alert/channel/hipchat/HipChatGlobalDescriptorActionApiTest.java
src/test/java/com/synopsys/integration/alert/common/ConfigurationFieldModelTest.java
src/test/java/com/synopsys/integration/alert/component/scheduling/SchedulingDescriptorActionApiTest.java
src/test/java/com/synopsys/integration/alert/component/settings/SettingsDescriptorActionApiTest.java
src/test/java/com/synopsys/integration/alert/mock/MockDescriptorAccessor.java
src/test/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckDistributionDescriptorActionApiTest.java
src/test/java/com/synopsys/integration/alert/provider/polaris/descriptor/PolarisGlobalDescriptorActionApiTest.java
src/test/java/com/synopsys/integration/alert/workflow/startup/AlertStartupInitializerTest.java

* Implement changes from pull request in the branch to merge into

Ps test require field accessor

---

src/main/js/MainPage.js
src/main/js/Navigation.js
src/main/js/component/AboutInfo.js
src/main/js/component/audit/Details.js
src/main/js/component/audit/Index.js
src/main/js/component/settings/SettingsConfigurationForm.js
src/main/js/distribution/Index.js
src/main/js/distribution/JobAddModal.js
src/main/js/distribution/job/BaseJobConfiguration.js
src/main/js/store/actions/descriptors.js
src/main/js/store/reducers/descriptors.js
src/main/js/util/descriptorUtilities.js

* Make the UI read descriptors and render the menu correctly

Ps ui menu

---

src/main/java/com/synopsys/integration/alert/web/config/ConfigController.java
src/main/java/com/synopsys/integration/alert/web/controller/AboutController.java
src/main/java/com/synopsys/integration/alert/web/controller/LoginController.java
src/main/java/com/synopsys/integration/alert/web/controller/ResponseFactory.java
src/main/java/com/synopsys/integration/alert/web/controller/SystemController.java
src/main/java/com/synopsys/integration/alert/web/provider/blackduck/BlackDuckDataController.java
src/test/java/com/synopsys/integration/alert/provider/blackduck/controller/BlackDuckDataControllerTest.java
src/test/java/com/synopsys/integration/alert/web/controller/AboutControllerTest.java

* Fix the response entities returned be the response factory class.

Fix the response factory and controllers to return original data

---

src/main/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckDescriptor.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckProviderUIConfig.java
src/main/js/App.js
src/main/js/MainPage.js
src/main/js/channels/EmailConfiguration.js
src/main/js/providers/BlackDuckConfiguration.js
src/main/js/store/actions/blackduck.js
src/main/js/store/reducers/blackduck.js
src/main/js/store/reducers/index.js
src/test/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckDescriptorTest.java

* Implement the changes to read and save the Blackduck Provider configuration
*
*

Ps blackduck provider config

---

src/main/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckProviderDescriptorActionApi.java
src/main/java/com/synopsys/integration/alert/web/config/ConfigActions.java
src/main/java/com/synopsys/integration/alert/web/model/configuration/FieldModel.java

* Make the warning message for the BlackDuck URL clear when the configuration is saved.

Ps blackduck system message fix

---

src/main/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckProviderDescriptorActionApi.java
src/main/java/com/synopsys/integration/alert/web/actions/SystemActions.java
src/main/java/com/synopsys/integration/alert/web/controller/SystemController.java
src/main/js/channels/EmailConfiguration.js
src/main/js/channels/HipChatConfiguration.js
src/main/js/component/settings/SettingsConfigurationForm.js
src/main/js/providers/BlackDuckConfiguration.js
src/main/js/store/actions/distributions.js
src/main/js/store/actions/system.js
src/test/java/com/synopsys/integration/alert/web/actions/SystemActionsTest.java
src/test/java/com/synopsys/integration/alert/web/controller/SystemControllerTestIT.java

* Fix the UI code to pull the errors from the response body correctly

Fix the UI to use the JSON keys from a validation response

---

src/main/java/com/synopsys/integration/alert/channel/hipchat/descriptor/HipChatDistributionUIConfig.java
src/main/java/com/synopsys/integration/alert/component/settings/SettingsUIConfig.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckDistributionUIConfig.java

Small PR for changes requested on an already merged branch.

Made small changes from an old PR

---

src/main/java/com/synopsys/integration/alert/component/settings/SettingsDescriptor.java
src/main/java/com/synopsys/integration/alert/component/settings/SettingsUIConfig.java

*
* Added missing validation for LDAP properties
* Added validation for Username and Password. Must put both values.
* Changed a field from text to number input

Added validation for username and passwords

---

package-lock.json
package.json
src/main/js/distribution/JobAddModal.js
src/main/js/distribution/job/BaseJobConfiguration.js
src/main/js/store/actions/distributionConfigs.js

* Fix the tab focus of the elements in the job add modal

Ps fix tab focus

---

src/main/js/MainPage.js

* . Fix the redirect route to be the first provider since the providers are alphabetical

Fix the redirect route to be the first provider

---

src/main/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckProviderUIConfig.java
src/main/java/com/synopsys/integration/alert/web/config/ConfigActions.java
src/main/java/com/synopsys/integration/alert/web/config/FieldModelProcessor.java
src/main/java/com/synopsys/integration/alert/web/config/JobConfigActions.java
src/main/java/com/synopsys/integration/alert/web/model/configuration/FieldModel.java

Fixed potential issue with sensitive fields when testing

Started fix for broken sensitive tests

---

src/main/java/com/synopsys/integration/alert/component/scheduling/SchedulingUIConfig.java
src/test/java/com/synopsys/integration/alert/component/scheduling/SchedulingDescriptorActionApiTest.java

Scheduling validation wasn't using the new select validation properly

Fixed scheduling validation

---

src/main/java/com/synopsys/integration/alert/component/settings/SettingsDescriptor.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/BlackDuckProvider.java
src/main/java/com/synopsys/integration/alert/web/config/ConfigActions.java
src/main/java/com/synopsys/integration/alert/web/config/FieldModelProcessor.java
src/main/java/com/synopsys/integration/alert/web/config/JobConfigActions.java
src/main/java/com/synopsys/integration/alert/workflow/startup/SystemValidator.java
src/test/java/com/synopsys/integration/alert/provider/blackduck/BlackDuckProviderTest.java
src/test/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckDescriptorTest.java
src/test/java/com/synopsys/integration/alert/web/controller/SystemControllerTestIT.java

*
*
* Fix the default settings to display default encryption and password fields.
* Add a check to the system validator for the default user email address

Ps fix default settings page

---

docker-entrypoint.sh

Copy certificates file into alert through docker secrets

update the script to look for truststore files containing certificates

---

src/main/resources/db/changelog/alert/4.0.0/changelog-configuration-global-migration.xml
src/main/resources/db/changelog/alert/4.0.0/changelog-configuration-stored-procedures.xml

Create a stored procedure to set the default for the environment variable override to true

Environment override default

---

alert-common/src/main/java/com/synopsys/integration/alert/common/AlertConstants.java
alert-common/src/main/java/com/synopsys/integration/alert/common/workflow/task/ScheduledTask.java
src/main/java/com/synopsys/integration/alert/Application.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/tasks/BlackDuckAccumulator.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/tasks/BlackDuckProjectSyncTask.java
src/main/java/com/synopsys/integration/alert/provider/polaris/tasks/PolarisProjectSyncTask.java
src/main/java/com/synopsys/integration/alert/workflow/scheduled/PhoneHomeTask.java
src/main/java/com/synopsys/integration/alert/workflow/scheduled/PurgeTask.java
src/main/java/com/synopsys/integration/alert/workflow/scheduled/frequency/ProcessingTask.java
src/test/java/com/synopsys/integration/alert/workflow/scheduled/ScheduledTaskTest.java

Noticed our tasks weren't running asynchronously causing things to get backed up. Now all tasks are async.

Made our tasks async

---

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/action/DescriptorActionApi.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/ConfigField.java

Similar to the related fields functionality, you can now set fields that are not allowed if other fields are selected.

Added a validation check for disallowed related fields

---

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/action/ChannelDistributionDescriptorActionApi.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/action/DescriptorActionApi.java
alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/ConfigurationFieldModel.java
alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/util/ConfigurationFieldModelConverter.java
alert-common/src/main/java/com/synopsys/integration/alert/common/rest/model/FieldModel.java
alert-common/src/test/java/com/synopsys/integration/alert/common/ConfigurationFieldModelTest.java
src/main/java/com/synopsys/integration/alert/component/settings/SettingsDescriptorActionApi.java
src/main/java/com/synopsys/integration/alert/component/settings/SettingsUIConfig.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckDistributionUIConfig.java
src/main/java/com/synopsys/integration/alert/web/config/ConfigActions.java
src/main/java/com/synopsys/integration/alert/web/config/FieldModelProcessor.java
src/main/java/com/synopsys/integration/alert/web/config/JobConfigActions.java
src/main/java/com/synopsys/integration/alert/workflow/startup/AlertStartupInitializer.java
src/test/java/com/synopsys/integration/alert/channel/ChannelDescriptorTest.java
src/test/java/com/synopsys/integration/alert/component/settings/SettingsDescriptorActionApiTest.java
src/test/java/com/synopsys/integration/alert/provider/polaris/descriptor/PolarisGlobalDescriptorActionApiTest.java
src/test/java/com/synopsys/integration/alert/web/actions/SystemActionsTest.java
src/test/java/com/synopsys/integration/alert/web/config/ConfigActionTestIT.java

Changed some names and made sure that we delete empty models from the DB the proper way.

Removed isSet functionality from DB objects

---

src/main/java/com/synopsys/integration/alert/database/provider/blackduck/data/BlackDuckProjectRepositoryAccessor.java

We weren't trimming description for projects when we called the save all repository method. I've added this change to the save all method.

Trim project description when saving when length is over 255 chars

---

src/main/js/MainPage.js
src/main/js/dynamic/GlobalConfiguration.js
src/main/js/field/FieldsPanel.js
src/main/js/util/fieldMapping.js
src/main/js/util/fieldModelUtilities.js

Added collapsable panels and header to the auto generated UI. Also fixed an issue with checkboxes not working.
The test modals have not been implemented. Should be the last step for auto-generated global pages.

Bm global auto ui

---

build.gradle
src/main/java/com/synopsys/integration/alert/component/settings/SettingsDescriptorActionApi.java
src/main/java/com/synopsys/integration/alert/web/security/AuthenticationHandler.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/AlertFilterChainProxy.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/AlertSAMLEntryPoint.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/AlertSAMLMetadataGenerator.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/AlertSAMLMetadataGeneratorFilter.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/AlertWebSSOProfileOptions.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/SAMLAuthProvider.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/SAMLContext.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/SAMLManager.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/SamlAntMatcher.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/UserDetailsService.java
src/main/java/com/synopsys/integration/alert/workflow/startup/StartupManager.java
src/main/js/component/settings/SettingsConfigurationForm.js
src/test/java/com/synopsys/integration/alert/component/settings/SettingsDescriptorActionApiTest.java
src/test/java/com/synopsys/integration/alert/workflow/startup/StartupManagerTest.java

Disable saml

---

alert-common/src/main/java/com/synopsys/integration/alert/common/channel/DistributionChannel.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/ChannelDescriptor.java
alert-common/src/main/java/com/synopsys/integration/alert/common/workflow/MessageReceiver.java
src/main/java/com/synopsys/integration/alert/channel/ChannelListener.java
src/main/java/com/synopsys/integration/alert/channel/email/descriptor/EmailDescriptor.java
src/main/java/com/synopsys/integration/alert/channel/hipchat/descriptor/HipChatDescriptor.java
src/main/java/com/synopsys/integration/alert/channel/slack/descriptor/SlackDescriptor.java
src/test/java/com/synopsys/integration/alert/channel/rest/RestDistributionChannelTest.java
src/test/java/com/synopsys/integration/alert/workflow/startup/AlertStartupInitializerTest.java

Instead of looping through descriptors to register our channels, I now just loop through the channels. The channels are gone from all descriptors.

Decoupling channels from descriptors

---

src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/SAMLContext.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/UserDetailsService.java
src/test/java/com/synopsys/integration/alert/web/security/authentication/saml/SamlManagerTest.java
src/test/java/com/synopsys/integration/alert/web/security/authentication/saml/UserDetailsServiceTest.java

Add tests to classes that we implement where we can test functionality for saml.  The tests found an issue with the roles in the UserDetailsService.  The changes include a fix for getting the roles.

Saml unit testing

---

src/main/css/audit.scss
src/main/js/component/audit/Index.js
src/main/js/component/common/NotificationTypeLegend.js

Add the fix for the license limit icon to the corrected 4.1.0 branch

JS: Adding icon for license limit

---

src/main/java/com/synopsys/integration/alert/channel/jira/JiraChannel.java
src/main/java/com/synopsys/integration/alert/channel/jira/actions/JiraConfigurationAction.java
src/main/java/com/synopsys/integration/alert/channel/jira/actions/JiraGlobalTestAction.java
src/main/java/com/synopsys/integration/alert/channel/jira/descriptor/JiraDescriptor.java
src/main/java/com/synopsys/integration/alert/channel/jira/descriptor/JiraDistributionUIConfig.java
src/main/java/com/synopsys/integration/alert/channel/jira/descriptor/JiraGlobalUIConfig.java
src/main/resources/db/changelog-master.xml
src/main/resources/db/changelog/alert/5.0.0/changelog-authentication.xml
src/main/resources/db/changelog/alert/5.0.0/changelog-configuration-initialization.xml
src/main/resources/db/changelog/alert/5.0.0/changelog.xml

Implementation of the Jira Channel skeleton.

Ps jira channel

---

src/main/java/com/synopsys/integration/alert/channel/jira/JiraChannel.java
src/main/java/com/synopsys/integration/alert/channel/jira/descriptor/JiraDescriptor.java
src/main/java/com/synopsys/integration/alert/channel/jira/descriptor/JiraDistributionUIConfig.java
src/main/resources/db/changelog/alert/5.0.0/changelog-authentication.xml
src/main/resources/db/changelog/alert/5.0.0/changelog-configuration-initialization.xml

Add the distribution fields for the Jira Channel. 
Fix some permission issues.

Ps jira distribution fields

---

build.gradle
src/main/java/com/synopsys/integration/alert/channel/jira/actions/JiraGlobalTestAction.java
src/main/java/com/synopsys/integration/alert/channel/jira/descriptor/JiraGlobalUIConfig.java

Added local dependency for jira common and implemented the Jira Cloud global test functionality.
This won't be merged until later so we can update the dependency to the appropriate version.

Added Global jira test functionality

---

src/main/css/table.scss
src/main/js/component/common/EditTableCellFormatter.js
src/main/js/component/common/IconTableCellFormatter.js
src/main/js/distribution/Index.js
src/main/js/dynamic/DistributionConfiguration.js
src/main/js/dynamic/loading/audit/AuditPage.js

Ps copy job

---

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/CountdownConfigField.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/ui/ProviderDistributionUIConfig.java
alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/UserModel.java
src/main/java/com/synopsys/integration/alert/web/config/JobConfigController.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/SAMLManager.java
src/test/java/com/synopsys/integration/alert/database/api/user/UserModelTest.java

Fix(java): Fix the Sonar Cloud issues against alert.

---

alert-common/src/main/java/com/synopsys/integration/alert/common/message/model/ComponentItem.java
alert-common/src/main/java/com/synopsys/integration/alert/common/message/model/ProviderMessageContent.java

First pass at the new models for message content.

Ps message models

---

alert-common/src/main/java/com/synopsys/integration/alert/common/provider/ProviderValidator.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/BlackDuckValidator.java
src/main/java/com/synopsys/integration/alert/workflow/startup/component/SystemValidator.java
src/test/java/com/synopsys/integration/alert/workflow/startup/SystemValidatorTest.java

To add to what is already done in your branch, this additional functionality allows different providers to insert their own validation to the System validator.

Remove BlackDuckVerifier from SystemValidator

---

alert-common/src/main/java/com/synopsys/integration/alert/common/channel/DistributionChannel.java
build.gradle
src/main/java/com/synopsys/integration/alert/channel/ChannelFreemarkerTemplatingService.java
src/main/java/com/synopsys/integration/alert/channel/email/EmailChannel.java
src/main/java/com/synopsys/integration/alert/channel/email/EmailMessagingService.java
src/main/java/com/synopsys/integration/alert/channel/hipchat/HipChatChannel.java
src/main/java/com/synopsys/integration/alert/channel/jira/JiraChannel.java
src/main/java/com/synopsys/integration/alert/channel/jira/descriptor/JiraDistributionUIConfig.java
src/main/java/com/synopsys/integration/alert/channel/slack/SlackChannel.java
src/main/java/com/synopsys/integration/alert/component/settings/PasswordResetService.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckVulnerabilityCollector.java
src/main/java/com/synopsys/integration/alert/workflow/scheduled/update/UpdateEmailService.java
src/test/java/com/synopsys/integration/alert/channel/ChannelFreemarkerTemplatingServiceTest.java
src/test/java/com/synopsys/integration/alert/channel/email/EmailChannelTestIT.java
src/test/java/com/synopsys/integration/alert/channel/email/EmailGlobalTestActionTest.java
src/test/java/com/synopsys/integration/alert/channel/email/EmailMessagingServiceTest.java
src/test/java/com/synopsys/integration/alert/channel/hipchat/HipChatChannelTest.java
src/test/java/com/synopsys/integration/alert/channel/hipchat/HipChatGlobalTestActionTest.java
src/test/java/com/synopsys/integration/alert/channel/slack/SlackChannelTest.java
src/test/java/com/synopsys/integration/alert/component/settings/PasswordResetServiceTest.java

This has MOST of the functionality we wanted for the Jira channel. There are a few cases where we don't have the information we want to and a fixme should be there explaining what we want or need.
There are also Freemarker template service changes here which I originally planned on using but ended up not.

Jira channel

---

alert-common/src/main/java/com/synopsys/integration/alert/common/enumeration/ComponentItemPriority.java
alert-common/src/main/java/com/synopsys/integration/alert/common/message/model/ComponentItem.java
alert-common/src/main/java/com/synopsys/integration/alert/common/message/model/ComponentKey.java
src/test/java/com/synopsys/integration/alert/common/message/model/ComponentItemTest.java
src/test/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyOverrideMessageContentCollectorTest.java

Changes to implement a comparator for ComponentItems to handle sorting the data without need custom component item objects.

Ps component priority

---

src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckVulnerabilityCollector.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckContent.java
src/test/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyOverrideMessageContentCollectorTest.java
src/test/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckVulnerabilityCollectorTest.java
src/test/java/com/synopsys/integration/alert/web/config/GroupConfigControllerTestIT.java

fix tests that were failing on the branch and re-write portions of the test to assert.

Ps fix tests

---

src/main/java/com/synopsys/integration/alert/workflow/scheduled/PhoneHomeTask.java
src/test/java/com/synopsys/integration/alert/PhoneHomeTest.java

BlackDuck is no longer required for phoning home and we now have more accurate data in the metadata.

Updated phone home to be independent of BlackDuck

---

src/main/java/com/synopsys/integration/alert/channel/jira/JiraIssueHandler.java

Added comments that hopefully clarify what we've done to the issue.

Jira update comments

---

Dockerfile
docker-entrypoint.sh

This seems to work well in the docker-compose deployment. I don't really have a way to test the other deployment mechanisms.

Data backup

---

alert-common/src/main/java/com/synopsys/integration/alert/common/AlertProperties.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/BlackDuckProperties.java
src/main/java/com/synopsys/integration/alert/workflow/scheduled/update/UpdateEmailService.java
src/main/java/com/synopsys/integration/alert/workflow/startup/StartupManager.java
src/main/java/com/synopsys/integration/alert/workflow/startup/SystemValidator.java
src/main/resources/email/templates/update_available.ftl
src/test/java/com/synopsys/integration/alert/util/TestAlertProperties.java
src/test/java/com/synopsys/integration/alert/workflow/startup/StartupManagerTest.java
src/test/java/com/synopsys/integration/alert/workflow/startup/SystemValidatorTest.java

Added the Alert server URL to the template.  Needed to create a method in AlertProperties to get the server URL.

Ps update email enhancement

---

src/main/java/com/synopsys/integration/alert/channel/email/EmailChannel.java
src/main/java/com/synopsys/integration/alert/channel/util/FreemarkerTemplatingService.java
src/main/java/com/synopsys/integration/alert/component/settings/PasswordResetService.java
src/main/java/com/synopsys/integration/alert/workflow/scheduled/update/UpdateEmailService.java
src/main/resources/email/templates/message_content.ftl
src/main/resources/email/templates/password_reset.ftl
src/main/resources/email/templates/update_available.ftl

Make the ALERT title text into a link and add the server URL to the footer.

Ps email server url

---

alert-common/src/main/java/com/synopsys/integration/alert/common/action/TestAction.java
alert-common/src/main/java/com/synopsys/integration/alert/common/message/model/AggregateMessageContent.java
alert-common/src/main/java/com/synopsys/integration/alert/common/workflow/MessageContentCollector.java
alert-common/src/main/java/com/synopsys/integration/alert/common/workflow/processor/MessageCombiner.java
alert-common/src/main/java/com/synopsys/integration/alert/common/workflow/processor/MessageOperationCombiner.java
alert-common/src/main/java/com/synopsys/integration/alert/common/workflow/processor/SummaryMessageContentProcessor.java
alert-common/src/test/java/com/synopsys/integration/alert/common/event/EventManagerTest.java
alert-common/src/test/java/com/synopsys/integration/alert/common/workflow/processor/ProcessorTest.java
alert-database/src/test/java/com/synopsys/integration/alert/database/api/AuditEntryAccessorTest.java
src/main/java/com/synopsys/integration/alert/channel/email/actions/EmailGlobalTestAction.java
src/main/java/com/synopsys/integration/alert/workflow/processor/MessageContentAggregator.java
src/test/java/com/synopsys/integration/alert/channel/ChannelTest.java
src/test/java/com/synopsys/integration/alert/channel/email/EmailChannelChannelDescriptorTestIT.java
src/test/java/com/synopsys/integration/alert/channel/email/EmailChannelTestIT.java
src/test/java/com/synopsys/integration/alert/channel/event/ChannelEventManagerTest.java
src/test/java/com/synopsys/integration/alert/channel/hipchat/HipChatChannelDescriptorTestIT.java
src/test/java/com/synopsys/integration/alert/channel/hipchat/HipChatChannelTest.java
src/test/java/com/synopsys/integration/alert/channel/slack/SlackChannelChannelDescriptorTestIT.java
src/test/java/com/synopsys/integration/alert/channel/slack/SlackChannelTest.java
src/test/java/com/synopsys/integration/alert/common/event/ContentEventTest.java
src/test/java/com/synopsys/integration/alert/common/message/model/AggregateMessageContentTest.java
src/test/java/com/synopsys/integration/alert/database/settings/repository/NotificationContentRepositoryIT.java
src/test/java/com/synopsys/integration/alert/workflow/filter/NotificationToDistributionEventConverterTestIT.java

Sort the aggregate message content before formatting by the creation of the notification from the provider.

Ps fix message order

---

alert-common/src/main/java/com/synopsys/integration/alert/common/workflow/processor/MessageCombiner.java
alert-common/src/main/java/com/synopsys/integration/alert/common/workflow/processor/SummaryMessageContentProcessor.java

Refactor the combination of items in the summary processor.  Add the type to the CategoryKey to be consistent with 5.0.0 keys that are created.

Ps fix summary

---

src/main/js/dynamic/loaded/audit/AuditPage.js

Audit page would not render due to an undefined calling a bind function

Fix(audit): Fix the audit page by removing binds to undefined functions.

---

alert-common/src/main/java/com/synopsys/integration/alert/common/message/model/ComponentAttributeMap.java
alert-common/src/main/java/com/synopsys/integration/alert/common/message/model/ComponentItem.java
alert-common/src/main/java/com/synopsys/integration/alert/common/message/model/ProviderMessageContent.java
alert-common/src/main/java/com/synopsys/integration/alert/common/workflow/MessageContentCollector.java
alert-common/src/main/java/com/synopsys/integration/alert/common/workflow/processor/SummaryMessageContentProcessor.java
src/main/java/com/synopsys/integration/alert/workflow/processor/MessageContentAggregator.java

Implement the 4.2.0 fix for summarization into 5.0.0

Ps fix summary format

---

src/main/java/com/synopsys/integration/alert/workflow/startup/AlertStartupInitializer.java

Fix(startup): Update the initializer based on PR feedback.

---

src/test/java/com/synopsys/integration/alert/workflow/startup/AlertStartupInitializerTest.java

Ps fix startup tests

---

alert-common/src/main/java/com/synopsys/integration/alert/common/message/model/ComponentAttributeMap.java
alert-common/src/main/java/com/synopsys/integration/alert/common/message/model/ComponentItem.java
alert-common/src/main/java/com/synopsys/integration/alert/common/workflow/processor/MessageCombiner.java
alert-common/src/main/java/com/synopsys/integration/alert/common/workflow/processor/SummaryMessageContentProcessor.java
alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultAuditUtility.java

Fix the summary to contain totals and remove the remediation information from the results.

Ps fix vulnerability summary

---

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/SelectConfigField.java
src/main/js/field/input/DynamicSelect.js
src/main/js/field/input/SelectInput.js
src/main/js/util/fieldMapping.js

Add the clearable option for the select fields.  
Always create an array for selected values.  Just push the single value when a single value is selected.

Ps single select error

---

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/CheckboxConfigField.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/HideCheckboxConfigField.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/ui/ProviderDistributionUIConfig.java
alert-common/src/main/java/com/synopsys/integration/alert/common/enumeration/FieldType.java
src/main/java/com/synopsys/integration/alert/web/config/FieldValidationAction.java
src/main/js/field/FieldsPanel.js
src/main/js/util/fieldMapping.js
src/main/js/util/fieldModelUtilities.js

New field type that allows us to hide other fields depending on the state of the field.
Nothing uses this at the moment but will once we add the last new field type.

Bm hide related fields

---

src/main/java/com/synopsys/integration/alert/workflow/startup/component/AlertStartupInitializer.java
src/main/js/field/FieldsPanel.js

Log the configuration fields for each descriptor.

Ps startup logging

---

src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckBomEditCollector.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckContent.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/tasks/BlackDuckAccumulator.java
src/test/java/com/synopsys/integration/alert/provider/blackduck/tasks/BlackDuckAccumulatorTest.java

Ps accumulator enhancement

---

src/main/java/com/synopsys/integration/alert/channel/jira/util/JiraIssueFormatHelper.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckBomEditCollector.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckCollector.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyCollector.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyOverrideCollector.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyViolationCollector.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckVulnerabilityCollector.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/util/BlackDuckDataHelper.java
src/test/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckVulnerabilityCollectorTest.java
src/test/java/com/synopsys/integration/alert/workflow/processor/MessageContentAggregatorTest.java

Add remediation information to vulnerability policy violations.  Also hit a size limit of 255 characters for the title.  Fixing the size limits of the summary and description are another issue to be resolved in a different PR.

Ps remediation info

---

src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckBomEditCollector.java

Make Bom edit consistent with the other collectors.

Ps bom component link

---

src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyViolationCollector.java

Add an empty vulnerability item to be able to collapse/resolve policy vulnerability data.

Ps vulnerability fix

---

src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckBomEditCollector.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckCollector.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyCollector.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyOverrideCollector.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckPolicyViolationCollector.java

Create component items for policy data.  We were only creating data for policies components that have vulnerabilities.

Fix(BomEdit): If there's policy data create a component item

---

package-lock.json
src/main/resources/db/changelog/alert/5.1.0/changelog-technical-debt.xml

Fixes the issue with our secure info being shown at startup.

Update DefinedFields with the proper values

---

src/main/java/com/synopsys/integration/alert/web/controller/BaseController.java
src/main/java/com/synopsys/integration/alert/web/provider/ProviderDataController.java
src/test/java/com/synopsys/integration/alert/web/controller/BaseControllerTest.java

Add a convenience method for the base controller if we need to log any of the parameters that are user provided.

Fix(provider): Fix the controller vulnerabilites in SonarCloud.

---

src/main/resources/db/changelog/alert/5.1.0/changelog-technical-debt.xml

I did a basic local test, but if @jamesrichard91 can try to reproduce the error he was seeing, that would be great.

Delete provider projects and users before adding DB constraint

---

src/main/java/com/synopsys/integration/alert/provider/blackduck/new_collector/BlackDuckMessageContentCollector.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/new_collector/BomEditMessageBuilder.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/new_collector/PolicyClearedMessageBuilder.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/new_collector/PolicyClearerMessageBuilder.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/new_collector/PolicyOverrideMessageBuilder.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/new_collector/PolicyViolationMessageBuilder.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/new_collector/VulnerabilityNotificationMessageBuilder.java

Implement policy cleared and policy override.

Ps policy cleared

---

src/main/java/com/synopsys/integration/alert/provider/blackduck/new_collector/BomEditMessageBuilder.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/new_collector/MessageBuilderConstants.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/new_collector/PolicyClearedMessageBuilder.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/new_collector/PolicyOverrideMessageBuilder.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/new_collector/PolicyViolationMessageBuilder.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/new_collector/VulnerabilityNotificationMessageBuilder.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/new_collector/util/BlackDuckResponseCache.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/new_collector/util/PolicyPriorityUtil.java

Implement the Bom Edit notification.

Feature(processor): Initial implementation for BOM edit notifications.

---

alert-common/build.gradle
src/main/java/com/synopsys/integration/alert/workflow/scheduled/PhoneHomeTask.java

Updated to BD 44.2.14 and used the new phone home modules feature instead of metadata

---

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/endpoint/CustomButtonField.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/endpoint/EndpointButtonField.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/endpoint/EndpointField.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/endpoint/EndpointSelectField.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/endpoint/UploadFileButtonField.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/endpoint/table/EndpointTableSelectField.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/ui/ProviderDistributionUIConfig.java
src/main/java/com/synopsys/integration/alert/channel/jira/cloud/descriptor/JiraGlobalUIConfig.java
src/main/js/field/EndpointButtonField.js
src/main/js/field/EndpointSelectField.js
src/main/js/field/input/TableSelectInput.js
src/main/js/util/fieldMapping.js

This isn't a change that is super required. But it does make a lot of the requests smaller.

Added fields to be passed as data to custom endpoint fields

---

src/main/java/com/synopsys/integration/alert/web/security/authentication/ldap/LdapManager.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/SAMLContext.java

Removed an exception being logged when verifying if a specific type of authentication was being used.

---

deployment/docker-compose/README.md
deployment/docker-compose/docker-compose.local-overrides.yml
deployment/docker-swarm/README.md
deployment/docker-swarm/docker-compose.local-overrides.yml
docker-entrypoint.sh
src/main/resources/application.properties

Make the truststore password and keystore password configurable by environment variable or docker secret file.

Ps cert fixes

---

alert-common/src/main/java/com/synopsys/integration/alert/common/channel/message/ChannelMessageParser.java

Added a small bit of additional functionalty. Any other changes to this will be done in the MS Teams reformat branch

Pulled out functionality to allow MS Teams to build their message cards

---

src/main/java/com/synopsys/integration/alert/channel/jira/cloud/JiraChannel.java
src/main/java/com/synopsys/integration/alert/channel/jira/cloud/actions/JiraGlobalTestAction.java
src/main/java/com/synopsys/integration/alert/channel/jira/cloud/web/JiraCustomEndpoint.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/JiraServerProperties.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/descriptor/JiraServerDescriptor.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/descriptor/JiraServerDistributionUIConfig.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/descriptor/JiraServerGlobalUIConfig.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/web/JiraServerCustomEndpoint.java
src/main/resources/db/changelog/alert/5.2.0/changelog-jira-server.xml

Implement the changes to install the marketplace app into Jira Server.

Ps jira server install

---

src/main/resources/db/changelog/alert/5.2.0/changelog-authentication-component.xml

Remove permissions to authentication for any user other than an admin.

Fix(permissions): Alow only admins to access Authentication in the UI.

---

build.gradle
src/main/java/com/synopsys/integration/alert/channel/jira/cloud/JiraChannel.java
src/main/java/com/synopsys/integration/alert/channel/jira/cloud/JiraIssueConfigValidator.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/JiraServerChannel.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/JiraServerIssueConfigValidator.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/AlertAuthenticationProvider.java
src/test/java/com/synopsys/integration/alert/channel/jira/JiraServerIssueConfigValidatorTest.java

Validate the issue types belong to the project.

Ps issue type validation

---

src/main/java/com/synopsys/integration/alert/channel/jira/cloud/JiraChannel.java
src/main/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudIssueConfigValidator.java
src/main/java/com/synopsys/integration/alert/channel/jira/cloud/descriptor/JiraDistributionUIConfig.java
src/main/java/com/synopsys/integration/alert/channel/jira/common/JiraConstants.java
src/main/java/com/synopsys/integration/alert/channel/jira/common/JiraIssueConfigValidator.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/descriptor/JiraServerDistributionUIConfig.java
src/test/java/com/synopsys/integration/alert/channel/jira/JiraCloudIssueConfigValidatorTest.java

Encapsulated common functionality in the JiraIssueValidators for Server and Cloud into one class.

Refactor(jira): Create a common issue validator.

---

alert-common/build.gradle
alert-common/src/main/java/com/synopsys/integration/alert/common/rest/ResponseBodyBuilder.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/actions/BlackDuckGlobalTestAction.java
src/main/java/com/synopsys/integration/alert/web/config/ConfigController.java
src/main/java/com/synopsys/integration/alert/web/config/JobConfigController.java
src/main/java/com/synopsys/integration/alert/web/config/PKIXErrorResponseFactory.java
src/main/js/dynamic/GlobalConfiguration.js
src/main/js/field/MessageFormatter.js
src/main/js/field/StatusMessage.js

Link are parsed out of the info text and converted to links.

Created a more detailed error for PKIX issues.

---

src/main/java/com/synopsys/integration/alert/channel/email/descriptor/EmailDistributionUIConfig.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckDistributionUIConfig.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckProviderUIConfig.java
src/main/js/dynamic/DistributionConfiguration.js

The java classes were only reformatted. The JS class was the one actually changed.

Fixed the channel distributions to display default values.

---

alert-common/src/main/java/com/synopsys/integration/alert/common/util/MarkupEncoderUtil.java
alert-common/src/test/java/com/synopsys/integration/alert/common/util/MarkupEncoderTest.java
src/main/java/com/synopsys/integration/alert/channel/msteams/MsTeamsMessageParser.java
src/main/java/com/synopsys/integration/alert/channel/slack/parser/SlackChannelMessageParser.java
src/test/java/com/synopsys/integration/alert/channel/msteams/MsTeamsChannelTest.java
src/test/java/com/synopsys/integration/alert/channel/msteams/MsTeamsMessageParserTest.java
src/test/java/com/synopsys/integration/alert/channel/slack/SlackChannelTest.java

This should be usable for any characters you want to convert.

Bm markup encoder

---

src/main/js/MainPage.js
src/main/js/Navigation.js

Spinner spins in main content page and the items in the left bar are removed until the descriptors are loaded.

Bm descriptor spinner

---

deployment/docker-compose/README.md
deployment/docker-swarm/README.md

Update the doc to clarify the docker-compose.local-overrides.yml for Alert should be the only file to contain Alert settings.   
Update the deployment commands

Fix(doc): Update the install based on customer feedback.

---

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/accessor/AuthorizationUtility.java
alert-common/src/main/java/com/synopsys/integration/alert/common/security/authorization/AuthorizationManager.java
alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultAuthorizationUtility.java
alert-database/src/main/java/com/synopsys/integration/alert/database/user/RoleRepository.java
src/main/java/com/synopsys/integration/alert/web/controller/metadata/DescriptorController.java
src/test/java/com/synopsys/integration/alert/web/controller/DescriptorControllerSpeedTestIT.java
src/test/resources/logback-test.xml

This is the same exact code from my previous performance PR. Just moved into this branch so it can be merged into 5.2.0

Performance test and increase

---

src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/AlertSAMLEntryPoint.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/SAMLAuthProvider.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/SAMLManager.java

made the logging changes for SAML from the 5.1.0 branch to 5.2.0.  Merging the original branch had too many changes.

Fix(SAML): Add more debug logging to the SAML classes.

---

build.gradle

Implement PR enhancement for findJar in master

Ps build enhancement

---

src/test/java/com/synopsys/integration/alert/database/api/user/UserAccessorTestIT.java

Fix(test): Fix the update user test to fix the build.

---

src/main/java/com/synopsys/integration/alert/channel/email/descriptor/EmailDistributionUIConfig.java

Add requested data field for additionalEmailAddresses custom endpoint field

---

src/main/js/dynamic/loaded/users/UserTable.js
src/main/js/field/TableDisplay.js

Ps user delete

---

src/main/js/dynamic/loaded/users/RoleTable.js
src/main/js/dynamic/loaded/users/UserTable.js
src/main/js/field/TableDisplay.js

Doesn't actually update or create copies yet. Just the basic structure

Bm edit col

---

src/main/java/com/synopsys/integration/alert/web/model/UserConfig.java
src/main/java/com/synopsys/integration/alert/web/user/RoleActions.java
src/main/java/com/synopsys/integration/alert/web/user/RoleController.java
src/main/java/com/synopsys/integration/alert/web/user/UserActions.java
src/main/java/com/synopsys/integration/alert/web/user/UserController.java
src/main/js/dynamic/loaded/users/UserTable.js

Due to all the UI issues I've run into updating the insert dialog with the field Errors for validation this PR just contains the backend validation code.  A separate PR will be created to add the validation to the UI.

Feature(users): Implement the validation for users and roles.

---

src/main/java/com/synopsys/integration/alert/web/user/UserActions.java
src/main/java/com/synopsys/integration/alert/web/user/UserController.java

Fix the assignment of roles for a newly created user.

Ps user role assignment

---

src/main/java/com/synopsys/integration/alert/web/user/UserActions.java
src/main/java/com/synopsys/integration/alert/web/user/UserController.java
src/main/js/dynamic/loaded/users/UserTable.js
src/main/js/store/actions/users.js

Ps user update

---

alert-common/src/main/java/com/synopsys/integration/alert/common/channel/NamedDistributionChannel.java
alert-common/src/main/java/com/synopsys/integration/alert/common/channel/key/ClassNameChannelKey.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/DescriptorKey.java
alert-common/src/main/java/com/synopsys/integration/alert/common/workflow/combiner/DefaultMessageCombiner.java
alert-common/src/test/java/com/synopsys/integration/alert/common/ConfigurationFieldModelTest.java
alert-common/src/test/java/com/synopsys/integration/alert/common/action/UploadEndpointManagerTest.java
alert-common/src/test/java/com/synopsys/integration/alert/common/descriptor/ChannelDescriptorTest.java
alert-common/src/test/java/com/synopsys/integration/alert/common/descriptor/DescriptorMapTest.java
alert-common/src/test/java/com/synopsys/integration/alert/common/provider/ProviderPropertiesTest.java
src/main/java/com/synopsys/integration/alert/channel/email/EmailChannelKey.java
src/main/java/com/synopsys/integration/alert/channel/jira/cloud/JiraChannelKey.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/JiraServerChannelKey.java
src/main/java/com/synopsys/integration/alert/channel/msteams/MsTeamsKey.java
src/main/java/com/synopsys/integration/alert/channel/slack/SlackChannelKey.java
src/main/java/com/synopsys/integration/alert/component/audit/AuditDescriptorKey.java
src/main/java/com/synopsys/integration/alert/component/authentication/descriptor/AuthenticationDescriptorKey.java
src/main/java/com/synopsys/integration/alert/component/scheduling/descriptor/SchedulingDescriptorKey.java
src/main/java/com/synopsys/integration/alert/component/settings/descriptor/SettingsDescriptorKey.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/BlackDuckProviderKey.java
src/main/java/com/synopsys/integration/alert/provider/polaris/PolarisProviderKey.java
src/test/java/com/synopsys/integration/alert/database/api/ProviderDataAccessorTestIT.java
src/test/java/com/synopsys/integration/alert/database/api/configuration/ConfigurationAccessorTestIT.java
src/test/java/com/synopsys/integration/alert/database/api/configuration/DescriptorAccessorTestIT.java
src/test/java/com/synopsys/integration/alert/web/controller/metadata/DescriptorControllerTest.java

Test message response now displays descriptor name instead of key.
WARNING: There are a lot of finals removed in this PR since I had to touch a lot of files. The majority of changes are in the first few files.

Bm fix test message

---

src/main/java/com/synopsys/integration/alert/web/user/UserActions.java
src/main/java/com/synopsys/integration/alert/web/user/UserController.java
src/main/js/dynamic/loaded/users/UserTable.js
src/main/js/field/TableDisplay.js
src/test/java/com/synopsys/integration/alert/database/api/user/UserAccessorTestIT.java
src/test/java/com/synopsys/integration/alert/web/actions/LoginActionsTestIT.java

Display the validation issues for creating and updating users.  Also ensure the table modal displays data for the correct user when editing.

Fix the user table issues to display errors

---

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/accessor/UserAccessor.java
alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultUserAccessor.java
alert-database/src/main/java/com/synopsys/integration/alert/database/user/UserEntity.java
build.gradle
src/main/java/com/synopsys/integration/alert/web/security/AuthenticationHandler.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/event/AuthenticationEventListener.java
src/main/resources/db/changelog/alert/5.3.0/changelog-user-management.xml
src/test/java/com/synopsys/integration/alert/database/user/UserEntityTest.java

Creating a Draft pull request while I sort out what is wrong with SAML authentication.

Feat(users): Prevent deletion of external users.

---

src/main/js/component/AboutInfo.js
src/main/js/store/actions/distributions.js

If the user is logged in via SAML and LDAP display a message that the user does not have access to channel or provider data.

Fix(users): Display messages that the user unauthorized.

---

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/ui/ProviderDistributionUIConfig.java
alert-common/src/main/java/com/synopsys/integration/alert/common/enumeration/FormatType.java

Added a more detailed description to the Format field

---

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/UserModel.java
alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultUserAccessor.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/event/AuthenticationEventManager.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/UserDetailsService.java
src/main/resources/db/changelog/alert/5.2.0/changelog-authentication-component.xml
src/main/resources/db/changelog/alert/5.2.0/changelog-default-users.xml
src/test/java/com/synopsys/integration/alert/component/settings/PasswordResetServiceTest.java
src/test/java/com/synopsys/integration/alert/database/api/user/UserAccessorTestIT.java
src/test/java/com/synopsys/integration/alert/database/api/user/UserModelTest.java

Disable the 'jobmanager' and 'alertuser' users in Alert.

Ps disable users

---

src/main/java/com/synopsys/integration/alert/workflow/startup/component/AlertStartupInitializer.java
src/main/java/com/synopsys/integration/alert/workflow/startup/component/AuthenticationSettingsMigration.java
src/main/java/com/synopsys/integration/alert/workflow/startup/component/ConfigurationLogger.java
src/main/java/com/synopsys/integration/alert/workflow/startup/component/CronJobsStartupComponent.java
src/main/java/com/synopsys/integration/alert/workflow/startup/component/EnvironmentVariableUtility.java
src/main/java/com/synopsys/integration/alert/workflow/startup/component/ProviderInitializer.java
src/main/java/com/synopsys/integration/alert/workflow/startup/component/SAMLStartupComponent.java
src/main/java/com/synopsys/integration/alert/workflow/startup/component/SystemMessageInitializer.java
src/main/java/com/synopsys/integration/alert/workflow/startup/component/SystemStatusValidator.java
src/test/java/com/synopsys/integration/alert/workflow/startup/AlertStartupInitializerTest.java
src/test/java/com/synopsys/integration/alert/workflow/startup/EnvironmentVariableUtilityTest.java

Migrate the old ALERT_COMPONENT_SETTINGS_ environment variables for authentication to the new authentication component configuration in the database.

Ps settings fix

---

src/main/java/com/synopsys/integration/alert/workflow/startup/component/AlertStartupInitializer.java
src/main/java/com/synopsys/integration/alert/workflow/startup/component/AuthenticationSettingsMigration.java
src/main/java/com/synopsys/integration/alert/workflow/startup/component/ConfigurationLogger.java
src/main/java/com/synopsys/integration/alert/workflow/startup/component/CronJobsStartupComponent.java
src/main/java/com/synopsys/integration/alert/workflow/startup/component/ProviderInitializer.java
src/main/java/com/synopsys/integration/alert/workflow/startup/component/SAMLStartupComponent.java
src/main/java/com/synopsys/integration/alert/workflow/startup/component/SystemMessageInitializer.java
src/main/java/com/synopsys/integration/alert/workflow/startup/component/SystemStatusValidator.java

In case we need to add items to the startup order the main existing components are set in increments of 10.

Ps startup range

---

src/main/java/com/synopsys/integration/alert/channel/jira/server/descriptor/JiraServerDistributionUIConfig.java

The description of the user name field mentions an email which is not valid.  The Jira server has it's own users so you need to use the username of the user not the email.  Clarify in the description.

Fix(jira): Fix the description of the user name.

---

src/main/css/table.scss
src/main/java/com/synopsys/integration/alert/channel/jira/cloud/JiraIssueConfigValidator.java
src/main/java/com/synopsys/integration/alert/channel/jira/common/JiraConstants.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/JiraServerIssueConfigValidator.java
src/main/js/dynamic/loaded/audit/Details.js

Fix the error message that is displayed in the audit table details.  Also update the sizing of components in the audit table details.

Ps jira exception message

---

alert-common/src/main/java/com/synopsys/integration/alert/common/message/model/LinkableItem.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/filter/BlackDuckDistributionFilter.java
src/main/java/com/synopsys/integration/alert/web/audit/AuditEntryActions.java
src/main/java/com/synopsys/integration/alert/web/config/ConfigActions.java
src/main/java/com/synopsys/integration/alert/web/model/LoginConfig.java

Fixes for Sonar Cloud issues.  Creating pull request for a build confirmation that all the issues are fixed.

Ps sonar fixes

---

src/main/java/com/synopsys/integration/alert/channel/jira/common/IssueTrackerFieldExceptionConverter.java
src/main/resources/db/changelog/alert/5.3.0/changelog-user-management.xml

Enable the job manager and alert user. Also add the error message so it can be shown for the Jira channels.

Fix(users): Enable system users and add 5.2.0 error message for Jira.

---

buildSrc/src/main/java/com/synopsys/integration/alert/build/RunServerTask.java
src/main/java/com/synopsys/integration/alert/workflow/startup/component/AuthenticationSettingsMigration.java

Fix the migration of old environment variables to the new authentication component environment variables.

Ps settings vars

---

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/accessor/CustomCertificateAccessor.java
alert-common/src/main/java/com/synopsys/integration/alert/common/security/CertificateUtility.java
alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultCustomCertificateAccessor.java
src/main/java/com/synopsys/integration/alert/web/certificates/CertificateActions.java
src/main/java/com/synopsys/integration/alert/web/certificates/CertificatesController.java
src/main/java/com/synopsys/integration/alert/web/model/CertificateModel.java
src/main/java/com/synopsys/integration/alert/workflow/startup/component/TrustStoreInitializer.java
src/main/resources/db/changelog/alert/5.3.0/custom-certificates.xml

Initial changes to provide a Rest API for certificate management.

Ps cert rest api

---

src/test/java/com/synopsys/integration/alert/web/certificates/CertificateActionsTestIT.java
src/test/java/com/synopsys/integration/alert/web/certificates/CertificateControllerTestIT.java
src/test/java/com/synopsys/integration/alert/web/certificates/CertificateTestUtil.java

All the tests were issuing get requests.  Updated the tests to issue the correct controller REST calls.

Fix(tests): Fix controller tests and add more.

---

alert-common/src/main/java/com/synopsys/integration/alert/common/security/CertificateUtility.java
src/main/java/com/synopsys/integration/alert/web/certificates/CertificatesController.java

Use a URI or a file path for resolving the trust store.

Ps cert util fix

---

src/main/resources/db/changelog/alert/6.0.0/changelog-init-auth-db.xml
src/main/resources/db/changelog/alert/6.0.0/changelog-init-config-db.xml

This is the PR to fix the build.

Add custom_certificate descriptor permissions to postgres initialization

---

src/main/java/com/synopsys/integration/alert/component/authentication/actions/AuthenticationApiAction.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/SAMLManager.java
src/main/java/com/synopsys/integration/alert/workflow/startup/component/SAMLStartupComponent.java

log generic exceptions and convert the api actions to after rather than before.

fix: Update SAML settings after database updated and log exceptions.

---

alert-common/src/main/java/com/synopsys/integration/alert/common/action/CustomEndpointManager.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/endpoint/CustomEndpoint.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/ui/ChannelSelectCustomEndpoint.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/ui/ProviderDistributionCustomEndpoint.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/ui/ProviderSelectCustomEndpoint.java
alert-common/src/test/java/com/synopsys/integration/alert/common/provider/ProviderPropertiesTest.java
src/main/java/com/synopsys/integration/alert/channel/email/web/EmailCustomEndpoint.java
src/main/java/com/synopsys/integration/alert/channel/jira/cloud/web/JiraCustomEndpoint.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/web/JiraServerCustomEndpoint.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/actions/BlackDuckGlobalApiAction.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/web/PolicyNotificationFilterCustomEndpoint.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/web/VulnerabilityNotificationFilterCustomEndpoint.java
src/main/java/com/synopsys/integration/alert/web/controller/CustomEndpointController.java
src/main/java/com/synopsys/integration/alert/workflow/startup/component/AlertStartupInitializer.java
src/test/java/com/synopsys/integration/alert/NotificationManagerTestITAlert.java
src/test/java/com/synopsys/integration/alert/audit/controller/AuditEntryActionsTest.java
src/test/java/com/synopsys/integration/alert/mock/entity/MockNotificationContent.java
src/test/java/com/synopsys/integration/alert/provider/blackduck/actions/BlackDuckGlobalApiActionTest.java
src/test/java/com/synopsys/integration/alert/provider/blackduck/tasks/BlackDuckAccumulatorTest.java
src/test/java/com/synopsys/integration/alert/workflow/scheduled/frequency/ProcessingTaskTest.java

Change to create the BlackduckProperties in custom endpoints via FieldModel

refactor: Convert custom endpoints to use FieldModel.

---

alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultCustomCertificateAccessor.java
src/main/java/com/synopsys/integration/alert/web/certificates/CertificateActions.java

Fixed the certificate existence check. 
Fixed the logging we have for id's and aliases in the CertificateModel.

Sonar cloud fixes

---

src/main/js/dynamic/loaded/users/PermissionTable.js
src/main/js/dynamic/loaded/users/RoleTable.js

When clicking on the add method to create a new role clear the permissionData object.
Need to transition from inProgress to not in progress to close the permissions dialog.

role dialog fixes

---

src/main/js/dynamic/loaded/users/UserTable.js

check if the user confirm password error is populated.  If it has then edit dialog should be shown with the error.

user password fix

---

alert-database/src/test/java/com/synopsys/integration/alert/database/api/DefaultAuditUtilityTest.java
alert-database/src/test/java/com/synopsys/integration/alert/database/api/DefaultAuthorizationUtilityTest.java

PR for the changes made to DefaultAuditUtilityTest for findMatchingAuditId, FindFirstByJobId, getPageOfAuditEtnries. Please let me know if there are any changes or feedback you have for the tests we've made here.

Mc db api tests

---

src/main/js/component/common/ConfigButtons.js
src/main/js/component/common/ConfirmModal.js
src/main/js/dynamic/GlobalConfiguration.js

Added a delete button with a confirmation modal to the config buttons.  The global configurations, provider and channel, will display a delete button to delete the configurations.

Add a delete button to the global configurations.

---

deployment/helm/templates/_helpers.tpl
deployment/helm/values.yaml

* GitHub: N/A
* JIRA: https://jira-sig.internal.synopsys.com/browse/IALERT-1656
* N/A
* Make imagePullSecrets in Values.yaml a list of strings
* Modify the function in _helpers.tpl to format the secrets as `- name: <secret>`

Helm Chart: Format imagePullSecrets as a list of strings for better user experience

---

src/main/java/com/synopsys/integration/alert/web/security/authentication/AlertAuthenticationProvider.java
src/main/java/com/synopsys/integration/alert/workflow/scheduled/update/UpdateChecker.java
src/test/java/com/synopsys/integration/alert/web/actions/LoginActionsTestIT.java

Backport of the fix for LDAP authentication from master.  Also fixed the UpdateChecker to pass a test with the new versioning scheme.

 fix ldap authentication

---

Dockerfile
alert-database/Dockerfile
build.gradle
deployment/docker-swarm/hub/docker-compose.yml
deployment/docker-swarm/standalone/docker-compose.yml
deployment/kubernetes/hub/3-alertdb.yml
deployment/kubernetes/hub/4-alert.yml
deployment/kubernetes/standalone/3-alertdb.yml
deployment/kubernetes/standalone/4-alert.yml
deployment/kubernetes/standalone/create.sh
deployment/kubernetes/standalone/delete.sh

Create a new volume for the database container.
Remove the alert specific user.  
Create a separate service for the alert database in Kubernetes.
Fixes 5.3.0 to 6.0.0 upgrades in docker swarm.

deployment fixes

---

alert-database/src/test/java/com/synopsys/integration/alert/database/api/DefaultNotificationManagerTest.java
alert-database/src/test/java/com/synopsys/integration/alert/database/api/DefaultProviderDataAccessorTest.java

Increasing the test coverage for DefaultProviderDataAccessor and DefaultNotificationManager

Mc alertdb tests

---

build.gradle
deployment/helm/synopsys-alert/templates/_helpers.tpl
deployment/helm/synopsys-alert/templates/alert-environ-secret.yaml
package-lock.json
package.json

adding quote to secret changing encryption key values during base64 encode and hence removing it

adding quote to secret changing encryption key values and hence removing it

---

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/Descriptor.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/ui/UIConfig.java
src/main/js/distribution/Index.js
src/main/js/dynamic/loaded/certificates/CertificatesPage.js
src/main/js/dynamic/loaded/users/UserManagement.js
src/main/js/field/TableDisplay.js
src/main/js/providers/ProviderTable.js
src/main/js/util/descriptorUtilities.js

Fixing the config field retrieval so state changes don't have lasting impacts. Updating the UI to make sure the correct descriptor is used.

Fixing UIConfig, and TableDisplay usage

---

src/main/java/com/synopsys/integration/alert/component/scheduling/actions/SchedulingGlobalApiAction.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/AlertWebSSOProfileOptions.java
src/main/java/com/synopsys/integration/alert/web/security/authentication/saml/SAMLContext.java
src/main/java/com/synopsys/integration/alert/workflow/scheduled/PurgeTask.java
src/test/java/com/synopsys/integration/alert/component/scheduling/SchedulingGlobalApiActionTest.java

Handle some Fixme, todo, and sonar cloud issues.

fixme changes

---

deployment/helm/synopsys-alert/README.md
deployment/helm/synopsys-alert/values.yaml

Updated helm installation README file.  You can see how the changes look by navigating here.
https://github.com/blackducksoftware/blackduck-alert/blob/ps_helm_docs/deployment/helm/synopsys-alert/README.md

 helm docs

---

build.gradle
buildSrc/src/main/java/com/synopsys/integration/alert/build/CreateKeystoreTask.java
buildSrc/src/main/java/com/synopsys/integration/alert/build/RunServerTask.java

Moving the runServer lines into the RunServerTask. Moving the createKeystore lines into CreateKeystoreTask. Adding helm validation tasks and cleanup. Updating the deployment files to exclude the helm tmp files.
I don't have helm setup locally so I have not yet tested the helm tasks.

Build changes

---

alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultProviderDataAccessor.java
alert-database/src/main/java/com/synopsys/integration/alert/database/provider/user/ProviderUserRepository.java
alert-database/src/test/java/com/synopsys/integration/alert/database/api/DefaultProviderDataAccessorTest.java

Need to remove old user and project relations.  We were never removing old relations only adding new relations.  Using similar logic to updating the projects where we determine what to add and what to remove.

duplicate email fix

---

deployment/docker-swarm/hub/docker-compose.yml
deployment/docker-swarm/standalone/docker-compose.yml

Make the memory limits for the postgres container consistent with the helm chart limits

Update the default memory constraints for postgres containers.

---

alert-database/src/main/resources/liquibase/6.0.0/settings-fields.xml

Update the timestamp columns from the settings descriptor to have non null values.

 upgrade fix

---

alert-database/src/test/java/com/synopsys/integration/alert/database/api/DefaultAuthorizationUtilityTest.java
alert-database/src/test/java/com/synopsys/integration/alert/database/api/DefaultUserAccessorTest.java

Increasing the test coverage for DefaultAuthorizationUtility and DefaultUserAccessor. Let me know if there are any improvements or suggestions for these tests.

Mc auth and user tests

---

docker-entrypoint.sh

Remove the method from the docker entry point to backup the old in memory database.

 Remove the in memory database backup.

---

package-lock.json
src/main/js/component/common/DescriptorLabel.js
src/main/js/distribution/Index.js

Refactor the job table to display tooltips for each column.

 Add tooltips to all job columns.

---

src/main/js/component/AboutInfo.js
src/main/js/util/descriptorUtilities.js

Create links if the user has access to descriptors with Global context otherwise list them.
If the user has no access to providers don't show the table.

about page fix

---

src/main/js/dynamic/loaded/certificates/CertificatesPage.js
src/main/js/dynamic/loaded/tasks/TaskManagement.js
src/main/js/dynamic/loaded/users/RoleTable.js
src/main/js/dynamic/loaded/users/UserTable.js
src/main/js/field/TableDisplay.js

Fixes for Linting errors with the classes using TableDisplay.

 Fix lint issues in classes using TableDisplay.

---

src/main/java/com/synopsys/integration/alert/AboutReader.java
src/main/java/com/synopsys/integration/alert/web/actions/DescriptorMetadataActions.java
src/main/java/com/synopsys/integration/alert/web/controller/metadata/DescriptorController.java
src/main/java/com/synopsys/integration/alert/web/model/AboutModel.java
src/main/java/com/synopsys/integration/alert/web/user/RoleActions.java
src/main/js/component/AboutInfo.js
src/main/js/store/reducers/about.js
src/main/js/util/descriptorUtilities.js
src/test/java/com/synopsys/integration/alert/AboutReaderTest.java
src/test/java/com/synopsys/integration/alert/common/message/model/AboutModelTest.java
src/test/java/com/synopsys/integration/alert/web/actions/AboutActionsTest.java
src/test/java/com/synopsys/integration/alert/web/controller/AboutControllerTest.java
src/test/java/com/synopsys/integration/alert/web/controller/metadata/DescriptorControllerTest.java
src/test/java/com/synopsys/integration/alert/workflow/scheduled/update/UpdateCheckerTest.java

- Have the about model list all possible providers and channels
- Have the UI check if the user has Global context permissions and create a NavLink to that part of the UI if the user has permissions.
- Take the contents of the DescriptorController and refactor it into an Actions class
- Add a method to generate DescriptorMetadata classes without any permission information.

about descriptor fix

---

src/main/css/app.scss

The description will wrap based on having left and right margins.

Fix the margins to allow the wrapping of text.

---

src/main/js/dynamic/loaded/tasks/TaskManagement.js
src/main/js/field/TableDisplay.js

Make the Edit and Columns in the Table Display configurable for the text and icon displayed.
Change the edit column to say view and have a file open icon.

Add an indicator that the column can be selected and viewed.

---

azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/model/NameModel.java
azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/service/board/columns/BoardColumnService.java

Azure Library: Board Columns

---

src/main/java/com/synopsys/integration/alert/channel/azure/boards/AzureBoardsChannelKey.java
src/main/java/com/synopsys/integration/alert/channel/azure/boards/descriptor/AzureBoardsDescriptor.java
src/main/java/com/synopsys/integration/alert/channel/azure/boards/descriptor/AzureBoardsDistributionUIConfig.java
src/main/java/com/synopsys/integration/alert/channel/azure/boards/descriptor/AzureBoardsGlobalUIConfig.java
src/main/java/com/synopsys/integration/alert/channel/azure/boards/web/AzureBoardsCustomEndpoint.java

This is the setup work for the new Azure Boards channel. Some of the descriptions and labels have placeholder values as we have not yet come up with what we will and won't need. 
If there are any suggestions you guys have to the strings that I've chosen for labels or descriptors, please let me know and I will change them.

Creaing descriptor and UI configs for Azure Boards

---

src/main/java/com/synopsys/integration/alert/channel/email/descriptor/EmailDescriptor.java
src/main/java/com/synopsys/integration/alert/channel/jira/cloud/descriptor/JiraDescriptor.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/descriptor/JiraServerDescriptor.java
src/main/java/com/synopsys/integration/alert/channel/slack/descriptor/SlackDescriptor.java

Updating other channel descriptors to use prefix rather than having the values duplicated.

Update Channel descriptors

---

alert-database/src/main/resources/liquibase/6.2.0/azure-boards.xml
alert-database/src/main/resources/liquibase/6.2.0/changelog.xml
alert-database/src/main/resources/liquibase/changelog-postgres-master.xml

This PR is for adding the descriptors and fields through liquibase. Also included is the liquibase changes for the different user permissions for the global and distribution configs.

feat: Adding liquibase changes for Alertboards

---

azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/service/type/WorkItemTypeFieldInstanceModel.java
azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/service/type/WorkItemTypeResponseModel.java
azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/service/type/WorkItemTypeService.java
azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/service/type/WorkItemTypeTransitionModel.java
azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/service/workitem/WorkItemIconModel.java

Azure Library: Work Item Types

---

alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultProviderDataAccessor.java
src/main/js/store/reducers/distributionConfigs.js
src/main/js/util/httpErrorUtilities.js

Create the correct error objects for the missing global config errors for the channel and provider.

 global config missing error message

---

src/main/js/dynamic/DistributionConfiguration.js

Separate the provider config name from the other provider fields and display it under the provider type field.

Move the provider config name to under the provider type field.

---

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/ui/ChannelSelectCustomEndpoint.java

Limit the channels in the select field based on the user permissions.

Only show channels in select based on permissions.

---

src/main/js/field/StatusMessage.js
src/main/js/providers/ProviderTable.js

Add the line that fixes the error messages showing up in the modal.  Make status message render an error or an action message.

add the missing line back and have errors take precedence in StatusMessage

---

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/validators/ValidationResult.java
alert-common/src/main/java/com/synopsys/integration/alert/common/exception/AlertFieldException.java
alert-common/src/main/java/com/synopsys/integration/alert/common/exception/AlertFieldStatus.java
alert-common/src/main/java/com/synopsys/integration/alert/common/exception/FieldErrorSeverity.java
alert-common/src/test/java/com/synopsys/integration/alert/common/descriptor/config/field/validators/ValidationResultTest.java
src/main/java/com/synopsys/integration/alert/web/config/FieldModelProcessor.java
src/main/java/com/synopsys/integration/alert/web/config/FieldValidationAction.java
src/test/java/com/synopsys/integration/alert/common/exception/AlertFieldStatusTest.java

Merge feat warnings into feature branch

---

alert-common/src/main/java/com/synopsys/integration/alert/common/channel/issuetracker/service/IssueCreatorTestAction.java
alert-common/src/main/java/com/synopsys/integration/alert/common/exception/AlertFieldStatus.java
alert-common/src/main/java/com/synopsys/integration/alert/common/exception/FieldErrorSeverity.java
alert-common/src/main/java/com/synopsys/integration/alert/common/rest/model/JobFieldErrors.java
alert-common/src/test/java/com/synopsys/integration/alert/common/rest/model/JobFieldErrorsTest.java
src/main/java/com/synopsys/integration/alert/web/certificates/CertificateActions.java
src/main/java/com/synopsys/integration/alert/web/config/ConfigActions.java
src/main/java/com/synopsys/integration/alert/web/config/FieldModelProcessor.java
src/main/java/com/synopsys/integration/alert/web/config/FieldValidationAction.java
src/main/java/com/synopsys/integration/alert/web/config/JobConfigActions.java
src/main/java/com/synopsys/integration/alert/web/user/RoleActions.java
src/main/java/com/synopsys/integration/alert/web/user/UserActions.java

First set of changes to get the code to compile with the AlertFieldStatus object for errors.

refactor: Use AlertFieldStatus in the web packages.

---

src/main/css/field.scss
src/main/js/field/LabeledField.js
src/main/js/store/actions/distributionConfigs.js

Render warnings and errors in the UI.

ui warning updates

---

src/main/js/distribution/Index.js

Fix the rendering of jobs in the distribution table if they are missing the provider config or have any errors.

 Check if the filtered list > 0 length.

---

alert-database/src/main/resources/liquibase/6.2.0/azure-boards.xml

Register the common distribution fields to the channel.

fix: Add the common fields to the Azure channel.

---

src/main/java/com/synopsys/integration/alert/web/config/JobConfigController.java

Add logging when catching IntegrationException

Mc azure distribution error log

---

alert-common/src/main/java/com/synopsys/integration/alert/common/channel/DistributionChannel.java
azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/service/comment/AzureWorkItemCommentService.java
azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/service/comment/model/WorkItemCommentRequestModel.java
azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/service/project/AzureProjectService.java
azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/service/workitem/AzureWorkItemService.java
src/main/java/com/synopsys/integration/alert/channel/azure/boards/service/AzureBoardsIssueHandler.java
src/main/java/com/synopsys/integration/alert/channel/azure/boards/service/AzureCustomFieldManager.java
src/main/java/com/synopsys/integration/alert/web/config/JobConfigController.java

Fix issues with creating and transitioning issues in Azure.

Feat azure testing

---

src/main/js/dynamic/loaded/users/PermissionTable.js

- Only display the contexts relevant to the descriptor selected
- Show no contexts until descriptor selected
- Hide upload permissions for descriptors other than Settings

UI: Fix Role Permissions Options

---

azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/service/process/AzureProcessService.java
azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/service/process/ProcessWorkItemTypeRequestModel.java
src/main/java/com/synopsys/integration/alert/channel/azure/boards/service/AzureCustomFieldManager.java

Create a copy of the Microsoft work item so it can be modified and we can add custom fields to it

Create a copy of the Microsoft work item

---

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/accessor/AuditUtility.java
alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/AuditEntryPageModel.java
alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultAuditUtility.java
src/main/java/com/synopsys/integration/alert/web/api/audit/AuditEntryActions.java
src/main/java/com/synopsys/integration/alert/web/api/audit/AuditEntryController.java
src/test/java/com/synopsys/integration/alert/web/api/audit/AuditEntryActionsTest.java
src/test/java/com/synopsys/integration/alert/web/api/audit/AuditEntryControllerTestIT.java
src/test/java/com/synopsys/integration/alert/web/api/audit/AuditEntryHandlerTestIT.java
src/test/java/com/synopsys/integration/alert/web/api/audit/AuditEntryRestModelTest.java
src/test/java/com/synopsys/integration/alert/web/api/audit/JobAuditModelTest.java

Change the AuditController and action class to use ActionResponse.

audit controller

---

deployment/docker-swarm/README.md
deployment/docker-swarm/docker-compose.local-overrides.yml
deployment/docker-swarm/external-db/README.md
deployment/docker-swarm/external-db/docker-compose.local-overrides.yml

Updating the swarm README and local overrides to add warnings. Also moved the secrets closer together for user convenience

Updating the swarm README and local overrides

---

alert-common/src/main/java/com/synopsys/integration/alert/common/action/SSLValidationResponseModel.java
alert-common/src/main/java/com/synopsys/integration/alert/common/action/ValidationActionResponse.java
alert-common/src/main/java/com/synopsys/integration/alert/common/action/api/AbstractConfigResourceActions.java
alert-common/src/main/java/com/synopsys/integration/alert/common/action/api/AbstractJobResourceActions.java
alert-common/src/main/java/com/synopsys/integration/alert/common/action/api/AbstractResourceActions.java
alert-common/src/main/java/com/synopsys/integration/alert/common/rest/model/ValidationResponseModel.java
src/main/java/com/synopsys/integration/alert/web/api/certificate/CertificateActions.java
src/main/java/com/synopsys/integration/alert/web/api/config/ConfigActions.java
src/main/java/com/synopsys/integration/alert/web/api/job/JobConfigActions.java
src/main/java/com/synopsys/integration/alert/web/api/role/RoleActions.java
src/main/java/com/synopsys/integration/alert/web/api/user/UserActions.java
src/main/js/dynamic/GlobalConfiguration.js
src/main/js/store/actions/globalConfiguration.js

No distinction was being made between success and error messages in validation.

Fix Global Config Test

---

src/main/java/com/synopsys/integration/alert/channel/azure/boards/service/AzureCustomFieldManager.java

Fixing the exception handling on the copyWorkItem method in Azure.

Fixing the exception handling on the copyWorkItem method in Azure.

---

alert-common/src/main/java/com/synopsys/integration/alert/common/action/ValidationActionResponse.java
alert-database/src/main/resources/liquibase/6.3.0/changelog.xml
alert-database/src/main/resources/liquibase/6.3.0/jira-plugin-fields.xml
src/main/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudContextBuilder.java
src/main/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudProperties.java
src/main/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudRequestDelegator.java
src/main/java/com/synopsys/integration/alert/channel/jira/cloud/actions/JiraCloudGlobalTestAction.java
src/main/java/com/synopsys/integration/alert/channel/jira/cloud/descriptor/JiraCloudDescriptor.java
src/main/java/com/synopsys/integration/alert/channel/jira/cloud/descriptor/JiraCloudGlobalUIConfig.java
src/main/java/com/synopsys/integration/alert/channel/jira/cloud/web/JiraCloudCustomEndpoint.java
src/main/java/com/synopsys/integration/alert/channel/jira/common/JiraGlobalTestAction.java
src/main/java/com/synopsys/integration/alert/channel/jira/common/util/JiraPluginCheckUtil.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/JiraServerContextBuilder.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/JiraServerProperties.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/JiraServerRequestDelegator.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/actions/JiraServerGlobalTestAction.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/descriptor/JiraServerDescriptor.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/descriptor/JiraServerGlobalUIConfig.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/web/JiraServerCustomFunctionAction.java
src/test/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudPropertiesTest.java
src/test/java/com/synopsys/integration/alert/channel/jira/server/JiraServerPropertiesTest.java
src/test/java/com/synopsys/integration/alert/channel/jira/server/JiraTestConfigHelper.java

Remove Jira Admin Requirements

---

src/main/java/com/synopsys/integration/alert/web/api/home/HomeActions.java
src/main/java/com/synopsys/integration/alert/web/api/home/HomeController.java
src/test/java/com/synopsys/integration/alert/web/api/home/HomActionsTest.java
src/test/java/com/synopsys/integration/alert/web/api/home/HomeControllerTestIT.java
src/test/java/com/synopsys/integration/alert/web/api/home/SAMLEnabledResponseModelTest.java
src/test/resources/spring-test.properties

Convert the HomeController to use an action class and process ActionResponse objects

home controller

---

alert-common/src/main/java/com/synopsys/integration/alert/common/rest/model/MultiFieldModel.java
src/main/java/com/synopsys/integration/alert/web/api/system/MultiSystemMessageModel.java
src/main/java/com/synopsys/integration/alert/web/api/system/SystemActions.java
src/main/java/com/synopsys/integration/alert/web/api/system/SystemController.java
src/main/js/store/actions/system.js
src/test/java/com/synopsys/integration/alert/web/actions/SystemActionsTest.java
src/test/java/com/synopsys/integration/alert/web/controller/SystemControllerTestIT.java

Convert SystemActions to use ActionResponse and convert tests to parameterized tests.

 system controller

---

alert-common/build.gradle
src/main/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudRequestDelegator.java
src/main/java/com/synopsys/integration/alert/channel/jira/cloud/actions/JiraCloudGlobalTestAction.java
src/main/java/com/synopsys/integration/alert/channel/jira/cloud/web/JiraCloudCustomEndpoint.java
src/main/java/com/synopsys/integration/alert/channel/jira/common/JiraConstants.java
src/main/java/com/synopsys/integration/alert/channel/jira/common/JiraGlobalTestAction.java
src/main/java/com/synopsys/integration/alert/channel/jira/common/util/JiraPluginCheckUtil.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/JiraServerRequestDelegator.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/actions/JiraServerGlobalTestAction.java
src/main/java/com/synopsys/integration/alert/channel/jira/server/web/JiraServerCustomFunctionAction.java
src/main/java/com/synopsys/integration/alert/channel/util/RestChannelUtility.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/BlackDuckPhoneHomeHandler.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/BlackDuckProperties.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/BlackDuckMessageContentCollector.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/builder/BlackDuckIssueTrackerCallbackUtility.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/builder/BlackDuckMessageBuilder.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/builder/BomEditMessageBuilder.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/builder/VulnerabilityNotificationMessageBuilder.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/builder/policy/PolicyCommonBuilder.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/builder/policy/PolicyViolationMessageBuilder.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/builder/util/VulnerabilityUtil.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/collector/util/BlackDuckResponseCache.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/filter/BlackDuckProjectNameExtractor.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/issues/BlackDuckCallbackHandler.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/issues/BlackDuckProviderIssueHandler.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/tasks/BlackDuckAccumulator.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/tasks/BlackDuckDataSyncTask.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/validators/BlackDuckApiTokenValidator.java
src/main/java/com/synopsys/integration/alert/provider/blackduck/web/PolicyNotificationFilterCustomFunctionAction.java
src/main/java/com/synopsys/integration/alert/workflow/scheduled/update/DockerTagRetriever.java

Update blackduck-common and check Jira permissions

---

deployment/helm/synopsys-alert/templates/postgres.yaml

Fix the path to preserve the postgres database data when upgrading.

fix: Fix the mount path for the postgres database.

---

alert-common/src/main/java/com/synopsys/integration/alert/common/security/authorization/AuthorizationManager.java
src/main/java/com/synopsys/integration/alert/ApplicationConfiguration.java
src/main/java/com/synopsys/integration/alert/web/api/role/RoleActions.java
src/main/java/com/synopsys/integration/alert/web/api/user/UserActions.java

Move the permission cache updates into authorizationManager

Move the permission cache updates into authorizationManager

---

buildSrc/deploymentTasks.gradle

helm chart push use absolute file path.

helm push fix

---

web/src/main/js/dynamic/DistributionConfiguration.js
web/src/main/js/dynamic/loaded/users/PermissionTable.js
web/src/main/js/field/StatusMessage.js
web/src/main/js/store/actions/distributionConfigs.js

- Jobs Table
- Permissions Table

Use StatusMessage (Part 1)

---

channel/src/main/java/com/synopsys/integration/alert/channel/azure/boards/descriptor/AzureBoardsGlobalUIConfig.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/descriptor/JiraCloudGlobalUIConfig.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/common/util/JiraIssueHandler.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/server/descriptor/JiraServerGlobalUIConfig.java
channel/src/test/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudIssueHandlerTest.java
channel/src/test/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudRequestDelegatorTest.java
channel/src/test/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudTestActionTest.java
channel/src/test/java/com/synopsys/integration/alert/channel/jira/server/JiraServerRequestDelegatorTest.java
channel/src/test/java/com/synopsys/integration/alert/channel/jira/server/JiraServerTestActionTest.java
component/src/main/java/com/synopsys/integration/alert/component/authentication/security/saml/SAMLManager.java
provider/src/main/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckProviderUIConfig.java

Updating some of the usages of "Url" I found to use capital "URL".

style: Update "Url" to "URL" in field models and some tests

---

src/test/java/com/synopsys/integration/alert/util/DatabaseConfiguredFieldTest.java
src/test/java/com/synopsys/integration/alert/web/api/job/JobConfigControllerTestIT.java

JobConfigControllerTestIT fixed by adding default values for some of the job fields.

Fixing the JobConfigControllerTestIT 

---

alert-common/src/main/java/com/synopsys/integration/alert/common/channel/issuetracker/service/IssueHandler.java
channel/build.gradle
channel/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudChannel.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudContextBuilder.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudProperties.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudPropertiesFactory.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/actions/JiraCloudDistributionTestAction.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/actions/JiraCloudGlobalTestAction.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/util/JiraCloudIssueHandler.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/web/JiraCloudCustomFunctionAction.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/common/util/JiraIssueHandler.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/server/JiraServerChannel.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/server/JiraServerContextBuilder.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/server/JiraServerProperties.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/server/JiraServerPropertiesFactory.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/server/actions/JiraServerDistributionTestAction.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/server/actions/JiraServerGlobalTestAction.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/server/util/JiraServerIssueHandler.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/server/web/JiraServerCustomFunctionAction.java
channel/src/test/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudPropertiesTest.java
channel/src/test/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudRequestDelegatorTest.java
channel/src/test/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudTestActionTest.java
channel/src/test/java/com/synopsys/integration/alert/channel/jira/common/JiraTestConfigHelper.java
channel/src/test/java/com/synopsys/integration/alert/channel/jira/server/JiraServerPropertiesTest.java
channel/src/test/java/com/synopsys/integration/alert/channel/jira/server/JiraServerRequestDelegatorTest.java
channel/src/test/java/com/synopsys/integration/alert/channel/jira/server/JiraServerTestActionTest.java

Making sure the Jira connections are using the proxy settings. 
Updating the int-jira-common version to the latest version.

Jira proxy usage, updating int-jira-common

---

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/field/endpoint/table/model/ProviderProjectOptions.java
alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/accessor/ProviderDataAccessor.java
provider/src/main/java/com/synopsys/integration/alert/provider/blackduck/BlackDuckProviderDataAccessor.java
provider/src/test/java/com/synopsys/integration/alert/provider/blackduck/mock/MockProviderDataAccessor.java
ui/src/main/js/distribution/Index.js
ui/src/main/js/field/input/TableSelectInput.js
web/src/main/java/com/synopsys/integration/alert/web/api/provider/project/ProviderProjectCustomFunctionAction.java

Serve paged responses to the UI for projects in table-select.

BlackDuck Project Paging

---

deployment/helm/synopsys-alert/templates/alert-environ-configmap.yaml
deployment/helm/synopsys-alert/templates/alert.yaml
deployment/helm/synopsys-alert/values.yaml

Updating the Alert port to be the same as the exposed node port

---

alert-common/src/main/java/com/synopsys/integration/alert/common/action/api/AbstractConfigResourceActions.java
alert-common/src/main/java/com/synopsys/integration/alert/common/action/api/ConfigResourceActions.java
channel/src/main/java/com/synopsys/integration/alert/channel/azure/boards/web/AzureBoardsCustomFunctionAction.java

An interface for autowiring config access into other REST API functionality.

Config Interface

---

alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultAuditAccessor.java
alert-database/src/test/java/com/synopsys/integration/alert/database/api/DefaultAuditAccessorTest.java
src/test/java/com/synopsys/integration/alert/component/audit/web/AuditEntryActionsTest.java

Will have some minor conflicts with PR#1286

feat(audit-accessor): DefaultAuditAccessor now uses the new JobAccessor.

---

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/job/details/DistributionJobDetailsModel.java
alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/job/details/DistributionJobDetailsModelJsonAdapter.java
alert-common/src/test/java/com/synopsys/integration/alert/common/persistence/model/job/details/DistributionJobDetailsModelJsonAdapterTest.java

Oops...turns out we did need a custom serializer as well...

Add custom serializer

---

alert-database/src/main/java/com/synopsys/integration/alert/database/job/email/EmailJobDetailsAccessor.java
alert-database/src/main/java/com/synopsys/integration/alert/database/job/email/additional/EmailJobAdditionalEmailAddressRepository.java

This is all in a transaction, so if something fails, the old emails will be rolled back.

Delete old additional email addresses before saving new ones

---

channel/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudRequestDelegator.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/util/JiraCloudIssueHandler.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/common/JiraCustomFieldResolver.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/common/model/JiraCustomFieldConfig.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/common/util/JiraCustomFieldValueReplacementUtils.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/common/util/JiraErrorMessageUtility.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/common/util/JiraIssueHandler.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/server/JiraServerRequestDelegator.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/server/util/JiraServerIssueHandler.java
channel/src/test/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudIssueHandlerTest.java

- Add utility to replace jira field values
- Abstract error message handling for readability and separation of concerns

Jira Field Value Replacement

---

alert-common/src/main/java/com/synopsys/integration/alert/common/provider/ProviderProjectExistencePopulator.java
alert-common/src/main/java/com/synopsys/integration/alert/common/rest/model/JobProviderProjectFieldModel.java
provider/src/main/java/com/synopsys/integration/alert/provider/blackduck/BlackDuckProjectExistencePopulator.java
src/test/java/com/synopsys/integration/alert/channel/ChannelDescriptorTestIT.java
src/test/java/com/synopsys/integration/alert/performance/utility/ConfigurationManager.java
src/test/java/com/synopsys/integration/alert/web/api/job/JobConfigActionsTest.java
src/test/java/com/synopsys/integration/alert/web/api/job/JobConfigControllerTestIT.java
ui/src/main/js/dynamic/DistributionConfiguration.js
ui/src/main/js/field/input/TableSelectInput.js
web/src/main/java/com/synopsys/integration/alert/web/api/job/JobConfigActions.java
web/src/main/java/com/synopsys/integration/alert/web/api/job/JobFieldModelPopulationUtils.java

The performance impact of doing this is significant. We should definitely consider a different approach if one exists.

Job UI - Missing Projects 

---

alert-common/src/main/java/com/synopsys/integration/alert/common/action/api/AbstractConfigResourceActions.java
alert-common/src/main/java/com/synopsys/integration/alert/common/action/api/AbstractJobResourceActions.java
alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/accessor/CustomCertificateAccessor.java
alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/accessor/DescriptorAccessor.java
alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/util/ConfigurationFieldModelConverter.java
alert-common/src/test/java/com/synopsys/integration/alert/mock/MockDescriptorAccessor.java
alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultCustomCertificateAccessor.java
alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultDescriptorAccessor.java
alert-database/src/test/java/com/synopsys/integration/alert/database/api/DefaultCustomCertificateAccessorTest.java
alert-database/src/test/java/com/synopsys/integration/alert/database/api/DefaultDescriptorAccessorTest.java
src/main/java/com/synopsys/integration/alert/workflow/startup/component/AlertStartupInitializer.java
src/test/java/com/synopsys/integration/alert/database/api/configuration/DescriptorAccessorTestIT.java
src/test/java/com/synopsys/integration/alert/workflow/startup/AlertStartupInitializerTest.java

Trying to keep the number of files touched per PR low.

Remove AlertDatabaseConstraintException: Batch 1

---

alert-common/src/main/java/com/synopsys/integration/alert/common/channel/message/ChannelMessageParser.java
alert-common/src/main/java/com/synopsys/integration/alert/common/email/MessageContentGroupCsvCreator.java
alert-common/src/main/java/com/synopsys/integration/alert/common/message/model/MessageContentGroup.java
alert-common/src/test/java/com/synopsys/integration/alert/common/workflow/processor/DefaultMessageContentProcessorTest.java
alert-common/src/test/java/com/synopsys/integration/alert/common/workflow/processor/DigestMessageContentProcessorTest.java
channel/src/main/java/com/synopsys/integration/alert/channel/email/EmailAddressHandler.java
channel/src/main/java/com/synopsys/integration/alert/channel/email/EmailChannel.java

Refactor MessageContentGroup

---

ui/src/main/js/field/input/TableSelectInput.js
ui/src/main/js/store/actions/audit.js
ui/src/main/js/store/actions/distributions.js

Special characters were not being handled appropriately in our search term queries.

Encoding the search terms in our queries so that special characters like the plus sign can be used in the search term.

---

alert-common/src/main/java/com/synopsys/integration/alert/common/util/DataStructureUtils.java
processor-api/src/main/java/com/synopsys/integration/alert/processor/api/NotificationProcessorV2.java
processor-api/src/main/java/com/synopsys/integration/alert/processor/api/extract/ProjectNotificationMessageExtractor.java
processor-api/src/main/java/com/synopsys/integration/alert/processor/api/extract/ProviderMessageExtractionDelegator.java
processor-api/src/main/java/com/synopsys/integration/alert/processor/api/extract/ProviderMessageExtractor.java
src/test/java/com/synopsys/integration/alert/processor/api/filter/DefaultJobNotificationExtractorTestIT.java

- Delegator
- (Abstract) Extractor
- `ProjectNotificationMessageExtractor`

ProviderMessageExtractor

---

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/config/GlobalConfigExistsValidator.java
alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/ConfigurationModel.java
channel/src/main/java/com/synopsys/integration/alert/channel/azure/boards/AzureBoardsChannel.java
channel/src/main/java/com/synopsys/integration/alert/channel/azure/boards/actions/AzureBoardsDistributionTestAction.java
channel/src/main/java/com/synopsys/integration/alert/channel/email/EmailChannel.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/JiraCloudChannel.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/actions/JiraCloudDistributionTestAction.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/server/JiraServerChannel.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/server/actions/JiraServerDistributionTestAction.java
channel/src/test/java/com/synopsys/integration/alert/channel/email/EmailChannelTestIT.java

trying to make it more clear to the user that they have not configured the global channel config.

Channels missing global configs

---

provider/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/detail/BomEditNotificationDetailExtractor.java
provider/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/AbstractBlackDuckComponentConcernMessageExtractor.java
provider/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/BomEditNotificationMessageExtractor.java
provider/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/model/BomEditWithProjectNameNotificationContent.java

Piggy-backed off of #1392 . Not to be merged before that.

BomEditNotificationMessageExtractor

---

processor-api/src/main/java/com/synopsys/integration/alert/processor/api/summarize/ProjectMessageSummarizer.java

SonarCloud code smell clean-up.

Summarizer Constants

---

provider/src/main/java/com/synopsys/integration/alert/provider/blackduck/BlackDuckProviderDataAccessor.java

adding a layer for log messages

---

channel-api/src/main/java/com/synopsys/integration/alert/channel/api/issue/send/IssueTrackerIssueCommenter.java
channel/src/main/java/com/synopsys/integration/alert/channel/azureboards2/delegate/AzureBoardsIssueCommenter.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira2/cloud/delegate/JiraCloudIssueCommenter.java

The first of many PRs for Azure Boards :)

Azure Boards Commenter

---

alert-database/src/main/resources/liquibase/6.4.0/store-blackduck-project-href.xml

Fix duplicate project PK

---

alert-database/src/main/java/com/synopsys/integration/alert/database/api/StaticJobAccessor.java
channel-api/src/main/java/com/synopsys/integration/alert/channel/api/convert/ComponentConcernConverter.java

- Query for job projects rather than lazily initializing them
- Fix component concern formatting

Fix lazy initialization and formatting issue

---

channel/src/main/java/com/synopsys/integration/alert/channel/jira2/cloud/delegate/JiraCloudIssueTransitioner.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira2/common/delegate/JiraIssueTransitioner.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira2/server/delegate/JiraServerIssueTransitioner.java

Abstracted common issue transition handling for Jira server/cloud.

Jira Server Transitioner 

---

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/accessor/JiraServerJobDetailsAccessor.java
alert-database/src/main/java/com/synopsys/integration/alert/database/api/StaticJobAccessor.java
alert-database/src/main/java/com/synopsys/integration/alert/database/job/jira/server/DefaultJiraServerJobDetailsAccessor.java
alert-database/src/test/java/com/synopsys/integration/alert/database/api/StaticJobAccessorTest.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira2/server/JiraServerDistributionEventReceiver.java

Added implementation for the `JobDetailsAccssor` for Jira server.
Dependent on 1454

Jm jira server accessor

---

channel/src/main/java/com/synopsys/integration/alert/channel/jira/server/actions/JiraServerConfigurationAction.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira2/server/JiraServerChannelV2.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira2/server/JiraServerProcessorFactory.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira2/server/action/JiraServerDistributionTestAction.java

Added JiraServerChannelV2 and JiraServerProcessorFactory.
I believe these are the final components of the new Jira Server implementation.

Jm Jira Server Channel

---

channel/src/main/java/com/synopsys/integration/alert/channel/jira/common/distribution/delegate/JiraIssueCreator.java

Fixed JiraPreconditionNotMetException message being swallowed by AlertException. (IALERT-2336)

Expose JiraException message

---

channel-api/src/main/java/com/synopsys/integration/alert/channel/api/convert/SimpleMessageConverter.java
channel/src/main/java/com/synopsys/integration/alert/channel/email/action/EmailGlobalTestAction.java
channel/src/main/java/com/synopsys/integration/alert/channel/email/distribution/EmailChannelMessageSender.java
channel/src/main/resources/templates/email/message_content.ftl
channel/src/test/java/com/synopsys/integration/alert/channel/email/action/EmailGlobalTestActionTest.java
test-common/src/main/java/com/synopsys/integration/alert/test/common/TestProperties.java

FYI Freemarker's `?has_content` checks nullability and blankness/emptiness.

Fix Global Email Test Action

---

channel/src/main/java/com/synopsys/integration/alert/channel/jira/server/JiraServerPropertiesFactory.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/server/action/JiraServerDistributionTestAction.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/server/distribution/JiraServerMessageSenderFactory.java
channel/src/main/java/com/synopsys/integration/alert/channel/jira/server/distribution/JiraServerProcessorFactory.java

Implement channel-api test-action for Jira Server

---

alert-database/src/main/resources/liquibase/6.4.0/migrate-distribution-jobs.xml

If we want to release this fix, it should be part of **6.4.3**.

Fix BlackDuck filter migration

---

build.gradle

This change was made for 6.4.3 as well

Add Thymeleaf dependency to fix 500 error.

---

ui/src/main/js/MainPage.js
ui/src/main/js/Navigation.js
ui/src/main/js/field/input/NumberInput.js
ui/src/main/js/global/CommonGlobalConfigurationForm.js
ui/src/main/js/global/GlobalRequestHelper.js
ui/src/main/js/global/channels/azure/AzureGlobalConfiguration.js
ui/src/main/js/global/channels/email/EmailGlobalConfiguration.js
ui/src/main/js/global/channels/jira/cloud/JiraCloudGlobalConfiguration.js
ui/src/main/js/global/channels/jira/server/JiraServerGlobalConfiguration.js
ui/src/main/js/global/components/auth/AuthenticationConfiguration.js
ui/src/main/js/global/components/scheduling/SchedulingConfiguration.js
ui/src/main/js/global/components/settings/SettingsConfiguration.js
ui/src/main/js/global/providers/blackduck/BlackDuckConfiguration.js
ui/src/main/js/global/providers/blackduck/BlackDuckModel.js
ui/src/main/js/global/providers/blackduck/BlackDuckProviderConfiguration.js
ui/src/main/js/global/providers/blackduck/BlackDuckProviderTable.js
ui/src/main/js/util/fieldModelUtilities.js

Should have a feature complete provider table page that now uses separate page urls instead of a modal for configuration manipulation

BlackDuck Provider table

---

ui/src/main/js/MainPage.js
ui/src/main/js/Navigation.js
ui/src/main/js/global/CommonGlobalConfigurationForm.js
ui/src/main/js/global/channels/azure/AzureGlobalConfiguration.js
ui/src/main/js/global/channels/email/EmailGlobalConfiguration.js
ui/src/main/js/global/channels/jira/cloud/JiraCloudGlobalConfiguration.js
ui/src/main/js/global/channels/jira/server/JiraServerGlobalConfiguration.js
ui/src/main/js/global/components/auth/AuthenticationConfiguration.js
ui/src/main/js/global/components/scheduling/SchedulingConfiguration.js
ui/src/main/js/global/components/settings/SettingsConfiguration.js
ui/src/main/js/global/providers/blackduck/BlackDuckConfiguration.js
ui/src/main/js/global/providers/blackduck/BlackDuckProviderTable.js

Fixed and verified permissions for the 3 basic users

Bm fix permissions

---

ui/src/main/js/field/StatusMessage.js
ui/src/main/js/field/input/NumberInput.js
ui/src/main/js/global/CommonGlobalConfigurationForm.js
ui/src/main/js/global/components/scheduling/SchedulingConfiguration.js

Fixed an issue with config buttons not displaying load spinner
Fixed an issue with status message not showing when the same message needed to be displayed
Fixed an issue with the scheduling configuration allowing people to clear the drop downs

Bm small fixes

---

ui/src/main/js/distribution/DistributionConfigurationForm.js
ui/src/main/js/distribution/channels/azure/AzureDistributionConfiguration.js
ui/src/main/js/distribution/channels/azure/AzureModel.js
ui/src/main/js/distribution/channels/jira/cloud/JiraCloudDistributionConfiguration.js
ui/src/main/js/distribution/channels/jira/cloud/JiraCloudModel.js
ui/src/main/js/distribution/channels/jira/server/JiraServerDistributionConfiguration.js
ui/src/main/js/distribution/channels/jira/server/JiraServerModel.js
ui/src/main/js/distribution/channels/msteams/MsTeamsDistributionConfiguration.js
ui/src/main/js/distribution/channels/msteams/MsTeamsModel.js
ui/src/main/js/field/FieldMappingField.js

feat: Implement Azure boards and channel skeletons.
feat: Add MSTeams channel and fix azure.
feat: Add fields for Jira Cloud and Server.
feat: Add field mapping field.
feat: Jira make field mapping readonly.

Implement missing distribution channels.

---

ui/src/main/js/common/input/EndpointSelectField.js
ui/src/main/js/common/input/TableSelectInput.js
ui/src/main/js/page/distribution/CommonDistributionConfigurationForm.js
ui/src/main/js/page/distribution/DistributionConfigurationForm.js
ui/src/main/js/page/distribution/DistributionConfigurationTable.js
ui/src/main/js/page/distribution/DistributionModel.js
ui/src/main/js/page/scheduling/SchedulingConfiguration.js
ui/src/main/js/page/scheduling/SchedulingModel.js

Cleaned up some of the Distribution code to to get it to a working state.
**This does not include any button permission fixes, that still needs to be done**

Bm fix distribution

---

ui/src/main/js/application/Navigation.js
ui/src/main/js/page/distribution/DistributionConfigurationForm.js

Added permissions handling for jobs

---

channel/src/main/java/com/synopsys/integration/alert/channel/azure/boards/web/AzureBoardsCustomFunctionAction.java

This fixes an issue with the UI not properly displaying the error info

Added the same error to multiple places in the action response

---

channel/src/main/java/com/synopsys/integration/alert/channel/jira/common/distribution/JiraMessageFormatter.java

I will create a test on _master_ after this is merged because the sub-projects have been refactored there.

Fix(Jira): Summary size limit 255 -> 254

---

channel-api/src/main/java/com/synopsys/integration/alert/channel/api/issue/action/IssueTrackerTestAction.java

Given our  refactor  in 6.5.0 we no longer generate AlertFieldExceptions for validation failures. Since the MessageResults that we now return do not have an error or warning associated with them the UI will not generate any failure messages. This workaround will create "empty" AlertFieldStatus errors that will tell the UI there was an error and where it failed in the banner.
Note that due to these changes we are no longer able to display field errors beneath each field when running test configuration.

Fix issue tracker errors displayed as success

---

alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/ChannelDescriptor.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/ComponentDescriptor.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/Descriptor.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/validator/ConfigurationFieldValidator.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/validator/FieldValidator.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/validator/GlobalConfigurationValidator.java
alert-common/src/main/java/com/synopsys/integration/alert/common/descriptor/validator/GlobalValidator.java
alert-common/src/main/java/com/synopsys/integration/alert/common/rest/FieldModelProcessor.java
api-provider/src/main/java/com/synopsys/integration/alert/api/provider/ProviderDescriptor.java
channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/descriptor/AzureBoardsDescriptor.java
channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/validator/AzureBoardsGlobalConfigurationValidator.java
channel-email/src/main/java/com/synopsys/integration/alert/channel/email/descriptor/EmailDescriptor.java
channel-email/src/main/java/com/synopsys/integration/alert/channel/email/validator/EmailGlobalConfigurationValidator.java
channel-jira-cloud/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/descriptor/JiraCloudDescriptor.java
channel-jira-cloud/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/validator/JiraCloudGlobalConfigurationValidator.java
channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/descriptor/JiraServerDescriptor.java
channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/validator/JiraServerGlobalConfigurationValidator.java
component/src/main/java/com/synopsys/integration/alert/component/authentication/descriptor/AuthenticationDescriptor.java
component/src/main/java/com/synopsys/integration/alert/component/authentication/validator/AuthenticationConfigurationValidator.java
component/src/main/java/com/synopsys/integration/alert/component/scheduling/descriptor/SchedulingDescriptor.java
component/src/main/java/com/synopsys/integration/alert/component/scheduling/validator/SchedulingConfigurationValidator.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/BlackDuckProvider.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/descriptor/BlackDuckDescriptor.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/factory/BlackDuckTaskFactory.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/task/accumulator/BlackDuckAccumulator.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/validator/BlackDuckGlobalConfigurationValidator.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/validator/BlackDuckGlobalValidator.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/validator/BlackDuckSystemValidator.java
src/test/java/com/synopsys/integration/alert/provider/blackduck/task/accumulator/BlackDuckAccumulatorTest.java
src/test/java/com/synopsys/integration/alert/startup/component/SystemValidatorTest.java

Along with name refactors and slight FieldValidator class changes

Blackduck validator

---

ui/src/main/css/table.scss
ui/src/main/js/page/distribution/DistributionConfigurationTable.js
ui/src/main/js/page/provider/blackduck/BlackDuckProviderTable.js

- Formatted enabled buttons with better spacing
- Added word wrap for cell content so that large names can still be read

Bm table styling

---

azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/http/AzureHttpService.java
azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/service/comment/AzureWorkItemCommentService.java
azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/service/query/AzureWorkItemQueryService.java
azure-boards-common/src/main/java/com/synopsys/integration/azure/boards/common/service/workitem/AzureWorkItemService.java
channel/src/main/java/com/synopsys/integration/alert/channel/azure/boards/AzureBoardsProperties.java
channel/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/search/AzureCustomFieldManager.java

- Logging improvement will help debug errors related to custom fields and redirect url 
- HTTP service refactor/simplification will help with developer debugging (one method rather than three duplicates)

Improve Azure Boards logging and simplify http service

---

provider/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/service/BlackDuckMessageBomComponentDetailsCreator.java

When origin(s) is/are present, the vulnerabilities link must include the origin in its path, otherwise it will return empty lists of vulnerabilities.

Fix vulnerabilities link

---

provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/validator/BlackDuckGlobalConfigurationValidator.java

Updated the api token validator to insert its result into the validation object

---

ui/src/main/js/page/channel/jira/cloud/JiraCloudDistributionConfiguration.js
ui/src/main/js/page/channel/jira/server/JiraServerDistributionConfiguration.js

Looking for some advice here on how to phrase this to refer the customer to the docs rather than list all options for custom field placeholder values.

Update descriptions to refer to docs

---

provider-blackduck/src/test/java/com/synopsys/integration/alert/provider/blackduck/processor/message/ProjectNotificationMessageExtractorTest.java
provider-blackduck/src/test/java/com/synopsys/integration/alert/provider/blackduck/processor/message/ProjectVersionNotificationMessageExtractorTest.java
provider-blackduck/src/test/java/com/synopsys/integration/alert/provider/blackduck/processor/message/RuleViolationClearedNotificationMessageExtractorTest.java
provider-blackduck/src/test/java/com/synopsys/integration/alert/provider/blackduck/processor/message/RuleViolationNotificationMessageExtractorTest.java
provider-blackduck/src/test/java/com/synopsys/integration/alert/provider/blackduck/processor/message/VulnerabilityNotificationMessageExtractorTest.java

Adding coverage for the remaining extractors in provider-blackduck processor/message package

Provider blackduck message extractor tests

---

alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultNotificationAccessor.java
alert-database/src/main/java/com/synopsys/integration/alert/database/notification/NotificationContentRepository.java
alert-database/src/test/java/com/synopsys/integration/alert/database/api/DefaultNotificationAccessorTest.java
provider/src/main/java/com/synopsys/integration/alert/provider/blackduck/task/accumulator/BlackDuckNotificationRetriever.java
src/test/java/com/synopsys/integration/alert/database/notification/NotificationContentRepositoryTestIT.java

Fix notification page sort

---

alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultProcessingJobAccessor.java
alert-database/src/main/java/com/synopsys/integration/alert/database/job/DistributionJobRepository.java
src/test/java/com/synopsys/integration/alert/database/api/ProcessingJobAccessorTestIT.java

Update the query to add a sort order on the job creation time.

Ps missing notification fix

---

src/test/java/com/synopsys/integration/alert/performance/NotificationRemovalTest.java

Create a performance test for the purge operation.

test: Create performance test for notification removal.

---

api-processor/src/main/java/com/synopsys/integration/alert/processor/api/summarize/ProjectMessageSummarizer.java
api-processor/src/test/java/com/synopsys/integration/alert/processor/api/summarize/ProjectMessageSummarizerTest.java

For Summary Distribution jobs we will now sort by type (Policy/Vulnerability) and then by severity in descending order.

Summary distribution sorting

---

channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/search/AzureBoardsAlertIssuePropertiesManager.java
channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/search/AzureBoardsSearcher.java
channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/search/AzureSearchFieldBuilder.java
channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/search/AzureSearchFieldMapBuilder.java
channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/search/AzureSearchFieldMappingBuilder.java

Modified additional places in the Azure channel that use properties for searching so that they store appropriately sized values.

Bm azure field too long

---

gradle.properties
ui/build.gradle

First build: 4 minutes
Second build: 36 seconds
Seems pretty good.

build: Introducing build cacheing

---

ui/src/main/js/common/input/mapping/FieldMappingRow.js
ui/src/main/js/common/input/mapping/FluidFieldMappingField.js

This field is less complex and doesn't have tables or modals leading to a cleaner UI. It doesn't offer data retrieval or drop down text fields at the moment.

Created a new field mapping field

---

alert-database/src/main/java/com/synopsys/integration/alert/database/configuration/repository/DescriptorConfigRepository.java
channel-email/src/main/java/com/synopsys/integration/alert/channel/email/web/EmailGlobalConfigAccessor.java
channel-email/src/main/java/com/synopsys/integration/alert/channel/email/web/EmailGlobalConfigController.java
service-email/src/main/java/com/synopsys/integration/alert/service/email/model/EmailGlobalConfigModel.java
ui/src/main/js/common/input/mapping/FluidFieldMappingField.js
ui/src/main/js/common/util/configurationRequestBuilder.js
ui/src/main/js/page/channel/email/standalone/ConfigurationForm.js
ui/src/main/js/page/channel/email/standalone/EmailGlobalConfigurationStandalone.js

Created the new UI for global Email. Should offer all the functionality the original page offered and is hidden behind a beta flag on the original page.
Still some known issues that exist as a new fixme in the email controller file. Will be fixing those issues next.

Bm global email

---

ui/src/main/js/page/channel/email/standalone/EmailGlobalConfigurationStandalone.js

Example of how we would need to setup the UI to track masked data appropriately

Email Global UI now appropriately handles password content

---

alert-common/src/main/java/com/synopsys/integration/alert/common/security/EncryptionUtility.java
component/src/main/java/com/synopsys/integration/alert/component/settings/encryption/model/SettingsEncryptionModel.java
component/src/main/java/com/synopsys/integration/alert/component/settings/encryption/validator/SettingsEncryptionValidator.java
component/src/main/java/com/synopsys/integration/alert/component/settings/encryption/web/SettingsEncryptionController.java
component/src/test/java/com/synopsys/integration/alert/component/settings/encryption/validator/SettingsEncryptionValidatorTest.java
src/test/java/com/synopsys/integration/alert/component/settings/encryption/web/SettingsEncryptionControllerTestIT.java
ui/src/main/js/application/MainPage.js
ui/src/main/js/common/util/configurationRequestBuilder.js
ui/src/main/js/common/util/fieldModelUtilities.js
ui/src/main/js/page/channel/email/standalone/ConfigurationForm.js
ui/src/main/js/page/settings/standalone/SettingsConfigurationStandalone.js
ui/src/main/js/page/settings/standalone/SettingsEncryptionConfiguration.js

Added a new beta page for settings encryption configuration. The proxy UI will be completed in a separate PR.

Settings Encryption UI component

---

alert-database/src/main/resources/liquibase/6.9.0/migrate-email-global-config.xml
channel-email/src/main/java/com/synopsys/integration/alert/channel/email/action/EmailGlobalTestAction.java
channel-email/src/main/java/com/synopsys/integration/alert/channel/email/database/accessor/EmailGlobalConfigAccessor.java
channel-email/src/main/java/com/synopsys/integration/alert/channel/email/distribution/EmailChannelMessageSender.java
channel-email/src/main/java/com/synopsys/integration/alert/channel/email/environment/EmailEnvironmentVariableHandlerFactory.java
channel-email/src/main/java/com/synopsys/integration/alert/channel/email/validator/EmailGlobalConfigurationValidator.java
channel-email/src/test/java/com/synopsys/integration/alert/channel/email/action/EmailGlobalConfigurationActionTest.java
channel-email/src/test/java/com/synopsys/integration/alert/channel/email/action/EmailGlobalTestActionTest.java
channel-email/src/test/java/com/synopsys/integration/alert/channel/email/action/EmailGlobalValidationActionTest.java
channel-email/src/test/java/com/synopsys/integration/alert/channel/email/distribution/EmailChannelTestIT.java
channel-email/src/test/java/com/synopsys/integration/alert/channel/email/validator/EmailGlobalConfigurationValidatorTest.java
service-email/src/main/java/com/synopsys/integration/alert/service/email/JavamailPropertiesFactory.java
service-email/src/main/java/com/synopsys/integration/alert/service/email/model/EmailGlobalConfigModel.java
service-email/src/test/java/com/synopsys/integration/alert/service/email/JavamailPropertiesFactoryTest.java
src/main/java/com/synopsys/integration/alert/update/UpdateEmailService.java

This PR is for several issues discovered:
- Fixing the serialization problem in EmailGlobalConfigModel
- Fix incorrect UUID being used for updates in the email accessor
- Add precondition check for email migrations in liquibase files

Various Email fixes

---

api-processor/src/main/java/com/synopsys/integration/alert/processor/api/summarize/ProjectMessageSummarizer.java

Summary now adds the component concern numeric values together instead of defaulting it to 1.

Fix Unknown version risk counts

---

ui/src/main/js/application/MainPage.js
ui/src/main/js/common/input/DynamicSelectInput.js
ui/src/main/js/common/input/EndpointSelectField.js
ui/src/main/js/page/channel/email/EmailDistributionConfiguration.js
ui/src/main/js/page/distribution/DistributionConfigurationForm.js
ui/src/main/js/page/settings/standalone/SettingsConfigurationStandalone.js
ui/src/main/js/page/settings/standalone/SettingsProxyConfiguration.js

Added the new  proxy UI tab to the settings page.
In addition, I've added the"name" field to  DynamicSelectInput.js. Previously "name" was used throughout the Alert UI without actually being implemented. In these cases, "id" and "name" would always match. I've made updates to make this constant for all other places in the UI not using this, and implemented a new id/name for the proxy configuration.

Proxy UI implementation

---

component/src/main/java/com/synopsys/integration/alert/component/settings/proxy/database/accessor/SettingsProxyConfigAccessor.java
component/src/main/java/com/synopsys/integration/alert/component/settings/proxy/validator/SettingsProxyValidator.java
component/src/test/java/com/synopsys/integration/alert/component/settings/proxy/validator/SettingsProxyValidatorTest.java
ui/src/main/js/page/settings/standalone/SettingsProxyConfiguration.js
web/src/main/java/com/synopsys/integration/alert/web/api/config/GlobalFieldModelToConcreteConversionService.java

* Fix the proxy validation for required fields
* Have the UI populate a default name for the configuration
* Refactor some code to convert a field model to a concrete implementation

fix: improve proxy validation and save new proxy models.

---

provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/action/BlackDuckDistributionFieldModelTestAction.java

Added validation to the BlackDuck test action to notify users of invalid projects if necessary

BlackDuck configured projects warning

---

provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/action/BlackDuckDistributionFieldModelTestAction.java

Adding missing project names to the test warning
Changed both selected project and project name pattern to use paged queries instead.

Update BD project test warnings

---

channel-email/src/main/java/com/synopsys/integration/alert/channel/email/database/accessor/EmailGlobalConfigAccessor.java
service-email/src/main/java/com/synopsys/integration/alert/service/email/model/EmailGlobalConfigModel.java
ui/src/main/js/page/channel/email/EmailGlobalConfiguration.js

Added a boolean field which will let us know whether the password field is set or not similar to how we did it previously.

Added a boolean to the email rest model

---

api-channel-issue-tracker/src/main/java/com/synopsys/integration/alert/api/channel/issue/callback/ProviderCallbackIssueTrackerResponsePostProcessor.java
api-channel-issue-tracker/src/test/java/com/synopsys/integration/alert/api/channel/issue/callback/ProviderCallbackIssueTrackerResponsePostProcessorTest.java
src/test/java/com/synopsys/integration/alert/processing/NotificationReceivedEventHandlerTestIT.java

Merge 6.8.0 and fix the breaking integration test.

 fix test and merge latest from 6.8.0

---

component/src/main/java/com/synopsys/integration/alert/component/settings/convert/ProxyConfigurationModelConverter.java
component/src/main/java/com/synopsys/integration/alert/component/settings/convert/ProxyConfigurationModelSaveActions.java
component/src/test/java/com/synopsys/integration/alert/component/settings/convert/ProxyConfigurationModelSaveActionsTest.java

Implementing concrete save actions for proxy and initial test coverage. Will be be publishing additional tests coverage in other commits.

Proxy save actions implementation

---

api-processor/src/main/java/com/synopsys/integration/alert/processor/api/NotificationContentProcessor.java
api-processor/src/main/java/com/synopsys/integration/alert/processor/api/extract/model/ProcessedProviderMessage.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/service/BlackDuckMessageBomComponentDetailsCreator.java
ui/package.json

This resolves the issue with issue trackers not receiving all messages due to a component having multiple origins
This resolves the issue with message boards receiving too many messages due to multiple origin notifications

Fixed duplicate and missing notifications

---

Dockerfile
build.gradle

docker upgrades

---

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/accessor/DistributionAccessor.java
alert-database-job/src/main/java/com/synopsys/integration/alert/database/api/DefaultDistributionAccessor.java
src/test/java/com/synopsys/integration/alert/database/api/DefaultDistributionAccessorTestIT.java

Ended up doing it in memory since the queries would not work with hibernate

Bm fix distribution filter

---

src/main/java/com/synopsys/integration/alert/update/UpdateChecker.java
src/test/java/com/synopsys/integration/alert/update/UpdateCheckerTest.java

Ps update fix

---

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/accessor/JiraServerJobDetailsAccessor.java
alert-database-job/src/main/java/com/synopsys/integration/alert/database/api/StaticJobAccessor.java
alert-database-job/src/test/java/com/synopsys/integration/alert/database/api/StaticJobAccessorTest.java
alert-database/src/main/java/com/synopsys/integration/alert/database/job/jira/server/DefaultJiraServerJobDetailsAccessor.java
alert-database/src/test/java/com/synopsys/integration/alert/database/job/jira/server/JiraServerJobDetailsAccessorTest.java
channel-email/src/main/java/com/synopsys/integration/alert/channel/email/database/accessor/DefaultEmailJobDetailsAccessor.java
channel-email/src/test/java/com/synopsys/integration/alert/channel/email/database/accessor/EmailJobDetailsAccessorTest.java
channel-jira-server/build.gradle
channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/database/accessor/JiraServerJobDetailsAccessorTest.java

Change the Jira Server channel job details processing to use JobDetailsAccessor2

 jira server job details

---

channel-email/src/main/java/com/synopsys/integration/alert/channel/email/environment/EmailEnvironmentVariableHandlerFactory.java
channel-email/src/test/java/com/synopsys/integration/alert/channel/email/environment/EmailEnvironmentHandlerFactoryTest.java
src/test/java/com/synopsys/integration/alert/channel/email/environment/EmailEnvironmentHandlerFactoryTestIT.java

Set the name of the configuration in the email configuration.

email env fix

---

channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/model/JiraServerGlobalConfigModel.java

Small commit to create the model for all of the other Jira Server changes to come. Mostly adding you guys to this PR for awareness as well as checking if anything is missing or should be added. Since the "Install Plugin Remotely" is its own action, I thought it doesn't really fit to add anything for it into the model.

Create a concrete model for Jira Server

---

channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/JiraServerPropertiesFactory.java
channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/action/JiraServerGlobalFieldModelTestAction.java
channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/convert/JiraServerGlobalConfigurationModelConverter.java
channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/distribution/JiraServerMessageSenderFactory.java
channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/distribution/JiraServerProcessorFactory.java
channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/environment/JiraServerEnvironmentVariableHandlerFactory.java
channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/model/JiraServerGlobalConfigModel.java
channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/web/JiraServerCustomFunctionAction.java
channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/JiraServerExternalConnectionTest.java
channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/JiraServerSummaryFieldLengthTestIT.java
channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/validator/JiraServerGlobalConfigurationValidatorTest.java
src/test/java/com/synopsys/integration/alert/channel/jira/server/action/JiraServerGlobalCrudActionsTestIT.java
src/test/java/com/synopsys/integration/alert/channel/jira/server/web/JiraServerGlobalConfigControllerTestIT.java

**Added password to the required arguments list.** I made this change as Password is technically required even tho it is null when obfuscated. The number of tests and classes that were forced to add the password after object creation should help show that this change is necessary.

Updated JiraServerPropertiesFactory to use the concrete model instead of dynamic

---

channel-email/src/main/java/com/synopsys/integration/alert/channel/email/database/accessor/EmailGlobalConfigAccessor.java
channel-email/src/main/java/com/synopsys/integration/alert/channel/email/environment/EmailEnvironmentVariableHandlerFactory.java
channel-email/src/test/java/com/synopsys/integration/alert/channel/email/environment/EmailEnvironmentHandlerFactoryTest.java
component/src/main/java/com/synopsys/integration/alert/component/settings/environment/ProxySettingsEnvironmentHandlerFactory.java
component/src/test/java/com/synopsys/integration/alert/component/settings/environment/ProxySettingsEnvironmentHandlerFactoryTest.java

Note, this is to remedy some of the issues that are outright failing when attempting to set up via the environment variables. This PR isn't intended to fix the problem with partial configurations or validating environment variables.

Proxy and Email environment variable fixes

---

provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/detail/RuleViolationClearedNotificationDetailExtractor.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/detail/RuleViolationNotificationDetailExtractor.java
provider-blackduck/src/test/java/com/synopsys/integration/alert/provider/blackduck/processor/detail/RuleViolationClearedNotificationContentDetailExtractorTest.java
provider-blackduck/src/test/java/com/synopsys/integration/alert/provider/blackduck/processor/detail/RuleViolationNotificationDetailExtractorTest.java
provider-blackduck/src/test/resources/json/ruleViolationClearedDuplicateNotification.json
provider-blackduck/src/test/resources/json/ruleViolationDuplicateNotification.json

Changed our policy extraction to pull out detailed notifications that only relate to the components that have this change

Fix issue with many policy updates causing too many issues to be created

---

ui/src/main/js/common/input/mapping/FluidFieldMappingField.js

Removed the ability to add a duplicate key, Instead clears existing one.

Fixed issue with duplicate field keys being allowed

---

alert-database/build.gradle
build.gradle
buildSrc/docker.gradle

Add a cleanImage task to remove an image from docker.

docker cleanup 

---

alert-common/src/main/java/com/synopsys/integration/alert/common/rest/model/SettingsProxyModel.java
alert-common/src/main/java/com/synopsys/integration/alert/common/rest/proxy/ProxyManager.java
alert-common/src/test/java/com/synopsys/integration/alert/common/rest/proxy/ProxyManagerTest.java
component/src/main/java/com/synopsys/integration/alert/component/settings/convert/ProxyConfigurationModelConverter.java
component/src/main/java/com/synopsys/integration/alert/component/settings/environment/ProxySettingsEnvironmentVariableHandler.java
component/src/main/java/com/synopsys/integration/alert/component/settings/proxy/database/accessor/SettingsProxyConfigAccessor.java
component/src/main/java/com/synopsys/integration/alert/component/settings/proxy/validator/SettingsProxyValidator.java
component/src/test/java/com/synopsys/integration/alert/component/settings/convert/ProxyConfigurationModelConverterTest.java
component/src/test/java/com/synopsys/integration/alert/component/settings/proxy/actions/SettingsProxyCrudActionsTest.java
component/src/test/java/com/synopsys/integration/alert/component/settings/proxy/actions/SettingsProxyTestActionTest.java
component/src/test/java/com/synopsys/integration/alert/component/settings/proxy/validator/SettingsProxyValidatorTest.java
src/test/java/com/synopsys/integration/alert/component/settings/environment/ProxySettingsEnvironmentVariableHandlerTestIT.java
src/test/java/com/synopsys/integration/alert/component/settings/proxy/actions/SettingsProxyTestActionTestIT.java
src/test/java/com/synopsys/integration/alert/component/settings/proxy/web/SettingsProxyControllerTestIT.java
src/test/java/com/synopsys/integration/alert/startup/component/StartupLogTest.java

I had to make significant changes to the validator to support the new model for email, this will more closely follow the process we use in email and jira.

Proxy model required fields

---

ui/src/main/js/page/channel/jira/server/ConcreteJiraServerGlobalConfiguration.js

Verify the status code is for an error.

fix: Make sure the status code is for an error.

---

ui/src/main/js/application/auth/AuthenticationConfiguration.js
ui/src/main/js/common/component/CollapsiblePane.js
ui/src/main/js/common/component/__tests__/CollapsiblePane.test.jsx
ui/src/main/js/common/component/__tests__/__snapshots__/CollapsiblePane.test.jsx.snap
ui/src/main/js/icons.js

_To Do:_ 
**Fix:**  
Convert the `CollapsiblePane.js` component from a class to functional.  This component doesn't need any state variables as it really is just a toggle switch that determines whether something (in this case, a couple of forms) should be expanded or not.
**Testing:**  
There are four areas where `CollapsiblePane.js` is called: in Authentication (LDAP & SAML), Distribution configuration when 'Jira Cloud' or 'Jira Server' is selected in the Channel field.

CollapsiblePane - Convert from class component to functional component

---

docker/blackduck-alert-db/Dockerfile
docker/blackduck-alert-rabbitmq/Dockerfile
docker/blackduck-alert/Dockerfile
docker/blackduck-alert/docker-entrypoint.sh

**Dockerfile**
* Consistency across images
* Combine commands
* Remove unnecessary commands
* Reorder command to leverage layer reuse
**docker-entrypoint.sh**
* Correct unset or unused variables
* Use environment variables set within Dockerfile
* Full path Java tools to be purposefully explicit
* Create and use new logIt() function to help with debugging entrypoint script
* Create and use new checkStatus() function to eliminate repeated code
* Create and use new validateAlertDBExists() function to eliminate repeated psql call
* Create and use new functions to set local and global (exported) variables based on existence of files in run environment
* Minor adjustments to design or implementation details for supportability

IALERT-2925 - Refactor Dockerfile and docker-entrypoint.sh

---

docker/blackduck-alert-rabbitmq/docker-entrypoint.sh

* Correct unset or unused variables
* Use environment variables set within Dockerfile
* Create and use new logIt() function to help with debugging entrypoint script
* Enable rabbitmq plugins in one call to reduce stdout
* Minor adjustments to design or implementation details for supportability

IALERT-2925 - Refactor docker-entrypoint.sh

---

docker/blackduck-alert/Dockerfile
docker/blackduck-alert/docker-entrypoint.sh

Final tweaks for docker related files

IALERT-2925 - Final tweaks for docker related files

---

api-channel-issue-tracker/src/main/java/com/synopsys/integration/alert/api/channel/issue/send/IssueTrackerIssueTransitioner.java
api-processor/src/main/java/com/synopsys/integration/alert/processor/api/summarize/ProjectMessageSummarizer.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/BlackDuckCacheHttpClientCache.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/BlackDuckProjectExistencePopulator.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/action/BlackDuckDistributionFieldModelTestAction.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/action/BlackDuckGlobalFieldModelTestAction.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/issue/BlackDuckIssueTrackerCallbackEventHandler.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/NotificationExtractorBlackDuckServicesFactoryCache.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/detail/BomEditNotificationDetailExtractor.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/AbstractBlackDuckComponentConcernMessageExtractor.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/ProjectNotificationMessageExtractor.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/ProjectVersionNotificationMessageExtractor.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/task/BlackDuckDataSyncTask.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/task/accumulator/BlackDuckNotificationRetrieverFactory.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/web/BlackDuckProjectCustomFunctionAction.java
web/src/main/java/com/synopsys/integration/alert/web/documentation/SwaggerConfiguration.java

* Update messaging to be consistent
* Update Swagger header to `Synopsys Alert`

IALERT-3052 - Consistent bd messages

---

src/test/java/com/synopsys/integration/alert/performance/ExternalPerformanceTest.java
src/test/java/com/synopsys/integration/alert/performance/LargeNotificationTest.java
src/test/java/com/synopsys/integration/alert/performance/utility/AuditCompleteWaitJobTask.java
src/test/java/com/synopsys/integration/alert/performance/utility/AuditProcessingWaitJobTask.java
src/test/java/com/synopsys/integration/alert/performance/utility/IntegrationPerformanceTestRunnerV2.java

IALERT-3067 
Added a new WaitJobCondition as well as calculating the average audit time

Break up wait job tasks into processing and audit complete

---

src/test/java/com/synopsys/integration/alert/performance/utility/AuditCompleteWaitJobTask.java

Added some additional logging whenever audit failures are detect to log the error and the name of the audit entry.
Also, I've refactored calculating the duration using the Duration object and formatting it to be consistent with other performance logging.

Performance audit info improvements

---

component/build.gradle
component/src/main/java/com/synopsys/integration/alert/component/diagnostic/database/DefaultDiagnosticAccessor.java
component/src/main/java/com/synopsys/integration/alert/component/diagnostic/model/AlertQueueInformation.java
component/src/main/java/com/synopsys/integration/alert/component/diagnostic/model/AuditDiagnosticModel.java
component/src/main/java/com/synopsys/integration/alert/component/diagnostic/model/DiagnosticModel.java
component/src/main/java/com/synopsys/integration/alert/component/diagnostic/model/NotificationDiagnosticModel.java
component/src/main/java/com/synopsys/integration/alert/component/diagnostic/model/RabbitMQDiagnosticModel.java
component/src/main/java/com/synopsys/integration/alert/component/diagnostic/model/SystemDiagnosticModel.java
component/src/main/java/com/synopsys/integration/alert/component/diagnostic/utility/RabbitMQDiagnosticUtility.java
component/src/test/java/com/synopsys/integration/alert/component/diagnostic/database/DefaultDiagnosticAccessorTest.java
component/src/test/java/com/synopsys/integration/alert/component/diagnostic/utility/RabbitMQDiagnosticUtilityTest.java
src/test/java/com/synopsys/integration/alert/component/diagnostic/utility/RabbitMQDiagnosticUtilityTestIT.java

Adding new diagnostic info for the running  java environment as well as the status of queues in rabbitMQ for Alert.

IALERT-3081: system & rabbitmq diagnostics

---

api-processor/src/main/java/com/synopsys/integration/alert/processor/api/filter/JobNotificationFilterUtils.java
api-processor/src/test/java/com/synopsys/integration/alert/processor/api/filter/JobNotificationFilterUtilsTest.java
ui/package-lock.json
ui/package.json

If the project name pattern or selected project matches check if the version name matches.  If we aren't filtering by project at all then the job applies to the project and short circuit.

pattern filtering to match on version

---

alert-platform/build.gradle

Comprehensive build run successfully.

IALERT-3107: Update to latest internal libs

---

alert-platform/build.gradle
build.gradle
channel-email/build.gradle
service-email/build.gradle

Reverts blackducksoftware/blackduck-alert#2159

Revert "IALERT-3107 - Update dependencies"

---

alert-platform/build.gradle

Updating  version of int-jira-common to 3.0.6

IALERT-3130: Fix jira cloud marketplace installation

---

api-channel/src/main/java/com/synopsys/integration/alert/api/channel/MessageBoardChannel.java
api-distribution/build.gradle
api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/JobSubTaskEventHandler.java
api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/audit/AuditEvent.java
api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/audit/AuditFailedEvent.java
api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/audit/AuditFailedEventListener.java
api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/audit/AuditFailedHandler.java
api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/audit/AuditSuccessEvent.java
api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/audit/AuditSuccessEventListener.java
api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/audit/AuditSuccessHandler.java
api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/JobSubTaskEventHandlerTest.java
api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/JobSubTaskMessageListenerTest.java
api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/audit/AuditEventTest.java
api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/audit/AuditFailedEventListenerTest.java
api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/audit/AuditFailedEventTest.java
api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/audit/AuditFailedHandlerTest.java
api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/audit/AuditSuccessEventListenerTest.java
api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/audit/AuditSuccessEventTest.java
api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/audit/AuditSuccessHandlerTest.java
api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/mock/MockAuditEntryRepository.java
api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/mock/MockAuditNotificationRepository.java
api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/mock/MockJobSubTaskRepository.java
api-distribution/src/test/java/com/synopsys/integration/alert/api/distribution/mock/MockNotificationCorrelationToNotificationRelationRepository.java
api-event/src/main/java/com/synopsys/integration/alert/api/event/distribution/JobSubTaskEvent.java
channel-slack/src/test/java/com/synopsys/integration/alert/channel/slack/distribution/SlackDistributionEventHandlerTest.java

- Added tests for the AuditEntry even handling classes.
- Refactored the classes to exist in the audit sub package

Added tests for all audit entry handlers.

---

channel-email/src/main/java/com/synopsys/integration/alert/channel/email/attachment/compatibility/ComponentItem.java
channel-email/src/test/java/com/synopsys/integration/alert/channel/email/attachment/compatibility/ComponentItemTest.java

* Update apply methods to perform assignment in fewer locations
* Add test coverage for everything in ComponentItem
* Code coverage verified increase of 0.2% and no new code smells

test: Add test coverage for ComponentItem

---

channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/web/JiraServerCustomFunctionAction.java
src/main/java/com/synopsys/integration/alert/update/DockerTagRetriever.java

View code smell info [HERE](https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS3457&severities=INFO&id=com.synopsys.integration%3Ablackduck-alert)

refactor: Address -info- code smells

---

channel-email/src/test/java/com/synopsys/integration/alert/channel/email/validator/EmailDistributionConfigurationValidatorTest.java
channel-email/src/test/java/com/synopsys/integration/alert/channel/email/validator/EmailGlobalConfigExistsValidatorTest.java
channel-email/src/test/java/com/synopsys/integration/alert/channel/email/validator/EmailGlobalConfigurationFieldModelValidatorTest.java

test: Add full test coverage for channel.email.validator

---

api-channel-jira/src/main/java/com/synopsys/integration/alert/api/channel/jira/util/JiraPluginCheckUtils.java
api-channel-jira/src/test/java/com/synopsys/integration/alert/api/channel/jira/util/JiraCallbackUtilsTest.java
api-channel-jira/src/test/java/com/synopsys/integration/alert/api/channel/jira/util/JiraPluginCheckUtilsTest.java
channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/action/JiraServerGlobalValidationActionTest.java
channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/validator/JiraServerGlobalConfigExistsValidatorTest.java

https://jira-sig.internal.synopsys.com/browse/IALERT-3152
Unit tests for files/packages mentioned in the ticket. See comments and subtask on ticket for TODO.

IALERT-3152 unit tests

---

alert-database/src/main/resources/liquibase/6.12.0/changelog.xml
alert-database/src/main/resources/liquibase/6.12.0/concrete-azure-boards-configuration-tables.xml
alert-database/src/main/resources/liquibase/changelog-postgres-master.xml
channel-azure-boards/build.gradle
channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/database/accessor/AzureBoardsGlobalConfigAccessor.java
channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/database/configuration/AzureBoardsConfigurationEntity.java
channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/database/configuration/AzureBoardsConfigurationRepository.java
channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/model/AzureBoardsGlobalConfigModel.java
channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/database/accessor/JiraServerGlobalConfigAccessor.java

Added database and accessor layers for Azure Boards. Unit and Integration tests will be included as part of a separate PR to unblock further development of this new endpoint.

IALERT-2949: Azure Boards persistence

---

channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsGlobalCrudActions.java
channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsGlobalValidationAction.java
channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/validator/AzureBoardsGlobalConfigurationValidator.java
channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsGlobalCrudActionsTest.java
channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/validator/JiraServerGlobalConfigurationValidator.java
channel-jira-server/src/test/java/com/synopsys/integration/alert/channel/jira/server/action/JiraServerGlobalCrudActionsTest.java

> Adds AzureBoardsGlobalConfigurationValidator and ValidationAction
> Use @Autowired annotation for jira server validator constructor
Ideally https://github.com/blackducksoftware/blackduck-alert/pull/2207 is merged before this PR

IALERT 2951 azureboards validation

---

channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/validator/AzureBoardsGlobalConfigurationValidator.java
channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/action/AzureBoardsGlobalValidationActionTest.java
channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/validator/AzureBoardsGlobalConfigurationValidatorTest.java

> Test files for Azure Boards validator/action
> Set certain variables to final in test files

Test: Azure Boards validator/action test files

---

buildSrc/deploymentTasks.gradle
deployment/docker-swarm/database-utilities.sh
deployment/helm/database-utilities.sh

- Create a script for docker swarm
- Create a script for helm
- Update build to include script in helm directory

IALERT-3149: Add scripts to backup and restore database

---

alert-platform/build.gradle
src/test/java/com/synopsys/integration/alert/performance/NotificationRemovalTest.java
src/test/java/com/synopsys/integration/alert/performance/ScalingPerformanceTest.java
src/test/java/com/synopsys/integration/alert/performance/serialization/ComponentUnknownVersionNotificationSerializationTest.java
src/test/java/com/synopsys/integration/alert/performance/utility/IntegrationPerformanceTestRunner.java
src/test/java/com/synopsys/integration/alert/performance/utility/IntegrationPerformanceTestRunnerLegacy.java

* Update to latest libraries which handles upgrading org.apache.commons:commons-text to address CVE-2022-42889
* Updates for changes from integration-common for ResilientJobConfig

build: Update to latest libraries to address CVE-2022-42889

---

channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/database/accessor/AzureBoardsGlobalConfigAccessor.java
channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/environment/AzureBoardsEnvironmentVariableHandler.java
channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/model/AzureBoardsGlobalConfigModel.java
channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/environment/AzureBoardsEnvironmentVariableHandlerTest.java

FEAT:
- AzureBoardsEnvironmentVariableHandler and unit test
- Remove unneeded toString() call in accessor

IALERT-2954 AzureBoardsEnvironmentVariableHandler and unit test

---

ui/src/main/js/page/channel/azure/AzureDistributionConfiguration.js
ui/src/main/js/page/distribution/DistributionConfigurationForm.js

Updating the azure board distribution job form to include the option to select which azure board the user would like to use.

IALERT-2957 Updating Azure Boards Distribution Job

---

channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/database/accessor/AzureBoardsGlobalConfigAccessor.java

Wrap deleteConfig in transactional required

---

deployment/docker-swarm/README.md
deployment/docker-swarm/external-db/README.md
deployment/helm/synopsys-alert/README.md

- Recommend creating a database backup before upgrade.

IALERT-3149: readme updates

---

ui/src/main/js/common/configuration/global/concrete/ConcreteConfigurationForm.js
ui/src/main/js/page/channel/azure/AzureBoardsPageForm.js

This PR serves to make the button labels in the Azure Boards Form more readable / easily distinguishable on the actions they perform.

IALERT-3229 Azure Boards Form Button Label Changes

---

alert-database/src/main/java/com/synopsys/integration/alert/database/configuration/repository/DescriptorConfigRepository.java
api-channel-issue-tracker/src/main/java/com/synopsys/integration/alert/api/channel/issue/model/IssueVulnerabilityDetails.java
api-channel-issue-tracker/src/main/java/com/synopsys/integration/alert/api/channel/issue/send/IssueTrackerIssueTransitioner.java
api-channel-jira/src/main/java/com/synopsys/integration/alert/api/channel/jira/distribution/custom/MessageReplacementValues.java
api-channel/src/main/java/com/synopsys/integration/alert/api/channel/convert/AbstractChannelMessageConverter.java
api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/JobSubTaskEventHandler.java
api-processor/src/main/java/com/synopsys/integration/alert/processor/api/filter/JobNotificationFilterUtils.java
channel-email/src/main/java/com/synopsys/integration/alert/channel/email/convert/EmailGlobalConfigurationModelConverter.java
channel-jira-cloud/src/main/java/com/synopsys/integration/alert/channel/jira/cloud/action/JiraCloudGlobalFieldModelTestAction.java
channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/action/JiraServerGlobalFieldModelTestAction.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/BlackDuckPhoneHomeHandler.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/action/BlackDuckDistributionFieldModelTestAction.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/service/BlackDuckMessageBomComponentDetailsCreator.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/task/accumulator/BlackDuckNotificationRetriever.java
test-common/src/main/java/com/synopsys/integration/alert/test/common/AuthenticationTestUtils.java
test-common/src/main/java/com/synopsys/integration/alert/test/common/MockRoleAccessor.java

* Unused imports
* Use isEmpty() instead of size() > x
* Unused throws
* Order of modifiers
* Simplify boolean expression (use && vs ?:)
* Return value vs creating variable and returning
* Remove unused boolean (BlackDuckDistributionFieldModelTestAction.java)
* Remove parenthesis around single lamda parameter

Address code smells

---

channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/search/AzureSearchFieldBuilder.java
channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/search/AzureSearchFieldMappingBuilder.java
channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/distribution/util/AzureBoardsSearchPropertiesUtils.java
channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/distribution/search/AzureBoardsAlertIssuePropertiesManagerTest.java
channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/distribution/search/AzureBoardsWorkItemFinderTest.java
channel-azure-boards/src/test/java/com/synopsys/integration/alert/channel/azure/boards/distribution/search/util/AzureBoardsSearchPropertiesUtilsTest.java

Use AzureBoardsSearchPropertiesUtil max_string_value_length as source of truth

AzureBoards string limit test failures

---

src/test/java/com/synopsys/integration/alert/channel/azure/boards/environment/AzureBoardsEnvironmentVariableHandlerTestIT.java

Missed a comment to separate the two in the original PR

IALERT-2954 Separate init and cleanup

---

ui/src/main/js/page/channel/azure/AzureBoardsPageForm.js

IALERT-3239 Show Validation in Progress Azure Error Message

---

src/test/java/com/synopsys/integration/alert/database/job/DistributionJobRepositoryTestIT.java

Test cases for the following scenarios:
Policy match, Sev match -> returns matches
Policy match, Sev empty -> returns matches
Policy empty, Sev match -> returns matches
Policy empty, Sev empty -> returns matches (AKA no filtering)
Policy NOT match, Sev empty -> returns none
Policy empty, Sev NOT match -> returns none
Policy NOT match, Sev NOT match -> returns none

DistributionRepostory IT tests for policy and vulnerability filtering

---

docker/blackduck-alert/docker-entrypoint.sh

If startup fails while running liquibase changes, the databasechangeloglock table will still be locked when Alert next tries to start. 
This PR adds a new function designed to unlock the table prior to launching Alert.
This was tested using a new install of Alert using swarm, as well as an upgrade install of Alert using swarm.

fix: Add logic to unlock databasechangeloglock

---

ui/package-lock.json
ui/package.json

See the following PRs:
https://github.com/blackducksoftware/blackduck-alert/pull/2286
https://github.com/blackducksoftware/blackduck-alert/pull/2285
https://github.com/blackducksoftware/blackduck-alert/pull/2284

Dependabot updates

---

deployment/docker-swarm/docker-compose.local-overrides.yml

With this line commented out, Alert using Swarm won't work "out of the box"

IALERT-3266 - Uncomment out services line

---

deployment/docker-swarm/docker-compose.local-overrides.yml

Reverts blackducksoftware/blackduck-alert#2292
This is only an issue if you edit the file and don't comment out the services line.

Revert "IALERT-3266 - Uncomment out services line"

---

provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/message/AbstractBlackDuckComponentConcernMessageExtractor.java
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/processor/model/AbstractProjectVersionNotificationContent.java

Created distribution items with Project Version url now direct to the components tab view. Affects all job types.

Navigate to components tab for Project Version

---

ui/.eslintrc.json
ui/src/main/js/application/MainPage.js
ui/src/main/js/page/certificates/CertificateModal.js
ui/src/main/js/page/certificates/CertificatesPageLayout.js
ui/src/main/js/page/certificates/CertificatesTable.js
ui/src/main/js/page/certificates/CertificatesTableActions.js
ui/src/main/js/page/certificates/DeleteCertificatesModal.js
ui/src/main/js/page/certificates/EditCertificateCell.js
ui/src/main/js/store/actions/certificates.js

IALERT-3247 Convert Certificate Management Table to New Table Format

---

alert-database/src/main/resources/liquibase/6.13.0/changelog.xml
alert-database/src/main/resources/liquibase/6.13.0/concrete-saml-configuration-table.xml
alert-database/src/main/resources/liquibase/changelog-postgres-master.xml

Columns include **id, name,** and from AuthenticationDescriptor:
// SAML Keys
public static final String KEY_SAML_ENABLED = "settings.saml.enabled";
public static final String KEY_SAML_FORCE_AUTH = "settings.saml.force.auth";
public static final String KEY_SAML_METADATA_URL = "settings.saml.metadata.url";
public static final String KEY_SAML_ENTITY_ID = "settings.saml.entity.id";
public static final String KEY_SAML_ENTITY_BASE_URL = "settings.saml.entity.base.url";
public static final String KEY_SAML_METADATA_FILE = "settings.saml.metadata.file";
public static final String KEY_SAML_WANT_ASSERTIONS_SIGNED = "settings.saml.want.assertions.signed";
// SAML Role Attribute Mapping
public static final String KEY_SAML_ROLE_ATTRIBUTE_MAPPING = "settings.saml.role.attribute.mapping.name";

Create saml table and columns

---

authentication-ldap/build.gradle
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/database/accessor/LDAPConfigAccessor.java
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/database/configuration/LDAPConfigurationEntity.java
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/database/configuration/LDAPConfigurationRepository.java
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/model/LDAPGlobalConfigModel.java

Add required files for LDAP entity:
- LDAPConfigurationEntity
- LDAPConfigurationRepository
- LDAPConfigAccessor
Update build.gradle for dependencies
Update LDAPGlobalConfigModel to set PW

IALERT-3260 - Add LDAP entity files

---

alert-common/src/main/java/com/synopsys/integration/alert/common/rest/AlertRestConstants.java
authentication-ldap/build.gradle
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/action/LDAPCrudActions.java
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/action/LDAPValidationAction.java
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/database/accessor/LDAPConfigAccessor.java
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/validator/LDAPConfigurationValidator.java
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/web/LDAPConfigController.java

Add new:
- LDAPCrudActions
- LDAPValidationAction
- LDAPConfigurationValidator
- LDAPConfigController
Naming changed for LDAPConfigAccessor
Edit for LDAP endpoint
Update build for required dependencies
** LDAPTestAction will be in another PR

IALERT-3265 - Add LDAP ConfigController files

---

api-authentication/src/main/java/com/synopsys/integration/alert/api/authentication/security/UserManagementAuthoritiesPopulator.java
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/action/LDAPTestAction.java
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/action/LdapManager.java
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/database/accessor/LDAPConfigAccessor.java
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/database/configuration/LDAPConfigurationEntity.java
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/model/LDAPConfigModel.java
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/model/LDAPConfigTestModel.java
authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/action/LdapManagerTest.java

This PR is merging into the source branch from this PR: https://github.com/blackducksoftware/blackduck-alert/pull/2328
* Implement (fully) logic for Test Configuration
* Remove copyright
* Fix bug in LDAPConfigurationEntity.java, found when testing using Postman
* Fix bug in LDAPConfigTestModel.java, found when testing using Postman
* Update test to reflect fix in bug, update for supportability

IALERT-3288 - Implement Test Configuration

---

ui/src/main/js/application/auth/BlackDuckSSOConfigImportModal.js
ui/src/main/js/application/auth/SamlForm.js

-Place Fill form button and model components in samlform
-Modify BDSSOConfigImportModal to set new form data format

IALERT-3274 saml fill form button update

---

authentication-ldap/build.gradle
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/environment/LDAPEnvironmentVariableHandler.java
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/model/LDAPConfigModel.java

* Implement LDAPEnvironmentVariableHandler
* Add needed setters in ConfigModel

IALERT-3264 - Implement LDAP environment variable handler

---

alert-database/src/main/resources/liquibase/6.13.0/concrete-saml-configuration-table.xml
api-authentication/src/main/java/com/synopsys/integration/alert/api/authentication/descriptor/AuthenticationDescriptor.java
authentication-saml/build.gradle
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/action/SAMLFileUploadActions.java
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/database/accessor/SAMLConfigAccessor.java
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/database/configuration/SAMLConfigurationEntity.java
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/model/SAMLConfigModel.java
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/validator/SAMLConfigurationValidator.java
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/validator/SAMLFileUploadValidator.java
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/web/SAMLConfigController.java

-Update saml build.gradle
-Create encryption and signing private key endpoints
-Create validators for key files

IALERT-3325 saml private key endpoints

---

authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/environment/LDAPEnvironmentVariableHandlerTest.java

IALERT-3342: LDAPEnvironmentVariableHandler tests

---

authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/action/LDAPCrudActionsTest.java

IALERT-3342: LDAPCrudActions tests

---

alert-database/src/main/resources/liquibase/6.13.0/changelog.xml

Add the file for running LDAP migration to the changelog to run at startup

LDAP migration not added to changelog

---

api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/JobSubTaskEventHandler.java
api-distribution/src/main/java/com/synopsys/integration/alert/api/distribution/execution/ExecutingJobManager.java
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/database/accessor/LDAPConfigAccessor.java
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/validator/SAMLConfigurationValidator.java

Address 4 "low hanging fruit" sonar issues:
3 "Remove useless curly braces around statement"
1 "Merge this if statement with the enclosing one"

6.13.0 Sonar issues

---

authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/action/LDAPTestActionTest.java
authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/action/LDAPValidationActionTest.java

IALERT-3342: LDAPTestAction & LDAPValidationAction tests

---

authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/LdapAuthenticationPerformerTest.java

IALERT-3342: LdapAuthenticationPerformer tests

---

provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/task/accumulator/BlackDuckAccumulator.java

Have the accumulator fire the notification received event if there are notifications written to the database.

IALERT-3356 accumulator event fix

---

docker/blackduck-alert/docker-entrypoint.sh

If configured PG admin user doesn't have admin permissions, the startup script will show errors when trying to run create_extension.sql, but the return status will be 0.
Add a check by querying the pg_roles table to check if user is an admin.
New log entries if user is an admin:
```
2023-02-22 15:50:15 :: Validating postgres admin permissions
2023-02-22 15:50:15 :: SUCCESS: Validating postgres admin permissions.
```
New log entries if user is NOT an admin:
```
2023-02-22 15:47:11 :: Validating postgres admin permissions
2023-02-22 15:47:11 :: ERROR: Validating postgres admin permissions (Code: 1).
```

IALERT-3347 - Check if configured admin user has admin permissions

---

alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultProcessingFailedAccessor.java

- Add a method to perform formatting

IALERT-3372: Format the timestamps.

---

src/main/java/com/synopsys/integration/alert/startup/component/SAMLStartupComponent.java

This is needed to configure/initialize SAML from environmental variables and migrated db

SAML Startup component

---

alert-common/src/main/java/com/synopsys/integration/alert/common/rest/api/FileUploadHelper.java
api-channel-jira/src/test/java/com/synopsys/integration/alert/api/channel/jira/util/JiraCallbackUtilsTest.java
api-channel-jira/src/test/java/com/synopsys/integration/alert/api/channel/jira/util/JiraPluginCheckUtilsTest.java
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/action/SAMLCrudActions.java
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/action/SAMLFileUploadActions.java
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/action/SAMLValidationAction.java
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/database/SAMLMetaDataModeConverter.java
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/database/accessor/SAMLConfigAccessor.java
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/database/configuration/SAMLConfigurationEntity.java
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/database/configuration/SAMLConfigurationRepository.java
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/model/SAMLConfigModel.java
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/security/AlertRelyingPartyRegistrationRepository.java
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/security/SAMLGroupConverter.java
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/security/SAMLManager.java
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/security/SAMLSignedAssertionsValidator.java
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/validator/SAMLFileUploadValidator.java
authentication-saml/src/main/java/com/synopsys/integration/alert/authentication/saml/web/SAMLConfigController.java
component/src/main/java/com/synopsys/integration/alert/component/authentication/security/AuthenticationHandler.java
component/src/main/java/com/synopsys/integration/alert/component/authentication/security/database/AlertDatabaseAuthenticationPerformer.java
component/src/main/java/com/synopsys/integration/alert/component/authentication/web/SAMLMetadataUploadFunctionController.java
component/src/main/java/com/synopsys/integration/alert/component/authentication/web/SamlMetaDataFileUpload.java
component/src/test/java/com/synopsys/integration/alert/component/authentication/validator/AuthenticationConfigurationValidatorTest.java
component/src/test/java/com/synopsys/integration/alert/component/authentication/web/SamlMetadataFileUploadTest.java
src/main/java/com/synopsys/integration/alert/startup/component/ConfigurationOverridesStartupComponent.java
src/test/java/com/synopsys/integration/alert/channel/azure/boards/environment/AzureBoardsEnvironmentVariableHandlerTestIT.java
src/test/java/com/synopsys/integration/alert/channel/azure/boards/web/AzureBoardsGlobalConfigControllerTestIT.java
src/test/java/com/synopsys/integration/alert/channel/jira/server/environment/JiraServerEnvironmentVariableHandlerTestIT.java
src/test/java/com/synopsys/integration/alert/startup/component/ConfigurationOverridesStartupComponentTest.java

Run IntelliJ optimize imports on entire source

IALERT-3300: IDE optimize imports

---

authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/LDAPAuthenticationPerformer.java
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/LDAPConfig.java
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/MappingLDAPAuthoritiesPopulator.java
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/action/LDAPManager.java
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/action/LDAPTestAction.java
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/model/LDAPConfigTestModel.java
authentication-ldap/src/main/java/com/synopsys/integration/alert/authentication/ldap/validator/LDAPConfigurationValidator.java
authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/LDAPAuthenticationPerformerTest.java
authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/LDAPTestHelper.java
authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/MappingLDAPAuthoritiesPopulatorTest.java
authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/action/LDAPManagerTest.java
authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/action/LDAPTestActionTest.java
authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/action/LDAPValidationActionTest.java
authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/validator/LDAPConfigurationValidatorTest.java
authentication-ldap/src/test/java/com/synopsys/integration/alert/authentication/ldap/web/LDAPConfigControllerTest.java
component/src/main/java/com/synopsys/integration/alert/component/authentication/actions/AuthenticationFieldModelTestAction.java
src/test/java/com/synopsys/integration/alert/component/authentication/web/AuthenticationActionsTestIT.java
src/test/java/com/synopsys/integration/alert/component/authentication/web/AuthenticationControllerTestIT.java

Naming changes for consistency
Ldap -> LDAP
inValid -> invalid

IALERT-3380 - authenitcation-ldap refactoring/renaming

---

provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/issue/BlackDuckProviderIssueHandler.java
provider-blackduck/src/test/java/com/synopsys/integration/alert/provider/blackduck/issue/BlackDuckProviderIssueHandlerTest.java

- The version url was changed for  IALERT-3119  
-  For the patch work around parsing the URL for the issues tab.
- Additional changes are more complicated for a patch.
- Added tests for callback

IALERT-3285: fix issue link

---

build.gradle
buildSrc/deploymentTasks.gradle
buildSrc/docker.gradle
gradle/wrapper/gradle-wrapper.properties

Changes in this PR:
* Upgrade to Gradle to leverage enhancement for onlyIf{}
* Add Gradle plugin to display task tree
* Add new variables to determine type of build (release, QA, or snapshot)
* Based on type of build, look for environment variables to set Helm repo(s) to push charts to (helmArtifactoryRepos)
* Organize buildSrc/deploymentTasks.gradle
* Add generic tasks to handle ALL Helm repo add's and ALL Helm push's
* Add dynamic tasks to generate repo add and push tasks for each repo
Below is the task graph before any edits:
```
------------------------------------------------------------
Root project 'blackduck-alert'
------------------------------------------------------------
:copyDeploymentFiles
:createDeploymentZip
\--- :copyDeploymentFiles
:helmLint
:helmDryRun
:helmPackage …
```

IALERT-3389 - Add logic to push helm charts to Artifactory

---

docker/blackduck-alert/docker-entrypoint.sh

Hosted solutions are unable to grant super user permissions. Because of this, we need to adjust how we handle validating the permissions for the admin user that won't also break on-prem customers.
- If admin user is a super user, **exit function successfully**
- If admin user is a super user, 'uuid-ossp' function exists, and databasechangeloglock table does not exist, **exit function successfully**
- If admin user is a super user, 'uuid-ossp' function exists, databasechangeloglock table exists AND admin user has SELECT and UPDATE access to table, **exit function successfully**
- if admin user is not super user, 'uuid-ossp' function does not exist, **exit function with error**
- If admin user is a super user, 'uuid-ossp' function exists, databasechangeloglock table exists AND admin user …

IALERT-3448: adjust how checking permissions works

---

deployment/docker-swarm/README.md
deployment/docker-swarm/database-utilities.sh
deployment/helm/database-utilities.sh
deployment/helm/synopsys-alert/README.md
provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/task/accumulator/BlackDuckAccumulator.java

If the accumulator fails for any reason, the lock should still be released. Enclose logic in try/finally.

IALERT-3456 - Release accumulator lock on failure

---

docker/blackduck-alert-rabbitmq/Dockerfile
docker/blackduck-alert/Dockerfile
gradle/wrapper/gradle-wrapper.properties
ui/package-lock.json
ui/package.json

Also check in rebuilt package-lock.json with npm 8.11.0

IALERT-3242, IALERT-3243 Update docker images

---

build.gradle
docker/blackduck-alert-db/Dockerfile
docker/blackduck-alert-db/alertdb-pg-migrate.sh
docker/blackduck-alert-rabbitmq/Dockerfile
docker/blackduck-alert/Dockerfile

- call apk update before apk adds in docker images
- postgres migration from 12.11

Security updates

---

ui/src/main/js/common/component/table/cell/MultiSelectCell.js
ui/src/main/js/common/component/table/cell/MultiSelectHeaderCell.js

Use jobId as identitifer for distribution tables

IALERT-3490 Selecting 1 dist job selects all 

---

alert-platform/build.gradle
build.gradle
src/test/resources/database/helm-test-postgres/templates/postgres.yaml
src/test/resources/database/init-docker-db.sh

To resolve: https://sig-bd-hub.app.blackduck.com/api/projects/5a799db5-1dce-46e4-98c6-e988216b55ff/versions/8f7a7450-2bca-4370-b883-cdc2f15ccda9/components?filter=bomInclusion%3Afalse&filter=bomMatchInclusion%3Afalse&filter=bomMatchReviewStatus%3Areviewed&limit=100&offset=0&sort=securityRiskProfile%20DESC
Recommendation was to upgrade to 3.0.6.

Update spring to 3.0.7 from 3.0.5

---

channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/database/accessor/JiraServerGlobalConfigAccessor.java
channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/database/configuration/JiraServerConfigurationEntity.java

Rename jiraAuthorizationMethod to authorizationMethod for jpa

[BE] IALERT-3499 Jira Server Authorization sort not working

---

ui/src/main/js/page/audit/AuditFailureTable.js
ui/src/main/js/page/certificates/CertificatesTableActions.js
ui/src/main/js/page/channel/azure/AzureBoardTableActions.js
ui/src/main/js/page/channel/jira/server/JiraServerTableActions.js
ui/src/main/js/page/distribution/DistributionTableActions.js
ui/src/main/js/page/provider/PoviderTableActions.js
ui/src/main/js/page/task/TaskManagementTable.js
ui/src/main/js/page/usermgmt/roles/RoleTableActions.js
ui/src/main/js/page/usermgmt/user/UserTableActions.js

Also disable refresh button for 1 sec after click as a visual indicator for user and to limit click rate

[UI] IALERT-3495 Add refresh button to tables

---

ui/src/main/js/page/channel/jira/server/JiraServerCopyCell.js
ui/src/main/js/page/channel/jira/server/JiraServerModal.js

Modified JiraServerModal and JiraServerCopyCell to match AzureBoardModal and AzureCopyCell

[UI] IALERT-3500 Fix jira server copy not working

---

ui/src/main/js/page/channel/azure/AzureBoardsDeleteModal.js
ui/src/main/js/page/channel/jira/server/JiraServerDeleteModal.js
ui/src/main/js/page/distribution/DistributionDeleteModal.js
ui/src/main/js/page/provider/ProviderDeleteModal.js
ui/src/main/js/page/usermgmt/roles/RoleDeleteModal.js
ui/src/main/js/page/usermgmt/user/UserDeleteModal.js
ui/src/main/js/store/actions/provider.js
ui/src/main/js/store/actions/users.js
ui/src/main/js/store/reducers/azure-boards.js
ui/src/main/js/store/reducers/certificates.js
ui/src/main/js/store/reducers/distribution.js
ui/src/main/js/store/reducers/jira-server.js
ui/src/main/js/store/reducers/roles.js
ui/src/main/js/store/reducers/users.js

-Fix successive deletes not working for tables
-Fix unchecked items in confirm delete prompt being deleted

IALERT-3504/3505 Fix successive actions not working for tables

---

alert-database-job/src/main/java/com/synopsys/integration/alert/database/distribution/DistributionRepository.java
alert-database/src/main/java/com/synopsys/integration/alert/database/audit/AuditFailedEntryRepository.java
channel-azure-boards/src/main/java/com/synopsys/integration/alert/channel/azure/boards/database/configuration/AzureBoardsConfigurationRepository.java
channel-jira-server/src/main/java/com/synopsys/integration/alert/channel/jira/server/database/configuration/JiraServerConfigurationRepository.java
ui/package-lock.json

- Use ILIKE for case insensitive searches except for numerical columns
- Fix lastUpdate column searches not working by using IS NOT NULL instead of != NULL
- Add auth type search for Jira Server
Other tables mentioned here are already case insensitive: https://github.com/blackducksoftware/blackduck-alert/pull/2486

IALERT-3507 Case insensitive search for Azure boards, jira server, and distribution tables

---

ui/src/main/js/common/component/table/cell/MultiSelectCell.js
ui/src/main/js/common/component/table/cell/MultiSelectHeaderCell.js
ui/src/main/js/page/channel/jira/common/FieldMappingDeleteModal.js
ui/src/main/js/page/channel/jira/common/JiraFieldMapDistributionTable.js
ui/src/main/js/page/channel/jira/common/JiraFieldMapTableActions.js
ui/src/main/js/page/channel/jira/server/JiraServerTable.js

Fix an issue where multi-select would select all fields as well as an issue where deletes were not working correctly and would delete un-staged field mappings.

IALERT-3527: Jira distribution configuration field mapping fixes

---

ui/src/main/js/common/component/input/NumberInput.js
ui/src/main/js/common/component/modal/ModalFooter.js
ui/src/main/js/page/provider/ProviderCopyCell.js
ui/src/main/js/page/provider/ProviderEditCell.js
ui/src/main/js/page/provider/ProviderModal.js
ui/src/main/js/page/provider/ProviderTable.js
ui/src/main/js/page/provider/ProviderTableActions.js

Adding in simple permission check to Provider Modal.  Also removing a proptype warning in the NumberInput field.

IALERT-3478: Adding permission checks to Provider Modal

---

ui/src/main/js/common/component/modal/Modal.js
ui/src/main/js/page/usermgmt/user/UserModal.js

- Fixes subsequents edit/copy user modal closing automatically after initial edit/save
- Apply styling for userModal based on window size to allow for dropdown menu view
3524 and 3539 are related

IALERT-3533 User modal fixes

---

ui/src/main/js/page/audit/AuditFailureTable.js
ui/src/main/js/page/channel/azure/AzureBoardsTable.js
ui/src/main/js/page/channel/jira/server/JiraServerTable.js
ui/src/main/js/page/distribution/DistributionTable.js

We want to reset the page number when a user decides to update the pagesize of a table.

IALERT-3540 Reset Page Number on Page Event

---

ui/src/main/js/page/channel/azure/AzureBoardsDeleteModal.js
ui/src/main/js/page/channel/azure/AzureBoardsTable.js
ui/src/main/js/page/channel/jira/server/JiraServerDeleteModal.js
ui/src/main/js/page/channel/jira/server/JiraServerTable.js
ui/src/main/js/page/distribution/DistributionDeleteModal.js
ui/src/main/js/page/distribution/DistributionTable.js
ui/src/main/js/page/provider/ProviderDeleteModal.js
ui/src/main/js/page/provider/ProviderTableActions.js
ui/src/main/js/page/usermgmt/roles/RoleDeleteModal.js
ui/src/main/js/page/usermgmt/user/UserDeleteModal.js

-Fix for azureboards not navigating to page 1 on delete 
-On page change, clear prevously selected rows

IALERT-3542 Add fix for not displaying message on 0 deletes

---

build.gradle
channel-email/src/main/java/com/synopsys/integration/alert/channel/email/web/EmailAddressFunctionController.java
ui/package-lock.json
ui/package.json
ui/src/main/js/common/component/input/DropdownField.js
ui/src/main/js/common/component/input/DynamicSelectInput.js
ui/src/main/js/common/component/table/Table.js
ui/src/main/js/common/component/table/TableBody.js
ui/src/main/js/common/component/table/TableFooter.js
ui/src/main/js/common/component/table/cell/MultiSelectCell.js
ui/src/main/js/page/channel/email/AdditionalEmailAddressesModal.js
ui/src/main/js/page/channel/email/EmailDistributionConfiguration.js

Adds the additional email address modal to 7.0.0.

IALERT-3556 add additional email addresses modal

---

gradle/wrapper/gradle-wrapper.properties

Upgrade to latest patch on existing gradle major version

---

component/src/main/java/com/synopsys/integration/alert/component/diagnostic/model/CompletedJobsDiagnosticModel.java
component/src/main/java/com/synopsys/integration/alert/component/diagnostic/model/JobExecutionsDiagnosticModel.java

Address sonar warning to make dependency serializable

Make dependency Serializable

---

alert-database/src/main/resources/liquibase/7.1.0/changelog.xml
alert-database/src/main/resources/liquibase/7.1.0/client-certificates-tables.xml
alert-database/src/main/resources/liquibase/changelog-postgres-master.xml

IALERT-3577 Create cert and private key tables

---

alert-database/src/main/java/com/synopsys/integration/alert/database/api/DefaultClientCertificateAccessor.java
component/src/main/java/com/synopsys/integration/alert/component/authentication/security/AuthenticationHandler.java
src/main/java/com/synopsys/integration/alert/configuration/ApplicationConfiguration.java
web/src/main/java/com/synopsys/integration/alert/web/documentation/SwaggerConfiguration.java

DefaultClientCertificateAccessor.java -> [Remove this empty statement.](https://sonarcloud.io/project/issues?open=AY1CwHrIy5vaCD3iOYhE&id=com.synopsys.integration%3Ablackduck-alert)
AuthenticationHandler.java -> [Rename "authenticationProvider" which hides the field declared at line 56.](https://sonarcloud.io/project/issues?open=AYhTLjamM1ZQdcv6Z-MU&id=com.synopsys.integration%3Ablackduck-alert)
ApplicationConfiguration.java -> [Remove this unused "logger" private field.](https://sonarcloud.io/project/issues?open=AYhTLivwM1ZQdcv6Z-MR&id=com.synopsys.integration%3Ablackduck-alert)
SwaggerConfiguration.java -> [Remove this unused "SUPPORTED_SUBMIT_METHODS" private field.](https://sonarcloud.io/project/issues?open=AYhTLkg4M1ZQdcv6Z-Mc&id=com.synopsys.integration%3Ablackduck-alert)

Address a few sonar warnings

---

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/ClientCertificateModel.java
alert-database/src/main/java/com/synopsys/integration/alert/database/api/ClientCertificateAccessor.java
component/src/main/java/com/synopsys/integration/alert/component/certificates/AlertClientCertificateManager.java
src/test/java/com/synopsys/integration/alert/component/certificates/AlertClientCertificateManagerTestIT.java
src/test/java/com/synopsys/integration/alert/database/api/configuration/ClientCertificateAccessorTestIT.java

Also to clarify it is one model/config

Condense client certificate class names for simplificity

---

alert-common/src/main/java/com/synopsys/integration/alert/common/persistence/model/ClientCertificateModel.java
alert-database/src/main/java/com/synopsys/integration/alert/database/api/ClientCertificateAccessor.java
api-certificates/src/main/java/com/synopsys/integration/alert/api/certificates/AlertClientCertificateManager.java
component/src/main/java/com/synopsys/integration/alert/component/certificates/web/ClientCertificateConfigurationValidator.java
src/test/java/com/synopsys/integration/alert/component/certificates/AlertClientCertificateManagerTestIT.java
src/test/java/com/synopsys/integration/alert/database/api/configuration/ClientCertificateAccessorTestIT.java
src/test/java/com/synopsys/integration/alert/startup/component/AlertClientCertificateManagerStartupComponentTestIT.java

To match the descriptor key value

Use clientCertificateContent as json field name

---

ui/src/main/js/page/certificates/MTLSCertificateLayout.js

Adds further tooltip description, required fields, and enable save when all fields present

IALERT-3638 Required fields for client certificates

---

alert-platform/build.gradle

Update version of saml dependency to address vulnerabilities.
comprehensive build was successful

IALERT-3642 - Update version of saml dependency

---

provider-blackduck/src/main/java/com/synopsys/integration/alert/provider/blackduck/validator/BlackDuckApiTokenValidator.java

Refactor the API token validation code to determine if the user has one of the current roles as before.  Otherwise look at the user's notification-subscriptions data.  Iterate through the notification-subscriptions paged data and check if the notifyUser property is set to true.  If one project has notifications enabled then this is a valid API token for use in Alert.

IALERT-3687: Fix API token validation check

---

build.gradle
src/test/resources/database/helm-test-postgres/templates/postgres.yaml
src/test/resources/database/init-docker-db.sh
src/test/resources/spring-test.properties

Matches BD's postgres version 15.7
Tested and verified the following:
- Docker compose upgrades to 15.7
- Helm upgrades to 15.7 from alert 7.1.2 to 7.2.0
- Creating config, distribution, and notification sent to email config
- All unit tests pass

IALERT-3494 Upgrade to 15.7 postgres

---

build.gradle
docker/blackduck-alert-rabbitmq/Dockerfile
docker/blackduck-alert/Dockerfile
gradle/wrapper/gradle-wrapper.properties

Upgrade base Docker images to latest patch version of image
Upgrade Gradle to latest patch version

IALERT-3741 - Update Gradle and base Docker images

---

component/src/main/java/com/synopsys/integration/alert/component/users/web/user/util/UserCredentialValidator.java

Discovered an issue where the common password dictionary would failed to load at runtime during the deployment. The ClassPathResource worked perfectly fine for unit tests and produced no errors. As the file does not exist when running from a jar we need to instead use an InputStream to read the contents of the common password dictionary.
The change here is primarily to reflect this and switches the usages of File to InputStream and to refactor accordingly.

IALERT-3679: Fix password dictionary loader

---

component/src/main/java/com/synopsys/integration/alert/component/authentication/security/AuthenticationHandler.java
ui/package-lock.json
ui/package.json
ui/src/main/css/logos.scss
ui/src/main/js/page/about/AboutInfoFooter.js

- Use 2.10.5 react-bootstrap for compatibility with bootstrap 5.0.0
- add "data:" to csp to allow rendering of bootstrap images  
- fix logo styling in login page for firefox

IALERT-3747 Firefox logo alignment and StatusMessage close button fix

---

alert-common/src/main/java/com/blackduck/integration/alert/common/descriptor/config/ui/DescriptorMetadata.java
ui/package.json
ui/src/main/css/app.scss
ui/src/main/css/audit.scss
ui/src/main/css/field.scss
ui/src/main/css/footer.scss
ui/src/main/css/header.scss
ui/src/main/css/messages.scss
ui/src/main/css/settings.scss
ui/src/main/css/table.scss
ui/src/main/css/variables.scss
ui/src/main/js/Index.js

This PR serves to remove any references to 'Synopsys' (case-insensitive) from our UI section of the repository.  Ultimately, this is the last step in UI rebranding.  From this point on we should be fully Black Duck.

IALERT-3699: Remove 'Synopsys' References from UI Codebase

---

component/src/main/java/com/blackduck/integration/alert/component/authentication/security/HttpPathManager.java

Adds favicon back to default paths

IALERT-3768 Fix favion not loading

---

ui/src/main/js/application/App.js
ui/src/main/js/application/MainPage.js

Main content takes 100vh and footer was overlayed on top. Share vh height and overflow if needed.

IALERT-3778 Scroll bar for distribution page

---

deployment/helm/blackduck-alert/README.md

Update readme for corrected helm repo

IALERT-3796 - Update helm repo to cloudnative

---

alert-platform/build.gradle

Comprehensive build run with expected results

IALERT-3829 - Update all BD library dependencies to latest
